### ISSUE TITLE
createStyleSheet disallows more than 31 stylesheets in <= IE9

### ISSUE THREAD

**Issue by Warhawk94** [less/less.js#1059]
I work at a corporation and we parse out all of the stylesheets less hits on our dev environment so we can debug each one individually if needed, because of this, in the dev env we do NOT compile/minify until build. Because of this, we have way more than 31 stylesheets, but because of this limitation, http://msdn.microsoft.com/en-us/library/ms531194(VS.85).aspx, it breaks in IE. What I'd recommend is instead of using createStyleSheet, to use the method of appending to the DOM in the \<head> to render the stylesheets.

**Comment by matthew-dean** [comment]
This is an old thread, and not a common issue, so I'll close this.

@szed Years late, but this was posted in the wrong repo. What you were looking for is: https://github.com/Crunch/Crunch-2/issues
