### ISSUE TITLE
IE 4095 selector limit issue using browser version of LESS

### ISSUE THREAD

**Issue by neilgoodman** [less/less.js#1115]
In a web app I currently develop we use the browser version of LESS in our debug builds in the following way:
1. We have a custom JSON manifest file that lists all of the LESS files in our project and in which order they should be included in the the HTML document.
2. A custom asset pipeline we developed reads the manifest file and inserts HTML like the following into our app's index:

``` html
<style type="text/less">
    @import "file1.less";
    @import "file2.less";
    @import "file3.less";
</style>
<script type="text/javascript" src="less.js"></script>
```

This works fine for us in Chrome and Firefox, but our app's compiled stylesheet has just crossed the 4095 selector limit that IE imposes per sheet (see more here: http://blogs.msdn.com/b/ieinternals/archive/2011/05/14/internet-explorer-stylesheet-rule-selector-import-sheet-limit-maximum.aspx).

For our release builds of the app we use LESS inside of Node.js and we have now combined this with BLESS (http://blesscss.com/). So far BLESS is working great for our release builds, but we still want to use the browser version of LESS in our debug builds.

Has anyone ran into this before? Any suggestions?

**Comment by pppdns** [comment]
I just bumped into this old thread, if anyone else has problem with IE's 4095 max selector problem, here is what we use:
https://github.com/project-collins/grunt-csssplit

config:

```javascript
{
    src: ['app.css'],
    dest: 'app.min.css',
    options: {
        maxSelectors: 4095,
        suffix: '.'
    }
}
```

this task automatically splits the CSS file to separate files if the number of selectors is higher than `maxSelectors`. For an `app.css` containing 5000 selectors it will create `app.min.1.css` and `app.min.2.css`, etc.


FYI: we use `watch` + auto LESS > CSS compiling + CSS livereload, so this procedure is automatic, the CSS refreshes on the page without page refresh everytime we save a LESS file
