### ISSUE TITLE
Using CSS3 background-size within the `background` shorthand property results in syntax error

### ISSUE THREAD

**Issue by yggi49** [less/less.js#1116]
CSS3’s new `background-size` property can be included in the `background` shorthand declaration by separating it from the `background-position` specification with a forward slash, like this:

```
div {
    background: url('/path/to/image.png') left center / contain no-repeat;
}
```

The result is a syntax error, though, with the parser obviously choking on the `/ contain` part—removing it also makes the error disappear.

Of course it is possible to work around this issue by escaping the entire value of the `background` property with `~"…"`, but it would be really nice to be able to use the default syntax without restrictions.

**Comment by gpv-dev** [comment]
I seem to be having this problem in lessc 2.1.1. 

<code>
/* less */
#header {
    height: 50px;
    width: 100%;
    padding: 0 10px;
    font-size: 20px;
    background: url("/img/nav-back.jpg") 0 0/100%;
    position: fixed;
}
</code>
<code>
/* compiled css */
#header {
    height: 50px;
    width: 100%;
    padding: 0 10px;
    font-size: 20px;
    background: url("/img/nav-back.jpg") 0 0/100%;
    position: fixed;
}
</code>

Running on Linux Mint 17 Qiana using lessc 2.1.1.

**Comment by seven-phases-max** [comment]
@gpv-dev

Your result is expected if you compile w/o [`--strict-math=on` option](http://lesscss.org/usage/#command-line-usage-strict-math`).

**Comment by gpv-dev** [comment]
@seven-phases-max

Thanks for the quick response. You suggestion was exactly what I needed.

**Comment by juukie** [comment]
Thanks @seven-phases-max, got it working:
`url(/assets/img/logos/foo.png) 0 0 / ~"167px auto" no-repeat;`
`url(/assets/img/logos/foo.png) 0 0 / contain no-repeat;`
