### ISSUE TITLE
Watch option for the lessc command

### ISSUE THREAD

**Issue by omarabid** [less/less.js#1171]
From the command line help, it doesn't appear that the utility has a watch function.

I'm not sure of the technical difficulty of such feature but it's much needed for serious development with less.

**Comment by corysimmons** [comment]
:+1: for LESS getting an official CLI watcher. This is a super legit feature and this request is 2 years old. :\

**Comment by jiyinyiyong** [comment]
I was using Gulp for a while. Now I'm totally in favor of Webpack. It's two years and the community changed a lot.

**Comment by royriojas** [comment]
Hi guys, It is been a while and the only watching option that is close to the one I would like is `gulp-progeny`. But I don't use gulp, and kinda prefer the command line approach and npm for that.

So I have made a cli watcher for less. Currently is inside `simpless` a module that it is a mashup, meaning that it has preconfigured the most common plugins I use. The watch mode works by setting a listener on all the imported files and referenced files using url that are relative the files.

https://github.com/royriojas/simpless

I'm totally open to factorize the wrapper into a simple and plain watcher wrapper (without the extra stuff), if you're still interested. 

Also I was thinking if there is any efforts in trying to provide incremental builds that don't depend on a watch mode. Like caching the parse results of a file and only processing it only if itself or any dependency of it has changed. 

Compile times are fast, though, so don't really know if this is an issue. Yet it will be cool to have it.
