### ISSUE TITLE
CIE Lab color conversion, for the L component

### ISSUE THREAD

**Issue by artscoop** [less/less.js#1182]
Hi,
Would adding CIELab conversion in order to benefit from the L channel be out of scope for Less ? HSL or HSV are convenient and simple, but perceptually, changing L/S ot V/S is often far less efficient than moving the L channel.
I happen to rely on the Lab color space very often in web design and digital painting.
I'm considering adding such a feature to Less but won't if you believe it has no practical use.
Thanks.

**Comment by seven-phases-max** [comment]
Implement as a plugin (first). See #1853 for more on the current "new color functions" approach.

**Comment by thorn0** [comment]
For reference, Lab and LCH color in the CSS spec draft:
https://www.w3.org/TR/css-color-4/#lab-colors
