### ISSUE TITLE
Mixin Interpolation

### ISSUE THREAD

**Issue by tomjn** [less/less.js#1196]
We have selector interpolation, yet mixin interpolation does not work

For example:

```
.device-type(@namespace:~'') {
    .@{namespace}-test { width:50%; }
}

.device-type(~"laptop-");
```

Would generate a css class laptop-test, that could be used here:

```
<div id="test" class="laptop-test"> .... </div>
```

However, if I add this, things fail:

```
#test {
    .laptop-test;
}
```

One would expect it to generate:

```
.laptop-test {
    width:50%;
}
.testdiv {
    width:50%;
}
```

**Comment by mhawk0** [comment]
I am afraid that calling a mixin with interpolated variable, e.g. 
```
.mixin@{useMixin}();
```
is still not supported yet?

**Comment by seven-phases-max** [comment]
>is still not supported yet?

No. Neither in interpolated nor in simple variable form.
