### ISSUE TITLE
HCV color model suggestion (source code attached)

### ISSUE THREAD

**Issue by ghost** [less/less.js#1239]
I suggest to add "HCV" color model support. HCV - Hue, Chroma (Colorful), Value (Grayscale).
https://github.com/Alexei03a/utils/blob/gh-pages/javascripts/libs/hcv-convert.js
Code maximum optimized.

**Comment by seven-phases-max** [comment]
Merging to discussion at #1853.

**Comment by acterhd** [comment]
HCV now HCG.
