### ISSUE TITLE
Expose method for `@import`ing LESS files

### ISSUE THREAD

**Issue by jonschlinkert** [less/less.js#1241]
I would like to be able to `@import` LESS files programmatically without actually touching an import statement.

I'm currently using some non-less.js hacks/workarounds to do this (with [assemble-less](http://github.com/assemble/assemble-less) in particular), but I'm wondering if there is a better, native Less.js solution.  This would be a powerful feature for 3rd party build systems.

**Comment by lukeapage** [comment]
Hi @jonschlinkert,

I'm still not sure I understand this feature request?

**Comment by jonschlinkert** [comment]
@lukeapage  sorry, this is so old I apologize for not following up the last time you commented. most likely I didn't see your reply. I believe I was looking for a way to programmatically inject import statements (or some equivalent) into the parse tree.  

I'm going to close for now so I don't distract you with this. If I can come up with an example, I'll link it here, and if you think it's worth it maybe we can re-open.
