### ISSUE TITLE
1.3.3 development/watch mode hogging cpu

### ISSUE THREAD

**Issue by generationfourth** [less/less.js#1306]
I was running 1.2.1 (on accident) for a while and the live updating with development/watch mode was working really smoothly. After I updated to 1.3.3 and I have watch mode running my code editor, espresso, jumps to 50-90% of my cpu. Basically it's unusable now. 

It seems to be any version from 1.3.1+. I'm not sure if this is the right spot for this but I'm getting desperate and was wondering if anyone had similar problems. I do not understand .js so I do not know how to trouble shoot. 

thanks

**Comment by matthew-dean** [comment]
Since this is related to an earlier version (and likely to do with sync AJAX, maybe?) is this still an issue?

**Comment by seven-phases-max** [comment]
I guess it's safe to close either way (untill someone reports the same with a current version :P).

**Comment by seven-phases-max** [comment]
Closing as no-longer-applicable.
