### ISSUE TITLE
feature: _index.less

### ISSUE THREAD

**Issue by jonschlinkert** [less/less.js#1339]
Syntax can be different, it's the concept that is important, originally mentioned by @lukeapage here:https://github.com/cloudhead/less.js/issues/1181#issuecomment-13546979. This isn't my concept, @lukeapage referenced the Stylus implementation, described here: http://learnboost.github.io/stylus/docs/import.html:

The idea is that a folder can contain a special "index" file, which references "sub-components", mixin libs, or feature-subsets related to that library. It might be useful to think of this as having the ability to define dependencies. 

``` css
./tablet
  |-- index.less
  |-- vendor.less
  |-- buttons.less
  |-- images.less
```

**Comment by lukeapage** [comment]
Merge this with #1181 and close it?

**Comment by matthew-dean** [comment]
I don't know why I thought this would break browser support. (Who knows, it was two years ago.) If it runs like stylus, an import line of ```@import "bootstrap";``` can just as easily trigger an http request first to bootstrap.less, and, failing that, a request to "bootstrap/index.less".

As far as merging, it still seems like a separate request, no? One is for grabbing all files present, and one is to support shorthand for importing a library's primary file.

But it makes sense that the content of index.less would probably be ```@import "*.less";``` for many Less libs once both are implemented.

**Comment by matthew-dean** [comment]
Since this issue was raised again in #2879 recently, part of the question was around what libraries do now. Many of them use the same `.less` name as the folder name. So if there are search fallbacks, it might make sense to do:
```less
@import "library";
```

1. Try to import "library.less";
2. Try to import "library/library.less";
3. Try to import "library/index.less";

This would make a nicer shorthand for library imports than writing:
```less
@import "library/library";
```

**Comment by thybzi** [comment]
The way you described (lib.less, **then lib/lib.less**, then lib/index.less) is just the best idea.
Better than current implementation in Stylus.
Love this and wait for this
