### ISSUE TITLE
Result of multiplication & division by % values off by 100×

### ISSUE THREAD

**Issue by lucasrizoli** [less/less.js#1366]
In LESS 1.4, it seems that the result of multiplying by a % value is 100× what it should be; dividing by a % value, 100× smaller than it should be.

For example, `foo: ( 50% * 256 )` will result in `foo: 12800%`, and `bar: ( 256 / 100% )` results in `bar: 2.56%`.

One can work around it with, say, `foo: ( 256 * ( 50% / 100 ) );` but that seems like a complicated way to get a result that, intuitively, seems straight-forward.

I cannot figure out if this odd result of multiplying and dividing by percentages in LESS is a known issue or if I'm just being thick—or both.

**Comment by acli** [comment]
Can we just have an option to completely disable calculations?

**Comment by seven-phases-max** [comment]
@acli 
>Can we just have an option to completely disable calculations?
[The option](http://lesscss.org/usage/#command-line-usage-strict-math) is there for a while.

**Comment by seven-phases-max** [comment]
My two cents for the topic would be (waring: Agressive wording!): I just can't see how a magical `of` operator (as in `A% of B`) operator can be associated with the multiplication operator (as in `A * B` -> `A repeated B times` then `A *  B = B * A` and so on). Yea, I know, many programs do this, even my calculator does this.. but this is still silly (these things are also dumb when it comes to operator precedence and miss other base arithmetic lessons from the grade 1, so they are barely to be used a model for a programming language).
I think the current Less behaviour for the use-statement (both `su on & off`) is fine. And if there's a need for an `of` operator - it should be just that - the `of` operator (How did  `*` or `/` come to be associated with that percentage thing at all? Doh! ).
