### ISSUE TITLE
Importers

### ISSUE THREAD

**Issue by thelucid** [less/less.js#1392]
I've just created a ticket on the Ruby bindings repo here https://github.com/cowboyd/less.rb/issues/65 but thinking that the issue may come down to Less itself.

Less assumes that `@import` statements should look for a file on the filesystem, which is not always the case for example when their content is stored in a database. 

Sass has the notion of 'Importers' (http://sass-lang.com/docs/yardoc/Sass/Importers.html), does Less have anything like this? ...otherwise it's a case of hacking up something to catch the filesystem calls and reroute them which is a horrible solution.

A much cleaner solution would be:

```javascript
var parser = new(less.Parser)({
  importer: function(filename) {
    return db.findMyFile(filename);
  },
  filename: 'style.less' // Filename, for better error messages
});

parser.parse('@import("from-bd.less"); p { .a-mixin; }', function (e, tree) {
  tree.toCSS({ compress: true });
});
```

**Comment by lukeapage** [comment]
You can now use less and plugin your own file manager which can handle file system calls.

http://lesscss.org/usage/#developing-less-how-to-run-less-in-other-environments

This was finished in v2.
