### ISSUE TITLE
Use Dynamically Generated Classes as Mixins

### ISSUE THREAD

**Issue by scottgit** [less/less.js#1399]
This request is similar (though does not seem to be exactly the same) to the closed issues of #617 and #1133. It is also related to #1325 (both there and here seeks to "use" what Jon there calls "non-existent" classes, so the solving of one may solve the other). (If I missed a more exact statement of the same issue, forgive me for posting this new one.) 

In all the issues use cases are sought, which I hope to provide here. The goal is to be able to essentially do the following (though it really becomes more powerful when in a loop structure):

Dynamically build a class name (which we can do now):

```
.myClassBuilder(@classname) {
   .@{classname} { some-properties: some values;}
}

.myClassBuilder(myName);

/* Outputs */

.myName { some-properties: some values;}
```

Then use that class name as a mixin (which currently gives a `.myName is undefined` error):

```
.my .big > .long .selector + .string {
    .myName;
}

/* Outputs */

.my.big > .long .selector + .string { some-properties: some values;}
```

Now as to reasons "why" to do it:
1. Since LESS is designed to use classes as mixins, intuitively users _expect_ it to work (this is evidenced by the links given in the following reasons).
2. [One use case is seen in this StackOverflow question trying to dynamically generate font sizing](http://stackoverflow.com/questions/17422158/less-using-classes-created-inside-guarded-mixins). _Note how the user expected it to work._ Now Martin's answer given on that question is a good _workaround_ for that case, but the workaround is still quite cumbersome compared to what the user wanted to do.
3. Another, perhaps more significant, use case is integrating with frameworks. In such a case, the framework may not be designed to make class properties accessible through a separate mixin like Martin advocated as a solution to the #2 problem. Further, the user of a framework like Bootstrap may not even know or understand the _underlying code_ of Bootstrap itself, and not realize which classes are or are not dynamically generated. [This is illustrated some in my answer on this StackOverflow question](http://stackoverflow.com/questions/15552875/less-and-bootstrap-how-to-use-a-span3-or-spanx-any-number-class-as-a-mixin), which is the same one noted in issue #1325. In such a case again, the expectation is that `.span3` would just "work" like any other class that can be used as a mixin (though there, it was really desired to be more "extended").

**The key benefit is in those instances where loops are generating numerical differences not only in class names themselves, but properties within those classes.** Being able to dynamically generate a number of classes based on whatever formula one wants, and then also being able to use those as a mixin would seem worthy of the effort to implement the feature. I hope this basic idea and the use cases here are enough to warrant a deeper look into this idea.

**Comment by adamwathan** [comment]
Sorry if this is the wrong place to ask this, but from what I can tell it does seem possible to mixin dynamically created classes in many cases, but not in others and I can't seem to get the mental model right.

Why does this example compile:

[Example 1](http://less2css.org/#%7B%22less%22%3A%22.foo%20%7B%5Cn%20%20.sm-p-1%3B%5Cn%7D%5Cn%5Cn%40spacer-1%3A%200.25rem%3B%5Cn%40spacer-2%3A%200.5rem%3B%5Cn%40spacer-3%3A%200.75rem%3B%5Cn%40spacer-4%3A%201rem%3B%5Cn%5Cn%40spacers%3A%5Cn%20%20%20%20.25rem%2C%5Cn%20%20%20%20.5rem%2C%5Cn%20%20%20%20.75rem%2C%5Cn%20%20%20%201rem%3B%5Cn%5Cn.generate-padding-utilities(%40i%3A%201)%20when%20(%40i%20%3C%3D%20length(%40spacers))%20%7B%5Cn%20%20%20%20%40size%3A%20extract(%40spacers%2C%20%40i)%3B%5Cn%5Cn%20%20%5Cn%20%20%20%20.%40%7Bfoo%7Dp-%40%7Bi%7D%20%7B%5Cn%20%20%20%20%20%20%20%20padding-top%3A%20%40size%3B%5Cn%20%20%20%20%20%20%20%20padding-bottom%3A%20%40size%3B%5Cn%20%20%20%20%20%20%20%20padding-right%3A%20%40size%3B%5Cn%20%20%20%20%20%20%20%20padding-left%3A%20%40size%3B%5Cn%20%20%20%20%7D%5Cn%5Cn%20%20%20%20.generate-padding-utilities(%40i%20%2B%201)%3B%5Cn%7D%5Cn%5Cn%40foo%3A%20~%5C%22sm-%5C%22%3B%5Cn%5Cn.generate-padding-utilities()%3B%22%7D)

```
.foo {
  .sm-p-1;
}

@spacer-1: 0.25rem;
@spacer-2: 0.5rem;
@spacer-3: 0.75rem;
@spacer-4: 1rem;

@spacers:
    .25rem,
    .5rem,
    .75rem,
    1rem;

.generate-padding-utilities(@i: 1) when (@i <= length(@spacers)) {
    @size: extract(@spacers, @i);

  
    .@{foo}p-@{i} {
        padding-top: @size;
        padding-bottom: @size;
        padding-right: @size;
        padding-left: @size;
    }

    .generate-padding-utilities(@i + 1);
}

@foo: ~"sm-";

.generate-padding-utilities();
```

...but this one doesn't:

[Example 2](http://less2css.org/#%7B%22less%22%3A%22.foo%20%7B%5Cn%20%20.p-1%3B%5Cn%7D%5Cn%5Cn%40spacer-1%3A%200.25rem%3B%5Cn%40spacer-2%3A%200.5rem%3B%5Cn%40spacer-3%3A%200.75rem%3B%5Cn%40spacer-4%3A%201rem%3B%5Cn%5Cn%40spacers%3A%5Cn%20%20%20%20.25rem%2C%5Cn%20%20%20%20.5rem%2C%5Cn%20%20%20%20.75rem%2C%5Cn%20%20%20%201rem%3B%5Cn%5Cn.generate-padding-utilities(%40i%3A%201)%20when%20(%40i%20%3C%3D%20length(%40spacers))%20%7B%5Cn%20%20%20%20%40size%3A%20extract(%40spacers%2C%20%40i)%3B%5Cn%5Cn%20%20%5Cn%20%20%20%20.%40%7Bfoo%7Dp-%40%7Bi%7D%20%7B%5Cn%20%20%20%20%20%20%20%20padding-top%3A%20%40size%3B%5Cn%20%20%20%20%20%20%20%20padding-bottom%3A%20%40size%3B%5Cn%20%20%20%20%20%20%20%20padding-right%3A%20%40size%3B%5Cn%20%20%20%20%20%20%20%20padding-left%3A%20%40size%3B%5Cn%20%20%20%20%7D%5Cn%5Cn%20%20%20%20.generate-padding-utilities(%40i%20%2B%201)%3B%5Cn%7D%5Cn%5Cn%40foo%3A%20~%5C%22%5C%22%3B%5Cn%5Cn.generate-padding-utilities()%3B%22%7D)

```
.foo {
  .p-1;
}

@spacer-1: 0.25rem;
@spacer-2: 0.5rem;
@spacer-3: 0.75rem;
@spacer-4: 1rem;

@spacers:
    .25rem,
    .5rem,
    .75rem,
    1rem;

.generate-padding-utilities(@i: 1) when (@i <= length(@spacers)) {
    @size: extract(@spacers, @i);

  
    .@{foo}p-@{i} {
        padding-top: @size;
        padding-bottom: @size;
        padding-right: @size;
        padding-left: @size;
    }

    .generate-padding-utilities(@i + 1);
}

@foo: ~"";

.generate-padding-utilities();
```

**Comment by seven-phases-max** [comment]
@adamwathan

Probably there's some bug in interpolated selector re-parsing not handling an empty value properly.

Either way this:
```less
.foo {
    .sm-p-1;
}
```
is an awful idea (by now I guess this is #1 in my "wide-spread Less anti-patterns list" as I have to fight it almost twice a day :).

Regardless of whether you generate `*-p-*;` for use in your HTML code or not, a reusable within Less itself thing shall be coded as a *normal* parametric mixin (where `sm` and `1` are mixin *parameters*, e.g.:
```less
.foo {
    .your-padding(sm, 1);
}

.your-padding(@device, @index) {
    @value: ... // get the value of interest depending no the passed parameters
     padding: @value;
}
```
See https://github.com/less/less.js/issues/3050, https://github.com/less/less.js/issues/2702#issuecomment-144727038, https://github.com/less/less.js/issues/1399#issuecomment-33680478, https://github.com/seven-phases-max/less-plugin-lists/blob/master/docs/for-adv.md#defining-mixins-quirk etc. for more details on why that `.sm-p-1;` thingy should be avoided even if possible.
