### ISSUE TITLE
Make `lessc`'s cli option `--include-path` available in client side less.js 

### ISSUE THREAD

**Issue by gitaarik** [less/less.js#1403]
`lessc` has the option `--include-path` where you can specify paths that will be used to find files when you use `@import`. Normally `@import` will look relative to the file the `@import` statement is located, but if you specify these include paths you won't have to use relative paths. Using these "absolute" imports prevents breaking your imports when you move your less files a directory higher or lower.

Unfortunately I haven't found anything about this feature in the clientside less.js. It would be nice if this would be an option. For example:

```
<script>
    less = {
        includePath: 'static/css/'
    }
</script>
<script src="less.js"></script>
```

Just like the other options documented at https://github.com/less/less.js/wiki/Browser-Options.

Here is the lessc code that processes the `include-path` option:
https://github.com/less/less.js/blob/290376f4eb57d54fbcffec97e272f42f40bb04c0/bin/lessc#L114

Today I just started looking into the less.css source. I would like to help implement this feature but I'm not sure how fast I'll be able to understand the sourcecode and implement this feature. Maybe somebody could help me get started?

**Comment by juplo** [comment]
+1 for this

I need this bind in 3rd party libraries, that I cannot change, during static local development.
