### ISSUE TITLE
Passing additional CSS directives to the whitelist from the environment

### ISSUE THREAD

**Issue by mdarens** [less/less.js#1419]
I'm attempting to get less.js working with [PrinceXML](http://www.princexml.com/), and their vendor-specific directives (notably `@prince-color`) and properties aren't prefixed with `-`. For properties this doesn't cause any issue, but the [less parser expects them in directives](https://github.com/less/less.js/blob/master/lib/less/parser.js#L1358) and will otherwise choke.
I think it would be nice to be able to pass additional allowed directives in at run time.
Does anybody else think this sounds like a good idea?

**Comment by matthew-dean** [comment]
Closing as this is implemented in https://github.com/less/less.js/pull/2783.
