### ISSUE TITLE
Log() or Debug() function

### ISSUE THREAD

**Issue by Soviut** [less/less.js#1459]
As LESS frameworks become more common, it gets harder and harder to determine if complex calculations are being evaluated as expected.

I propose a debugging function that prints to either the node console during compilation or the browser console if being run in the browser. Something simple like the console.log() we're all familiar with. If `log()` is too close to `Math.log()` then perhaps `debug()` is less ambiguous.

Ideally, multiple values could be output at once and the line number the function was called on would be very useful.

**Comment by matthew-dean** [comment]
This is dependent on the root functions PR, but this should be trivial to do as a plugin once that work is completed.

**Comment by brykov** [comment]
What's status here?
