### ISSUE TITLE
less.modifyVars not updating variables value with pixel

### ISSUE THREAD

**Issue by itsmebharat** [less/less.js#1488]
less.modifyVars not updating variables value with pixel 

For example

In less file i have created a variable like
@SCREEN_BODY_WIDTH:500px;
and using this variable like
.contentWidth
{

  width: @SCREEN_BODY_WIDTH;
## }  

Now if I want to change its value using modifyVars like

less.modifyVars({'@SCREEN_BODY_WIDTH' : '100px'}) it never changes width property and webpage using old value 500px.

Please Help!

BS

**Comment by gwmaster** [comment]
can you check why its not working for me change the @card-padding-base
AntTheme.js run
window.less.modifyVars(vars)
http://gwmaster.byethost32.com/starterProject/
