### ISSUE TITLE
Less functionality of relative when using dynamic compiler different than lessc

### ISSUE THREAD

**Issue by Deklin** [less/less.js#1510]
In our environment we operate in two modes
1. Development using the less dynamic compiler
2. Production using lessc to compile the CSS.

Our CSS structure is as followed

index.html
- Relative URL's enabled
  css/base.less
- @imports common/common.less (relative)
  css/common/common.less
- @imports less/icons.less (relative)
  css/common/less/icons.less
- Has entries for background icons e.g.
  background: url(../images/common/logo.png) no-repeat left;

So the base structure is

index.html
css/*
css/common/*
css/common/less/*
css/common/views/*
images/*

The issue we are having is as follows.

We are using the relative URL option in both the compiler and the dynamic compiler.

Dynamicly compiled CSS URL result:

url("http://127.0.0.1:8020/myapp/src/main/css/common/views/../images/common/logo.png") no-repeat scroll left center transparent

Note that the views folder is where the .less file is that contains a reference to a background image. This is in contrast to a fully compiled less file which all consolidates into one file. So the issue is the 'relative' path is wrong for the same CSS based on using the dynamic compiler vs the lessc compiler.

lessc compiled CSS URL result.
url("common/common/views/../images/common/logo.png") no-repeat scroll left center transparent

This url is even more broken.

In both cases the expected result should simply be  

url("../images/common/logo.png") no-repeat scroll left 

However if this were the case (and you manually edit the runtime style sheet, it only works for the lessc rendered page. the dynamic rendered page needs 

url("images/common/logo.png") no-repeat scroll left 

to work properly. This is because the css/base.less file we use when dynamically compiled loses the path it started in of css and changes it to the basepath where index.html is. this means ../images doesn't exist because instead images is off the root path in the dynamic version.

There is a large inconsistency here and in general some relative url issues in the lessc that still have yet to be resolved.

Any questions or clarifications, please let me know.

**Comment by seven-phases-max** [comment]
Just following up this issue with a recent similar issue I've faced at [here](http://stackoverflow.com/questions/32014887/issue-using-font-face-with-less/32015168#comment51936570_32015168) at SO: My question is *Why* font-face `src` urls are translated from relative to absolute at all? I.e. (taking @gnrlwart example) my expectation would be that `url('Roboto-Regular-webfont.woff')` should pass to the browser *as is* (with whatever proper modification according to `relativeUrls` option), just like it goes with `server-side` Less version and no `http://luna:2255/.../...` should appear there at all.

**Comment by Giwayume** [comment]
+1 please fix. Having this issue as well with font paths.

**Comment by seven-phases-max** [comment]
@Giwayume Are you sure you properly understand what is the issue above? (i.e. that it applies only to certain browser-specific situations?)

**Comment by graingert** [comment]
@Giwayume just use webpack or browserify with live reload.

**Comment by Giwayume** [comment]
Yes, I get it. I'm using the browser plugin in environments where I can't setup a nodejs server.

**Comment by graingert** [comment]
You don't need a node server in production, only to build the application or in development

**Comment by Giwayume** [comment]
I understand that. NodeJS is not approved software in my company on certain machines, even developer boxes. I won't bore you with the details, but the end result is:
**"You have a supported browser plugin that has a bug, fix it".**

I'm not looking for workarounds.

**Comment by graingert** [comment]
@Giwayume maybe try SCSS?

**Comment by matthew-dean** [comment]
@Giwayume Node.js is not a requirement, nor a browser. The Less core library is not centered around any one environment and is, in fact, generic JavaScript. What it does is load separate Environment and FileManager plugins for each environment. So, if you want to, you can create a custom environment that's neither Node.js nor "browser", that uses a file system that's database-based, whatever you want to do. All that's required is that your file manager return the contents of a file when asked.

So, Less doesn't run "on Node". It doesn't run on anything other than JavaScript. Anything platform-specific is via a plugin.

**Comment by Giwayume** [comment]
WOW this blew up lol.

_All I'm saying is +1 to the resolution of this issue._

@matthew-dean 
1. I know that nodeJS isn't a browser, it's server software that also functions as a command-line tool.
2. When I say "plugin", I mean referencing less.js in the browser `<script src="less.js"></script>`
3. This has nothing to do with file managers or databases. It's an issue where a web browser is compiling the CSS vs nodeJS compiling the CSS.

@graingert 
Not funny or practical.

**Comment by matthew-dean** [comment]
@Giwayume 

> I know that nodeJS isn't a browser

I was totally baffled what you were talking about, since I never suggested that you said Node.js was a browser. But then I re-read what I wrote. What I was saying is that neither Node nor a browser are a requirement; it was just an ambiguously phrased sentence.

My suggestion:
- Don't use the relative path option, and don't use relative paths.

Just write:
```less
background: url(/images/common/logo.png);  // remove the relative path
```

Not that, if it's a bug, it shouldn't be fixed. But I think you're backing yourself into a corner by trying to make a magic solution of relative paths interpreted the same in two environments.

**Comment by seven-phases-max** [comment]
<sub>Btw., speaking of "workarounds"... In fact, in a long run,  `relativeUrls = true` is nothing but a workaround itself. Since the paths are rewritten relatively to the root *Less file*, the links are valid *only* if the resulting *CSS file* (or HTML with resulting inline styles if it's about browser version) is located at the same level as the Less file. This covers typical development pattern of having Less files in `/less` and CSS files in `/css`, but can't obviously cover anything else.
So in general I guess library/framework authors should be encouraged (or even enforced) to provide a path variable, e.g.:</sub>
```
@lib-font-path: "../fonts/"
... {
    src: url(~"@{lib-font-path}/magic.woff");
}
```
<sub>and never rely on a particular value of the option value and/or throw it at a user.</sub>

**Comment by Giwayume** [comment]
Sorry if I'm not being clear. I'm not expecting this input:

example.less
```
body {
    background-image: url("../path/relative/to/generated/css.png");
}
```
To give this output:
```
body {
    background-image: url("localhost:8080/application/path/relative/to/generated/css.png");
}
```

LESS shouldn't be touching my URL paths and it is.

**Comment by matthew-dean** [comment]
@Giwayume In that case you should disable relative URLs, as I suggested. http://lesscss.org/usage/#using-less-in-the-browser-relativeurls

To your credit, the line here in the docs doesn't really make any sense: "When false, URLs are already relative to the entry less file." This line shouldn't even be here. Your import paths are always the same, regardless of this setting (AKAIK). All this does is turn on/off URL rewriting in ```url(...)``` statements. So, if set to false, the output is the same as input. That really has nothing to do with the original less file location.

**Comment by matthew-dean** [comment]
I'll still say that the way relativeUrls is documented doesn't really make it clear what will happen. It needs more than one line of explanation.

**Comment by Giwayume** [comment]
I think I have a fundamental misunderstanding of LESS's default behavior vs CSS. I get what you're saying, you can't fake the browsers ability to resolve paths relative to each CSS file since the final output is either a single CSS file or inline style block.

**Comment by matthew-dean** [comment]
@Giwayume Correct. In the browser, Less can't (or currently doesn't, or shouldn't) create a linked CSS file. So, it kind of has to say, "If there _were_ a linked CSS file, what would these paths point to?" And that's what's inserted into the style block for the page. So what's important is not so much that it doesn't mess with your relative URLs, it's that the rewriting Less might need to do corresponds with your intent.

**Comment by seven-phases-max** [comment]
>I'll still say that the way relativeUrls is documented doesn't really make it clear what will happen. It needs more than one line of explanation.

Yes! ([Above](https://github.com/less/less.js/issues/1510#issuecomment-131216466) me was also confused by non-naked urls in the result, and only at writing my recent post I finally realized that since it goes as inline HTML styles it just can't work like it would in a CSS file).

**Comment by matthew-dean** [comment]
This issue is marked as ReadyForImplementation. Is there actually an action item on this or should this issue be closed?
