### ISSUE TITLE
Support for "\0" media query reference (IE8 - 10)

### ISSUE THREAD

**Issue by jodriscoll** [less/less.js#1538]
`@media screen and (min-width:0\0)` & `@media screen\0`

Produces a syntax error, however, it's a valid media query usage for targeting IE9 and IE10. (http://www.impressivewebs.com/ie10-css-hacks/)

Also,
http://blog.keithclark.co.uk/wp-content/uploads/2012/11/ie-media-block-tests.php

Is there a work around for this or did I miss a fix/method on how to make this work?

Thanks,
J

**Comment by jasonwilliams200OK** [comment]
Is this still relevant?

**Comment by seven-phases-max** [comment]
@jasonwilliams200OK

Both
```less
@media screen and (min-width:0\0) {
    .box {
        width: 100%;
    }
}

@media screen\0 {
    .box {
        width: 100%;
    }
}
```
compile just fine with current Less versions.

**Comment by seven-phases-max** [comment]
Closing as fixed in a 2.x (which one?) release.

**Comment by aajahid** [comment]
I'm using lessc 2.5.1 and I just tried following syntax

    @media screen and (min-width:0\0) {
        .box {
            width: 100%;
         }
    }

And throws `'ParseError: Missing closing ')' in .....`

Was the issue really fixed or the issue came back again?

**Comment by matthew-dean** [comment]
@aajahid You're right. It no longer compiles. My guess is that it was fixed and then something reverted the fix. @seven-phases-max @lukeapage  Reopen?

**Comment by seven-phases-max** [comment]
Yep, reopening (No idea when it was broken again). Either way for these kind of hacks (notice it's not even valid CSS min-width!) it's probably would be a good idea to recommend to always recommended to use escaping to save yourself from this kind of surprises, e.g.:
```less
@media screen and (min-width: ~"0\0") {
    .box {
        width: 100%;
     }
}
```
^ Should be always fine.

**Comment by matthew-dean** [comment]
>  it's probably would be a good idea to always recommended to use escaping for IE hacks to save yourself from that sort of surprises

I don't disagree, and this should probably be added to docs. Escapes (such as in selector names) we should support, but if a value is really invalid and is a hack, yet is supported by the Less string-escaping syntax, that might be okay, as long as it wasn't accidental and is documented.

As @cloudhead said to me in #549, Less.js somewhat acts as a defacto linter (to some degree). That is, we have plenty of cases where invalid CSS will fail. If it fails here, but the value is invalid anyway, that seems ok. BUUUT the reverse argument is that these particular CSS hacks are rather common, and it would be convenient for the user to drop in examples from http://browserhacks.com/ and have them just work.

**Comment by jraadt** [comment]
Just tested this again and it still seems to be broken in the latest.

```
@media screen\0 {
    .box {
        width: 100%;
    }
}
```

**Comment by stalinb87** [comment]
+1 having the same issue here

**Comment by seven-phases-max** [comment]
Consider merging to #2207 (or vice-versa?).

**Comment by lichenhao** [comment]
I use the less import with css file which contain a css like this:
*file: http://demo.com/a.less.css*
```css
.someclass{
    width: 12px\0; /* ie8 */
}
```
the base less file ：
```
@import (less) "http://demo.com/a.less.css";
```
Then throw an error.

**Comment by seven-phases-max** [comment]
@lichenhao Works fine in up-to-date Less versions: [demo](http://less2css.org/#%7B%22less%22%3A%22.someclass%7B%5Cn%20%20%20%20width%3A%2012px%5C%5C0%3B%20%2F*%20ie8%20*%2F%5Cn%7D%5Cn%22%7D)
Either way see [escaping](http://lesscss.org/features/#features-overview-feature-escaping) and [`(inline)`] (http://lesscss.org/features/#import-options-inline) (the latter is what you need in this case instead of `(less)`).

**Comment by seven-phases-max** [comment]
Merging to #2207.
