### ISSUE TITLE
Extends, nesting and the & combinator.

### ISSUE THREAD

**Issue by pedrocorreia** [less/less.js#1554]
Hi, and first of all thank you for making and maintaining LESS.

I'm not sure if this is a bug or i'm simply not understanding the intended usage for extends, but i thought that this:

``` CSS
.foo {

    /* foo */

    &.bar {
        /* prop A */
        /* prop B */
    }

    &.baz {
        &:extend(&.bar);
        /* prop C */
    }

}
```

would result in this:

``` CSS
.foo {
    /* foo */
}
.foo.bar,
.foo.baz {
      /* prop A */
      /* prop B */
}
.foo.baz {
      /* prop C */
}
```

It does not. However writing the full selector as the extend argument works:

```
.foo {

    /* foo */

    &.bar {
        /* prop A */
        /* prop B */
    }

    &.baz {
        &:extend(.foo.bar);
        /* prop C */
    }

}
```

I imagined that the & symbol would do the same magic with extends. 
And having it not work, seemed really counter-intuitive.

**Comment by mattez** [comment]
Hi. I like LESS but... Dont you know is this is an issue in SASS too? Thank you.

**Comment by seven-phases-max** [comment]
@mattez

Not a good idea to ask if Fortran supports something at the C++ issue tracker (not counting that issue-trackers are normally not for general language questions at all) :) Consider ask at the [SO](http://stackoverflow.com/questions/tagged/sass).
