### ISSUE TITLE
Minor min/max and extract/length argument handling inconsistency

### ISSUE THREAD

**Issue by seven-phases-max** [less/less.js#1608]
I noticed this when I was updating the corresponding less/docs files:

Both `min`/`max` and `extract`/`length` are able to work with value "lists" but they do that in exactly opposite way. The `min`/`max` accept variable number of arguments but do not work with a variable having comma or space separated values (or space separated values as a single argument). Contrary, `extract`/`length` accept a list as a variable but do not work with variable number of arguments.

I.e.:
```
example {
    @list: 1, 2, 3;

    v1: max(1, 2, 3);    // OK
    v2: length(1, 2, 3); // Not OK
    v3: max(@list);      // Not OK
    v4: length(@list);   // OK
    v5: max(1 2 3);      // Not OK
    v6: length(1 2 3);   // OK
}
```

It is not a critical issue at all (should not create any real problems), but eventually I guess we would like to have more consistency there. It should not be too hard to extend all four to work with more argument variants in more similar manner (w/o changing their current 1.5.0 behaviour when it is `// OK`).

P.S. Of course it's really hard to imagine why you would want to write `length(@x, @y, @z);` to get `3`, but why not?

**Comment by seven-phases-max** [comment]
OK, since the plugin subsystem is here it's probably a good time to close requests like this. Plugins can not only add a new, but also override existing functions (though this feature is not yet strictly specified).

**Comment by matthew-dean** [comment]
Oh? You can monkey patch functions with ```@plugin```? We should add that to docs.

**Comment by seven-phases-max** [comment]
[Yes](https://github.com/less/less.js/blob/v2.4.0/lib/less/functions/function-registry.js#L4-L6). There's comment that this probably could throw a warning but it's uncertain: 
 - On one hand, if someone is advanced enough to write a plugin he is also assumed to be smart enough to decide for intentional overrides.
 - On the other hand, this has a flaw in: some plugin adds function `foo` and *later* the core also adds its `foo` too...

**Comment by matthew-dean** [comment]
> On the other hand, this has a flaw in: some plugin adds function foo and later the core also adds its foo too...

True, and that's a real risk, but I suppose I'm anticipating that inline and command-line plugins will limit the amount of new functions added to core. And..... in truth, this shouldn't cause a conflict directly, because the plugin should replace the (new) base function. If they want to use the new function, they would need to refactor / rename the custom function in their plugin.

**Comment by seven-phases-max** [comment]
Yes, for same reasons I think it should stay as is with no warnings.
