### ISSUE TITLE
Inconsistent `--strict-math` handling of certain properties (hardcoded `font` etc.)

### ISSUE THREAD

**Issue by satya61229** [less/less.js#1627]
Some magic is happening in LESS. I used 
 ceil(@font-size-base * 1.25);  
.. .
...
 ceil(@font-size-base * 1.25);  

First ceil was working but not the 2nd one. I was working with prepros downloaded recently. I checked in less2css.org there also same result. Now, it is working on less2css. 

Another, issue was with this simple line of code:
@font-size-base * 1.25;

This was also used two times in my less. One for tablet and another for desktop with different number. First one was giving calculated number but another one was giving:
0.6em * 1.5; instead of calculated value.

I put the code here using which I was trying ceil and other:

http://stackoverflow.com/questions/19705791/why-this-less-css-is-failing

Also, "1em" with quote was coming whereas expected output was 1em.

**Comment by seven-phases-max** [comment]
Merging to #1880 (since this one is impossible to "fix" w/o breaking a lot of things anyway).
