### ISSUE TITLE
Support multiple input files.

### ISSUE THREAD

**Issue by phadej** [less/less.js#1631]
At the moment:

``` sh
% lessc --version
lessc 1.5.0 (LESS Compiler) [JavaScript]
% lessc --help
usage: lessc [option option=parameter ...] <source> [destination]
```

It would be nice to change `lessc` (and underlying library) to allow multiple input sources:

```
usage: lessc [option option=parameter ...] <source> [<source> ...]

options:
  -o, --output=FILE Destination file
```

**Comment by ronkorving** [comment]
So, from the linting perspective (see issue above), that is one use-case. And I don't wanna make a single less file that imports hundreds of others (sorry, I work on big projects) just for the sake of linting them.
