### ISSUE TITLE
Define Custom Mixins via Javascript

### ISSUE THREAD

**Issue by ryanfitzer** [less/less.js#1632]
Just as custom functions can be added to `less.tree.functions`, is there any way to do the same with mixins?

This would solve a lot of problems where the declarative nature of LESS makes certain things complicated (conditionals, loops, etc.).

Apologies if I've missed where this is explained (I've been researching it for hours).

**Comment by lukeapage** [comment]
It looks like this specific feature (see description - not the side track) has been abandoned. Will re-open if disagreement.
