### ISSUE TITLE
Support for site root-relative paths with the data-uri function?

### ISSUE THREAD

**Issue by Nettsentrisk** [less/less.js#1634]
As far as I can tell, less.js doesn't currently support the use of site root-relative paths (e.g., "/images/image.png") within LESS files with the data-uri function, which requires access to the file to base64-encode it. (This problem may apply to other areas as well.)

There are currently no tests for the data-uri function that use a site root-relative path, though I understand this might be due to practical reasons.

**Comment by SomMeri** [comment]
Fixed by previous commit. Data uri function now uses paths specified through `include-path` command line option. Programmatic equivalent is property `paths`.
