### ISSUE TITLE
Support sourceMapPrefix

### ISSUE THREAD

**Issue by blittle** [less/less.js#1644]
I am super excited about source map support! One thing that would be really nice to support is a way to drop directories from the file path prefixes within the sourcemaps. This is supported in uglifyjs sourcemaps and is very useful: https://github.com/gruntjs/grunt-contrib-uglify#sourcemapprefix

**Comment by lukeapage** [comment]
In v2 I refactored the source map options to improve things a bit. If there are still problems or concerns in v2 please open a new issue.
