### ISSUE TITLE
`--clean-css` option is not compatible with `--source-map`

### ISSUE THREAD

**Issue by iki** [less/less.js#1656]
* clean-css does not currently support source maps, so the generated map is most probably incorrect: https://github.com/GoalSmashers/clean-css/issues/125
* clean-css also strips (or does not insert) the `/*# sourceMappingURL=` comment.

Example: compare
`lessc --compress --source-map style.less style.min.css`
with
`lessc --clean-css --source-map style.less style.min.css`.

It would make sense to exit with an error when both options are specified by user on command line, or throw an error if called from js, e.g. from grunt-contrib-less.

**Comment by bdkjones** [comment]
So... any word on this? It's been months.

**Comment by seven-phases-max** [comment]
@bdkjones Read the post right above yours: update `clean-css` installed with `less-plugin-clean-css` to the latest version and you're there.

**Comment by bdkjones** [comment]
I read the entire thread, thanks. The post above mine implies that it's in beta. ("[...] if people want to test [...]") I'm looking for confirmation that this is ready for use in production.

**Comment by lukeapage** [comment]
Sorry, its no longer in beta, its out.

**Comment by redfox05** [comment]
If its out of beta then that's a good thing then? Does that mean it's fixed?

**Comment by lukeapage** [comment]
It is fixed. The sorry was for not updating the issue.
