### ISSUE TITLE
Callback when client side less screen is ready

### ISSUE THREAD

**Issue by markrogers123** [less/less.js#1666]
Using client side less, it takes several seconds to render a twitter bootstrap screen.

While less is creating the css, the browser shows unstyled html.

(I use client side less so users can change less options at runtime.)

Is there a js callback or other feature which will let me hide the screen and unhide it when less has finished creating the css (equivalent of document.ready).

If not, can the facility be added?

**Comment by TWiStErRob** [comment]
`hasFinished` from #2226  has been renamed to `pageLoadFinished` in https://github.com/less/less.js/commit/8b42ae388305a9c8e38ddbbc97f0f374d96342c2

I managed to achieve this in my dev env with Less 2.5.3:
```html
<style type="text/css" id="prevent-fouc">
	body {
		display: none !important;
	}
</style>
<script type="text/javascript">
	less = {
		env: "development",
		async: true
	}
</script>
<!-- include styles and less -->
<script type="text/javascript">
	less.pageLoadFinished.then(function() {
		$('#prevent-fouc').remove();
	});
</script>
```

*Disclaimer: I support not making the user's browser compile the whole Bootstrap or any other CSS framework, it's a horrible idea: just think mobile phones have limited capacity.*

**Comment by seven-phases-max** [comment]
Closing as added in `v2.0.0`.
