### ISSUE TITLE
For debate: Allow strong typing of variables

### ISSUE THREAD

**Issue by matthew-dean** [less/less.js#1754]
Suggestion for discussion: allow variables to be strongly typed according to the types defined in Less. This would allow compiler errors to be thrown if you assign a disallowed type, and for Less editing tools to restrict input.

The syntax is up for debate, but perhaps something like this:

```
@var-color      @red: #f00;
@var-number     @num: 42;
@var-string     @str: "This is a string";
@var-url        @url: "http://google.com/"
@var-keyword    @key: true;
@var-unit       @unit: 42px;
@var-percentage @per: 12%;
```

If a Less library assigned these units, then you could enforce the typing upon usage, as in:

```
@num: "I'm going to assign a string!"

// Type error: Variable @num must be a number.
```

**Comment by matthew-dean** [comment]
Just to revisit this, TypeScript is a good example of an implementation of strong-typing for a weak-typed language: 
```js
onCellClick(evt: JQueryEventObject) {
        var x = <HTMLElement>evt.target;
        // etc
}
```
Strong types are not required, and regular JS is valid TypeScript. What it does is allow the author (or library designer), to specify expected types, and notify via a parsing error that a variable was incorrectly assigned, and so the output won't be unusable CSS, as in:
```
.block {
  height: #eee;
}
```
It also allows features like Intellisense or whatever brand of auto-complete, because the type can be more intelligently auto-completed, or you could have color-pickers for colors, etc.

It's also a helpful self-documenting tool, as a library author can specify the expected type for a variable that is used for customization.

@SomMeri - I think it would be useful if it threw an error, as an error would help protect the author from _valid_ but _unusable_ CSS. 

@rjgotten What about something like square brackets? I think some kind of enclosure might be less confusing than more colons, and also less confusing then my original syntax which just looked like extra vars.

```
.mixin( @brand[color] : value ) { }
```
As you mentioned, @SomMeri, the type could just be any of the types currently supported in the istype guards.

**Comment by seven-phases-max** [comment]
Btw., a simple way to get this is to provide a compile time `assert` function, e.g.::

@var: "foo";

div {
    width: assert(@var, isnumber(@var), "Your optional message here");
    // assert returns its 1st arg if the 2nd arg is true and throws the 3rd arg error otherwise).
}
```
with no need of any special syntax (just scetchning, I'd like to have a bit more compact/clean method).

**Comment by matthew-dean** [comment]
True. If plugins make this possible, then maybe in a plugin is where to put it.  

It just that a plugin would make this statement even more true:

> Speaking of manually written type marks (comments or keywords), I suspect it won't be so easy to persuade a library authors to use those until it is supported in many editors.

...since loading a Less plugin is not yet a trivial thing for the average CSS author.
