### ISSUE TITLE
generated sourcemaps add an extra newline...

### ISSUE THREAD

**Issue by jonschlinkert** [less/less.js#1761]
in `sourcesContent`:

```json
{
  "version": 3,
  "sources": [
    "test/fixtures/style3.less"
  ],
  "names": [],
  "mappings": "AAAQ;EACN,WAAA;EACA,gBAAA",
  "sourcesContent": [
    "#footer {\n  color: #377;\n  background: #233;\n}\n"  // here there should not be a newline after the parens
  ]
}
```
this is really a very small matter, but it causes unit tests to fail so it might be worth addressing. 

@lukeapage I'm thinking this is actually a [source-map](https://github.com/mozilla/source-map) issue, but I couldn't quite track down where the newline was being added in the build chain from grunt-contrib-less > less.js > source-map, so I wanted to bring it up here first to get your feedback.

**Comment by lukeapage** [comment]
Fixed the sourcemap issue, which just effected lessc
