### ISSUE TITLE
Extend from @import (reference) 

### ISSUE THREAD

**Issue by SomMeri** [less/less.js#1878]
Selectors from file imported as (reference) can extend rulesets in the main file. I think that nothing from reference imported file should appear in the main file, unless main file asks for it (either by extend or mixin).

The file `import-as-reference-extend.less` contains one extend:
````
.unusedAndReference:extend(.mainRuleset) {
	unused-and: reference;
}
````

and `main.less` imports it as reference:
````
@import (reference) "import/import-as-reference-extend.less";
.mainRuleset {
	main: ruleset;
}
````

It is compiled into:
```
.mainRuleset,
.unusedAndReference {
  main: ruleset;
}
```

Expected result:
```
.mainRuleset{
  main: ruleset;
}
```

Tested on windowns node.js less-1.6.3.js

**Comment by JLLeitschuh** [comment]
1+ Even if there was a work around that would be great.

**Comment by hybopressthemes** [comment]
+1

I am facing same issue. Please make it a priority, its been 1+ years since it was first reported here. 

As we use automation tools to generate css and also minify etc. So its passed onto users, and not only it adds extra bytes but also confuses users if they have a look at css files. (I know I can manually clean it up, but why should I, if I have already invested so much in automation).

Hopefully it gets solved soon, or at-least provide hack until you fix it in core..

**Comment by matthew-dean** [comment]
I just ran into a variant of this bug, in which a class that extended another class ended up in the resulting CSS, even though BOTH classes were behind an ```@import (reference)``` call. Meaning, just the presence of an ```:extend``` seems to break the ```(reference)``` feature.

**Comment by alexkrauss** [comment]
We are running into this in a highly modular setup, with particularly bad consequences:
- Many components. Each component `foo` has its own less file `foo.less`
- Everything is packaged together in the end using [webpack](https://webpack.github.io/).
- Most of these component styles import basic library material: `@import (reference) '../base-styles'`
- The library material makes frequent use of extend
- Thus we get large parts of the library duplicated, which leads to prohibitively large bundles even for just a few pages.

So, this is just to emphasize the importance of this issue :-).

**Comment by SomMeri** [comment]
This should be fixed by #2729 .

**Comment by mohammed-softordi** [comment]
@SomMeri thanks you work, is this merge released? I am having the same problem with the latest release (2.5.1).

**Comment by seven-phases-max** [comment]
@mohammed-softordi You can find if the changes were released by comparing the PR merge date (Nov 20, 2015 in this case) to the releases date in the [Changelog](https://github.com/less/less.js/blob/master/CHANGELOG.md) (the latest release is `2.5.3` of 2015-09-25).

**Comment by SomMeri** [comment]
@mohammed-softordi No it was not released yet. That pull request was finished last December while last release was in September.

**Comment by mohammed-softordi** [comment]
@seven-phases-max @SomMeri thanks, it would be really great if you could release the fix but, no pressure :-)
