### ISSUE TITLE
Namespace imported less code does not get properly referenced, when there's a (reference) keyword.

### ISSUE THREAD

**Issue by CMCDragonkai** [less/less.js#1896]
As per the discussion in https://github.com/less/less.js/issues/1895

This code:

```css
@import (less, reference) "any.css"; //this works as expected
#Namespace {@import (less, reference) "any.css";} //this does not as the reference does not do anything
```

Works in the sense that there's no syntax error.

However the reference keyword does not do anything. The entire CSS in "any.css" gets imported in the outputted CSS file.

**Comment by SomMeri** [comment]
This should be fixed by #2729 .
