### ISSUE TITLE
Phantom can not parse LESS

### ISSUE THREAD

**Issue by roelvanduijnhoven** [less/less.js#1938]
I am using `webshot` to try to generate a screenshot of a website that is compiling LESS on the client machine. However this fails. `webshot` uses `Phantom.js` as an underlying mechanism.

For example when I target this Fiddle http://jsfiddle.net/Yhcz4/23/ I get the following Phantom error in the `initFunctions` function (when I remove this line other unrelated errors pop up)

```
TypeError: 'undefined' is not a function (evaluating '_math.bind(null, Math[f], mathFunctions[f])')
```

What am I doing wrong. Or is Phantom JS simply not able to work with Less.js?

**Comment by RALifeCoach** [comment]
@lukeapage Thats for the document update. Could you also please provide an example of what that shim might look like for those of us newer to Steal, etc.?

**Comment by seven-phases-max** [comment]
@RALifeCoach
> Could you also please provide an example of what that shim might look like

It a "standard" ES5 polyfill script: [es-5 shim](https://github.com/kriskowal/es5-shim) (The link is right in the doc section @lukeapage pointed to).
