### ISSUE TITLE
Recognize :hover and put it at the end of selector

### ISSUE THREAD

**Issue by mohebifar** [less/less.js#1942]
It seems there's something unseen in LESS to me. I expect something like this in CSS:

    .animate.fade-in, .animate-hover.fade-in:hover {
      animation-name: fade-in;
    }
my LESS is :

    .animate, .animate-hover:hover {
      &.fade-in {
        animation-name: fade-in;
      }
    }
But what I get is :

    .animate.fade-in, .animate-hover:hover.fade-in {
      animation-name: fade-in;
    }
:hover's place is not right in output.

**Comment by lukeapage** [comment]
closing due to lack of response
