### ISSUE TITLE
set* versions of color channel functions

### ISSUE THREAD

**Issue by matthewwithanm** [less/less.js#1948]
Currently, most of the color operation functions modify a channel relative to its current value. (`fade` is the exception here, allowing you to specify the alpha value to use for the result, regardless of the input value.)

It would be nice if there were set\* functions for each of the color channels. For example, `setlightness(@c, @lightness)` would be equivalent to `hsl(hue(@c), saturation(@c), @lightness)` in the same way that `fade(@c, @alpha)` is to `rgba(red(@c), green(@c), blue(@c), @alpha)`.

**Comment by seven-phases-max** [comment]
Implement as plugin (first). See #1853 for more on current "new color functions" approach.
