### ISSUE TITLE
sourceMapLessInline option doesn't appear to work

### ISSUE THREAD

**Issue by macgyver** [less/less.js#1982]
I could definitely be doing this wrong (for one thing I got confused by the translation from hyphen-delimited to camelCase) but I tried passing

```
{
    sourceMap: true,
    sourceMapMapInline: true,
    sourceMapLessInline: true
}
```

as an option to the less render method, but the "sourceMapLessInline" param does not seem to be taking effect - I do see the map data being appended inline to the generated CSS file but the LESS is not being added inline, as it would be when using `lessc --source-map-less-inline --source-map-map-inline source.less destination.css`

**Comment by kmdavis** [comment]
found a one line fix for this in https://github.com/less/less.js/blob/master/lib/less/parse-tree.js#L32

if you change `options.sourceMap` to just `options` it works; the SourceMapBuilder is expecting a hash of options, not a boolean option
