### ISSUE TITLE
Feature Request: syntax to behave as other selector

### ISSUE THREAD

**Issue by egana** [less/less.js#1983]
I request the syntax to behave as an other selector, like the following:

```
.some-component {
  color: red;
}
.other-component {
  margin: 0px;
  .some-component {
    font-size: 15px;
  }
}

header {
  &:as(.other-component);
   ul {
    &:as(.some-component);
  }
}
```

which is compiled to 

```
.some-component, header  ul {
  color: red;
}
.other-component, header {
  margin: 0px;
}
.other-component .some-component, header .some-component, header ul {
  font-size: 15px;
}
```

The result style for "header" is the same as "extend(.other-component all)", but the result style for "header  ul" is different from "extend(.some-component all)" (see below).

Briefly, the above 'as' syntax make the selector behave exactly the same as other selector.
The ul element of <header><ul>...</ul></header> is styled exactly the same as the .some-component element of <div class="other-component"><div class="other-component"></div></div>, which means not only the styles for descendant selector '.some-component .other-component', but the styles for the single selector '.other-component'.
##### Difference from mixin

The following code (using mixin):

```
header {
  .other-component;
  ul {
    .some-component;
  }
}
```

is compiled to 

```
header {
  margin: 0px;
}
header .some-component {
  font-size: 15px;
}
header ul {
  font-size: 15px;
}
```

which 'header ul' element is no longer red (as .some-component).
##### Difference from extend

The following code (using extend):

```
header {
   &:extend(.other-component all);
  ul {
    &.extend(.some-component all);
  }
}
```

is compiled to 

```
.some-component,
header ul {
  color: red;
}
.other-component,
header {
  margin: 0px;
}
.other-component .some-component,
header .some-component,
.other-component header ul {
  font-size: 15px;
}
```

which 'header ul' element is no longer 15px (as '.other-component some-component')

Of course, the desired output can be obtained like the following:

```
header {
  &:extend(.other-component);
  ul {
    &:extend(.other-component .some-component);
    &:extend(.some-component);
  }
}
```

However, this code repeat the same class names twice, so have less maintainability. Moreover, the deeper the nest is, the harder this workaround is. 
##### When to be required

In usual case, this syntax isn't necessarily required, since you can use just '.some-component' and '.other-component' classes.

However, when you use some CSS framework (such as Twitter Bootstrap) but don't want to embed the framework's class directly into html (see [Please stop embedding Bootstrap classes in your HTML!](http://ruby.bvision.com/blog/please-stop-embedding-bootstrap-classes-in-your-html)), this feature is useful.
For example, Twitter Bootstrap has many components (Navbar, Dropdown etc...) and almost all of them is consist of many nested class. When introducing these components but not using Bootstrap class directly, the problem same as the above example happens.

**Comment by seven-phases-max** [comment]
Cosing as (partially) implemented with the `extend` feature. Any further improvements for `extend` need newer tickets (don't miss a few already existing though).
