### ISSUE TITLE
 The compiler does not keep empty lines and whitespaces

### ISSUE THREAD

**Issue by belyan** [less/less.js#2014]
My project is about 100 CSS files that I want to rewrite LESS.

I use the following style when writing CSS code:
- four spaces before each property;
- empty line to separate groups of properties.

For a start, I rewrote one CSS file on LESS, but after compiling 4 spaces were replaced by 2, and empty lines cut. As a consequence the output CSS file different from what it was before.

LESS file

```
body {
    color: white;

    background-color: black;
}
```

ER CSS file

```
body {
    color: white;

    background-color: black;
}
```

AR CSS file

```
body {
  color: white;
  background-color: black;
}
```

Because of this, I find it difficult to track in the version control system what changes have occurred in the CSS changes due to the compiler, or changes as a result of my mistakes in the file LESS.

Is it possible to make the compiler kept whitespace and newlines as in the original file?

**Comment by thehung2224** [comment]
Hi @belyan How did you solve your problem?
