### ISSUE TITLE
When an inline defined ruleset that contain comments with quotes is passed into a mixin, a ParseError may result

### ISSUE THREAD

**Issue by rjgotten** [less/less.js#2032]
When passing a ruleset into a mixin, it is possible to define the ruleset inline, instead of storing it into a variable up front. If such an inline defined ruleset contains comments that have an unbalanced amount of single or double quotes, then the compiler produces a parse error for unmatched quotes. E.g. 

````
.wrap(@ruleset) {
  .wrapper { @ruleset();  }
}
.wrap({
   // '
  .rule { value : test }
});
````
Leads to: `` ParseError: unmatched `'` ``

When the ruleset is stored inside a temporary variable, this issue does not occur and the correct output is produced. E.g.
````
.wrap(@ruleset) {
  .wrapper { @ruleset(); }
}

@ruleset: {
  // '
  .rule { value : test }
};

.wrap(@ruleset);
````
Correctly produces `.wrapper .rule { value: test; }`

**Comment by SomMeri** [comment]
I just tested it on current master and it worked correctly. The issue was probably fixed in the meantime.
