### ISSUE TITLE
Source map basepath does not apply to map's file property?

### ISSUE THREAD

**Issue by rla** [less/less.js#2086]
Directory structure:
```
public/css
|-- src
|   |-- config.less
|   `-- style.less
|-- style.css
`-- style.css.map
```

Command for building style.css:
```
node_modules/.bin/lessc --compress \
--source-map=public/css/style.css.map \
--source-map-basepath=public/css/ \
--source-map-less-inline public/css/src/style.less public/css/style.css
```

File `public/css/style.css` contains (as expected):
```
/*# sourceMappingURL=style.css.map */
```

But `public/css/style.css.map` contains:
```
{"version":3,"file":"public/css/style.css", ...
```

I had expected:
```
{"version":3,"file":"style.css", ...
```

However, this might not be a bug and maybe it should be possible to specify this "reverse mapping" with a completely separate parameter. In Chrome, the "wrong value" actually does not seem to cause any trouble (for now).

Less version:
```
lessc 1.7.3 (Less Compiler) [JavaScript]
```

Possibly related: #1740

**Comment by lukeapage** [comment]
this should be better now, please open a new issue if you still get issues in v2
