### ISSUE TITLE
Option to prefix functions?

### ISSUE THREAD

**Issue by stevenvachon** [less/less.js#2102]
I'm using Myth with Less.js and would prefer to use the CSS spec of `color()` and not Less.js'. I'd also prefer not to muck up my code with "tilde quotes":
```css
color: ~"color( var(--header-color) blend(var(--header-color-dark) 50%) )";
````

I see this as being similar to the `strictMath` option.

~~Essentially, I'd like to use Less.js mainly for its nesting ability only.~~

**Edit:**
Actually, I need `data-uri()`, so *disabling* options is not a great idea. **New idea in following comment.**

**Comment by stevenvachon** [comment]
Running into this issue again but with [cssnext](http://cssnext.io).

http://lesscss.org/usage/#plugins-for-plugin-authors does not mention whether access is given to Less' core functions. I haven't yet started any dev on it, but may have to for my current project.

**Comment by seven-phases-max** [comment]
>http://lesscss.org/usage/#plugins-for-plugin-authors does not mention whether access is given to Less' core functions/methods.

Nothing there's is write-protected so it's not a problem to remove core `color` function within a plugin.

**Comment by stevenvachon** [comment]
Won't that cause issues with mixing, though? Is there a way to prefix the function only in a css context?

**Comment by seven-phases-max** [comment]
>Won't that cause issues with mixins, though?

Mixins? You mean, will it break a code that uses Less's `color`? Sure, it will.

> Is there a way to prefix the function only in a css context?

Define "CSS context". Less functions can be used everywhere CSS functions can so there's no "non-CSS context" (or in other words, any CSS code you pass through the Less (except `@import (inline)) is in "Less-context").

**Comment by stevenvachon** [comment]
I was hoping to force the use of underscore prefixed functions outside of mixins only. Mixins should still support unprefixed. It makes sense that this wouldn't be possible.

**Comment by seven-phases-max** [comment]
It's possible to do the opposite (i.e. limit your `nextcss` code to a certain scope) if using ["the other" plugin format]:

```less
& {
    @plugin "your-disable-color-plugin.js";
    // here goes the code (including imports) where you want `nextcss` `color(...)`
}
```
where `your-disable-color-plugin.js` would be something like
(since there it's easier to overwrite/override the core function by "do nothing" version instead of removing the original):
```js
functions.add("color", function() {});
```
(or so, honestly I did not used this plugin format yet).

**Comment by stevenvachon** [comment]
Interesting, but the goal is to provide a means of keeping the Less CSS code as future-CSS-like as possible -- meaning that `@plugin` is litter.

**Comment by stevenvachon** [comment]
I suppose that I could write a new color function that looks for differing arguments and either returns literal input or uses existing functionality. Sounds like a can of bugs, though.

**Comment by stevenvachon** [comment]
Published [less-plugin-future-compat](https://www.npmjs.com/package/less-plugin-future-compat).
