### ISSUE TITLE
Custom Path Resolver Function Support

### ISSUE THREAD

**Issue by KenPowers** [less/less.js#2107]
It would be great if LESS could be passed a custom path resolver function to be used for imports. Something like:

```
var parser = new(less.Parser)({
  pathResolver: function (path) {
    // return location of file to be imported
  }
});
```

It could be potentially beneficial to support async path resolution as well:

```
var parser = new(less.Parser)({
  pathResolver: function (path, done) {
    done(/*resolved path*/);
  }
});
```

This would be especially handy for client-side development as, if I'm not mistaken, it appears that the `paths` option for the LESS parser doesn't do anything on the client.

Is this something somebody could easily implement?

**Comment by am11** [comment]
Hey guys, hopefully this will provide some useful pointers.

We have recently implemented a similar feature in node-sass called custom importer (https://github.com/sass/node-sass/issues/530), which basically passes the custom function to libsass (via v8/libuv). Libsass calls us back whenever it encounters an import statement.

The signature we used are bit different.

Async:

```sass
var sass = require('node-sass');

sass.render({
  file: 'blah.scss',
  success: function(result) { console.log(result); },
  importer: function(url, prev, done) { return done(processIt(url, prev)); },
});
```

Sync:

```sass
var sass = require('node-sass');

var result = sass.renderSync({
  file: 'blah.scss',
  importer: function(url, prev) { return processIt(url, prev); },
});
```

(naturally the async variant can also just return, but sync can't have a callback)

It is available in the current beta release (https://github.com/sass/node-sass/releases/tag/v2.0.0-beta). The README highlights the usage details.

This was the simple version, covering the basic use-cases of feature.

Now, what else can happen in this arena? (this probably is not the super urgent requirement) Someone may wonder: does having `prev` suffice or should there be whole import chain (up to the prev mark) returned to the user? We haven't opted for that route yet. You may want to take at the related discussion that transpired here: https://github.com/sass/libsass/pull/691.

This kind of ideas can grown crazy, so the simple version would do the job.  Besides, the API consumers can always keep track of imports, given they have option like https://github.com/xzyfer/sass-graph/, which can provide info about the file in terms of graph nodes. After all it is the node.js world; plug, play and reuse stuff! :)

**Comment by KenPowers** [comment]
@am11 -- LESS 2.x actually now has plugins. Check out the [`less-plugin-npm-import`](https://github.com/less/less-plugin-npm-import) project.

It would seem that the syntax they landed on is:

```less
@import "npm://package/file";
```

So theoretically, plugins can do anything we want.
