### ISSUE TITLE
Parsing Error "Unrecognised input" for color operations with color names

### ISSUE THREAD

**Issue by BoffoF** [less/less.js#2124]
Hi,

when you use color names (e.g. yellow) in operations it leads to Parsing Error "Unrecognised input", for example:
 
x{x:(yellow - #070707)} 

When using additional parameter with color name it is working, for example

@myColer : yellow;
x{x:(@myColer - #070707)} 

From my point of view the first approach should also work. Can you please try to fix it on your side?

Best regards,
Florian

**Comment by SomMeri** [comment]
Fixed by #2775
