### ISSUE TITLE
rootpath doesn't work on absolute URLs

### ISSUE THREAD

**Issue by sbrandwoo** [less/less.js#2129]
I was hoping to use the `rootpath` option to prefix all of my URLs with "http://static.example.com/", and the documentation says:

> Allows you to add a path to every generated import and url in your css.

Actually this only works on relative URLs, not absolute ones. In this case I imagine you just need to update the documentation to reflect this, or should the option be expanded to cover the absolute case as well?

**Comment by lukeapage** [comment]
@sbrandwoo I cannot reproduce. I used the following command 

```bash
lessc test/less/urls.less -rp=http://www.blah.co.uk/test/
```
and
```css
uri: url('../data/data-uri-fail.png');
```
change to...
```css
uri: url('http://www.blah.co.uk/data/data-uri-fail.png');
```
