### ISSUE TITLE
Client-side use: @imported file from /bower_components wasn't found

### ISSUE THREAD

**Issue by machal** [less/less.js#2131]
I'm compiling relative complex LESS file from browser with these parameters:

```
<script>
  less = {
    env: "development",
    async: true,
    relativeUrls: true,
    poll: 100000
  };
</script>
```

In one of my nested LESS files there is direct import from bower_components/ folder inside my project:

```
@import "../../../../../../bower_components/responsive-navigation/src/stylesheets/pine.less";
```

During compilation I'm getting this error message:

```
FileError: 'http://../bower_components/responsive-navigation/src/stylesheets/pine.less' wasn't found (0)
in site_nav.less on line 48, column 1:
```

I was hoping there is some parameter like `relativeUrls` but for @imported files URL, but how it seems it works for CSS `url(…)` constructs only.

Any ideas how to solve it?

**Comment by lukeapage** [comment]
closing due to lack of response?
