### ISSUE TITLE
Cannot put import by reference inside of a mixin

### ISSUE THREAD

**Issue by blakemann** [less/less.js#2162]
I have been working on a complex importing strategy where I set all of my paths in a config file, and then use a mixin to import various different components as needed.

This approach doesn't seem to work well with files imported by reference, however. It seems that importing a file by reference inside of a mixin in this way causes it to output all of the contents of the file, and not just what is used.

To give you a very simplified example, I have something like this:

```
// config.less

// Normally the sub-mixin calls would be controlled by variables passed in, but for simplicity, let's say both get called always
.importer(){
    .import-certain-file();
    .import-last-file();
}

.import-certain-file(){
    @import "certain-file";
}

.import-last-file(){
    @import (reference) "last-file";
}
.import-last-file();

```

```
// certain-file.less

h1 {
    color: black;
}
```

```
// last-file.less

._color-white {
    color: white;
}
```

```
// main.less

@import "config";
.importer();

h1 {
    &:extend(._color-white);
}
```

So, `certain-file.less` contains a rule setting `h1` to be black, but I want to override that in my main less file.. using a class name that was specifically made to be extended (imported by reference so that the original class name of `._color-white` is not output into my code)

But that messes with the (reference) import, giving me this final output:

```
h1 {
    color: black;
}
._color-white, h1 {
    color: white;
}
```

Which technically works, but means I've got extra unwanted selectors being dropped into my code.. which is especially bad when in reality, my `last-file.less` is a big file full of "extension" classes, many of which don't even get used on every project.

I believe the problem lies in the fact that importing by reference inside of a mixin causes all styles inside that file to be output, rather than just when they are used.

**Comment by SomMeri** [comment]
This should be fixed by #2729 .
