### ISSUE TITLE
code comments 

### ISSUE THREAD

**Issue by jonschlinkert** [less/less.js#2167]
This isn't really a request, just thinking out loud.

@lukeapage, for v2.0, would you be opposed to using block comments in the code instead of line comments? If so, we can automatically generate the actual API documentation (e.g. not the user docs, but at least API docs) directly from the code comments. Some devs find the comments distasteful. I like using them because it saves work and helps others to get more involved. 

[The readme on this repo](https://github.com/jonschlinkert/options-cache) is a good example of what I mean. The tool I use automatically extracts the comments and generates the markdown documentation. It also generates the heading with line numbers and links the actual actual code.  It can also generate multi-file tables of contents automatically. Currently, only comments that have `@api public` are included in the generated result, but any kind of filters could be implemented.

One other upside to this is that we can take the resulting markdown files and have assemble automatically generate the HTML pages. 

There are only a few conventions that need to be followed for the docs to generate successfully. if this is interesting to you, let me know and I'll put some bullets together.

**Comment by matthew-dean** [comment]
Closing as suggested by @lukeapage a while ago. Specific PRs can be made to add comments or a larger project could be tracked in less-meta.
