### ISSUE TITLE
`&:extend(...);` in detached rulesets is interpreted as a `property: value;` statement

### ISSUE THREAD

**Issue by seven-phases-max** [less/less.js#2179]
Minimal example:
```
@expand: {&:extend(b);};

b {color: red}

c {@expand();}
```
Expected result:
```
b, c {
  color: #ff0000;
}
```
Actual output:
```
b {
  color: #ff0000;
}
c {

}
```
Same goes for `c:extend(...);` but in that case it's expected (see below).

---
Offtopic: hmm, that's interesting, only now I realized that indeed that `&:extend(...);` construction is weird (because it *does* have `property: value;` syntax), so in this context the following inconsistentinces jump out:
```
// conventional CSS ruleset:
a {
    &:extend(b);   // OK, extend
    c:extend(b);   // OK, but interpreted as property: value; (expected)
    c:extend(b) {} // OK
    &:extend(b) {} // Error (unexpected)
}
```
(I guess this probably was already noticed in earlier threads but I can't find it quickly).

**Comment by lukeapage** [comment]
This is actually working now.. no idea who or what fixed it...
