### ISSUE TITLE
Keep within Scope

### ISSUE THREAD

**Issue by micchickenburger** [less/less.js#2193]
It seems to me the less.js browser library assumes it will always be a global variable, but it shouldn't.  For example, I can scope the library like so:

### less-1.7.5.js (Initial):
    (function (window, undefined) {
        ...
    })(window);

### less-1.7.5.js (Scoped):
    window.myAPI = {};
    (function () {
        this.less = function (window, undefined) {
            ...
        };
    }).apply(myAPI);

### Dynamically load a page in an iframe that contains LessCSS:
    var iframe = document.createElement('iframe');
    iframe.src = 'someFile.html';
    iframe.addEventListener('load', function (event) {
        this.contentWindow.less = {
            errorReporting: 'console',
            globalVars: {}
        };
        myAPI.less(this.contentWindow);
    });

This should work perfectly well, except that a few statements (particularly when executing `myAPI.less.refreshStyles()`) reference the parent page's document element instead of the contentDocument from within its scope.  Replacing each instance of `document.` to `window.document.` repairs the issue.

**Comment by SomMeri** [comment]
I think that this could be closed?

**Comment by micchickenburger** [comment]
I appreciate the help!
