### ISSUE TITLE
Recursive rulesets and extending rulesets

### ISSUE THREAD

**Issue by matthew-dean** [less/less.js#2211]
I've just started playing with rulesets, and I had this construction.

```
//core.less
#library {
  .nav() {
    @list: {
      display: block;
      other: property;
    };
  }
}
```

I wanted to try overriding the detached ruleset. So far, so good.

```
//overrides.less
#library {
  .nav() {
    @list: {
      display: inline;
    }
  }
}
```

Works awesome! BUT... then I thought, "Hmm, what if someone wanted to keep the existing ruleset and just extend it." I knew I couldn't use extend because there was no selector, so I tried this (even though I figured it wouldn't work).

```
//overrides.less
#library {
  .nav() {
    @list: {
     @list();
      display: inline;
    }
  }
}
```

At that point, the compiler locked up and was unrecoverable.

Now, granted, I wrote what looks like an obvious recursion loop. Clearly my fault. That said, I'm wondering if there's a way to detect / escape / throw an error when this occurs?

**(Follow up ?'s: is there a way to 1. extend a ruleset, 2. reference a ruleset via a namespace like: `#library > .nav() > @list();` rather than needing to write `#library > .nav() { @list(); }`. I didn't see this in the docs.)**

**Comment by matthew-dean** [comment]
As a follow up to this, this is how I solved extending vs. overriding.

```
//core.less
#library {
  .nav() {
    @list: {
      display: block;
      other: property;
    };
  }
}
// override
#library {
  .nav() {
    @list: {
      override: ruleset;
    };
  }
}
// extend
#library {
  .nav(list) {
    extend: value;
  }
}
// mixins.less
#library {
    .nav(@item) {
        #library.nav();
        @rules: @@item;
        @rules();
    }
}
// rendering
ul {
  #library.nav(list);
}
```

**Comment by matthew-dean** [comment]
Even though I found a solution, I still think this should be left open, because the compiler should detect unrecoverable loops and throw an error, not lock up.

**Comment by seven-phases-max** [comment]
That's quite neat pattern.
(Before DRs I used something like [this](https://gist.github.com/seven-phases-max/11ef1b12145baa97fadd), but the method there is obviously limited to a single override).

**Comment by matthew-dean** [comment]
Thanks, it took me about 30 iterations to come up with that pattern. I'm building it into an OOLESS library, so it will have a production use at some point.

**Comment by seven-phases-max** [comment]
Closing as expected behaviour.
