### ISSUE TITLE
Unexpected render result for browser version

### ISSUE THREAD

**Issue by Justineo** [less/less.js#2242]
Input: `x` (only one letter, any letter in fact)
Output (node): `ParseError: Unrecognised input in ...`
Output (browser): empty string

Input: `xx` (two letters)
Output (node): `ParseError: Unrecognised input in ...`
Output (browser): `Parse error: Unrecognised input. Possibly missing something`

F.Y.I.
I'm compiling Less code using `less.render` (2.0.0-b2) / `parser.parse` (1.7.x and below) in browser environments.
See results [here](http://ecomfe.github.io/est/fiddle/#est=false&code=eHg%3D).

**Comment by lukeapage** [comment]
I actually find it fails in node and the browser. Anyway, added a test and fixed.
