### ISSUE TITLE
when using data-uri with svg, should it default to url instead of base 64 encoding

### ISSUE THREAD

**Issue by lukeapage** [less/less.js#2250]
As per #2184 and #2249 we cannot remove encoding, but it would be better to not require people to specify a mime type to stop base64 encoding.

Would need to ensure that this applies to all svg files.

**Comment by matthew-dean** [comment]
Nope: CanIuse.com confirms IE must have base64 encoding, so that must be the default: http://caniuse.com/#feat=datauri

**Comment by matthew-dean** [comment]
The commit should probably be reverted to base64 by default for SVG.

**Comment by lukeapage** [comment]
@matthew-dean try it first - http://dbushell.com/demos/svg/utf8uri/test2.html
as long as it is url-encoded, it works. non-url-encoded does not work in IE, thats true, but less url encodes..
