### ISSUE TITLE
data-uri function does not respect the "paths" parameter when used via programmatic API

### ISSUE THREAD

**Issue by aldendaniels** [less/less.js#2275]
I encountered this issue when using [Lessify](https://www.npmjs.org/package/node-lessify).

The LESS programmatic API accepts a `paths` parameter:
```javascript
less.render('.myclass {...}', {paths: '/a/b/c/'}, function(error, css) {
   ...
});
```

`@import` directives correctly resolve file paths relative to the directories in the `paths` array.

The `data-uri()` function, by contrast, appears to ignore the `paths` option - all file paths are resolved relative to the working directory of the node process that invoked the LESS compiler.

--------------
Needless to day, LESS is an addictively useful tool. Thanks for creating it!

**Comment by SomMeri** [comment]
Fixed by previous commit.
