### ISSUE TITLE
 Incorrect summation colors?

### ISSUE THREAD

**Issue by nicothin** [less/less.js#2291]
less:
<pre>p {
  color: rgba(255, 0, 0, 0.75) + rgba(0, 255, 0, 0.75);
}</pre>
css:
<pre>p {
  color: rgba(255, 255, 0, 0.9375);
}</pre>
Where did the value of 0.9375?
0.75 expected in the alpha channel.

**Comment by tomekwi** [comment]
> cunning unexpected algorithm

@nicothin this behaviour goes inline with that of Photoshop, Inkscape, Gimp and any other image editing program I know. Try overlapping two half-transparent rectangles over a transparent background and see what you get.
