### ISSUE TITLE
Add support for partials

### ISSUE THREAD

**Issue by hanifbbz** [less/less.js#2295]
We've put our company branding guidelines in SASS format and released it as a private bower package. It basically includes brand colors, fonts, etc. These guidelines are broken into several partials:

````
_fonts.scss
_colors.scss
company.scss  //@import "fonts"; @import "colors";
company.css   //the result of compiling company.scss
````

This works fine. Anyone who is doing a SASS project in our company basically `bower install`s the company guidelines and either imports those SASS partials to build upon that (for example customizing their CSS library of choice based on our brand colors) or directly uses the CSS.

The SASS compilers by convention don't create a CSS for files that start with an underscore. For less however, it's a different story.

````
_fonts.less
_fonts.css       //the useless output of the fonts file (mostly variables and paths)
_colors.less
_colors.css      //the useless output of the colors (mostly variables and mixins)
company.less     //@import "fonts"; @import "colors";
company.css      //the result of compiling company.scss
````

Would it be possible to support this convention in LESS? I know about issue #2042 and that's basically a confusion. Some people however claim that LESS partials exist: https://www.playframework.com/documentation/2.0/AssetsLess

I think partials is a very neat feature that allows organizing your code without worrying about configuring your automated build tools to follow these conventions. Here is the partials documentation from SASS:

> You can create partial Sass files that contain little snippets of CSS that you can include in other Sass files. This is a great way to modularize your CSS and help keep things easier to maintain. A partial is simply a Sass file named with a leading underscore. You might name it something like _partial.scss. The underscore lets Sass know that the file is only a partial file and that it should not be generated into a CSS file. Sass partials are used with the @import directive.

**Comment by iampivot** [comment]
Maybe this could be supported by a plugin? Netbeans does the same thing, trigger compile for saved partials, which ends up compiling both the partial and the file including it.

**Comment by seven-phases-max** [comment]
@iampivot

>Maybe this could be supported by a plugin? 

What exactly? Yet again, `lessc` does not (and should not) decide what it compiles and what it does not. *You* do this.

>Netbeans does the same thing, trigger compile for saved partials, which ends up compiling both the partial and the file including it.

Then it's a matter of fixing/reconfiguring the Netbeans itself to this this in a proper way (or raise a bug report there if it's not possible).

---
Either way you can always replace `lessc` with you own script and/or batch-file (to be called from Netbeans) that filters files to be compiled by some mask.
