### ISSUE TITLE
Is a space not valid before an operator?

### ISSUE THREAD

**Issue by codecowboy** [less/less.js#2305]
works:

```
#mypara {
  color: @color;
  border: @basethickness solid black;
  padding: @basepadding @basepadding+20;
}
```
not working:
```
#mypara {
  color: @color;
  border: @basethickness solid black;
  padding: @basepadding @basepadding +20;
}
```
compiles to '  padding: 10px 10px 20;' 

In case it is relevant, I am using grunt to compile less using grunt-contrib-less

**Comment by seven-phases-max** [comment]
I'd say it's perfectly expected. It may be confusing at first (you don't face this in other languages because most of them do not have whitespace as an array delimiter) but it's hard to invent a rationale for any other behaviour.
