### ISSUE TITLE
Rhino Support in 2.x

### ISSUE THREAD

**Issue by renoth** [less/less.js#2316]
How does Rhino support work in 2.x? I noticed that the information on the webpage is outdated because there is no less-rhino in 2.x although the website states:
http://lesscss.org/#command-line-with-rhino

"Each less.js release contains also rhino-compatible version."
and
"java -jar js.jar -f less-rhino-<version>.js lessc-rhino-<version>.js styles.less styles.css"

How does one proceed here?

**Comment by xtracoder** [comment]
It would be nice to at least update [documentation](http://lesscss.org/#command-line-with-rhino), which currently says ...
> Each less.js release contains also rhino-compatible version.

... and causes waste of time trying to find the way to run LESS 2.x with Rhino.

**Comment by topera** [comment]
Yes.....I also wasted precious time because of this...

**Comment by matthew-dean** [comment]
Unfortunately, there aren't active maintainers who know anything about Rhino. Without expertise in Rhino, the maintenance of that piece has fallen by the wayside.

I would propose that someone make a separate less-rhino repo that's more dedicated to this piece, and that this is removed from the main less.js repo.
