### ISSUE TITLE
data-uri does not accept fragment only value in URLs

### ISSUE THREAD

**Issue by BarakChamo** [less/less.js#2320]
This is an existing issue relevant to this closed issue.
https://github.com/less/less.js/issues/1959

The generated url is incorrect if a reference is made to an inline SVG and not an external file:

CSS (in folder 'components'):

    path.nv-line {
        marker-mid: url('#line-marker');
    }

Inline SVG:

    <defs>
        <marker id="line-marker">
             <circle cx="6" cy="6" r="5"></circle>
        </marker>
    </defs>

The URI generated:

     'components/#line-marker'

[An example of using inline SVG references](http://jsfiddle.net/Zv57N/)

**Comment by lukeapage** [comment]
is `components/#line-marker` valid? It seems to me that if it refers to the page context rather than the less context then it seems okay to make an exception for url's that are just `#.*` ?
