### ISSUE TITLE
Variable interpolation in an import not working if file includes an inline css statement

### ISSUE THREAD

**Issue by dcneiner** [less/less.js#2336]
I ran into this tonight when trying to use lessc 2.1.1 to compile LESS for my application. 

I was inlining some CSS files (normalize.css, etc) using the `@import (inline) "...";` syntax and in the same LESS file, further down I was using variable interpolation to `@import` a theme file (a variable I would pass in via `globalVars`). I made a [reduced test case](https://gist.github.com/dcneiner/f80dadd099922c60be43) to reproduce the issue. The error that is thrown from my test case is this:

```
undefined_methodError: Object /* Normal CSS Stuff*/

html, body { font-size: 16px; }
 has no method 'variables' in /Users/DougN/Development/lessbug/site.less on line 5, column 1:
```

The following is the minimum code needed to see the error (plus the referenced files):

```less
@import (inline) "include.css";

@themeName: "sample";
@import "@{themeName}.theme.less";
```

[Here is a gist](https://gist.github.com/dcneiner/f80dadd099922c60be43) with all three files from the test case. The easiest way to reproduce is to [download the files](https://gist.github.com/dcneiner/f80dadd099922c60be43/download) from the gist, then from the command line compile it with `lessc`:

```sh
lessc site.less
```

Simply removing the `@import (inline) "include.css";` line keeps the bug from occurring.

In my live app code, I even tried `@importing` the inlined CSS files in a separate LESS file from the one where I was attempting variable interpolation, but the error still occurred.

**Comment by leigeber** [comment]
I am also seeing this issue. If the css file is renamed to less everything works but not when imported inline as css.

**Comment by lukeapage** [comment]
Thanks for the report, I will try and get it fixed this w/e.
