### ISSUE TITLE
Client-side use: HTML Import support

### ISSUE THREAD

**Issue by Jamtis** [less/less.js#2345]
Hi there,

I'm recently working with [polymer](https://polymer-project.org) elements are they are pretty cool.

Polymer elements are (dynamically) embedded via [HTML Imports](http://www.html5rocks.com/en/tutorials/webcomponents/imports/).

**The problem:**

A `<link rel="stylesheet/less">` tag in an imported element is **not recognized** neither the `<script src="less.js">` is in the imported nor in the main document...

This issue does not only apply on polymer but on all HTML import based elements which - I think - makes it quite an important feature to have.

**Example:**

I committed a version of the project at which I discovered this technology could be quite handy.

[Here's the commit](https://github.com/Jamtis/Gravis/tree/e700930348e3fa5828c15b0ace7d71ced269acd7) and a direct link to the [demo](https://rawgit.com/Jamtis/Gravis/e700930348e3fa5828c15b0ace7d71ced269acd7/gravis-sigmajs/demo/demo.html) which lies at /gravis-sigmajs/demo/demo.html.

**A little explanation:**
gravis-sigmajs/gravis-sigmajs.html defines an element which contains a certain less stylesheet as a `<link>` tag.

This `<link>` is not recognized because it is not in the main document.

**Recommendation:**

I suggest to scan for `<link rel="import" href="path/to/element.html">` in the main document, follow the imported documents and scan them just like the main document but add the compiled `<style>` tags in the **imported document** to avoid inconsistencies.

So, what do you think?
Do you also see the need for this feature or is there another way that's better suited?

**Additionally:**

In regard to [ShadowDom](http://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-201/) scanning shadowRoots could be handy too.

Greetings

Nicholas

**Comment by lukeapage** [comment]
Using less in the browser as a development tool is outdated - better to compile on the server and use live reload.
Using less in the browser for production is a bad idea unless really required - and its probably not required in the browser in conjunction with html imports.
I may be wrong of course, feel free to argue why its useful.

If you do want it, less exposes methods for processing stylesheets (though its not a perfect API, we'd like to improve) I would encourage any improvements in API (if required) to allow you to write a extension to less.js core that does this, it shouldn't be too hard.

**Comment by Jamtis** [comment]
It seems to me that it's a discussion about the client-usage in generell.
If the client-usage is further supported actively (?) then I plead for implementing it.
As I guess their is no active support for client-usage so any feature request would be obsolete.
What's the future direction of the client-usage?
