### ISSUE TITLE
Extend looses @supports from a file imported by reference

### ISSUE THREAD

**Issue by SomMeri** [less/less.js#2359]
Extend does not output `@supports` located in a file included with reference import option.

Imported file file1.less:
````
@supports(display: flex) {
  .class1{
    display: flex;
  }
}
````

Main file test.less:
````
@import (reference) "file1.less";

.class3{
  &:extend(.class1);
}
````

Less.js output:
````
<empty>
````

Expected output:
````
@supports(display: flex) {
  .class3 {
    display: flex;
  }
}
````

**Comment by ddprrt** [comment]
@media works fine.

**Comment by lukeapage** [comment]
Not surprising, they are handled in different ways.
Really they should extend the same base class and then `@support` would support bubbling like `@media`

**Comment by ddprrt** [comment]
Does `@media` has any special features which have to be considered for the output? Would suggest an `AtRule` class handling both.

**Comment by lukeapage** [comment]
Yes, the way media conditions are combined. We have a directive node
already for 'at rules'. I would consider

Directive
DirectiveRuleset
  BubblingDirectiveRuleset (abstract)
    Media
    Supports

At the mo it is

Directive
  Media

**Comment by SalmanPK** [comment]
+1 for bubbling support.
