### ISSUE TITLE
@import "not-a-css" statement included in rendered css

### ISSUE THREAD

**Issue by pribilinskiy** [less/less.js#2364]
Whenever a trailing `css` is encountered by `@import` statement, the `@import` statement is included in the rendered css (and that leads to errors).

Examples:
```
@import "some-file-css";
@import "whatevercss";
```

Expected that a corresponding `"some-file-css.less"` and `"whatevercss.less"` files will be imported

**Comment by lukeapage** [comment]
yes, its a bit unfortunate.

I know people have used

```
@import "fileonweb.php#css";
```
in order to get it to load as a css file, before we had import options.

The work-around is to use

```
@import (less) "filecss";
```

I think we should fix it and probably make it see css in url params.

**Comment by lukeapage** [comment]
This is the common example
```less
http://fonts.googleapis.com/css?family=Open+Sans
```

**Comment by pribilinskiy** [comment]
Didn't thought about those use-cases
Thanks!

**Comment by maxbrunsfeld** [comment]
Is it intended that `@import "some-directory/css` produces a CSS import?
