### ISSUE TITLE
Automatically simplify redundant selectors when parsing nested rules

### ISSUE THREAD

**Issue by SolusSoftworks** [less/less.js#2365]
When styling a page using LESS a user may create something like this:

    #wrapper {
      margin: 0 auto;

      #sidebar {
        float: right;
        width: 300px;
      }

      #main {
        margin: 0 auto;
      }
    }

The above code when parsed by LESS would produce a CSS file like so:

    #wrapper {
      margin: 0 auto;
    }

    #wrapper #sidebar {
      float: right;
      width: 300px;
    }

    #wrapper #main {
      margin: 0 auto;
    }

This is fine and will produce the expected result however, it generates selectors with redundant ID's: `#redundantID #styledElement { property: value; }`. An ID attribute should be unique so there can never be a case where that redundant ID would be different.

Obviously the user could simply choose not to nest those styles though that would then make the LESS code less logical and make it harder to locate those styles. It would be preferable if LESS automatically cut off anything in the selector before that last ID selection in order to keep the resulting CSS as logical and minified as possible. 

Anything before the last ID in the selector can be omitted as long as there are no pseudo class (`:hover`) or attribute (`[title="foo"]`) selectors which check a parents status as the user could be applying different styles based on the status of a parent.

Some examples of this functionality: 
- `#wrapper #main` can become `#main`
- `a img#logo` can become `#logo`
- `a:hover img#logo` can't be reduced to `#logo` but can become `a:hover #logo`

The following code should return the optimized selector when provided the current selector string though is probably poorly written and needs optimizing. :P

    function minifySelector(s)  {
      var sArr = s.split(/(:[a-z]+|\[.+\])/g); //split selector at pseudo classes and attributes
      var minifiedString = '';
      
      //loop through array and minify strings
      for (var i = 0; i < sArr.length; i++) {
        //check if needs minifying
        if (/(:[a-z]+|\[.+\])/g.test(sArr[i]) == false) {
          minifiedString += minify(sArr[i]);
        } else {
          minifiedString += sArr[i];
        }
      }
      
      return minifiedString;
    }

    function minify(s) {
      var pos = s.lastIndexOf("#"); //find location of final ID
      if (pos >= 0) {
        //check if string starts with a space (needs to be preserved)
        if (s.charAt(0) == " ") {
          return " " + s.slice(pos);
        } else {
          return s.slice(pos);
        }
      }
      return s;
    }

**Comment by lukeapage** [comment]
I don't think its less' job to change selectors like this.

Correct me if I am wrong but although id's are meant to be unique, they do not have to be - someone can make a page with 6 id's and a selector with 2 id's to select it.

I would suggest that people refactor their code and use a namespace if you want to keep selectors together e.g.

```less
/*Wrapper Code*/
& {
  #wrapper {
    margin: 0 auto;
  }

  #sidebar {
    float: right;
    width: 300px;
  }

  #main {
    margin: 0 auto;
  }
}
```

**Comment by SolusSoftworks** [comment]
While it is true that ids do not have to be unique in that no errors will be shows should you use them, there is no situation when developing in a way which honors the specification where you would need to select elements with such specificity or would benefit from doing so. For cases where it would make a difference to the resulting webpage you should be using classes anyway.

While using namespaces would work to a certain extent it detracts from the whole point of using a pre-processor in the first place. Nesting allows you to easily show the logical structure of the HTML and allows you to edit most LESS styles without ever needing to look at the markup. 

The whole point of LESS is to make the CSS more maintainable. Nesting style definitions in such a way allows you to show the relationship between elements. This is important for certain position styling. It allows you to see which element will be the container for absolutely positioned elements as well as how child flex elements will be arranged in the parent.

I believe it IS LESS' job to change selectors like this when dealing with nested rules as it is LESS that generates those rules. I'm not saying that this should be something which needs to be changed and thus potentially break existing code. Obviously, it would be wise to include it as an option which is off by default as the standard minification is for those of us who adhere to standards and prefer to keep the code as simple as possible.

**Comment by seven-phases-max** [comment]
-1 (not even commenting since it's already enough rationale for not writing such nice examples of ridiculous nesting elsewhere).

**Comment by lukeapage** [comment]
Sorry, I don't think this is something we want to add to less core.
