### ISSUE TITLE
Visitor plugin: adding rules

### ISSUE THREAD

**Issue by aarontam** [less/less.js#2371]
We are currently using LESS 1.7.x and want to come up with a solution for this version. What is the recommended way to add rules using a visitor plugin? More specifically, we conditionally want to add some media query rules based on our inspection of nodes we are visiting. I had a difficult time finding much documentation on visitor plugins, so if this exists somewhere I would love to have a reference to it, as well. Thanks!

**Comment by lukeapage** [comment]
We don't have alot of documentation, but we use it internally, so the best way of learning is through examples.

The inline-images plugin replaces one node with another.. notice the isReplacing which means that every implemented function needs to return the node's replacing the current one.

https://github.com/less/less-plugin-inline-urls/blob/master/lib/inline-images.js

if you return an array (e.g. when processing a rule you return 2 rules in an array) it will be flattened

If you return null or an empty array then the current node will be removed.

See the visitors here that are used internally:

https://github.com/less/less.js/tree/master/lib/less/visitors

the tocss visitor is also a simple example, mostly removing nodes not to be output, but its the same principle.

https://github.com/less/less.js/blob/master/lib/less/visitors/to-css-visitor.js

**Comment by aarontam** [comment]
@lukeapage Thanks for the info! We'll see what we can do with that, otherwise we may take a step back and attack the problem from a different angle.
