### ISSUE TITLE
modifyVars does not work with string path 

### ISSUE THREAD

**Issue by jimmyphong** [less/less.js#2372]
i try to work with less js and available string path in less

code

available.less

        @image-path : "/assets/images";

        @bg-image : "/bg/01.png";

style.less

      @import "available.less";
       body{
           background: url('@{image-path}@{bg-image}') repeat top left;
       }

in javascript 

       less.modifyVars({
		'@bg-image' : "/bg/08.png"
	});

i get error ParseError: Unrecognised input

@bg-image: /bg/08.png;

how to fix it

so if i change modifyVars to 

       less.modifyVars({
		'@bg-image' : "'/bg/08.png'"
	});

with value wrap in double quote + single qoute it work !

Thanks

**Comment by lukeapage** [comment]
I think thats what you have to do.. its hard to guess whether its a string
or a value or a color etc.

**Comment by seven-phases-max** [comment]
Yep, this is expected since `'@bg-image' : "/bg/08.png"` means `@bg-image: /bg/08.png;` which is invalid Less statement. In JavaScript you have to use double quotes there (one pair of quotes is for JS and the second pair is for Less).

**Comment by gnextia** [comment]
hi, try the following example

var less = require('less');
less.render("@icon-font-path: '../lib/bootstrap/fonts/';  .class { src: @icon-font-path };", {
    "compress" : false,
    "modifyVars" : {'icon-font-path':"'fonts/'"}
}, function(e, output) {
    console.log(output.css);
});

**Comment by seven-phases-max** [comment]
Closing as expected behaviour.
