### ISSUE TITLE
Using less in the browser in production mode broken in 2.2.0

### ISSUE THREAD

**Issue by scottohara** [less/less.js#2381]
I realise that in production it’s better to precompile less -> css;  but it seems that since 2.2.0 the production mode is broken (I think?).

Here’s what I think is happening; but I’ll need someone more familiar with the code and it’s intended design to confirm if this is a genuine issue.

#### Activating production mode
When less is:

* run in the browser AND
* the host is not local (ie. 0.0.0.0, 127.0.0.0, localhost) AND
* the port is standard (80/443) AND
* the env is not explicitly set to development (eg. `<script type="text/javascript" src=“less.js" data-env=“development"></script>`)

....the mode defaults to 'production', and *.less files are cached in localStorage.

#### Caching behaviour
The [code that fetches](https://github.com/less/less.js/blob/master/dist/less.js#L177) the cached CSS from localStorage returns the data if the lastModified timestamp matches:

```
getCSS: function(path, webInfo) { 
  var css = cache && cache.getItem(path), 
        timestamp = cache && cache.getItem(path + ':timestamp'); 

  if (timestamp && webInfo.lastModified &&
    (new Date(webInfo.lastModified).valueOf() ===
    new Date(timestamp).valueOf())) { 
    // Use local copy
    return css; 
  } 
}
```

The function `loadInitialFileCallback()` [calls getCSS()](https://github.com/less/less.js/blob/master/dist/less.js#L600); then calls the `loadStyleSheets()` callback; but doesn’t pass the fetched css  ([second parameter](https://github.com/less/less.js/blob/master/dist/less.js#L708) in `callback(null, null, …)`):

```
var css = cache.getCSS(path, webInfo); 
if (!reload && css) { 
  webInfo.local = true; 
  callback(null, null, data, sheet, webInfo, path);  // second param: null?
  return; 
}
```

```
loadStyleSheets(function (e, css, _, sheet, webInfo) {  // second param: null?
  if (e) { 
    errors.add(e, e.href || sheet.href); 
    reject(e); 
    return; 
  } 
  if (webInfo.local) { 
    less.logger.info("loading " + sheet.href + " from cache."); 
  } else { 
    less.logger.info("rendered " + sheet.href + " successfully."); 
  } 
  browser.createCSS(window.document, css, sheet); 
  less.logger.info("css for " + sheet.href + " generated in " + (new Date() - endTime) + 'ms'); 
```

The result is that the `<style>` tag that less creates in `browser.createCSS()` has `null` contents, eg.

```
<link rel="stylesheet/less" type="text/css" href="css/foo.less">
<style type="text/css" id="less:css-foo">null</style>  <!-- note the null here -->
```

I would have expected the inline style tag to have the contents fetched from localStorage.  Am I reading this correctly?

Obviously a workaround is to explicitly set data-env="development";  but then you lose any performance benefit of having the compiled CSS cached.

**Comment by lukeapage** [comment]
Thanks, fixed the call you pointed out - it looks wrong to me too and I think I know how it was broken.
