### ISSUE TITLE
Error compiling bootstrap.less. what did I miss

### ISSUE THREAD

**Issue by MathijsvVelde** [less/less.js#2386]
every time when I try to compile my own .less file, I get the following error:

    SyntaxError: variable @height, visibility is undefined in {web         root}/resources/less/bootstrap/component-animations.less on line 31, column 3:
    30   overflow: hidden;
    31   .transition-property(~"height, visibility");
    32   .transition-duration(.35s);

I use the Less compiler in NetBeans so I don't write all the less command, but this is the one that is being executed:

     "/bin/bash" "-lc" "\"/usr/local/bin/lessc\" \"--source-map\" \"--source-map-rootpath=../less\" \"--source-map-url=extraStyle.css.map\" \"--clean-css\" \"{web root}/resources/less/extraStyle.less\" \"{web root}/resources/css/extraStyle.css\""

And in this file the error occurs:

    //
    // Component animations
    // --------------------------------------------------

    // Heads up!
    //
    // We don't use the `.opacity()` mixin here since it causes a bug with text
    // fields in IE7-8. Source: https://github.com/twbs/bootstrap/pull/3552.

    .fade {
      opacity: 0;
      .transition(opacity .15s linear);
      &.in {
        opacity: 1;
      }
    }

    .collapse {
      display: none;
      visibility: hidden;

      &.in      { display: block; visibility: visible; }
      tr&.in    { display: table-row; }
      tbody&.in { display: table-row-group; }
    }

    .collapsing {
      position: relative;
      height: 0;
      overflow: hidden;
      .transition-property(~"height, visibility");
      .transition-duration(.35s);
      .transition-timing-function(ease);
    }

**Comment by SomMeri** [comment]
What lessc version do you use? I tried your code with lessc 2.1.1 and got different error:
````
NameError: .transition is undefined in test.less on line 12, column 3:
11   opacity: 0;
12   .transition(opacity .15s linear);
13   &.in {
````

The error I got seem to be correct, because line 12 calls `.transition` and that one is not defined inside the file.

**Comment by bassjobsen** [comment]
see also: http://stackoverflow.com/questions/27920826/error-compiling-bootstrap-less-what-did-i-miss/27924737

**Comment by SomMeri** [comment]
@bassjobsen You meant that the issue is equivalent of: 
````
.mixin(@list) {
  property: @@list;
  p2: @list;
}
.selector {
  .mixin(~"1 2");
}
````

and therefore returns correct error?

**Comment by bassjobsen** [comment]
I can not see an issue in the code of @MathijsvVelde. Possible there is an error in the `extraStyle.less`. But i don't have any code of that. I only tried to show what may cause the error.
There is no issue with the error in my example, cause the variable is not defined.

**Comment by MathijsvVelde** [comment]
I finally came to the conclusion that I had two mixins with the same name but with a different approach for the variables.
I did not notice it because the second mixin was in another .less file (a mixin library).
after having the file excluded from import everything worked fine again.

At the moment I use Lessc 2.2.0 (newest on npm)
So maybe an idea for version 2.2.1, a check for double mixins (or only there names)

Thank you for your time anyway!!!

**Comment by bassjobsen** [comment]
@MathijsvVelde Less compiles all matching mixins, which is a feature of Less. Also see for instance http://lesscss.org/features/#mixins-parametric-feature-pattern-matching. You can use namespaces (http://lesscss.org/features/#mixins-feature-namespaces) to prevent collisions. Namespacing Bootstrap has some issues, see: http://stackoverflow.com/questions/19793508/compiling-issue-in-bootstrap-3-with-namespace
