### ISSUE TITLE
Nested File-Import with Sub-Element Selector has unexpected result

### ISSUE THREAD

**Issue by gustavpursche** [less/less.js#2395]
```less
/* main.less */

html[lang="ru"] {
  @import "languages/ru/clip.less";
}
```

```less
/* clip.less */

.clip {
  &_sublabel { ... }
  &_module[data-module="touristinfo"] &_details { ... }
}
```

Result:

```css

/* correct */
html[lang="ru"] .clip_sublabel { ... }

/* incorrect */
html[lang="ru"] .clip_module[data-module="touristinfo"] html[lang="ru"] .clip_details { ... }

/* expected */
html[lang="ru"] .clip_module[data-module="touristinfo"] .clip_details { ... }
```

OS: Ubuntu 14.10
Less-Version: `less@1.7.5`

**Comment by seven-phases-max** [comment]
Could you please provide more info on why you think it "fails"? In fact the result is expected (I guess the point of your confusion is the behaviour of `&` there so see [the docs](http://lesscss.org/features/#parent-selectors-feature) for more details).

**Comment by gustavpursche** [comment]
The unexpected part is the difference between:

```less
.some {
  &_thing &_within { ... }
}
```

which, I guess, renders to:

```less
.some_thing .some_within { ... }
```

But when it's nested, as shown above

```less
/* main.less */
.wrap {
  @import( 'include.less' )
}

/* include.less */
.some {
  &_thing &_within { ... }
}

```
compiles to

```less
.wrap .some_thing .wrap .some_within { ... }

```

but I believe it should be

```less
.wrap .some_thing .some_within { ... }
```

Otherwise it messes the nested single selector up. Don't you think so, @seven-phases-max? Otherwise it would not be possible to wrap a block easy inside of another block (a `html.js`/ `html.no-js` CSS-Class, e.g.) ...

**Comment by seven-phases-max** [comment]
>but I believe it should be

Well, no, regardless of what we think personally the `&` keyword in Less "represents all parent selectors (not just the nearest ancestor)". This is stated in the docs section I linked above.

>Otherwise it would not be possible to wrap a BEM-Block easy inside of another block

The `&` Less feature is not designed specifically for BEM or any other particular naming scheme.

---
So in summary: this is expected behaviour. (See also related #1075 feature request as well as duplicates of this one: #1158, #1575, #2388 etc.)

**Comment by seven-phases-max** [comment]
Closing as expected behaviour.
