### ISSUE TITLE
Less 2.2.0 Page loads properly the first time. Page is broken after refresh.

### ISSUE THREAD

**Issue by ecarpio** [less/less.js#2396]
I am using Less 2.2.0 for a client project. Everything works fine on localhost (using WAMPSERVER). When I upload files to my client's host (Bluehost) the page will load up fine when hitting the url where the files are uploaded. After refreshing the browser the less file is not loaded. I am using bootstrap as well.

I've loaded an older version of LESS 1.7.4 and that seems to work fine. Any Ideas why 2.2.0 is not working?

**Comment by lukeapage** [comment]
No, we need more info

**Comment by ecarpio** [comment]
This demo uses 1.7.4
http://formula99.com/less/demo1/

This one uses the latest 2.2.0. This demo will load correctly the first time but when you refresh the page the page breaks. Please refresh after loading the first time. 
http://formula99.com/less/demo2/

**Comment by ecarpio** [comment]
Any help please?

**Comment by lukeapage** [comment]
I think its the cache problem. We will release a fixed version soon.

**Comment by EugeneDae** [comment]
I have the same problem in Chrome and Safari with Apache running on OS X Yosemite.

**Comment by ecarpio** [comment]
Thank you for checking this out for us!

**Comment by lukeapage** [comment]
Please retry with the latest release. Will re-open if problem continues.

**Comment by ecarpio** [comment]
Thank you! Will report if I find anything else.
