### ISSUE TITLE
Use of Web Workers for Less.js (performance improvement in the browser)

### ISSUE THREAD

**Issue by kuus** [less/less.js#2406]
Less in the browser could be improved using web workers, a practical reason is for instance a css live editor where there are no ways to run the compiler server side.

On this branch of my fork https://github.com/kuus/less.js/tree/web-worker **\*  I did some work to allow less.js to be imported through a web worker (so no `window` / `document` objects) and been used programmatically:

``` javascript
window = {};
importScripts(LESSJS_WORKER_URL);
window.less.render(LESS_INPUT_STRING, lessOptions, function (iDontKnow, output) {
      // console.log(iDontKnow, output);
      postMessage(output.css);
      // output.css = string of css
      // output.map = string of sourcemap
      // output.imports = array of string filenames of the imports referenced
});
```

It works, and the experience is much better (no UI freezing). Any thoughts or interest in working on this?

**Related issues**:
https://github.com/less/less.js/issues/2118

**Links**:
_Web workers and less.js (not very useful)_
https://www.quora.com/What-is-the-best-way-to-compile-less-js-on-a-production-server
https://news.ycombinator.com/item?id=1446197

**Web workers**
https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/basic_usage
https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Advanced_concepts_and_examples

**\* _This branch is, at the time of writing, up to date with main master branch here._

**Comment by k-lange** [comment]
We're using less in a webworker, and it works quite well. It's really easy if you use browserify to build your webworker, something like this:

```js
var less = require('less/lib/less')();

self.onmessage = function (event) {
    less.render(event.data)
        .then(function (result) {
            self.postMessage(result.css);
        });
});
```

**Comment by kuus** [comment]
hi @k-lange , yes I'm doing the same thing and it works. But do you use a fork of less.js or the current latest release as is? Are you able to take advantage of `localStorage` for file caching since it's not a web-worker object?

**Comment by Pingendo** [comment]
+1

**Comment by Pingendo** [comment]
@kuus did you succesfully patched the 2.4 version ?

**Comment by AngeIII** [comment]
Any news about ability to use lessjs as webworker with all benefits such as browser cache and localstorage and app cache(variable)? what work now?

**Comment by bedney** [comment]
For some reason, I wasn't able to make the browserify version work.
I was able to get the latest release (2.5.1) to run in a worker thread by doing some old-school patching (note that this goes *inside* of the `.js` file that is getting loaded into the worker):
```
window = self;
window.document = {
    getElementsByTagName:
        function(tagName) {
            if (tagName === 'script') {
                return [{dataset: {}}];
            } else if (tagName === 'style') {
                return [];
            } else if (tagName === 'link') {
                return [];
            }
        }
};

importScripts('...path.../less.min.js');

<< worker code as per @k-lange above>>
```
It works like a charm for me, but YMMV.

**Comment by ntucker** [comment]
In addition to bedney's change, I added

```
        // Fix relative paths to an absolute since we execute this within a blob
        if (url.length > 2 && url[0]=="/" && url[1] != "/" && location.origin) {
            url = location.origin + url
        }
```

to the beginning of FileManager.prototype.doXHR to set absolute positions so I could use this within a blob based webworker.
