### ISSUE TITLE
lessc won't overwrite read-only files

### ISSUE THREAD

**Issue by FrankV01** [less/less.js#2408]
Lessc won't overwrite read-only files however when a file is readonly and can't be overwritten, Lessc won't report that back to the user. Therefore, the command appears to succeed. I'm using lessc 2.1.2 (sorry, I can't test this on other version right now)

The command I'm issuing is `lessc my_less_file.less ../my_output.css`

I'm on Windows 7.  Node version v.0.10.26

**Comment by SomMeri** [comment]
It is because nodejs `writeFileSync` does not report on errors, it just fails silently. We need to use `writeFile` instead.
