### ISSUE TITLE
less 2.0+ omits trailing comments

### ISSUE THREAD

**Issue by RogerHaase** [less/less.js#2412]
When compiling a less file with the nodejs/npm lessc command, if any imported .less or .css file has a comment after the last css rule, that comment is not written to an uncompressed css output file. The problem started with version 2.0.0 and persists through 2.2.0.

Within our project we are using an import to copy instructions to new developers to say do not edit the css file directly, but rather update the less file and compile the result. The bug also effects the output from projects like pygments where the last line of a css file ends with:

    .il { color: #0000DD; font-weight: bold } /* Literal.Number.Integer.Long */

In the above case,  /* Literal.Number.Integer.Long */ is not copied to the uncompressed css output file.

**Comment by lukeapage** [comment]
thanks, can't believe this wasn't spotted til now. I've fixed and it will be in the next release (v. soon)
