### ISSUE TITLE
30/15rem outputs 2 instead of 2rem

### ISSUE THREAD

**Issue by regisphilibert** [less/less.js#2418]
Problem appeared for me with the latest CodeKit but this has been reproduced using most recent version of less.js
Exemple : 
*LESS*
@fontRem = 17rem;
.whatever{
	font-size:25/@fontRem;
}
*CSS OUTPUT*
.whatever{font-size:1,47058824}
(unit is absent)
*Used to be*
.whatever{font-size:1,47058824rem}

This only fails with the / operator and only if left unit is absent.
30rem/15rem does output 2rem

Strict unit is set to default (off)

**Comment by lukeapage** [comment]
looks like behaviour changed in v2 and probably shouldn't have.

with strict units it is correct because the final unit of your output is "1/rem"

**Comment by hermanndettmann** [comment]
I have the same issue with em-units!

**Comment by hawkz** [comment]
It does seem that units should be preserved according to the docs: http://lesscss.org/features/#features-overview-feature-operations

"If a unit is used in an operation... Less will use that unit for the final output."
