### ISSUE TITLE
I'm having general rendering issues with iPhone and Firefox

### ISSUE THREAD

**Issue by simonferndriger** [less/less.js#2424]
The client version 2.3.1 has some rendering issues in Firefox (width cannot be properly calculated anymore) and strange less errors on iPhone with iOS 8. It works in the latest Chrome, however.

After compiling the less on the server, all problems are "solved".

These problems were not present in the previous version 1.7.4

**Comment by lukeapage** [comment]
Can you provide any more information e.g. by debugging firefox?

**Comment by simonferndriger** [comment]
Sure, I can provide you an internal development URL which works just 
fine in Chrome, but not at all in Firefox.
Can I write you a private email, because these URLs should be kept 
privately only.

- Simon

www.lookr.com <http://www.lookr.com> — Take a look around the world

Am 03.02.2015 um 07:59 schrieb Luke Page:

**Comment by lukeapage** [comment]
Yes.. any ideas how? Im always stuck.. twitter?

**Comment by simonferndriger** [comment]
http://lookr:thisisnext@dev.lookr.com/lookout/new/1292512947 (just tell me when you see this so I can delete this post)

**Comment by lukeapage** [comment]
Delete it, i get mail notifications...

**Comment by lukeapage** [comment]
I've tried out that url in firefox and less loads okay. Its slow - but it seems all the time is spent in doXHR request, loading 20+ less files synchronously, one after another. I don't have an iphone, though I know we have had problems on the iphone.

As I always mention, I would compile server-side and use live reload to for development in the browser.

**Comment by simonferndriger** [comment]
OK, I think you are missing the point. Please let me explain the problem more clearly.

In Firefox with client-side LESS (does not render correctly, because 'width' cannot be calculated, i.e. is 0):
![image](https://cloud.githubusercontent.com/assets/1435963/6036822/51dfd07a-ac4b-11e4-8417-c618624cb3eb.png)

In Chrome with client-side LESS (works just fine, i.e. the same way as after server-side LESS compilation with all browsers):
![image](https://cloud.githubusercontent.com/assets/1435963/6036838/a1a0d51e-ac4b-11e4-924a-d10b01e61265.png)

---

So, we actually DO use the client-side LESS only for development. BUT we do test it always in different browsers before we publish. So, it is necessary for us to have LESS working on client side as well in all (modern) browsers.

**Comment by simonferndriger** [comment]
Additionally, in Chrome I get the following warning (client side):

`less.js:13 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.`

**Comment by lukeapage** [comment]
Ok, what is the less code that produces different results in firefox ..
e.g. the less that gets evaluated to width: 0 ?

**Comment by simonferndriger** [comment]
OK, the HTML tag tag gets evaluated to width=0 is `<section id="webcamNavigation" class="overlay thumbs-row">`

**Comment by simonferndriger** [comment]
I checked again, the problem starts earlier. `$.is(':in-viewport')` does not get triggered for `<section id="webcamNavigation" class="overlay thumbs-row">` (even though it is visible - could be a timing issue?)

**Comment by simonferndriger** [comment]
But when I scroll after dom.ready, I can trigger this script again, and then it *is* in viewport.
However, here starts the second problem:

- If I have to console open from start, it renders correctly - as in Chrome
- If I don't have the console open, it renders incorrectly, because it renders the thumbnails, i.e. `<a href="" class="thumb thumb-single jui-tooltip" aria-hidden="false" style="background-image:url(http://images.lookr-cdn.com/daylight/thumbnail/1292519342-Airolo.jpg)" title="View X"></a>` **below** each other (vertially), instead of **nearby** each other (horizontally) - even if there are only 2 thumbnails left which would have enough space to render horizontally.

Since they get rendered vertically, the script determines that there is not enough space available and shows no thumbnails at all.

---

Initial load:
![image](https://cloud.githubusercontent.com/assets/1435963/6060633/9c66ce42-ad3f-11e4-9c6b-af3d32a20258.png)

After scrolling (no console):
![image](https://cloud.githubusercontent.com/assets/1435963/6060638/aba45794-ad3f-11e4-844b-a01692a282f6.png)


Console output:
![image](https://cloud.githubusercontent.com/assets/1435963/6060648/b9633c7e-ad3f-11e4-8cff-7da5404b1550.png)


Console output code:
		for(var i=$items.length-1; i >= 0; i--){
			$items.eq(i).attr('aria-hidden', 'true').appendTo(nav.$hidden);
			
    console.log('in-viewport:'+nav.$.is(':in-viewport'));
			if(!nav.$.is(':in-viewport'))
				return;
				
    console.log(nav.$.height() +' ?<? '+ nav.itemHeight*2);
			if(nav.$.height() < nav.itemHeight*2)
				return;
		}

**Comment by matthew-dean** [comment]
What is ":in-viewport"? Is that a jquery plugin providing that pseudo-selector? If so, what indicates less is the issue?

**Comment by simonferndriger** [comment]
Yes, it is a jQuery plugin (http://www.appelsiini.net/projects/viewport) - but to simplify it, you can ignore the "in-viewport" problem, and just look at the second problem, which does not include the viewport but online the height of the container `nav.$.height()` and the height of the items/thumbnails in the container `nav.itemHeight`.

These are calculated wrong since we updated LESS. With the old LESS (the rest was the same) it worked just fine. That's why we can be sure it's because of the LESS update.
