### ISSUE TITLE
Cleaning up selectors when calling extend multiple times on same class?

### ISSUE THREAD

**Issue by ghost** [less/less.js#2426]
Hi,

in my opinion this is not an issue when following some guidelines and avoid calling an extend multiple times. In plain CSS we used to avoid duplicate rules so why care less when using a preprocessor?

Anyway, I like extends (done right) ;) and I don't like people blaming the tool but we have discussion on Twitter about bloat from using extend. 

Consider this code (which I did not write): ;) 

```
.bar {
  a: b;
}
.foo {
  &:extend(.bar);
}
.norf, .foo {
  &:extend(.bar); 
  c: d;
}
```

.foo appears multiple times in the same selector group:

```
.bar,
.foo,
.norf,
.foo {
  a: b;
}
.norf,
.foo {
  c: d;
}
```

What do you think? Should LESS clean duplicate selectors or should it not to force DRY when writing:

```
.bar {
  a: b;
}
.foo, .norf {
  &:extend(.bar);
}
.foo {
  c: d;
}
```

**Comment by seven-phases-max** [comment]
This particular example does not appear to be *that* bloat if you compare it to a result of inheriting some real project classes (for instance to inherit Bootstrap button you need something like `:extend(.btn all)` which will generate about hundred of new selectors you'll use most likely never use ;)

**Comment by melbon** [comment]
Any updates?

**Comment by seven-phases-max** [comment]
Use CSS minifiers (most will optimized the example just find).
I'm closing this in favour of #1468 (see also tickets referenced there for more insight of various pitfalls).
