### ISSUE TITLE
`--verbose` deprecated, alternative for `watch` workflow?

### ISSUE THREAD

**Issue by gabssnake** [less/less.js#2441]
Hi there, thanks for the work you are doing, I really like Less and use it every day.

I am using `lessc` with a `watch` task along `browserify` and other tools in the command line to compile my client code on file system changes. For this I use plain node `script` in `package.json` (I know about and also use Grunt/Gulp in other configs).

The particular task looks something like this (uses `npm i -g watch`) :

		watch 'lessc --source-map --autoprefix --verbose /less/main.less /bundle.css' /less/

Console output :

		> Watching /less/
		> app@3.2.1 build:css /app
		> lessc --source-map --verbose --autoprefix /less/main.less /style.css

		lessc: wrote /style.css
		lessc: wrote /style.css.map

I really like having the info on what was done (or at least some feedback like now), so I was wondering why is the `--verbose` option being depecrated (as per the `--help`) ? Is there going to be some alternative ? Are there any thoughts on exposing this info in some other way ? So that maybe a less-plugin-watch could output it to the user ?

		lessc --source-map --autoprefix --watch --verbose /less/main.less /style.css

If anything I would like it enhanced with bytes written and time spent, à la `browserify` with `watchify` :

		lessc: 4664 bytes written to /style.css (0.21 seconds)

**Comment by lukeapage** [comment]
It was deprecated back when it didn't do anything.. but now it does, so we should remove it from that section and consider adding info as you suggested.

**Comment by gabssnake** [comment]
Thank you @lukeapage, that is great news!
