### ISSUE TITLE
globalVars not working in production env

### ISSUE THREAD

**Issue by umefarooq** [less/less.js#2443]
Hi i am facing a problem using less.js i have define globalVar in less options with development environment it works fine but with production is not loading include less files here is my less option code 

```javascript
less = {
    env: "development",
     globalVars:{
         color_path:"it.less"
     }
  };
```
i am giving color path because every sub domain site will have different colors for the layout. i am passing less file name to be included at run time

**Comment by bassjobsen** [comment]
I can not reproduce your issue, but you should notice that `env: "development"` disables caching too, also see https://github.com/less/less.js/issues/1698. Less caching stores compiled code in the local storage of your browser.

**Comment by umefarooq** [comment]
ok thanks mean to check i  need to clear local storage cache during development
