### ISSUE TITLE
@import (once) breaks with indirection

### ISSUE THREAD

**Issue by seriema** [less/less.js#2444]
Frankly I'm not sure if this is a bug or a feature, but it's not behaving as I'd expect from reading the docs.

Doc's on [import-once](http://lesscss.org/features/#import-options-once):

> The default behavior of @import statements. It means the file is imported only once and subsequent import statements for that file will be ignored.

So if I include a file twice, it's included the first time and ignored subsequent times. Ok. But if I include that file indirectly and then directly then it's using the last import and not the first that's used.

I have `lessc 2.3.1 (Less Compiler) [JavaScript]`.
## The files

**style.less**

```
span:before {
  content: 'stylefile';
}
```

**wrapper.less**

```
@import "style";
```
## Use case 1, where it works

**main1.less**

```
@import "style"; // Including the file directly.

span:before {
  content: 'mainfile';
}

@import "style";
```

**main1.css**

```
span:before {
  content: 'stylefile';
}
span:before {
  content: 'mainfile';
}
```
## Use case 2, where it's wrong

**main2.less**

```
@import "wrapper";  // Including style.less indirectly.

span:before {
  content: 'mainfile';
}

@import "style";
```

**main2.css**

```
span:before {
  content: 'mainfile';
}
span:before {
  content: 'stylefile';
}
```

Is this a bug or is there something I've missed? Because now my stuff gets overwritten.

**Comment by seven-phases-max** [comment]
I suppose this is because of https://github.com/less/less.js/issues/1617#issuecomment-31108161.

**Comment by lukeapage** [comment]
as I said there

 > because imports work as a breadth first tree search, not a depth first tree search.. It doesn't execute them asyncronously, it puts them in the order it finds them (but searching and honouring imports at a lower level, not a deeper level). its always been that way and changing it now would fix this example and break another.

If someone has put the 2nd import in the top level file because the specificity demands it go later then fixing this would mean it is put earlier, not later. So my thoughts are that its less likely to cause a problem with the current technique.

Also IMO if you are importing files multiple times and relying on ordering, you are doing something wrong!

**Comment by seriema** [comment]
Thanks for the info guys.
> if you are importing files multiple times (1) and relying on ordering (2), you are doing something wrong (3)!

(1) If I remember correctly, LESS used to import files multiple times and that was a common enough problem for people to warrant the `once` and even making it the default.

(2) Since CSS is based on the order of rules then counting on it is a pretty big deal for me and I can't see how it wouldn't be for everyone else.

(3) I can understand your gut-reaction but I don't think that should contradict 1 and 2. In simple terms my project is pretty huge, with some `base` stuff, then `shared` stuff (that sometimes builds on `base`), and project specific stuff that can mix and match from `base` and `shared` to create new stuff. Because of the import order project specific stuff can pull in `base` after `shared`, thus overriding its style. Maybe `reference` import would be better, but I can't even count on `once` so it feels way too scary atm.

Tree-search algorithms aside, the docs clearly state that the first import is used and I don't see any room to misinterpret that into what's going on now. But then again, it's way past my bedtime. =)

**Comment by seriema** [comment]
I deleted my previous comment =)

I agree that our LESS is pretty crazy, but I'd expect it to generate unnecessarily large CSS with duplicate selectors and that's completely our own fault. I'm hoping that `reference` might be a better option for us. Still though, based on the documentation and any use case I can think of I don't see how the current behavior would be expected by anyone.

**Comment by patricklx** [comment]
also, multiple namespace import wont work anymore. e.g.:  
`.foo {@import 'special'}`
`.bar {@import 'special'}` <-- not done

**Comment by seven-phases-max** [comment]
@patricklx

For your example you need to use [`multiple`](http://lesscss.org/features/#import-options-multiple) option and it's been this way since version 1.4.x.

**Comment by syuilo** [comment]
> For your example you need to use multiple option and it's been this way since version 1.4.0.

Great! I solved similar problem. thanks.
