### ISSUE TITLE
New unit px2rem

### ISSUE THREAD

**Issue by dandaka** [less/less.js#2451]
### Now ###

1. It is much easier to design responsive websites in REM units. In result you get scalable design.
2. Design is done in PX units. And will stay like this in foreseeable future due to inertia with graphics editors.
3. There are a few options to convert PXs to REMs
  * Manually with calculator. Cons: Hard to iterate back to design (case: design file has changed and you need to understand, if you have to change REM — no chance)
  * With a mixin. Code gets bloated and you need to specify each rule separately.

For this case I use a following mixin:

```
.selector {
  .convert-rem(margin-top, 20px);
}

.convert-rem(@selector, @amt, @rem-base-xs: @rem-base-xs) when (ispixel(@amt))
{
    @{selector}: unit((@amt / @rem-base-xs), rem);
}
```

### How it should be ###

```
LESS
@rem-base: 16px;
.selector {
  margin-top: 20pr;
}

CSS
.selector {
  margin-top: 1.25rem; // = 20/16 px
}

```

This code has may advantages:
* Clear
* Easy to check back with design and iterate on
* Minimal syntax

**Comment by seven-phases-max** [comment]
And how (beside syntactic sugar to save just two extra characters) this is different from:
```
@pr: (1 / 16rem);
.selector {
  margin-top: 20 * @pr;
}
```
?

**Comment by dandaka** [comment]
@seven-phases-max Works like magic. Sorry for a stupid question.

**Comment by seven-phases-max** [comment]
@dandaka  It's not really that stupid. I actually can imagine some sort of "customizable-overloaded units" so one could write really short code like `margin: 1u 2u 3u 4u;` instead of `margin: 1 * @u 2 * @u 3 * @u 4 * @u;`. But it's barely to appear in the core, the good news are that if I'm not mistaken this is relatively easy can be implemented via plugin.
