### ISSUE TITLE
Error when :extend's selector can't be found

### ISSUE THREAD

**Issue by tomekwi** [less/less.js#2459]
> this fails silently:
> 
> ```less
> .foo {
>   &:extend(.bar-baz);
> }
> 
> .bar {
>   &-baz {
>     some: stuff;
>   }
> }
> ```
> 
> ```
> $ lessc this
> .bar-baz {
>   some: stuff;
> }
> ```
> 
> _[– from #2453](https://github.com/less/less.js/issues/2453#issuecomment-74580893)_

Putting aside if it should work or not – that's being discussed in #2200.

In my view it should throw some kind of error when `selector` is undefined in the scope of `:extend(selector)`. Like undefined mixins throw a SyntaxError.

Otherwise there's no way to spot the failure other than manually scanning through the output.

**Comment by seven-phases-max** [comment]
Non-matched `extend`s produce warnings [now](https://github.com/less/less.js/blob/master/CHANGELOG.md#230) (the only problem you won't see a warning when compiling with anything other then `lessc in.less out.css` but that's the warning implementation itself to be polished further).

As for error or warning thing itself it might be questionable (rationale behind warnings is that you may have some generic code that intentionally uses not always matching `extends`), but this actually to be solved if we'll go a canonical compiler route and have multiple warning levels controlled by cli-options including one for `warning -> error` (i.e. "warning implementation polishing" again).

**Comment by tomekwi** [comment]
> Non-matched extends produce warnings now (the only problem you won't see a warning when compiling with anything other then lessc in.less out.css but that's the warning implementation itself to be polished further).

I can close this issue then. I have some more, but I guess it'd be better if I write them in an issue dedicated to the implementation of warnings. Is there such @seven-phases-max?

**Comment by seven-phases-max** [comment]
> Is there such?

No (I actually was thinking of creating one myself, but I just do not want to spam issues unless I'm about to put at least part on myself and for the moment I'm a bit limited in coding).
