### ISSUE TITLE
Comments in variables/values break built-in functions and ops.

### ISSUE THREAD

**Issue by sdenel** [less/less.js#2475]
@color1: #FFF;/* comment1 */
    @color2: #FFF/* comment2 */;
    html {
    	color: mix(blue, @color1, 50%);
    	color: mix(blue, @color2, 50%);
    }

gives me, with lessc:
<pre>
<b>RuntimeError: error evaluating function `mix`: undefined is not a function in</b> (...).less on line 5, column 9:
4 	color: mix(blue, @color1, 50%);
5 	color: <b>mix(blue, @color2, 50%);</b>
6 }
</pre>

**Comment by seven-phases-max** [comment]
Related to #2431 and specifically https://github.com/less/less.js/commit/97d039f26796472ebee655bcd6b87c1a088dac36#commitcomment-9636520.

@sdenel Yes, currently this is sort of known behaviour: comments should not appear *in* the values.

**Comment by lukeapage** [comment]
Ive worked out a plan but it is alot of work and breaking changes for
plugins. May be worth stripping for functions in the time being.

**Comment by lukeapage** [comment]
I wrote it up here: https://github.com/less/less.js/issues/2477

will keep this around for a short term fix
