### ISSUE TITLE
Create Gitter.im group for LESS community.

### ISSUE THREAD

**Issue by rstellar** [less/less.js#2478]
Really helpful for getting quick questions answered.

**Comment by seven-phases-max** [comment]
You could create PR at https://github.com/less/less-docs (Notice the `pencil` icon in the top right corner of each docs section, it let to to make a PR into the docs for three mouse clicks). Though currently we have some minor doubts about how to actually organize such "to-community" links (see https://github.com/less/less-docs/pull/300).

**Comment by seven-phases-max** [comment]
Closing as belonging to [less/less-docs](https://github.com/less/less-docs).
