### ISSUE TITLE
Format function with %s, %S options and hex colors

### ISSUE THREAD

**Issue by SomMeri** [less/less.js#2480]
The `%s` and `%S` options of format function does not allow hex colors as argument. They print `undefined` instead:

Input:
````
.formattingMixin(@name, @parameter) {
  format1: @name %("%% s: %s", @parameter);
  format2: @name %("%% S: %S", @parameter);
}

#format {
  .formattingMixin(~"hex color", #ff00ff);
}
````

actual output:
````
#format {
  format1: hex color "% s: undefined";
  format2: hex color "% S: undefined";
}
````

expected output:
````
#format {
  format1: hex color "% s: #ff00ff";
  format2: hex color "% S: #ff00ff";
}
````

**Comment by seven-phases-max** [comment]
Do you mean it needs to be changed from:

>`s`, `S` - can be replaced by any kind of argument except color. If you use them in combination with string, only the string value will be used - string quotes are omitted.

to (something like):

>`s`, `S` - outputs value without quotes (if any)

**Comment by SomMeri** [comment]
@seven-phases-max It is not changed yet :) , but yes, that is what I mean.

**Comment by seven-phases-max** [comment]
Yes, I mean the way it's to be changed (using the docs quote just as its definition reference).
