### ISSUE TITLE
paths option does not work for image-size.

### ISSUE THREAD

**Issue by tobiastom** [less/less.js#2482]
The pull request #2387 did add the include-path support to the `data-uri` function. The `image-size` function does not have this support right now.

@SomMeri do you think you could add support for it was well? :)

**Comment by SomMeri** [comment]
Closing, because the issue was fixed by previous commit.

**Comment by tobiastom** [comment]
@SomMeri Thank you so much!

**Comment by SomMeri** [comment]
@tobiastom I did not fixed it, @bassjobsen did. I  just found out the code is already there and closed the issue.

**Comment by tobiastom** [comment]
Oh, I missed that. So I revoke my thanks to you and instead give them all to @bassjobsen. Thank you for adding this.

P.S. @SomMeri Thanks for taking care about my issue. :)
