### ISSUE TITLE
Client Side: *.less must be called before less.js script

### ISSUE THREAD

**Issue by ptim** [less/less.js#2483]
Hi! Thanks for less!

I'm finding that I need to include my stylesheets *before* the less.js script, otherwise the less is not compiled. I raise this as an issue because the docs say:

> To use less in the browser, you firstly need to include the less script.
> ...
> This will find any less style tags on the page
https://github.com/less/less-docs/blob/master/content/usage/using-less-in-the-browser.md

Wasn't sure if I should lodge the issue here or in the https://github.com/less/less-docs/ repo, but opted for here because I found an issue closed in the main repo: https://github.com/less/less.js/issues/21

Cheers, Tim

"less.js": "~2.4.0" (installed via bower)

**Comment by seven-phases-max** [comment]
>To use less in the browser, you firstly need to include the less script.

Well, this just means that it won't work w/o `less.js` (it does not really say "put the script *before* links", just literally "you need to put the script into your page before you can use Less in the browser"). I understand how "first" confused you so we might remove it from there (but honestly it was really just your too deep guesswork behind the lines).

And at [Client-side usage](http://lesscss.org/#client-side-usage) it does say what you'r looking for:
>Make sure you include your stylesheets before the script.

**Comment by seven-phases-max** [comment]
I'm closing this anyway as wrong repo (yes, this belongs to less/less-docs). Do not hesitate to create a ticket there if you think that duplicating the tip at the [Using Less in the Browser](http://lesscss.org/usage/#using-less-in-the-browser) important.
