### ISSUE TITLE
Error while compiling mixin with ruleset

### ISSUE THREAD

**Issue by MatrixZ** [less/less.js#2493]
Compiling the below less file throws parsing error. What am i doing wrong?

less code
```less
.bg({
 background-color: @color;
});
```
Error details

>/Library/Ruby/Gems/2.0.0/gems/less-2.2.2/lib/less/parser.rb:35:in `block (2 levels) in parse': expected ')' got '{' (Less::Error)
	from at Parser.parser.parse (/Library/Ruby/Gems/2.0.0/gems/less-2.2.2/lib/less/js/lib/less/parser.js:343:24)
	from /Library/Ruby/Gems/2.0.0/gems/less-2.2.2/lib/less/parser.rb:25:in `block in parse'
	from /Library/Ruby/Gems/2.0.0/gems/less-2.2.2/lib/less/java_script/v8_context.rb:90:in `block in do_lock'
	from /Library/Ruby/Gems/2.0.0/gems/less-2.2.2/lib/less/java_script/v8_context.rb:88:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/less-2.2.2/lib/less/java_script/v8_context.rb:88:in `Locker'
	from /Library/Ruby/Gems/2.0.0/gems/less-2.2.2/lib/less/java_script/v8_context.rb:88:in `do_lock'
	from /Library/Ruby/Gems/2.0.0/gems/less-2.2.2/lib/less/java_script/v8_context.rb:60:in `lock'
	from /Library/Ruby/Gems/2.0.0/gems/less-2.2.2/lib/less/java_script/v8_context.rb:30:in `exec'
	from /Library/Ruby/Gems/2.0.0/gems/less-2.2.2/lib/less/java_script.rb:26:in `exec'
	from /Library/Ruby/Gems/2.0.0/gems/less-2.2.2/lib/less/parser.rb:24:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/less-2.2.2/bin/lessc:98:in `<top (required)>'
	from /usr/bin/lessc:23:in `load'
	from /usr/bin/lessc:23:in `<main>'

**Comment by goto-bus-stop** [comment]
https://github.com/cowboyd/less.rb/ uses Less 1.7.0, which doesn't have this feature.

**Comment by SomMeri** [comment]
I am closing this since the code is working in less.js.
