### ISSUE TITLE
[DOCUMENTATION] Programmatically using the paths configuration with a string results in an obscure error when using data-uri function

### ISSUE THREAD

**Issue by mschnee** [less/less.js#2500]
When using the data-uri function while the paths options is a string instead of an array.
In 
fileManager.loadFileSync() called from functionRegistry.add("data-uri");
file-manager.js expects paths to be an array.
lib/less/less-node/file-manager.js line 75:
```
 if (options.paths) {
        paths.push.apply(paths, options.paths);
    }
```

If you try to supply a string, you will receive an ambiguous error:
```
'error evaluating function `data-uri`: Function.prototype.apply: Arguments list has wrong type in file /Users/mschnee/Projects/testapp/src/less/lib/ie-old.less
```

The solution for the end user is to change their usage of the paths option from a string to an array.  
```
options = { paths: "target/css" };
options = { paths: ["target/css"] };
```
Users used to using gulp and glob are likely to expect strings and arrays of strings to be used interchangibly.

Either the documentation should be updated to reflect this fact, or the ```options.paths``` check above should promote the value to array (can PR if desired)

**Comment by lukeapage** [comment]
this came up before, I'm sure.

found it: https://github.com/less/less.js/blob/master/lib/less/contexts.js#L40

I think it just needs to be in the Eval context too. PR will be merged, thanks!

**Comment by SomMeri** [comment]
This was closed by https://github.com/less/less.js/pull/2505
