### ISSUE TITLE
@import doesn't work when extension is not specified and path contains dot(.)

### ISSUE THREAD

**Issue by muttsoo** [less/less.js#2503]
Import statements containing file names like the one's mentioned below cause the less compilation to fail. It appears that the framework attempts to add the extension if its not mentioned, but it fails when extension is not specified and file name contains dot(.).

`@import my.file`

It works fine when the file names are simple with just one dot (.) in them or contains .less extension. 

`@import 'myfile.less'`
`@import 'my.file.less'`
`@import 'myfile'`

I suspect following code in "abstract-file-manager.js" is causing the issue which is trying to add the extension if its not mentioned.

```
abstractFileManager.prototype.tryAppendLessExtension = function(path) {
    return /(\.[a-z]*$)|([\?;].*)$/.test(path) ? path : path + '.less';
};
```

**Comment by seven-phases-max** [comment]
Hmm, I'm not sure I actually understand the problem but how is compiler supposed to guess that `.file` in the `my.file` is not an extension? (It's never declared that `less` extension is obligatory, so one may expect `@import (less) "whatever.foobar";` to import `whatever.foobar` and not `whatever.foobar.less`).

**Comment by lukeapage** [comment]
Weve had alot of bugs about this. Always adding less causes problems other people cant fix (web urls mainly), so this is expected behaviour.

**Comment by lukeapage** [comment]
To clarify the bugs were ones saying the opposite to this issue

**Comment by muttsoo** [comment]
In my case there are lot less files present like this,  is there any way I can fix it?  my be adding some preprocessor or postprocessor ?

**Comment by lukeapage** [comment]
Dont use dot in filename or specify full filename. Sorry, cant see a good
enough reason to add an option. You are free to write an import plugin that
overrides the normal file plugin and always adds .less

**Comment by matthew-dean** [comment]
@muttsoo Any system that allows extension-less declaration runs into this. In curl (the AMD loader), if you have a JS file with .min.js, you have to add the .js. As @seven-phases-max says, since you CAN add an extension in the ```@import``` call, there's no  way to know that .file ISN'T the extension. Solution: Write the full filename or don't have other periods in your filename.
