### ISSUE TITLE
Windows - lessc called with filenames in command line, surrounded in quotes, mangles those file names and then cant find them

### ISSUE THREAD

**Issue by wahuneke** [less/less.js#2508]
Call lessc like this, for example (or using the .bin/lessc.cmd, you get the same result)

"C:\Program Files\nodejs\node.exe" node_modules\less\bin\lessc 'C:\Users\bill\myproj\test.less' 'C:\Users\bill\myproj\test.css'

Note the ' tick used on the input and output filenames. You will get this error message:

lessc: ENOENT, open 'C:\Users\bill\myproj\'C:\Users\bill\myproj\test.less''

Observe that it fails to recognize this as an absolute path. Not sure of the best place to fix this or the best way to fix it. I am not a nodejs or even a Javascript developer.

I will do my best nonetheless and will open a pull request

**Comment by seven-phases-max** [comment]
Use `"` not `'`. Curiously I can't find any MS documentation on any special meaning of singe quotes in `cmd` but [it looks like] it's pretty non-standard thing.

Here's quote from `cmd /?`:

>```
The special characters that require quotes are:
     <space>
     &()[]{}^=;!'+,`~`
```

Notice a single quote character is marked as requiring quotes too :)

**Comment by matthew-dean** [comment]
Yes, those characters require special quotes because "Matthew's File.doc" is a valid Windows filename. So you can't use single quotes around a path, as it probably assumes the ```'``` is part of the path.

**Comment by wahuneke** [comment]
Granted! I could use " instead of single tick.  (single tick _does_ work btw, at least in windows 8.1)

I wish I could just use ", but this is in Django, my app calls another app, calls another app, calls Python2.7 standard windows installation - module pipes.py which then promptly wraps everything in single quote (does not use double quotes).

I'd rather not fork python2.7 and try to create a custom windows installation for that... :) I'd rather just fix it in less.js  (even though it's not your fault )

But yeah, you're right there's no need to take out " so I'll modify the patch.

**Comment by wahuneke** [comment]
@matthew-dean 

Yes, I'm beginning to see the problem now, .... and I see why Windows works the way it does.

BUT! what kind of weirdo starts their file names with ' ? and who would end their LESS files with .less'  ?  Probably nobody. Just kidding, I completely respect that you prefer to respect the actual windows specification.

But practically speaking, if you just look for the ticks on the beginning and end string of we'll probably screw up nobody, but if we dont use this patch you'll mess me up and probably any other Django user running my particular combination of versions and tools. :)

Your judgement call.

**Comment by wahuneke** [comment]
Here's the python2.7 code, for your amusement:

# Safe unquoted
_safechars = frozenset(string.ascii_letters + string.digits + '@%_-+=:,./')

def quote(file):
    """Return a shell-escaped version of the file string."""
    for c in file:
        if c not in _safechars:
            break
    else:
        if not file:
            return "''"
        return file
    # use single quotes, and put single quotes into double quotes
    # the string $'b is then quoted as '$'"'"'b'
    return "'" + file.replace("'", "'\"'\"'") + "'"

**Comment by seven-phases-max** [comment]
>grrr.. why isnt my markdown working?

wrong quotes (again :). I fixed it for you.

**Comment by wahuneke** [comment]
```javascript
(function() {
    console.log("haha");
    console.log("oh. backticks, not single quote. Roger that");

    return "I get it now. how amazing";
})();
```
