### ISSUE TITLE
@import url(/unqouted/path) fails

### ISSUE THREAD

**Issue by texclayton** [less/less.js#2516]
This can be reproduced by removing the quotes in the second line of test/less/import/import-test-a.less.
Line 2 will then be:
```css
@import url(deeper/url-import.less);
```

Run 'grunt test' and see the failure:
> ERROR: 'null.less' wasn't found. Tried - E:\less.js\test\less-bom\import\null.less,test\less-bom\null.less,null.less

See lib/tree/import.js:
```javascript
Import.prototype.getPath = function () {
    if (this.path instanceof Quoted) {
        return this.path.value;
    } else if (this.path instanceof URL) {
        return this.path.value.value;
    }
    return null;
};
```
This returns null because `this.path` is an Anonymous because `evalForImport` sets it:
```javascript
Import.prototype.evalForImport = function (context) {
    var path = this.path;
    if (path instanceof URL) {
        path = path.value;
    }
    return new Import(path.eval(context), this.features, this.options, this.index, this.currentFileInfo);
};
```

**Comment by seven-phases-max** [comment]
Added a `bug` mark. 
The curious thing is that the docs never mention `@import url(.../*.less);` as a valid statement :)
It's always `@import ".../*.less";` (and indeed `url()` looks like totally redundant thing in this case, But sure, for compatibility with CSS it should be supported... after all `@import url(".../*.less");` works fine).
