### ISSUE TITLE
Comunity Speed Test

### ISSUE THREAD

**Issue by Sinius15** [less/less.js#2523]
Dear Less Community,

I am a computer-science student in Holland and i am doing research on css-preprocessors. One of the aspects i am interested in is the community support. This is a test to discover the reaction speed of the community to issues. I will measure the time it takes to close this issue. 
Would the first person who reads this please close this issue?

Thanks in advance!

**Comment by seven-phases-max** [comment]
Closing per OP request.

**Comment by Sinius15** [comment]
@seven-phases-max Thanks! You are the first to respond. Congratulations.

**Comment by lukeapage** [comment]
Damn several whole hours late!

**Comment by matthew-dean** [comment]
Dang it, I hate losing at contests! lol

**Comment by seven-phases-max** [comment]
Hey, but we won this one!

**Comment by matthew-dean** [comment]
@seven-phases-max  Ohhh... I thought @Sinius15 meant that you won. Now I realize it was that Less had won. :-) I'm not surprised. We're pretty on top of responding to issues. GO TEAM!

**Comment by SomMeri** [comment]
:)
