### ISSUE TITLE
relativeUrls option regression

### ISSUE THREAD

**Issue by gustavnikolaj** [less/less.js#2524]
Given these files:

parent.less:
```less
@import "sub/child.less";
```
and child.less:
```less
body {
    background: url(images/cats.png);
}
```

I get the following output from running lessc:
```
$ lessc parent.less foo.css ; cat foo.css
body {
  background: url('images/catzz.png');
}
$ lessc --relative-urls parent.less foo.css ; cat foo.css
body {
  background: url('sub/images/catzz.png');
}
```

The `--relative-urls` flag to lessc is working as expected.

Now, given a file called less.js in the same directory:
```js
var less = require('less');
var filePath = require('path').resolve(__dirname, 'parent.less');

var relativeUrls = process.argv[2] === 'relativeUrls';

require('fs').readFile(filePath, 'utf-8', function (err, data) {
    less.render(data, { paths: [__dirname], relativeUrls: relativeUrls }, function (err, output) {
        console.log(output.css);
    });
});
```

You get the following results:
```
$ node less.js
body {
  background: url('images/catzz.png');
}
$ node less.js relativeUrls
body {
  background: url('images/catzz.png');
}
```

It's clearly not the behavior you expect after reading the documentation: http://lesscss.org/usage/#using-less-in-the-browser-relativeurls

I found this when I upgraded a project from less 1.5.1 to 2.4.0. 

Am I completely off, or did something break?

**Comment by gustavnikolaj** [comment]
Providing the filename option to less.render fixes that. 

```diff
var less = require('less');
var filePath = require('path').resolve(__dirname, 'parent.less');

var relativeUrls = process.argv[2] === 'relativeUrls';

var options = {
     paths: [__dirname],
+    filename: filePath,
     relativeUrls: relativeUrls
};

require('fs').readFile(filePath, 'utf-8', function (err, data) {
    less.render(data, options, function (err, output) {
        console.log(output.css);
    });
});
```

**Comment by otbe** [comment]
Maybe this "fix" should be added to the docs. Struggled around an hour with this issue...

**Comment by seven-phases-max** [comment]
@otbe Third paragraph in http://lesscss.org/usage/#programmatic-usage (Yes, it could be better, but so far none offered any better text. So if you have one do not hesitate to make a PR).

**Comment by JaKXz** [comment]
@gustavnikolaj thank you!
