### ISSUE TITLE
Add the possibility to @import less files using an absolute path

### ISSUE THREAD

**Issue by neulandmedienagentur** [less/less.js#2528]
I try to import a less file in my style.css file.

That works:
`@import "../../../file/file/lessfile";`
That doesent work:
`@import "http://example.com/file/file/lessfile";`

**Comment by seven-phases-max** [comment]
Absolute paths and external urls are known to work in recent Less versions (see [demo](http://codepen.io/seven-phases-max/pen/PwLxEd?editors=110)).


So please provide more details for you example (Less version, exact error message you get, real URL of the file you're trying to import (so it can be tested), eetc. etc).
And do not hesitate to read https://github.com/less/less.js#reporting-issues.

**Comment by neulandmedienagentur** [comment]
Frontend URL:
http://dev.simplex-server.de/de/startseite.html

style.css:
http://dev.simplex-server.de/files/simplex-01/dev/css/style.css

I dont understand that this one works:
@import "http://dev.simplex-server.de/files/simplex-basic/dev/css/variables.less";
And this not:
@import "http://less.simplex-server.de/grid.less";

**Comment by seven-phases-max** [comment]
What error do you get when the second file "does not work"? ([here](http://codepen.io/seven-phases-max/pen/PwLxEd?editors=110) for example both are imorted just fine).

**Comment by neulandmedienagentur** [comment]
I dont get any error. As you can see, the complete css dont work:
http://dev.simplex-server.de/de/startseite.html#!watch

**Comment by neulandmedienagentur** [comment]
In the current version line 4 is "active" instead of line 3. If I "activate" line 3, it works fine and its the same less file.

**Comment by seven-phases-max** [comment]
Well, if you open your browser console you see the following error:
>XMLHttpRequest cannot load http://less.simplex-server.de/grid.less. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://dev.simplex-server.de' is therefore not allowed access.

For more details about what this error is about and how to solve it see:
* [No 'Access-Control-Allow-Origin' header is present on the requested resource.](http://stackoverflow.com/questions/20433655)
* [HTTP access control (CORS)](https://developer.mozilla.org/en-US/docs/HTTP/Access_control_CORS)

**Comment by seven-phases-max** [comment]
Closing as not a Less issue.
