### ISSUE TITLE
Less compiles incorrectly when scoping certain bootstrap selectors

### ISSUE THREAD

**Issue by dylanmensaert** [less/less.js#2534]
Trying to scope bootstrap into a single class gives me some unexpected results:

*Writing following code:*
`.test-panel {
    @import 'bootstrap/less/bootstrap';
}`

*Outputs:*
![Screenshot compiled css file](https://cloud.githubusercontent.com/assets/4887627/6980413/9a1b5958-d9f1-11e4-88e1-b304f9d93185.png)

**Unexpected result** on *line 5865 -> 5910* where selectors are scoped into `.test-panel` a second time.
**Expected result** for *line 5865* would be: `.test-panel .dl-horizontal dd:before,`

Note that this problem only occurs for the selectors seen in this screenshot. Every other selector in the bootstrap file compiles just fine.

I am using *"grunt-contrib-less": "1.0.0"* as the compiler.

**Comment by seven-phases-max** [comment]
See #2052. For a workaround see https://github.com/less/less.js/issues/1709#issuecomment-29707217.

**Comment by seven-phases-max** [comment]
Closing as expected behaviour. (More details in #1730, #1850, #2052).
