### ISSUE TITLE
Add command line usage to README

### ISSUE THREAD

**Issue by corysimmons** [less/less.js#2536]
New to LESS. If there is a way to use LESS with the command line, (e.g. `less input.less output.css`) then could you add that to the README? Thanks

**Comment by corysimmons** [comment]
Found it here: http://lesscss.org/usage/index.html#command-line-usage

Could you add this link to the README for newb convenience? :)

**Comment by seven-phases-max** [comment]
The http://lesscss.org is at the beginning of the readme. I don't think that the `#command-line-usage` section is something special among other sections to deserve its own link (if would make sense if Less is a just cli-tool but it's not).

**Comment by corysimmons** [comment]
No problem. Sidenote: there's no official CLI watcher for LESS?

**Comment by seven-phases-max** [comment]
>there's no official CLI watcher for LESS?

No, there's not.
