### ISSUE TITLE
Cannot read property 'numerator' of undefined

### ISSUE THREAD

**Issue by corysimmons** [less/less.js#2538]
```less
.move(@fraction: '1/1') {
  left: calc(100% * ~'@{fraction}');
}
```

Throws `Cannot read property 'numerator' of undefined` error. I've Google'd for a while and can't find anyone else repeating this error.

I am intentionally passing the fraction as a string as well for actual reasons.

**Comment by corysimmons** [comment]
I was able to solve my issue by escaping every bit of the `calc()` line except for the variables.

It's really ugly and hard to maintain, so hopefully someone will chime in with a better method.

**Comment by seven-phases-max** [comment]
What result this snippet is supposed to produce? if it's just about getting `calc` unprocessed see #974 and [`---strict-math`](http://lesscss.org/usage/#command-line-usage-strict-math)

**Comment by corysimmons** [comment]
I actually figured out I was supposed to use `%()` for my problem.

**Comment by L924553229** [comment]
将 `left: calc(100% * ~'@{fraction}')` 修改为 `left: ～”calc(100% * ~'@{fraction}')“`
