### ISSUE TITLE
Does not equal?

### ISSUE THREAD

**Issue by corysimmons** [less/less.js#2540]
Does LESS have a does not equal comparison operator? I'm trying `!=` (as it's the opposite of `=`) but it doesn't seem to be working... =[

**Comment by lukeapage** [comment]
Try <>

**Comment by corysimmons** [comment]
@lukeapage Thanks. I'm trying that but now I'm getting:

```
SyntaxError: expected expression in /Users/cory/Desktop/lost/less/lost.less on line 416, column 21:
415       }
416       & when (@gut <> 0) {
417         margin-right: calc(99.99% * @_fraction - (@gut - @gut * @_fraction) + (@gut * 2)) !important;
```

**Comment by seven-phases-max** [comment]
Dudes, you are not serious, right? [Guard Oprators](http://lesscss.org/features/#mixin-guards-feature-guard-logical-operators).

**Comment by lukeapage** [comment]
Oh yes,  I must have a short memory (and im not near a computer)

**Comment by seven-phases-max** [comment]
Closing as not an issue.

**Comment by corysimmons** [comment]
`& when not` works
