### ISSUE TITLE
Suggestion: ability to insert Selectors with wildcards

### ISSUE THREAD

**Issue by ldetomi** [less/less.js#2548]
I suggest a quick way to use partial selectors name. For example:
1) Classname that BEGIN with 'foo' string:
Proposed LESS syntax: 

    .*foo { ... }

CSS Output:

    [class^="foo"] { ... }

2) ID that END with 'foo' string:
Proposed LESS syntax: 

    #foo* { ... }

CSS Output:

    [id$="foo"] { ... }

3) Classname that CONTAIN 'foo' string:
Proposed LESS syntax: 

    .*foo* { ... }

CSS Output:

    [class*="foo"] { ... }

More intuitive and quickier to write. Don't you think?

**Comment by seven-phases-max** [comment]
are you really typing these `[]` *so* much?

**Comment by matthew-dean** [comment]
-1

**Comment by lukeapage** [comment]
Sorry i think the syntax is confusing too. 
Id be more keen for a function to construct selectors,  assign to a variable and use as selector,  then maybe using that directly in the selector as a second step - but even then the gain is minimal for the work and complexity.

**Comment by ldetomi** [comment]
Pity.... my idea started by syntax that a user commonly uses in a shell environment. If you want to find a file fro example you use this approach, I thought that could be more intuitive, compact and streamless...
