### ISSUE TITLE
when use css guards plus mixins seems not to be working

### ISSUE THREAD

**Issue by maxidr** [less/less.js#2566]
My case:

app.less

    @import "../../vendor/nifty-v2.2/less/nifty.less";
     

    .project-selector .project-name { 
        .label;
        .label-mint;      // line 203
        font-size: 100%;
    }

nifty.less

    @enable-mint                : true;

    & when (@enable-mint = true) {
        .label-mint{background-color: @mint-bg}
    }
   

When try to use the .label-mint as a mixin fails with the error:

    [20:38:34] Error with LESS: .label-mint is undefined in file /Users/maxidr/Projects/customer_insight/dashboard-frontend/src/less/app.less line no. 203

I'm really lost, I'm using the mixin in a wrong way? 

Thanks

**Comment by seven-phases-max** [comment]
Mixins defined in a ruleset are visible in that ruleset only. And `& {}` is also just a ruleset (it's not really an euphemism for an`if` statement).

For your example the solution is as simple as:
```
@enable-mint: true;

.label-mint when (@enable-mint = true) {
    background-color: @mint-bg;
}
```

**Comment by maxidr** [comment]
Thank you very much Max!, I understand now.

**Comment by seven-phases-max** [comment]
Closing as "expected behaviour".
