### ISSUE TITLE
@import should be a reserved keyword

### ISSUE THREAD

**Issue by tobmaster** [less/less.js#2567]
Currently when using @import with a colon following the compilation doesn't break but silently skips the import.
As its clear that its interpreted as a variable, I would expect it to break or at least warn about the issue. Cause its otherwise it becomes a hard to spot error in bigger projects. Because rules never get applied.

This should throw an error.

```
@import: 'foo.less';
```

**Comment by matthew-dean** [comment]
Fair enough. There are probably a few keywords that would fall in this category.

**Comment by rjgotten** [comment]
Where you do stop though?
`@import`, `@media` , `@supports`, `@font-face`, `@whatever-else-gets-added-to-css-over-time`.

Turning these things into reserved keywords is going to cause pain to existing code-bases...

**Comment by seven-phases-max** [comment]
I would stop at `@identifier value;` at-rues *only*. Others are barely can be confused with variable definition statement (if I want my `@page` variabe I don't care of other's typo problems to be honest). I would even also make it to be warning instead of a error, however since warnings currently do not always appear , well... could be a error... not a big deal after all...

**Comment by tobmaster** [comment]
Hey @rjgotten thanks for your valuable addition.

I think that @import is imho the most important because the affects whole files that are not used then at all. The others might be suspects to be reserved as well (needs more thinking). But they are still different cause they all are blocks that should be followed by a braces. 
Maybe parsing might become slightly slower cause a look ahead is required though.

And to be true, you can't use one of these as a variable names in real projects because they are css grammar and would always be reasons to break something.
So I wouldn't expect any project to use those cause hell would break loose. Or do you have, or can construct, an reasonable example?

For future additions to the css syntax this might also be a BC-Break yes.
