### ISSUE TITLE
Less 2.5.0 in a web worker fails to execute

### ISSUE THREAD

**Issue by KidkArolis** [less/less.js#2569]
I've added the following tweak to less.js for it to work

```js
// This fails due to accessing document.currentScript - document is undefined
// addDataAttr(options, browser.currentScript(window));

// This prevents less.registerStylesheets() from getting called which breaks in a worker
options.onReady = false;
```

Would be great if less would detect it's a worker and tweak the initialization logic in that case.

I could take a closer look at this if it's something of interest to you. For now, I just wanted to report this issue.

**Comment by seven-phases-max** [comment]
Hmm, shall we merge this to #2406? (since it's more like the same feature-request rather than bug/issue).

**Comment by lukeapage** [comment]
closing in favour of #2406

**Comment by KidkArolis** [comment]
Should this be added as one of requirements in #2406? Specifically "being able to run the entire less.js in a worker". Not just "using workers as a less optimization". I don't think they're quite the same. My use case here is running the entire less.js inside an `ace` editor worker.

**Comment by seven-phases-max** [comment]
@KidkArolis 

But `less.render` (which is discussed in  #2406) *is* sort of `the entire less.js` as soon as you have no `document` in a web worker and have to disable any autocompilation on page load.
