### ISSUE TITLE
Compilation issue in IOS

### ISSUE THREAD

**Issue by hiren-talsaniya** [less/less.js#2571]
Hello,
I got an issue while using .less files in my HTML file only in IOS device (Ipad).

I have attached style.less and less.js in my HTML file in header section and works fine in all browser in windows os but i found an issue in IOS that .less not compiling.
So is there any other way to solve this issue or i missed something ?

Thanks...!!!

**Comment by seven-phases-max** [comment]
See #1723.

**Comment by seven-phases-max** [comment]
Closing as duplicate of #1723.
