### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by kriskowal** [less/less.js#2572]
I would like to use a mode where all import directives are resolved through Node.js’s own module system such that .less files can be imported from the same package or a dependency package using Node.js’s own module identifier resolution semantics.

Such could be accomplished using @substack’s [node-resolve](https://github.com/substack/node-resolve).

I do not propose that this feature be implemented for the client-side loader, but merely as a mode exposed by a command-line option for users of lessc as a build step to generate a CSS bundle incorporating dependencies from packages installed with npm.

While I hope that a member of this community would find this feature useful enough to implement it, I can offer a weekend or two to give this idea a push if it is merge-worthy. Otherwise, it looks like Less has all the hooks I would need to implement an alternate FileManager and provide an alternate command-line interface for this feature.

**Comment by seven-phases-max** [comment]
[less-plugin-npm-import](https://github.com/less/less-plugin-npm-import)?

**Comment by lukeapage** [comment]
Feel free to suggest improvements to the plugin or make your own different plugin and we will reference it,  but we wouldn't put it into core.

**Comment by kriskowal** [comment]
Thank you.
