### ISSUE TITLE
less.render failing inconsistently

### ISSUE THREAD

**Issue by andrepadez** [less/less.js#2577]
I am running a custom buider, that joins a lot of different .less files and compiles it with less.
From time to time, the compilation fails with the error below:
![screen shot 2015-04-28 at 19 38 55](https://cloud.githubusercontent.com/assets/1013997/7376233/ad8c3a24-edde-11e4-98b0-0fa21f49d281.png)
There is no consistent way to reproduce it, i can run it 10 times, with the files unchanged and it fails on one of them; sometimes it fails more than once in a row, it's really annoying.
As you can see, in the console.log( lessToCompile 93551) that is the unchanged length of the css i send  to compile. 
I have checked for possible race conditions but i'm using Promise.all and the then() is always fired with the same output.

I am happy to provide the original less code to render, but in private.
Thank you

**Comment by lukeapage** [comment]
Is there any chance you could
a. try it outside of your build chain against lessc?
b. let us know the version you are using - try it against the latest if you aren't using the latest
c. if it still fails sometimes, reduce your code to a test-case by removing less until the problem stops happening

Thanks

**Comment by andrepadez** [comment]
Thanks for the reply @lukeapage . I think i got it working now.
I'm using version 2.5.0 of less.js.
The flow goes like this: 
* i read a lot of .less files in different locations
* i add each one to an array
* in the end, i join the array of strings with arr.join()
* i use less.render to compile it

I was doing arr.join('') without a separator and i believe that was the problem (though i don't understand why it compiled most of the times). Now i'm joining the files content with \n and i haven't got a failure.

Thank you very much, i think this issue can be closed.

**Comment by lukeapage** [comment]
thanks
