### ISSUE TITLE
let less parser support heredoc to convenient multi line string input

### ISSUE THREAD

**Issue by keven-wang** [less/less.js#2580]
i want to add a function for less to genererate svg string , the function will be used as follows: 

``` css
background-image: svg-cont('width:80', 'height:100', <<EOF
        <path d="m100,100"/>
        <path d="m100,50"/> 
       ...
EOF);
```

but the parser of the less didn't support heredoc, so it's diffcult to input multi line string. i edit parser.js  implements heredoc. so i want my edit can be merged. the following is my edit.

----------------parser.js

``` js
                quoted: function () {following
                    /* the orginal implements
                   var str, j = i, e, index = i;

                    if (input.charAt(j) === '~') { j++; e = true; } // Escaped strings
                    if (input.charAt(j) !== '"' && input.charAt(j) !== "'") { return; }

                    if (e) { $char('~'); }

                    str = $re(/^"((?:[^"\\\r\n]|\\.)*)"|'((?:[^'\\\r\n]|\\.)*)'/);
                    if (str) {
                        return new(tree.Quoted)(str[0], str[1] || str[2], e, index, env.currentFileInfo);
                    }*/

                    var str_reg  = /^"((?:[^"\\\r\n]|\\.)*)"|'((?:[^'\\\r\n]|\\.)*)'/;
                    var here_reg = /<{2,}(\w+)([\S\s]+?)\1/;
                    var str, j = i, e, isStr, isHereDoc, index = i;

                    if (input.charAt(j) === '<') { isHereDoc = true; }
                    if (input.charAt(j) === '~') { j++; e = true; $char('~'); } // Escaped strings
                    if (input.charAt(j) === '"' || input.charAt(j) === "'") { isStr = true; }

                    if(isHereDoc && (str = $re(here_reg)) ){
                        return new(tree.Quoted)('"', str[2].trim(), false, index, env.currentFileInfo);
                    }else if( isStr && (str = $re(str_reg)) ){
                        return new(tree.Quoted)(str[0].charAt(0), str[1] || str[2], e, index, env.currentFileInfo);
                    }
                },
```

**Comment by seven-phases-max** [comment]
Multiline strings were discussed at #1648, but the context and use-case there were quite different so I'm not closing this as a duplicate.

Regardless of above, please learn how to work with GitHub forks and pull-requests (https://help.github.com/categories/collaborating/). Additionally see [Contributing Notes](https://github.com/less/less.js/blob/master/CONTRIBUTING.md#feature-requests).

**Comment by seven-phases-max** [comment]
Technically this can be achived with something like:
```less
div {
    background-image: svg-cont(
        'width:80', 'height:100', `' \
        <path d="m100,100"/> \
        <path d="m100,50"/> \
               ... \
        '`);
}
```

But this is quite hackish.

**Comment by keven-wang** [comment]
sorry, i am a newer of git, i will learn how to use forks and pull-requests。 i will not use \ to generate muli line string. it is ugly and it is be diffcult to read, you can not figure out whether some space exists behind \。if not support heredoc i'd better to use following code to input:
```css
background-image: svg-cont('width:80', 'height:100',
        '<path d="m100,100"/>'
        '<path d="m100,50"/>' 
);
```
it's not convenient, but it's easy to read. a lot of language support heredoc like ruby(my favorite)、php、C#...。i can not think out why we not support it, it's so easy to support it.

**Comment by battlesnake** [comment]
Backslash continuation is explicit and readable - I can tell that a line is continued by the trailing backslash, and tell that it continues from the previous one if that has a trailing backslash.  Bash-style `<<EOF` is less readable by that same reasoning.

Wouldn't it be cleaner to have the SVG in separate SVG files instead, and to use the build system to inline them into the LESS or the generated CSS during build?

**Comment by seven-phases-max** [comment]
@battlesnake
>and to use the build system to inline them into the LESS or the generated CSS during build? 

You don't even need any external tool for this since `data-uri`(http://lesscss.org/functions/#misc-functions-data-uri) does this.
Though I can imagine reasons you don't want it in a separate file:
Beside ovbivious but not so important idea of "keeping tiny/depended snippets of code consolidated", curretnly there's a major show-stopper for the inlined SVG. Unlike any other svg code insertion methods, the CSS-inlined svg *cannot be styled by the CSS itself* (that's fun and pitty :).
So by explicitly inlining svg as a string you get an option/wrokaround to style/parametrize it least via variables, e.g.:
```less
@width: 80;
background-image: svg-cont('width:@{width}', 'height:100',
        '<path d="m100,100"/>'
        '<path d="m100,50"/>' 
);
```
Otherwise you have to put the svg into the HTML (or invent even more dirty tricks [like this](http://codepen.io/seven-phases-max/pen/neAdb?editors=110))

**Comment by battlesnake** [comment]
Interesting, I didn't know that CSS doesn't get applied to inline SVG

Regarding syntax, I think a good golden rule is "look at how Bash does it, and do the opposite".

**Comment by matthew-dean** [comment]
>  I didn't know that CSS doesn't get applied to inline SVG

It only does if the SVG is inline in the HTML document. You can also reference a CSS file from within the SVG file, so there's no reason that CSS file couldn't be the same LESS-generated one. That might be a cleaner approach.

**Comment by battlesnake** [comment]
I built an interactive SVG-based project a few months ago, I think some browsers/devices had issues with referencing stylesheets from in SVG documents (I recall that IE and mobile Safari were the worst offenders for SVG bugs)

**Comment by matthew-dean** [comment]
See the link. Apparently it may work if you embed using <object>.

**Comment by battlesnake** [comment]
I tried object / embed / iframe / img.  For some methods, the interactivity broke on certain browsers/platforms - whatever implementation I use in that finished version is based on compromises over browser bugs.

**Comment by matthew-dean** [comment]
@battlesnake You're probably right. Browsers still suck at cross-platform SVG, and they'll fail at different times. I did an SVG-based mobile app once. Mobile Safari would grind to a halt because it allocated memory for the total calculated size of SVG, regardless of how much was actually drawn in the document. Mobile IE would crash at random times depending on the number of SVGs and their interactivity.

**Comment by keven-wang** [comment]
first, thanks focus and reply for this issue.  i explain why i wanted add this features for less.  
@seven-phases-max guessed righit. i didn't like write code in a separate file, beacuse you can not change some set through less variable, and  it can not  "keeping tiny/depended snippets of code consolidated". 

in the project , i use svg as background image for some icon instead of png image or gif image. because must input some long attriubte such as xmlns when writing svg code, i changed less code and add a function for less to generate svg code, then  i can only write svg content and some key attibutes.  but in less it is diffcult to  input a mulitline string and passed to a javascript function to handle.

@seven-phases-max's idea [](http://codepen.io/seven-phases-max/pen/neAdb?editors=110) is not convenient enough, because has a lot of svg tag and atttriubtes , i canot write  a lot of mixins to map them.
