### ISSUE TITLE
LESS to JSON instead of CSS?

### ISSUE THREAD

**Issue by Pomax** [less/less.js#2581]
Is there a way to make LESS generate JSON output instead of CSS, so that it can be easily further manipulated by automation tools? (If not built in, is there some way to hook into LESS's AST to write it out as a JSON file?)

**Comment by seven-phases-max** [comment]
>Is there a way to make LESS generate JSON output instead of CSS, so that it can be easily further manipulated by automation tools?

No.

>If not built in, is there some way to hook into LESS's AST to write it out as a JSON file?

You can write your own [plugin](http://lesscss.org/usage/#plugins-for-plugin-authors) to render the AST to a desired format.

**Comment by seven-phases-max** [comment]
I'm marking this for closing since it's not an issue or a bug report.

**Comment by Pomax** [comment]
cheers
