### ISSUE TITLE
generated source map from sourceMapFileInline points to input:<lineno>

### ISSUE THREAD

**Issue by wprater** [less/less.js#2583]
when generating the source map file inline, the result seems to tell the browser the filename is `input:<lineno>` vs the .less file.  any ideas why this would be happening?

**Comment by seven-phases-max** [comment]
Some more info on how exactly you do it? E.g. command-line, programatically, something else? Please [do make us torture you](https://github.com/less/less.js/blob/master/CONTRIBUTING.md#reporting-issues).

**Comment by wprater** [comment]
it's being done programmatically leveraging the middleware example. 

```
/**
 * Run the middleware on files that contain .less
 */
function lessMiddleware (req, res, next) {
  var parsed = require('url').parse(req.url);
  if (parsed.pathname.match(/\.less\.css$/)) {
    return less(parsed.pathname).then(function (o) {
      res.setHeader('Content-Type', 'text/css');
      res.end(o.css);
    }, function(err) {
      console.log(err);
    });
  }
  next();
}

/**
 * Compile less
 */
function less(src) {
  var LessPluginAutoPrefix = require('less-plugin-autoprefix');
  var autoprefix = new LessPluginAutoPrefix({ browsers: ['last 2 versions'] });

  var lessFile = 'client' + src.replace('.css', '');
  var f = require('fs').readFileSync(lessFile).toString();
  return require('less').render(f, {
    sourceMap: {sourceMapFileInline: true},
    paths: ['./client/styles'],
    plugins: [autoprefix],
  });
}
```

I'll see about creating a test case.

**Comment by seven-phases-max** [comment]
You need to set `filename` option. See #2342 for more details. (it's mentioned in the docs, but indeed it looks like this should be stressed as a *must* for a programmatic usage).

**Comment by wprater** [comment]
I had found that issue and made such an attempt with no success.  with the correct options, Im now getting the path!  thank you.
