### ISSUE TITLE
"when" function question

### ISSUE THREAD

**Issue by brood09** [less/less.js#2585]
Hi, 
I have a situation:
It is able to create the function"when" in function"when" ? but if yes, how? Thx: 

@a: 1;
@b: 1;
@header-height: 200;

.myFunction(@a) when (@a > 2) {
  .body {
    color: blue;
  }
}

.myFunction2(@b) when (@b = 1) {
    .body {
      color: red;
    }
}

.header {

    & when (@header-height < 125) {
      .myFunction(@a);
    }

    & when (@header-height > 125) {
      .myFunction2(@b);
    }
}

**Comment by seven-phases-max** [comment]
Please use [backticks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) to format your code.
Also note this issue tracker is for issue and bug reports (see https://github.com/less/less.js#more-information). For general "How-To" Less language questions consider using [SO](http://stackoverflow.com/questions/tagged/less).

**Comment by seven-phases-max** [comment]
Closing as not an issue.
