### ISSUE TITLE
@import (inline, optional) fails with source maps enabled

### ISSUE THREAD

**Issue by mmelvin0** [less/less.js#2599]
If I do the following:

```less
@import (inline, optional) 'file.css';
```

When `file.css` is missing, LESS still tries to generate a source map and fails in `SourceMapOutput.add` since `this._contentsMap[fileInfo.filename]` is `null` for the optional, missing import.

Disabling source maps (or supplying `file.css`) allows the build to complete successfully.

**Comment by mmelvin0** [comment]
I'm willing to try my hand at fixing this... any hints as to how I can tell during source map generation that an import was in fact optional?

**Comment by lukeapage** [comment]
A simple guard around `this._contentsMap[fileInfo.filename]` might be okay..  That or better,  look at where sourcemap gets its list of fileInfo's and make optional not present imports not add to that list (prob.  In import manager or the import node)

**Comment by mmelvin0** [comment]
I originally changed what `Import.eval()` was returning so it didn't have a null filename, but opted for this change to `ImportVisitor` instead as it seemed simpler and uses already existing hooks for skipping an import.
