### ISSUE TITLE
Load less variables from JSON

### ISSUE THREAD

**Issue by donnes** [less/less.js#2606]
I'm developing a "module builder", when I will create "modules" (header, footer, forms, etc) for my websites.
So I will load all "module" dependencies from a JSON file.

##### `module.json` - Read module dependencies.
```
{
	"variables": {
		"less" : {
			"header_blue_bg": "@pallet_01_color_01",
			"header_blue_color": "@pallet_02_color_01",
			"header_blue_link": "@pallet_03_color_01"
		}
	},
	"files": {
		"js": [
		],
		"less": [
			"less/header_blue.less"
		]
	}
}
```

> `@pallet_XX_color_XX` - Are variables of color picker.

##### `header_blue.less`
```
.header {
	background: @header_blue_bg;
	color: @header_blue_color;

	a {
		color: @header_blue_link;
	}
}
```
> Well, note that I don't have a `variables.less` and my variables are been loaded from the JSON.
I loaded my variables and I used a `less.modifyVars()` function to change the variables, but it don't work.

In console I receive an error that tells me that the variables are undefined.

Well, is it and sorry for bad english.

**Comment by seven-phases-max** [comment]
>I loaded my variables and I used a  less.modifyVars()  function to change the variables

Show the code of converting your JSON stuff to `.modifyVars()` parameter(s). Also specify how exactly you compile (comman line `lessc`?, browser script? etc.) W/o this info it's almost impossibe to guess what could be wrong.

**Comment by donnes** [comment]
I'm working with AngularJS to make the app.

#### First I push my less file to the document.
```
	this.initLess = function (file) {
		var lessFile  = file; // tmp_main.less
		var lessLink  = document.createElement('link');
		lessLink.rel  = "stylesheet/less";
		lessLink.type = "text/css";
		lessLink.href = lessFile;
		less.sheets.push(lessLink);
		less.refresh();
	};
```
#### After I use AJAX to read my JSON and get the variables with foreach.
```
	this.getJson = function(url) {
		var json;

		$.ajax({
			dataType: 'json',
			url: url,
			cache: false,
			async: false,
			success: function (ret) {
				json = ret;
			}
		});

		return json;
	}

	this.getLessVariables = function () {
		var module = getJsonService.getJson("../modules/header/default/module.json"),
			variables = [];


		for (var var_name in module['variables']['less']) {
			
			variables += '@'+var_name+ ': ' + module['variables']['less'][var_name] + ";\n";
		}

		return variables;
	}
```

#### Last I use a function to get the variables from color picker.
```
	$scope.$on('colorpicker-selected', function(event, colorObject) {
		var myArray = [];
		$scope.variablesLess['@'+colorObject.name] = colorObject.value;
		myArray.push($scope.variablesLess);
		less.modifyVars(myArray);
		less.refreshStyles();
	});
```

**Comment by seven-phases-max** [comment]
@donnes So... where this `@model_default_navbar_bg` is actually defined? Is it one of the variables you set via `modifyVars`? Or is it defined elsewhere? (and if it's "elsewhere", is that "elsewhere" file is actually imported in files you get the error for?)

**Comment by donnes** [comment]
@seven-phases-max So, `@model_default_navbar_bg` is `@pallet_01_color_01` when `@pallet_01_color_01` is set via `modifyVarys` in colorpicker function.

```
{
	"less": {
		"model_default_navbar_bg": "@pallet_01_color_01"
	}
}
```

What I want to do is setting my variables from a JSON without need set they in `variables.less`, for example.

**Comment by seven-phases-max** [comment]
@donnes I see. But the main point in my question is "do you import the file where this `@model_default_navbar_bg` is defined in the files you compile"? Actually, I start to think that the whole problem is not in `modifyVars` at all but in missing imports...

**Comment by donnes** [comment]
@seven-phases-max 

#### main.less
```
@model_default_navbar_bg: "somevalue"; - Is getting from JSON (not is defined here)

.navbar {
	background: @model_default_navbar_bg;
}
```

The variable `@model_default_navbar_bg` is defined in my less, but I don't set a value for her. I want set the value via `modifyVars`.

**Comment by seven-phases-max** [comment]
@donnes Note that definitions (or anything) are not shared between Less files `<link>`ed in your document (each `<linkrel= "stylesheet/less">` is compiled separately), so if (for example) `tmp_main.less` (you include there *independently* of the `main.less`) tries to access `@model_default_navbar_bg` it can't see the default one defined in `main.less` (unless `tmp_main.less` explicitly imports `main.less`).

**Comment by donnes** [comment]
@seven-phases-max And not have any possibility to set a variable without defined a default?

Because I will need get my variables from JSON and write in `tmp_main.less` and imports to `main.less` I will have a great performance problem. Imagine all this in real time, with several people connected.

**Comment by seven-phases-max** [comment]
@donnes

>And not have any possibility to set a variable without defined a default?

No there's no direct way (after all `less.js` is not designed as a run-time dynamic CSS manipulation library, so almost any client-side usage of it is almost an abuse edge-case).

Either way, there're few possibilities: 
A. Do you really need `tmp_main.less` at all? (note that when you call `refreshStyles` you recompile *each* linked Less file anyway so from performance point of view it would be the same if you just create one file that imports all Less code required for the particular page and put all the default stuff there).
B. Depending on `tmp_main.less` content: you could just generate the Less code directly as text. Notice that `modifyVars` does nothing but translating `{a: b}` to `"@a: b;"` string and then appending that string to a linked Less file (also being just a string at this point) being modified. (I.e. you could do all this on your own in your script w/o creating a link to an external file, by generating the same code text in a `<style>` tag instead).

**Comment by donnes** [comment]
@seven-phases-max 

Well, if not possible like I thought I'll try the options that you show me.
I wanted to do something more magical. (haha)

Sorry for bothering!!
When I have a result I back to post here.

Thank you very much!
