### ISSUE TITLE
Ability to output a parse tree back to less

### ISSUE THREAD

**Issue by kastermester** [less/less.js#2616]
I'm doing some work for my company, where we use less to write our stylesheets in (big surprise!).

As part of our build we do some custom transformations on our less files. Right now all of this is happening inside the entire less -> css process. I would very much like to take this step and turn it into its own build process (ie. apply our custom transformations on the less tree, without compiling less to css). For our particular case, this should technically not be a problem, and I have written code that does this without any issues, my only problem is I can't seem to find a way to output the less parse tree back out as less.

FYI: I don't need any evaluation of anything at all. Mainly I'm interested in transforming `@import` calls (change the import path) and `url(...)` function invocations and stuff like this.

Have I missed something? Is this actually possible?

**Comment by seven-phases-max** [comment]
> Is this actually possible?

No, there's no such feature. 

There's corresponding feature-request: #1271, but as far as I can guess nobody plans to actually implement this.

**Comment by SomMeri** [comment]
I think that you did not missed anything, less.js does not have such functionality.

This [thread](https://github.com/less/less.js/issues/2202) is about similar topic and mentions some less beautifiers, maybe one of them could do what you need.
