### ISSUE TITLE
import by reference inlines source's inline imports

### ISSUE THREAD

**Issue by rayshan** [less/less.js#2620]
Hi!

`2.5.1` with no CLI flags

`a.less` has:
```less
@import (inline) "normalize.css";
// a bunch of stuff
```

`b.less` has:
```less
@import (reference) "a.less";
// nothing else
```

`normalize.css` is inlined in both `a.css` and `b.css` output.

Desired:

`normalize.css` is inlined in only `a.css` output.

Related:
https://github.com/less/less.js/issues/2464
https://github.com/less/less.js/pull/2470

**Comment by NicBright** [comment]
I've just experienced the same issue (same use-case: inlining normalize.css). Couldn't describe it better than rayshan.
