### ISSUE TITLE
Feature - Provide sourceMapSourceRoot pass-through option

### ISSUE THREAD

**Issue by am11** [less/less.js#2621]
`sourceRoot` is path of the source-map [spec](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit?pli=1#heading=h.75yo6yoyk7x5), which states:

> **Resolving Sources**
> If the sources are not absolute URLs after prepending of the “sourceRoot”, the sources are resolved relative to the SourceMap (like resolving script src in a html document).

The value will be emitted _as is_ in the map's JSON with `sourceRoot` key, without needing any validation. This is for the browsers or downstream agents to prepend/resolve other paths in map file at runtime. 

For that matter, I propose adding `sourceMapSourceRoot` (code usage) and `--source-map-source-root`.

IMO, this should not affect other existing options; consumers will need to bare in mind that in most cases the usage would demand `sourceMapRootPath` (applied at compile time) xor `sourceMapSourceRoot` (applied at runtime).

Duplicate: https://github.com/less/less.js/issues/1771 (also similar option was added in libsass to fix an issue reported in node-sass: https://github.com/sass/node-sass/issues/731, while the ruby-sass still lacks this option)

**Comment by seven-phases-max** [comment]
Mm, I could miss somthing (never bother with sourcemaps myself), but isn't is this the default compiler behaviour?
E.g. if you do just `lessc --source-map foo/x.less x.css` the path in the source map is `"foo/q.less"`,
same way for `lessc --source-map:z/z.map foo/x.less x.css` it's `""../foo/q.less""`...
Should it differ with the proposed option?
`

**Comment by am11** [comment]
@seven-phases-max,
Currently the `.map` output emitted by lessc looks like this:

```json
{
    "version": 3,
    "sources": [ "../fonts/DejaVu/dejavu.less", "MAIN.css", "../MAIN.less" ],
    "names": [ ],
    "mappings": "AAAA;EAEI,2BAAA;EACA,qDAAA;EACA,4JAAA;CCAH;ACFD;EACI,aAAA;CDIH",
    "file": "MAIN.css"
}
```

With this option in the mix, when set, the ouput will look like:

```bash
 lessc --source-map --source-map-source-root my/basepath foo/x.less x.css 
```

```json
{
    "version": 3,
    "sources": [ "../fonts/DejaVu/dejavu.less", "MAIN.css", "../MAIN.less" ],
    "names": [ ],
    "mappings": "AAAA;EAEI,2BAAA;EACA,qDAAA;EACA,4JAAA;CCAH;ACFD;EACI,aAAA;CDIH",
    "file": "MAIN.css",
    "sourceRoot": "my/basepath"
}
```

At runtime, the browser (such as Chrome) will resolve the sources as: "my/basepath/../fonts/DejaVu/dejavu.less".

nit: in the above example, the `sources[]` array shouldn't contain the `.css` file (but only the `.less` sources, `file` option is already there for generated `.css`). I am trying to spot into lessc code what is causing it. :) (Is it intentional?)

**Comment by seven-phases-max** [comment]
@am11

Ah, I see, thanks!
(so with this option the `--source-map-rootpath` is ideally to be deprecated because they simply overlap? I'm not sure though if this could break the `--source-map-basepath`).

**Comment by am11** [comment]
@seven-phases-max, IMO, the existing `--source-map-rootpath` and the proposed `--source-map-srouce-root` can co-exist. The former resolves the paths at runtime while the latter will just emit the value in `.map` file as is for browsers to compile. Therefore, no breaking change is intended with this addition. :)

**Comment by seven-phases-max** [comment]
>The former resolves the paths at runtime while the latter will just emit the 

Yes, I understand, I was more just worrying about their count.

**Comment by am11** [comment]
> I was more just worrying about their count.

I agree; this is a genuine concern. :smile: 
Nonetheless, IMO more is better in this case. lessc nailed it with all those customization options for source-map and other paths resolutions. I have discovered lack of such options in many other trans-compilers (CoffeeScript, LiveScript etc.), which leads to mysterious limitations. I think there is a need of an API or speclet to unify source-maps and path-related behaviour of various trans-compilers, so the downstream consumers do not need to learn varied implementations if the upstream conforms with some well-known interface.
