### ISSUE TITLE
Turkish Language

### ISSUE THREAD

**Issue by ermeydan** [less/less.js#2622]
Hi,

We are students at Computer Engineering Department of Istanbul University. We use a lot of Less and we decided to translate documentation for our Turkish people better understanding. If this is possible for you we are ready to translate. 

We are waiting your feedback, Thanks.

Best Regards,
Burak Ermeydan, Deniz Güzel

**Comment by seven-phases-max** [comment]
See #2492, #2356 etc. I.e. you don't really need any specific stuff (or any special permission) to do the translation. Just fork [the documentation repository](https://github.com/less/less-docs) and begin. Then when it's ready PR a link to the translated site.

**Comment by seven-phases-max** [comment]
Closing as not an issue.
