### ISSUE TITLE
less.refreshStyles(); refresh all .less files instead of refreshing specific .less file

### ISSUE THREAD

**Issue by bamsbale** [less/less.js#2627]
I'm using .less styles and less.js for my asp.net project and bit confusing that how to modify variables in specific .less file and refresh only that specific file.

In my case it'll reset all the .less files including master page .less files when I'm trying to change variables in child page.

Thank you !

**Comment by lukeapage** [comment]
Its not possible. either
a) handle the refresh yourself - see https://github.com/less/less.js/blob/master/lib/less-browser/index.js#L224
b) submit a patch back to us where refresh takes an argument for the file to refresh
