### ISSUE TITLE
ParseError: Could not parse call arguments for "rgba(255, 255, 255, 0.)"

### ISSUE THREAD

**Issue by void256** [less/less.js#2628]
Compiliing `@my-color: rgba(255, 255, 255, 0.);` produces a `ParseError: Could not parse call arguments or missing ')' ` when using lessc 2.5.1.

In my opininion '0.' should be treated as a valid alpha value for specifing rgba colors.

Steps to reproduce this issue from the commandline:

```
> lessc -v
lessc 2.5.1 (Less Compiler) [JavaScript]

> cat styles.less 
@my-color: rgba(255, 255, 255, 0.);

> lessc styles.less 
ParseError: Could not parse call arguments or missing ')' in /private/tmp/styles.less on line 1, column 33:
1 @my-color: rgba(255, 255, 255, 0.);
2 
```

**Comment by seven-phases-max** [comment]
A minimal test would be just:
```
@a: (1.); // error
```

I.e. it's simply something wrong with parsing any `digit.` when in parens.

**Comment by Panya** [comment]
> In my opininion '0.' should be treated as a valid alpha value for specifing rgba colors.

Why it should be treated as a valid alpha value if it's invalid by CSS spec (see http://www.w3.org/TR/css-syntax-3/#number-token-diagram)? I think current behavior is correct.

**Comment by seven-phases-max** [comment]
@Panya Indeed, our mistake - I guess we both trapped up by other language stereotypes where `0.` is valid floating point number.

**Comment by seven-phases-max** [comment]
Closing as expected behavior (`.` must be followed by one or more digits per [CSS spec.](http://dev.w3.org/csswg/css-values-3/#numbers)).
