### ISSUE TITLE
less 2 tests failed

### ISSUE THREAD

**Issue by vadim-kuhtin** [less/less.js#2630]
>> NameError: variable @global-var is undefined in src/main/webapp/node_modules/less/test/browser/less/global-vars/simple.less on line 2, column 10:
>> 1 .test {
>> 2   color: @global-var;
>> 3 }

**Comment by seven-phases-max** [comment]
Could you provide more details? How (and why) you compile this file?

The file is used to test [](http://lesscss.org/usage/#using-less-in-the-browser-globalvars) option and thus it requires the variable to be defined externally (hence the error is expected if you try to compile this file alone).
Note that files in [`test/browser`](https://github.com/less/less.js/tree/master/test/browser) dir are used to test only some specific browser functionality and usually require some specific environment and options (in other words they are not really supposed to be used anywhere except the test suite itself). If you need just "some" valid Less code to test your setup, use files in [`test/less`](https://github.com/less/less.js/tree/master/test/less) (those files represent basis Less features and most of them are fine to be compiled w/o any special options and dependencies).

**Comment by SomMeri** [comment]
Closing for lack of response.
