### ISSUE TITLE
Multi-target selectors separated across multiple lines

### ISSUE THREAD

**Issue by 190n** [less/less.js#2631]
When I use a multi-target selector, like
```css
h1, h2, h3 {
    /* ... */
}
```

It's separated across multiple lines:
```css
h1,
h2,
h3 {
    /* ... */
}
```

This causes it to fail under Firefox.

**Comment by seven-phases-max** [comment]
Hmm... Could you provide more details? 
```css
h1,
h2,
h3 {
    /* ... */
}
```
is valid CSS code and it's very unlikely to fail in either browser. So if anything goes wrong it's something beyond just that.

**Comment by 190n** [comment]
Okay, I put this in a file called `index.html`:
```html
<style src="main.css"></style>
<div>hi</div>
<span>hi</span>
```
and the following in `main.css` in the same directory:
```css
div,
span {
    font-weight: bold !important;
}
```

I tried opening `index.html` in Chrome and Firefox, and both times neither of the hi's were bold. I tried it without !important too.

**Comment by seven-phases-max** [comment]
It does not work simply because external stylesheets should be included with [`<link>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link) tag:
```html
<link href="main.css" rel="stylesheet">
```
and [`<style>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style) element is only for inline code.

**Comment by seven-phases-max** [comment]
Closing as not an issue.

**Comment by 190n** [comment]
Oh, I must've blanked on that when I wrote the example code. The code where I first noticed the error did use `link` but it's been resolved now -- must've been a caching issue.
