### ISSUE TITLE
--no-comments option needed

### ISSUE THREAD

**Issue by edwardcoolson** [less/less.js#2632]
Hi Everybody! I'd like to suggest to have the option to strip out **all** the comments, not only single line ones. Why it may be necessary? Some folks are still use text editors that are not capable to do syntax highlighting of  LESS files (Example: Komodo Edit 5). These folks simply turn on CSS highlighting for LESS files that works more or less okay. So they may prefer to write '/\* \*/' comments instead of '//' -- to have them correctly highlighted in their editors. And of course the option to remove '/\* \*/' comments -- without any compression -- would be helpful.

Thank you.

**Comment by seven-phases-max** [comment]
An option to serve as a workaround for some 3-rd party tool problems does not look like a good idea (currently Less development is very conservative and any option/feature that is not a "must have" usually has high resistance).
For this particular use-case you can use [less-plugin-no-comment](https://github.com/cobomi/less-plugin-no-comment), `clean-css`` + csscomb` (or similar) combo etc. etc. (there's a lot of way to strip comment from CSS file).

**Comment by edwardcoolson** [comment]
@seven-phases-max Thank you Max, it works.

**Comment by seven-phases-max** [comment]
OK, then I'll close it (untill someone requests a "to the core!" thing).

**Comment by seven-phases-max** [comment]
Closing as implemented as [plugin](https://github.com/cobomi/less-plugin-no-comment) (or achivable w/o Less at all).
