### ISSUE TITLE
Deprecate -x option mentioned in Using Less at lesscss.org

### ISSUE THREAD

**Issue by dandv** [less/less.js#2633]
At http://lesscss.org/#using-less-command-line-usage:

> To output minified CSS, simply pass the -x option.

**Comment by seven-phases-max** [comment]
Makes sense (I moved it to https://github.com/less/less-docs though, [#349](https://github.com/less/less-docs/issues/349)).

**Comment by seven-phases-max** [comment]
Closing as moved to [[less-docs/#349](https://github.com/less/less-docs/issues/349)]https://github.com/less/less-docs/issues/349).
