### ISSUE TITLE
Implicitly called mixins don't expose variables to parent scope

### ISSUE THREAD

**Issue by edwardcoolson** [less/less.js#2641]
Hi Everybody!

I have this code to conditionally set a variable inside a mixin:

    /*@theme: dark;*/
    @theme: light;

    .theme when (@theme = dark) {
      @background: darkblue;
    }

    .theme when (@theme = light) {
      @background: blue;
    }

    body {
      background-color: @background;
    }

This gives an error that @background is not defined. After some playing with the code, I found the code that works (I just added parentheses to the mixin and made explicit call to it):

    /*@theme: dark;*/
    @theme: light;

    .theme() when (@theme = dark) {
      @background: darkblue;
    }

    .theme() when (@theme = light) {
      @background: blue;
    }

    .theme;  

    body {
      background-color: @background;
    }

Why is this ? Is it right behavior or just a bug?

Thank you.

**Comment by seven-phases-max** [comment]
Expected behavior. See [Mixins](http://lesscss.org/features/#mixins-feature). In you first snippet you simply don't invoke `.theme` as a mixin (it's the same behaviour for either parametric mixin definition or a plain ruleset).

**Comment by seven-phases-max** [comment]
Closing as expected behaviour.
