### ISSUE TITLE
Parametric mixins: parameters don't match error

### ISSUE THREAD

**Issue by edwardcoolson** [less/less.js#2645]
Hi guys,

I have this code that don't compile. The compiler issues "Wrong number of arguments..." error message:

    .mixin(@height) {
      height: @height;
    }

    .mixin(@width, @height: 10px) {
      width: @width;
  
      .mixin(@height: @height);
    }

    // mixin call
    div {
      .mixin(@height: 20px);
    }

I call the mixin with a single named parameters, the first mixin shall match but it does not. For some reason the compiler tries to match the second and not the first as if the first does not exist. If I comment the second, the first begins to work.

What is wrong with this code?

**Comment by seven-phases-max** [comment]
Confirmed. The code indeed is valid but the second mixin throws its error w/o taking into that there're other matching mixins.
