### ISSUE TITLE
less disable generation .map ? 

### ISSUE THREAD

**Issue by AlexyOd** [less/less.js#2649]

**Comment by seven-phases-max** [comment]
? 
Could you elaborate? Less does not generate any `.map` files by default, so examine your (or whatever build environment you use) options.

**Comment by AlexyOd** [comment]
when i build some less. some one create *.css.map ...

**Comment by seven-phases-max** [comment]
So as I said "examine your (or whatever build environment you use) options"... How do you build it?

**Comment by AlexyOd** [comment]
and in end css 
/*# sourceMappingURL=style.css.map */

**Comment by AlexyOd** [comment]
ctrl + b ) and it build

**Comment by seven-phases-max** [comment]
(Please take into into account we're not a telepaths here, don't make me torture you of every possible question related to *your* build environment. *Where* exactly (what Editor, IDE or whatever) do you press this `ctrl + b`?)

**Comment by AlexyOd** [comment]
in tool > build system  mark "lessc" so when i press ctrl+b worck lessc

**Comment by seven-phases-max** [comment]
What is the name of the application you have open when you do this? (Well, let me guess Microsoft Visual Studio?)

**Comment by AlexyOd** [comment]
sublime text

**Comment by AlexyOd** [comment]
ok in cmd i write lessc and see
...
--source-map[=FILENAME]  Outputs a v3 sourcemap to the filename (or output filename.map);
...
can i do sime thing wth this ???

**Comment by seven-phases-max** [comment]
Finally. Sublime. Then as I said "examine your Sublime options" (first find out what Sublime plugin you actually use to bind `lessc`, then read this plugin readme or manual for how to set/change options it launches Less compiler with).

---
For the future take into account that this issue tracker is for issue/bug-reports *only*. For a generic "How-To" questions consider using [SO](http://stackoverflow.com/questions/tagged/less). And before opening an issue ticket next time please read [Reporting Issues](https://github.com/less/less.js/blob/master/CONTRIBUTING.md#reporting-issues).

**Comment by seven-phases-max** [comment]
Closing as not a Less issue.
