### ISSUE TITLE
Lessc corrupting import file

### ISSUE THREAD

**Issue by Luke-j** [less/less.js#2651]
I'm running lessc v1.4.2 from the command line via PHPs exec() function. Recently though it's been occasionally scrambling the file I'm using to import the other .less files. The file ends up looking like this (shortened):

````
@import "confa/orte/coER ".l//////

loutot;///nio/t///aphy.leamse/tmpoundSvgg/ree/imps/rPi
@import  ///blr//les/
@idTalTconfigrle./s "conrss"tat"ig////rorleontime.lessheabnsg;e.l/////pot

/s"poeskgroab"conaTabt "mpor
@rorts/h/typog Ss"cmp/////gabl/lt "ces/p";
@cehmpmafig/bac
srbi///let//////////taoea////// "configimes/deimport "cole.lessonentsnents/tabl@imponenHEADess";
@imp;
@in;mless";coders/sts";ents/tboimpo///nts"conf.lesdt;
````

Any help is much appreciated!

**Comment by seven-phases-max** [comment]
I'm afraid it's too specific problem with too many unknowns to suggest anything helpful. Personally I'd start to look at `exec()` timeout things, but in general it can be virtually anything (incl. hardware problems).

**Comment by Luke-j** [comment]
Hmm, I understand. For the moment I've simply removed write access to the import file, which seems to do the trick. I'm as confused as you are as to what exactly is causing this.

**Comment by lukeapage** [comment]
my guess is it's quite unlikely to be lessc modifying that file.

**Comment by seven-phases-max** [comment]
>my guess is it's quite unlikely to be lessc modifying that file.

Yes, this is almost for sure since neither Less itself (nor Node in general) even open the file for writing...

**Comment by seven-phases-max** [comment]
Closing as not a Less issue.
