### ISSUE TITLE
Improve grayscale color support

### ISSUE THREAD

**Issue by rentalhost** [less/less.js#2653]
Current we can define a color in hexadecimal like `#RRGGBB`. Sometimes we need use some grayscale color, so we need repeat the desired color, like `#CCC` to `#CCCCCC` or `#CDCDCD`.

I suggest make it better, by allowing set one color only, in two models:

 * `#C` is equals to `#CCCCCC`
 * `#CD` is equals to `#CDCDCD`

On first model, we will have 16 colors support, and second 256 colors support. All in grayscale, of course.

**Comment by seven-phases-max** [comment]
Well, assuming that in Less you don't have to explicitly hand-write so many colors value like you do in CSS, such `3->1` and `6 -> 2` sugar does not sound like something valuable at all (especially counting possible conflict with future CSS standards this may introduce).

**Comment by rentalhost** [comment]
I know that here not is the best place to solve doubts, but what `3->1` mean? Is some kind of feature?

**Comment by seven-phases-max** [comment]
By `3->1` I mean using `#c` instead of `#ccc`.

**Comment by rentalhost** [comment]
Ah, yes. Now I get. Thanks!

**Comment by matthew-dean** [comment]
Don't think this will happen in core. You can do something like this, however:
```
.gray(@color) {
	color: replace(@color, "#([0-9a-fA-F]{2})|#([0-9a-fA-F]{1})", "#$2$2$2$2$2$2$1$1$1");
}
.box {
	.gray(~"#C");
	.gray(~"#CD");
}
//output
.box {
  color: #CCCCCC;
  color: #CDCDCD;
}
```

**Comment by seven-phases-max** [comment]
In CSS they recently added `gray` function to the [drafts](https://drafts.csswg.org/css-color/#grays), so it would probably nothing wrong of adding such `gray` to build-in functions (since eventually it will have to be such function in the core anyway when mentioned CSS "module" comes to TR or so).

**Comment by matthew-dean** [comment]
Nothing wrong? It isn't a problem that we have functions that are the same names as upcoming color filters? 

...Ah, was just testing. Looks like we passthrough names if the values aren't colors. Are we always going to be safe doing that?

That spec is interesting. It looks like they're proposing adding a number of calculated values similar to what Less already has.

**Comment by seven-phases-max** [comment]
>It isn't a problem that we have functions that are the same names as upcoming color filters?

Actually no, for colors it's the opposite. We *must* have functions that CSS has. E.g. see `rgba` and `hsl` for example. If Less has no `rgba` function the following code fails:
@color: rgba(1, 2, 3, .4);
div {
    color: lighten(@color, 15%);
}
```
So it's the same for `gray` (and yep, in Less `gray(33)` will then render to `#212121` and `gray(33, .5)` will render to gray(33, 33, 33, .5). Though when `gray` becomes less or more widely supported by browser it would be quite trivial to add `gray` optimization for the output).

**Comment by seven-phases-max** [comment]
Closing as too minor sugar feature (feel free to open a new ticket for a `gray` function).
