### ISSUE TITLE
Less creating source maps containing the compiled css `<input css 1>`

### ISSUE THREAD

**Issue by zanona** [less/less.js#2656]
I've been noticing that when compiling less and setting source map options like:

```js
less
    .render(contents.toString(), {
        filename: 'app.less',
        sourceMap: {
            outputSourceFiles: true,
            sourceMapBasepath: process.cwd(),
            sourceMapFileInline: true
        }   
    })
```

when having the following structure:

- `app.less` (imports `test.less`)
- `test.less`

The map generated will contain `app.less`, `test.less` and **also** the compiled css `<input css 1>` version which is not needed.

This is how it is formatted using LESS:
![screen shot 2015-08-06 at 16 52 39](https://cloud.githubusercontent.com/assets/32017/9116299/94ed2426-3c5b-11e5-9d8e-38cd92eb3e29.png)

and this is how it is formatted when compiled through SASS:
![screen shot 2015-08-06 at 16 49 57](https://cloud.githubusercontent.com/assets/32017/9116250/3fa6523a-3c5b-11e5-9d52-6c7ca7da5a8c.png)

Is there any way to disable the addition of the compiled css on the source maps and having only the source files instead? thanks

**Comment by seven-phases-max** [comment]
I can't reproduce your result with the options like above. Though I can if I also put Autoprefixer (as plugin for example) into the chain (then Autoprefixer indeed does put `<input css 1>` mappings (instead original Less lines) for the statement it adds).

**Comment by zanona** [comment]
Hey Max, thanks for the tip. You were completely right. I was using auto-prefixed after LESS compiling which caused that behaviour.

By simply adding extra options to postcss, fixed the issue.

```
postcss([autoprefixer]).process(less.css, {
    from: 'app.less'
});
```

Sorry about that and thanks again.

**Comment by seven-phases-max** [comment]
Probably I'd suggest to open a feature request at the AP repo, since ideally, when passing an external source-map through, it should map its new statements to the original sources and not to the input CSS (I was  under impression that I saw such issue ticket there, but I can't find it quickly, so maybe it was a delusion).
