### ISSUE TITLE
@import (less) ignoring "look in" paths

### ISSUE THREAD

**Issue by garygreen** [less/less.js#2663]
If you setup less to look for imports in "bower_components" it will import the bootstrap one just fine, but it can't find the select2.css one.

```less
@import 'bootstrap/less/bootstrap.less';
@import (less) 'select2/select2.css';
```

**Comment by seven-phases-max** [comment]
Just because there's no 'select2/select2.css', it's 'select2/dist/css/select2.css'.

**Comment by garygreen** [comment]
I'm using older version of select2 https://github.com/select2/select2/tree/3.5.2

**Comment by seven-phases-max** [comment]
Just in case, what is exact error message and what is exact `--include-path` including quotes if any)?

**Comment by garygreen** [comment]
My bad
