### ISSUE TITLE
promises seem not to be that optional

### ISSUE THREAD

**Issue by chrysn** [less/less.js#2665]
while promise is declared an optional dependency, lessc seems not to work without it at all.

tested on debian sid with node 1.4.2-1: unless promise is installed, cloning the git repository and running `echo 'x {a:1}' | ./bin/lessc -` gives an empty output. when an output file is specified, it is not opened for writing. nevertheless, the return code is 0, indicating success to all kinds of automation tools.

**Comment by seven-phases-max** [comment]
If I recall correctly, promises are set to be optional so that we won't have to be bloated with redundant modules when it's installed in the up-to-date `node` with native promises (`node >= 0x11.x`). The requirement to install optional polyfills sounds like a reasonable expectation for an older environment.

**Comment by rjgotten** [comment]
@chrysn 
An optional dependency is a dependency that will be tried for install and will be skipped over without aborting installation if installation fails for some reason. (E.g. the dependency cannot be found; has no compatible version; lists incompatible os or engine requirements, etc.)

If your runtime *can* install the package it *will* install the package. It's not optional in the sense that you as a user can yourself opt out of the dependency and use a module without it. NPM does have that concept though: it's called a peer dependency...

**Comment by lukeapage** [comment]
its difficult..  it might be required for lessc but for someone consuming the less package,  they can easily use the less api without promises..  thats why its optional
