### ISSUE TITLE
error evaluating function `lighten`: undefined is not a function

### ISSUE THREAD

**Issue by AjithR04** [less/less.js#2671]
I have tried to implement the javascript variable in the lighten function, but it throws error while compiling it. 

js:
var color = "#aaaaaa";

less:
```
@color: ~`color`;
@header-color: lighten(@color, 20%);
```

When I run the sample it throws the error 

![image](https://cloud.githubusercontent.com/assets/13574028/9350515/2c05be46-466f-11e5-8349-d831eaad7133.png)

Is there any thing I missed?

**Comment by seven-phases-max** [comment]
In Less strings or escaped strings are not colors. Use [`color`](http://lesscss.org/functions/#misc-functions-color) function to convert a string to color value.
Besides, using inline JavaScript statements and external JS variables in those is a bad idea in general (you never can be sure where or when those inline JS statements are evaluated). 
If you need to set variable values externally use [`--global-vars/--modify-vars`](http://lesscss.org/usage/#command-line-usage-global-variable) options.

**Comment by seven-phases-max** [comment]
Closing as expected behaviour.
