### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Romiko** [less/less.js#2673]
Hi,

If I store a base64 encoded image as a background-image e.g.:

background-image: url(@body-backgroundLayoutImage-href); 

Later the var @body-backgroundLayoutImage-href contains base64 image:
data:image/png;base64,xyz.....

We using Less-1.7.4.js

**Comment by seven-phases-max** [comment]
Not enough information. First of all it's actually not very clear what exactly causes the error... Do you really try to set a raw base-64 thing as a variable value? Theoretically it's probably possible, but in practice it's quite strange usage and you'd better to use [`data-uri`](http://lesscss.org/functions/#misc-functions-data-uri) instead.

Either way, speaking of the particular error, it would be helpful if you provide the actual code (obviously we can't reproduce your result with just `data:image/png;base64,xyz.....`).

**Comment by Romiko** [comment]
Hi, I updated to the latest version of less and it is fixed. I think it is pretty clear, base64 encoded url('xxx') caused stack size issues, this was in 1.7.4. It is not a problem anymore, must have been max Less variable size limits.
