### ISSUE TITLE
`npm install -g less` will drop in endless loop by npm 3.x

### ISSUE THREAD

**Issue by cuixiping** [less/less.js#2680]
I tested with npm 3.2.0 and npm 3.3.1,  run `npm install -g less` will not end in hours.

**Comment by lukeapage** [comment]
Using the latest npm (3.3.3) I cannot reproduce. I've been keeping up to date with npm and haven't seen any problem with npm, so it could be something in your environment and/or it could be an npm bug.

If you still get this with the latest npm 3.3.3, please raise with npm and feel free to link to this issue.
