### ISSUE TITLE
OR predicate in less guard throws compilation error in dotless

### ISSUE THREAD

**Issue by AjithR04** [less/less.js#2684]
I have tried to compile some less files which have the guard with or predicates. I know there is an and predicate for less guards, but or predicate throws compilation error in dotLess?

Please refer the less codes as below

@tree: "";
& when (@tree = "Neem"), (@tree = ""){
 /*------Neem-------*/
 .neem{
   color: green;
 }
}
& when (@tree = "Other"), (@tree = ""){
/*------Others-------*/
 .others{
    color: brown;
  }
}
So I can access all the codes or such specific code to pass some variable in the less css.

The above code is working fine in less.js compilation but it doesn't work in the dotless compilation.

Please let me know if I have missed something? I got this error while compiling in dotless version 1.5.1.0. Thanks in advance.

![image](https://cloud.githubusercontent.com/assets/13574028/9727256/ae1a0b0c-561a-11e5-82dc-9cb49010e31f.png)

**Comment by AjithR04** [comment]
I got the issue is due to the comment line, when I remove the comments inside the rules its gone. But I got another issue "Unable to cast object of type 'dotless.Core.Parser.Tree.Ruleset' to type 'dotless.Core.Parser.Tree.Rule' " :-(

**Comment by seven-phases-max** [comment]
Wrong repo. Please report at https://github.com/dotless/dotless.

**Comment by seven-phases-max** [comment]
Closing as not Less issue.
