### ISSUE TITLE
Throw Error: "Unrecognised input" as if the input has Chinese font name without quotes.

### ISSUE THREAD

**Issue by iahu** [less/less.js#2693]
Hi, as we can use Chinese font name _without quotes_ in most browsers (windows platform: >=ie6, chrome, firefox, opera). I suggest that the `keyword` function in `parser.js` pass Chinese font name which without quotes instead of throw an "Unrecognised" error.

```
keyword: function () {
    var k;
    // add Chinese word to range.
    k = $re(/^%|^[\u4e00-\u9fa5_A-Za-z-][\u4e00-\u9fa5_A-Za-z0-9-]*/);
    if (k) {
        var color = tree.Color.fromKeyword(k);
        if (color) {
            return color;
        }
        return new(tree.Keyword)(k);
    }
},
```

**Comment by seven-phases-max** [comment]
My concern is performance. Notice this function is evaluated for *every single* entity in the source code string so more complex regexp could be quite overkilling. Browsers may be more tolarate but according to [the spec](http://www.w3.org/TR/CSS21/syndata.html#value-def-identifier):
>In CSS, identifiers (including element names, classes, and IDs in selectors) can contain only the characters [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_);

Assuming quoted font names work fine (do they?), I'd vote against this.

**Comment by iahu** [comment]
I think performance is not a point.
I have make a simple test code.
```
var fs = require('fs');
var loopCount = 1000;
var less = require('less');
var parser = new (less.Parser)({});

fs.readFile('./test/test.less', 'utf-8', function (err, content) {
	var startTime = new Date();

	for (var i = 0; i < loopCount; i++) {
		countParseTime(i, loopCount-1);
	}

	function countParseTime (i, max) {
		parser.parse(content, function (err, tree) {
			if (err) {
				console.log(err);
				return;
			}
			if (i >= max) {
				console.log( new Date() - startTime );
			}
		});
	}
});
```
both run 12 times on my computer (mac os x).

short regexp: 132 | 132 | 134 | 131 | 139 | 133 | 131 | 136 | 135 | 138 | 141 | 132
long regexp : 134 | 131 | 139 | 133 | 131 | 136 | 135 | 138 | 141 | 132 | 133 | 133

The tow codes almost make no difference at aspect of performance.

**Comment by rjgotten** [comment]
1000 is far, far too low of a loop count to start noticing statistically relevant ifferences.
Bump that up to 10.000 or 100.000 and more importantly: run it on a file of significant size, so that you outscale the start-up costs of booting up the parser.

**Comment by iahu** [comment]
ok, Think your tips.

BTW, I have made a [node command line tool](https://github.com/iahu/normalizeFontFamily) to fix some error like this.

**Comment by rjgotten** [comment]
> to fix some error

@iahu , you *are* aware that your tool will fail horribly on perfectly valid CSS, right?
E.g.
```css
.font-family::before {
  /*...*/
}
```
Will be consumed by your regex `/(font-family\s?:)([^;!}]+)?/g` and will bomb horribly.

**Comment by iahu** [comment]
@rjgotten Thank your feedback.I'll fixed at next commit.
