### ISSUE TITLE
Missing closing ')' when referencing a mixin.

### ISSUE THREAD

**Issue by Giwayume** [less/less.js#2695]
Consider the following:
```
.input(@rules) {
	input[type="text"],
	input[type="email"],
	input[type="search"],
	input[type="password"],
	input[type="date"],
	input[type="datetime-local"],
	input[type="tel"],
	input[type="time"],
	input[type="url"],
	input[type="number"] {
		@rules();
	}
}
.input-container {
	.input({
		padding-right: @input-icon-width;
	});
	.icon + .input({
		padding-left: @input-icon-width;
	});
}
```

I am getting "Missing closing ')'" when attempting the CSS next sibling selector with a mixin ".icon + .input({". Is this a bug, not in the design, or am I missing something?

**Comment by matthew-dean** [comment]
A mixin can't be called as part of a selector, as far as I know. It doesn't really make sense because the mixin won't emit a selector in your example. So it's like writing ```.icon + { }```

**Comment by lukeapage** [comment]
yep. @Giwayume you are trying to do 2 things at once.

I think [this example is what you want to do...](http://less2css.org/#%7B%22less%22%3A%22%40input-icon-width%3A%201%3B%5Cn%5Cn.input(%40rules)%20%7B%5Cn%20%20%20%20input%5Btype%3D%5C%22text%5C%22%5D%2C%5Cn%20%20%20%20input%5Btype%3D%5C%22email%5C%22%5D%2C%5Cn%20%20%20%20input%5Btype%3D%5C%22search%5C%22%5D%2C%5Cn%20%20%20%20input%5Btype%3D%5C%22password%5C%22%5D%2C%5Cn%20%20%20%20input%5Btype%3D%5C%22date%5C%22%5D%2C%5Cn%20%20%20%20input%5Btype%3D%5C%22datetime-local%5C%22%5D%2C%5Cn%20%20%20%20input%5Btype%3D%5C%22tel%5C%22%5D%2C%5Cn%20%20%20%20input%5Btype%3D%5C%22time%5C%22%5D%2C%5Cn%20%20%20%20input%5Btype%3D%5C%22url%5C%22%5D%2C%5Cn%20%20%20%20input%5Btype%3D%5C%22number%5C%22%5D%20%7B%5Cn%20%20%20%20%20%20%20%20%40rules()%3B%5Cn%20%20%20%20%7D%5Cn%7D%5Cn.input-container%20%7B%5Cn%20%20%20%20.input(%7B%5Cn%20%20%20%20%20%20%20%20padding-right%3A%20%40input-icon-width%3B%5Cn%20%20%20%20%7D)%3B%5Cn%20%20%20%20.icon%20%2B%20%26%20%7B%5Cn%20%20%20%20%20%20.input(%7B%5Cn%20%20%20%20%20%20%20%20padding-left%3A%20%40input-icon-width%3B%5Cn%20%20%20%20%20%20%7D)%3B%5Cn%20%20%20%20%7D%5Cn%7D%22%7D)
