### ISSUE TITLE
Compile border-radius with two params separated by slash

### ISSUE THREAD

**Issue by csharpninja** [less/less.js#2697]
Hi,

when compile border-radius with two params separated by slash like:

```css
border-radius: 100px / 10px;
```

at the output I have only the last radius:

```css
border-radius: 10px;
```

**Comment by seven-phases-max** [comment]
Use either [`--strict-math=on`](http://lesscss.org/usage/#command-line-usage-strict-math) or [escaping](http://lesscss.org/features/#features-overview-feature-escaping), e.g. `border-radius: 100px ~'/' 10px;`.

**Comment by seven-phases-max** [comment]
Merging to #1880.
