### ISSUE TITLE
add class to overall parent selector

### ISSUE THREAD

**Issue by janwagner** [less/less.js#2700]
Hi there シ

I am looking for a way to add a nested selector to the overall parent.

It is possible to do this
```
.parent {
    .child {
        .grandchild & {
            ...  
        }
    }
}
```
Output
```
.grandchild .parent { ... }
```

### And I am looking for a way to do this
```
.parent {
    .child {
        .grandchild ***ADD ME TO THE OVERALL PARENT*** {
            ...  
        }
    }
}
```
Output
```
.parent.grandchild  { ... }
```

Is there any way yet?

THX Jan

**Comment by seven-phases-max** [comment]
The issue tracker is not support forum (it's meant to be used only for issue/bug reports and feature requests), so strictly speaking question like this are offtopic here too. (In general SO is a better place to start).

---
Either way for you example it would be as simple as (not counting your samples above turned to be incorrect after you modified theme comparing to https://github.com/less/less-docs/issues/363):
```less
.parent {
        .grandchild& {
            ...  
        }
}
```
i.e. it's really as simple as: "& is expanded *exactly* where you place it" (usually it's assumed to become evident from variouse example in [Parent Selectors](http://lesscss.org/features/#parent-selectors-feature).

**Comment by seven-phases-max** [comment]
Closing as not an issue.
