### ISSUE TITLE
Interpolation of variable, mixin and function names (a.k.a. "Dynamic" variables/mixins/functions)

### ISSUE THREAD

**Issue by WalkerCodeRanger** [less/less.js#2702]
Using less 2.5.1 on http://less2css.org  I can use [variable variable Names](http://lesscss.org/features/#variables-feature-variable-names) to access a variable.

```
@var-name: "foo";
@foo: 45px;
.selector
{
    width: @@var-name;
}
```

Outputs:

```
.selector {
  width: 45px;
}
```

However when I try to declare the varible the same way, it gives an error:

```
@var-name: "foo";
@@var-name: 45px;

.selector
{
    width: @@var-name;
}
```

Gives:

```
ParseError: Unrecognised input on line 2, column 1:

1 @var-name: "foo";
2 @@var-name: 45px;
3 
```

The real world use case for this is I would like to have a grid framework that supports a variable number of breakpoints the user can change the names of.  So I need to take a list of screen size names and declare a bunch of variables based on those.  i.e.

```
@screen-size-names: xs, s, m, l, xl;
@screen-breakpoints: 544px, 7568px, 991px, 1200px;
```

And then use mixins to declare variables like `@screen-s-min`, `@screen-m-max` etc.

**Comment by rjgotten** [comment]
> So I need to take a list of screen size names and declare a bunch of variables based on those.

No. You need to declare keyed dictionaries; which you can build with lists...

**Comment by WalkerCodeRanger** [comment]
@rjgotten I don't know what you mean when you say "keyed dictionaries; which you can build with lists". Can you provide a reference to an example or an example less?

**Comment by seven-phases-max** [comment]
>Can you provide a reference to an example or an example less?

This depends on the code you need to use such "variables" in. In general yes, the need for such variable-variable-names hints that there's something wrong with the approach (just think of it: you define something with *unknown* name to represent a value you would refer to later by the same *unknown* name... It does not make any sence really). And yes, lists/arrays and more "structured" (whatever this could mean in general) programming are much more clean and straight-forward (compared to both gypotetical variable-name-variable-definition and variable-name-variable-access (yet another closely related anti-pattern of "moving every thing into a dedicated global variable")).

A simplest example (just *example*, guessing you would use those variables for some grid generation) would be:
```less
@devices:
	s   544px,
  	m   768px,
  	l   991px,
  	xl 1200px,
  	z  2400px;

.make-grid-colomns();
.make-grid-colomns(@i: length(@devices)) when (@i > 0) {
    .make-grid-colomns(@i - 1);
    @device: extract(@devices, @i);
    @name:   extract(@device, 1);
    @size:   extract(@device, 2);
    @media (min-width: @size) {
    	column-@{name}-bla-bla {
      		blee-blu: blo-bla;  
      	}
    }
}

```

But there're too many variations/optimization and zillion of other tips and tricks to use in particular situations (for a concrete use-case it's better to ask at SO or so).

**Comment by WalkerCodeRanger** [comment]
@seven-phases-max Thanks, I now understand what he meant by "keyed dictionaries" I didn't realize you could do that, though I guess it makes sense given that lists can be separated with commas or spaces.

I still think I need the functionality I filed this ticket for.  Normally, I would agree that defining "something with unknown name to represent a value you would refer to later by the same unknown name... It does not make any sense really."  If this were simply my own style sheet I would agree with you.  However, I am trying to write a library something like bootstrap.  The ability to define variable variables means that users of my library could change the number and names of the breakpoints and then have access to variables with those names.  That will be much more straightforward for a user of my library than understanding how to pull things out of lists etc.  So a hypothetical user of my library might do something like:

	@devices:
		tiny   340px,
		small  768px,
		big   1200px;
		
	@media @screen-tiny-only
	{
		.some-class
		{
			color: #123;
		}
	}

From their perspective, there are no unknown names.  They know that the names should be tiny, small, and big.  They directly use a variable with a reasonable name to them.

**Comment by seven-phases-max** [comment]
```less
@devices:
    tiny   340px,
    small  768px,
    big   1200px;

@media @screen-tiny-only ...
```

The main problem of this code is that if you add another screen size ("very-big") to the arrays above it will have no effect until you also explicitly write `@media @screen-very-big-only` for every case you need it, so it spoils the very idea of "dynamic" names (i.e. if you have to know it must be `@screen-very-big-only` then it's no point in having those values as a list).

**Comment by WalkerCodeRanger** [comment]
That isn't a problem because I am not expecting people to add device sizes to an existing project.  Rather I am assuming they will be defined project to project near the beginning of that project.

**Comment by seven-phases-max** [comment]
>That isn't a problem because I am not expecting people to add device sizes to an existing project. 

Then there's no need for lists (that's the main point - if you use dedicated vars you don't need any lists, if you use a list of these values you don't need vars).

**Comment by WalkerCodeRanger** [comment]
I don't think you are understanding what I am doing.  Let's imagine that Alice and Bob both download my library.

**My Library**

	@devices:
		s   544px,
		m   768px,
		l   991px,
		xl 1200px;
		
	// Mixins that dynamically declare @screen-s-min, @screen-m-max for each device.

**Alice's Project**

	@import "library.less"

	@media @screen-xl-only
	{
		// ...
	}

**Bob's Project**

	@import "library.less"

	@devices:
		tiny   340px,
		small  768px,
		big   1200px;

	@media @screen-tiny-only
	{
		// ...
	}

Bob is able to change the device list for his project, then use nat So I do need to declare variable variables.  My library needs to be dynamic and then various users of it need to use explicit variables like `@screen-xl-only` and `@screen-tiny-only`.

**Comment by seven-phases-max** [comment]
>I don't think you are understanding what I am doing.

Well, no, actually I do understand it perfectly. As I meantioned above if you want a fully customizible set of media queries forget about dedicated global vars. Bob's project may look like: 
```less
@import "library.less";

@devices:
    tiny   340px,
    small  768px,
    big   1200px;

.media(tiny, {
    // ...
}
```
(just one of possible syntaxes).

**Comment by matthew-dean** [comment]
I have to concur with @seven-phases-max and @rjgotten. "Defining" variable variables doesn't make sense, because it is, by nature, a referential syntax. And they're suggesting other patterns to achieve the same thing, and I could think of a few more to solve the same problem.

For example, if Bob or Alice need to override the value of a global var, it would be as simple as:
```
@screen-xl-only: 849px;
```
If, however, Bob wanted to change the NAME of that var, it would be as simple as:
```
@screen-hugetastic-only: @screen-xl-only;
```
...and then he could use ```@screen-hugetastic-only``` to his heart's content. So I don't think you need lists or extract loops at all. I don't really use lists, because I find Less loops a kind of anti-pattern, but that's more my personal preference.

**Comment by WalkerCodeRanger** [comment]
First, setting aside my use case for a moment, I think it is just a matter of consistency.  If you document that `@@something` is a variable variable, then I would expect to be able to use it anyplace I would put a variable name.  I can do that, except I can't put it on the left hand side of a declaration.  That feels inconsistent to me.

Second, since there are some questions about the library I am thinking of creating I will try to provide some more detail.  The plan is that it would be a mixin only library.  Initially, it would support responsive grids and media queries.  Over time I would hope it would grow to incorporate lots of other functionality like [Bootstrap](http://getbootstrap.com/) except only as mixins so users weren't forced into one way of organizing styles and constantly surprised by the millions of styles the framework applies.  I'm sure some of these additional mixins would be affected by the media queries.  I think it would be great to add features along the lines of [Compass](http://compass-style.org/) as well though I am not that familiar with it.  I like less more than Sass and think that the lack of a really great mixin library is part of what is pushing people to Sass.  When creating a library, I think end user syntax and clarity is very important to adoption.  It makes sense for the library authors to jump through hoops and experience pain to create a good experience for users.  I am open to alternate syntaxes, but so far haven't seen one I think is as clear as what could be done if I could declare variable variables.  I readily admit I am not a Less guru, so there may be a good one I am not aware of yet.  With all that said, something more concrete will probably help to clarify.

In the discussion below, I will describe the API of the library without going into all the mixins it would take to create that.

My library should support not just re-definable breakpoints, but a variable number of breakpoints since different sites work well with a different number of breakpoints.  When changing the number of breakpoints, it makes sense to rename them.

	@screen-size-names: xs, s, m, l, xl;
	@screen-breakpoints: 544px, 768px, 991px, 1200px;

 I am using two different lists because there is one more screen size name than there are breakpoints (breakpoints divide the screen sizes into ranges).

Based on the screen size names (possibly overridden by a customer), there would be mixins allowing the creation of what bootstrap calls a container.  This defines in much greater detail the behaviour of the page width.   An example usage might be:

	@page-default-margin: 16px;
	
	.my-page
	{
		.page();
		.page-xs-fluid(@page-margin: 8px);
		.page-s-fluid();
		.page-m-fixed();
		.page-l-fixed();
		.page-xl-fixed();
	}
	
This allows the user to control for each screen size whether the the page is fluid or fixed size and what the margins and padding should be. In general, there are two mixins per page size `@size`.  They are `.page-@{size}-fluid(@page-padding: @page-default-padding; @page-margin: @page-default-margin)` and `.page-@{size}-fixed(@page-padding: @page-default-padding; @page-margin: @page-default-margin)`.

When laying out elements on the page, there are a set of mixins that work similar to bootstrap grids (except they use inline-block instead of float).  Rows are created using:

	.grid-row(@gutter: @grid-default-gutter) { /* ... */
	.grid-row-align(@align) { /* ... */ }
	.grid-row-vertical-align(@align) { /* ... */ }

Then, for each screen size `@size` there are mixins:

	.grid-cell-@{size}(@width; @gutter: @grid-default-gutter; @columns: @grid-default-columns) { /* ... */ }
	.grid-cell-@{size}-offset(@width: @gutter: @grid-default-gutter; @columns: @grid-default-columns) { /* ... */ }
	.grid-cell-@{size}-push(@width; @columns: @grid-default-columns) { /* ... */ }
	.grid-cell-@{size}-pull(@width; @columns: @grid-default-columns) { /* ... */ }

This set of mixins allows users to have different numbers of columns and different gutter width for different elements.

Up to this point everything I have described can be done with less today.

Given that the user has used many mixins each named after the screen sizes that they have potentially customized, when they need to do some media query for a style they are applying, it seems natural to them that they should be able to use variables with the same names. i.e. 

	@media @screen-tiny-only
	{
		.some-class
		{
			color: #123;
		}
	}
	
There would be a set of such variables for each screen size `@size`.  There would be `@screen-@{size}-only`, `@screen-@{size}` (that size and up), and `@screen-@{size}-down`. (I know that was not valid syntax but I thought it would be a clear way to express what I meant).  There would be additional media query variables like `@screen-high-res` and other useful variables like `@screen-@{size}-min` and `screen-@{size}-max` (the min and max size for given screen size).

This last functionality is what I would use declaring variable variables for.  In this context, I think it makes a lot of sense and provides the most intuitive syntax to the user.

If something I have said is unclear, I'm happy to answer questions.  However, at this point I think I have pretty much stated my case for this feature.  If you don't agree that is fine.  I leave it up to whatever process the less community has for deciding what features make it into the language.  However, to keep less relevant I would strongly encourage that features like this and [other powerful features needed to create advanced mixin libraries](http://stackoverflow.com/q/32640746/268898) be added.  I don't expect typical users to use features like this.  Just like in C# and Java how many developers don't ever create a generic class, but they are integral to libraries every developer uses.

**Comment by seven-phases-max** [comment]
>```less
@page-default-margin: 16px;

.my-page
{
    .page();
    .page-xs-fluid(@page-margin: 8px);
    .page-s-fluid();
    .page-m-fixed();
    .page-l-fixed();
    .page-xl-fixed();
}
```

In Less I suggest this should be:
```less
@page-default-margin: 16px;

.my-page
{
    .page();
    .page-xs-fluid(xs, fluid, @page-margin: 8px);
    .page-s-fluid(s, fluid);
    .page-m-fixed(m, fixed);
}
```
and so on, and you *don't* need any global variables for this. So for me it yet again seems like it's just the Bootstrap way of implementing grid stuff and mixins is what misdirecting you (BS grid implementation way is a stone age approach *forcing* predefined set of devices).

**Comment by matthew-dean** [comment]
I was also going to suggest keyword guards on mixins as @seven-phases-max. And I would also echo that Bootstrap's way of doing things wasn't what I would call "best practices" for Less code. (I suspect much of the stuff they had to simplify in order to have cross-platform support with Sass.)

And, having tinkered with building a Less library (which maybe someday I'll finally finish), I can tell you that all of your user goals are possible with Less's existing feature set, just not perhaps in the exact method you're aiming at.

And, with Less's (unfortunately undocumented) inline, scoped plugins, Framework authors have unparalleled power to build features that don't cause conflicts with other frameworks nor end-user styles, and don't require any extra steps on the part of the user to "install" or "build", unlike extensions for Sass and PostCSS. (See: #2479) So there's a lot of power possible there.

**Comment by seven-phases-max** [comment]
Yes, sure this does not mean that we don't need other features that could make "structured" code better (in particular #1848, #2433 and so on). But this "interpolate definitions" stuff you're looking for is a wrong move because it's nothing but an attempt to *workaround* the fundamental limitation of predefined set of entities (vars and mixins) by introducing yet another level of indirection thus essentially just staking kludges on top of each other, while the problem should be solved directly via proper language entities with natural arbitrary data support (structures, arrays, mixins args and so on... to stress the weirdness: of`.grid-cell-@{size}-offset`-like mixins are as strange as `round_{value}()` function would be, you will wonder if you see that instead of normal `round(value)`, will you? ;)

**Comment by seven-phases-max** [comment]
To not sound unfounded here's concrete example. Bootstrap `.make-*-column-offset` [mixins](https://github.com/twbs/bootstrap/blob/v3.3.5/less/mixins/grid.less#L52) are defined like this:
```less
.make-sm-column-offset(@columns) {
    @media (min-width: @screen-sm-min) {
         margin-left: percentage((@columns / @grid-columns));
    }
}
```
+ same code repeated for every device in their hardcoded set.

In a modern library this can be implemented as (here I'm using lists and less-plugin-lists since currently it's the easiest and the shortest way (for me at least), but there're other methods to do the same):
```
@devices:
      sm 768px,
      md 992px,
      lg 1200px;


// not showing media-free branch for xs (or whatever first device it may be) to keep code evident
.make-column-offset(@device, @columns) {
    @media (min-width: at(@devices, @device)) {
         margin-left: (@columns / @grid-columns * 100%);
    }
}
```
See? It's *times* less code (actually it will be even less verbose since you'll have shared [`.media`-like mixin](https://github.com/less/less.js/issues/2702#issuecomment-143278183) anyway) and *no* limits on the count of the breakpoints. And Bob can now use it the way you wanted it:
```less
@import "library.less"

@devices:
      tiny   340px,
      small  768px,
      big   1200px;

.bobs-news-column {
    .make-column-offset(small, 2.42);
}
```

**Comment by rjgotten** [comment]
> In a modern library this can be implemented as

Yup. dictionary/map style lookup on a nested list and a generic mixin that takes the map's key as a parameter. That's what I'd suggest as well.

Given unlocking mixins you could also do nifty stuff like having one mixin set the 'media key' and unlocking a set of mixins for further manipulation that curry this parameter so your API consumers don't have to repeat it. E.g.

```less
.grid-define(@media) {
  .grid-gutters(@width) {
    #grid-internal > .grid-gutters(@media, @width);
  }
}

#grid-internal {
  .grid-gutters(@media, @width) {
     ...
   }
}
```
used as:
```less
.my-grid {
  .grid-define(small);
  .grid-gutters(10px);
}
```

**Comment by markentingh** [comment]
I actually have a really good example.

I am creating a CSS framework on top of LESS & eventually SASS. 

My framework uses 600+ LESS variables exposed to the user specifically used for colors. So the user includes my framework.less in their own theme.less file, then they set up the default values for the 600+ variables in their own .defaults() function.

then it gets tricky.

Each section of their web page can use a different theme, so their header might use a dark theme, body might use a light theme, side bar might use a blue theme, so they'll have to set up 600+ variables for each section of their website, and then they call a .render() function to render the CSS for each section of their website using the provided variables. 

This is how I want the workflow for my users to be like:

.defaults(){ ... set up 600+ default color variables here ... }


```
.header{
   .defaults();
   .render();
}
.menu{
    .default();
    @bg:#d0d0d0; //slightly different background color from default theme
    @bg-hover:#ddd; //slightly different hover color from default theme
    .render();
}
```

Now this is where dynamic variable names come to play

If one section in their LESS file uses different colors for a button compared to the default colors, they'll have to change 15 different variable names, just for 1 button type (types include default, apply, cancel, disabled, special, etc). To change all 6 different button types, they'll have to change 90 different variables. Instead, I want them to execute a function that modifies the default variables values for a specific button type before they call the .render() function.

for example:

```
.sidebar{
    .defaults();
    @bg:#980444;
    .button('apply', #a0e066, #a6eeaa, #fff, #fff, ...etc);
    .button('cancel', #a0e066, #a6eeaa, #fff, #fff, ...etc);
    .button('disabled', #a0e066, #a6eeaa, #fff, #fff, ...etc);
    .render();
}
```

this allows them to focus on generating different themes for different sections of their web page without having hundreds of lines of LESS, just to change the colors of their theme.

**Comment by seven-phases-max** [comment]
I'm not convinced. Yet again see my example there. Your example shows nothing but general fail of any frameworks using armies of global variables named like `bla-bla-theme-bla-bla-component-bla-bla-actual-variable-name`. So in this regard any string-based concatenation "dynamic" variables idea becomes nothing but a kludge to overcome the problem of the initially flawed approach.

So yet again see #2702 for namespacing improvement proposal.
Also quite related discussion on #2442.

(Doh! In other languages they considered global variables to be harmful yet in 1970s. I can understand how   that `bla-bla-bla-variable-name` attern became widespread in Less, but it's not an excuse to tolerate the incedintal "namespacing via variable name concatenation" trick anymore and definitely not a good idea to push it further. So set on fire and burn burn burn!)

**Comment by matthew-dean** [comment]
@markentingh I was going to suggest another option based on scoped, matching mixins. But after I wrote up my example, I ran into this bug: #2984.

Like @seven-phases-max said, we will probably close this issue not because variable referencing / overriding doesn't need improvement, but because a better syntax for addressing some of those things is already on the table.

**Comment by markentingh** [comment]
it's alright. Perhaps my whole approach to my framework is wrong to begin with. Keep up the good work, guys.

**Comment by seven-phases-max** [comment]
Renaming the ticket to serve both cases since they almost always come together as the "Attempting to simulate namspaces and/or parameters via string based manipulation of identifiers" anti-pattern.

**Comment by mchaov** [comment]
I think there is a merit here, although not for dynamic variables. See this example:

@color-transformation: lighten;
@some-var: @color-transformation(red, 10%);

**Comment by rjgotten** [comment]
@mchaov 

Storing function names inside variables is highly ambiguous. There is no way to discern a keyword from a function name in the parsing phase and during evaluation, the presence of plugins and plugged in functions makes it highly problematic as well.

Your particular case will eventually be covered by mixins being able to return values and being able to be passed by reference, like detached rulesets. The pairing of those two features gives less the ability to create lambdas.

A possible future syntax for that might be:

```less
.some-mixin(@color-transform) {
  @some-var : @color-transform(red);
}

// ...

.color-transform(@color) : @return {
  @return : lighten(@color, 10%);
}
.some-other-mixin(.color-transform);
```

But it's all still being debated and conceptualized.

**Comment by csergiu** [comment]
If you don't give us the option to create functions like in Sass then at least let us do dynamic variable names, this is so frustrating, I'm trying to write a mixing to calculate my em size based on the font-size in px and I can't return a custom value to be used in multiple places, so for example if I have:

```
.something {
  .emSize(20px);
  .emSize2(20px);
  margin: @emSize auto @emSize2;
}
```

SO I have to create a duplicated mixin just because I can't have a custom returned variable name? At least give us the ability to create functions that automatically return a value, something like this:
```
.something {
  margin: emSize(20px) auto emSize(30px);
}
```

I also don't want to write the long version of the property just because it's against the coding style we're using.

**Comment by seven-phases-max** [comment]
>If you don't give us the option to create functions like in Sass

You have it for [more than 2.5 years by now](https://github.com/seven-phases-max/less-plugin-functions/blob/master/CHANGELOG.md#002).

>SO I have to create a duplicated mixin just because I can't have a custom returned variable name? 

What is the point of asking to support a dirty kludge instead of asking to support a proper solution instead?

**Comment by csergiu** [comment]
> You have it for more than 2.5 years by now.

I was expecting it to be built-in and I didn't know about the plugin, my apologies. I would suggest adding this to the core as it's something that a lot of people are using.

**Comment by seven-phases-max** [comment]
For the particular use-case though, I believe the proper solution would be a an arbitrary-unit-conversion-plugin (auoconverting whatever units( incl. virtual) back and froths depending on its settins), so one would simply write something like: `margin: 20epx auto 30epx` - this is faster, shorter and times more readable.

**Comment by rjgotten** [comment]
Agree with @seven-phases-max 
A custom function with a signature like `em-scalar(value, base)` seems what you need here.
Validate that `value` and `base` are `Dimension` nodes with conversion-compatible units -- e.g. mm and cm; pt and px; etc. -- then convert to the same unit; divide to obtain scalar value; change unit to em; and done.

**Comment by csergiu** [comment]
@rjgotten this is what I ended up with:
```
.function-em-size(@size: 16px, @parentFontSize: 16px) {
  return: unit(@size/@parentFontSize, em);
}
```

**Comment by matthew-dean** [comment]
Closing since there a few solutions suggested.
