### ISSUE TITLE
"ParseError: Unrecognised input" with negative value and "!ie" keyword

### ISSUE THREAD

**Issue by bd808** [less/less.js#2704]
This less:
```
#p-search {
  margin: 2px !ie;
}
```
produces this css:
```
#p-search {
  margin: 2px !ie;
}
```
However this less:
```
#p-search {
  margin: -2px !ie;
}
```
produces this parser error:
```
ParseError: Unrecognised input on line 2, column 16:

1 #p-search {
2   margin: -2px !ie;
3 }
```

The `!ie` keyword here is intentionally broken CSS syntax that MediaWiki (and probably other crusty old codebases) use to mark IE6/7-speciific CSS. First reported in https://github.com/oyejorge/less.php/issues/259

**Comment by seven-phases-max** [comment]
`!ie` is not standard CSS thing so it's expected Less kicks it out. For non-standard CSS tricks&hacks use [escaping](http://lesscss.org/features/#features-overview-feature-escaping). E.g.:
```less
margin: -2px ~"!ie";
```


(In certain cases the compiler may pass certain non-standard values as they are, e.g. `margin: 2px !ie;` will pass w/o a error, but it's nothing but side-effect of certain internal optimizations to speed up parsing).

**Comment by seven-phases-max** [comment]
Closing as expected behaviour.
