### ISSUE TITLE
Small feature tweak - keyword "or"

### ISSUE THREAD

**Issue by matthew-dean** [less/less.js#2705]
When guards were added to Less, CSS did not use an "or" operator (that is: the word ```or```), so the closest parallel was the use of the comma in @media queries.

Now that ```@supports``` has been added, it mostly follows the syntax of ```@media``` but for whatever reason, W3C went with an explicit "or" instead of a comma.

So, to allow some flexibility and maybe make new devs a little happier, I suggest we allow either a comma or the ```or``` keyword in guards.
```
// equal
.mixin (@a) when (@a > 10), (@a < -10) { ... }
.mixin (@a) when (@a > 10) or (@a < -10) { ... }
```
I can't imagine this is a controversial change, especially given the added syntax in CSS. But, might as well put it out there before making a PR.

Oh, and if/when implemented, it would make sense to me to substitute "or" in the documentation for mixin examples, and just note that a comma can be used like ```@media```.

**Comment by nyong2** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

neloog2@naver.com 님께 보내신 메일 <[less.js] Small feature tweak - keyword "or" (#2705)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by seven-phases-max** [comment]
+1

**Comment by nyong2** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

neloog2@naver.com 님께 보내신 메일 <Re: [less.js] Small feature tweak - keyword "or" (#2705)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by SomMeri** [comment]
+1 

Plus, ability to use `or` inside parentheses `when ((cond1) or (cond2)) and (@a < -10) ` would be great too.

**Comment by matthew-dean** [comment]
@SomMeri That seems reasonable too.

**Comment by matthew-dean** [comment]
I'll mark as ready for implementation. If someone figures out a strong objection, we can change it.

**Comment by lukeapage** [comment]
+1

**Comment by SomMeri** [comment]
@matthew-dean Are you working on this or want to work on this?

**Comment by matthew-dean** [comment]
@SomMeri I don't have time for it currently. Should be a small change.
