### ISSUE TITLE
Не срабатывает 'extend' при попытке привязаться к 'parentSelector'

### ISSUE THREAD

**Issue by BeklievParviz** [less/less.js#2706]
> If you don't know Russian language - please, translate it with [Google Translator](https://translate.google.com).

-
В документации есть раздел [**Parent Selectors**](http://lesscss.org/features/#parent-selectors-feature).
Но метод **`extend`** вместе с **`Parent Selector`** - не работает.

**Например, есть такой код ([http://lesscss.org/less-preview](http://lesscss.org/less-preview/#%7B%22less%22%3A%22.base%20%7B%5Cn%20%20%26-class%20%7B%5Cn%20%20%20%20color%3A%20white%3B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn.new-class%20%7B%5Cn%20%20%26%3Aextend(.base-class)%3B%5Cn%7D%22%7D))**
```javascript
.base {
  &-class {
    color: white;
  }
}

.new-class {
  &:extend(.base-class);
}
```

**Результат такой**
```javascript
.base-class {
  color: white;
}
```

--
:exclamation: Почему `new-class` не сливается с `base-class`?

**Comment by seven-phases-max** [comment]
>If you don't know Russian language - please, translate it with Google Translator.

Не, так не выйдет, язык тут только английский, так что бремя использования Google Translator ложится на писателей, а не на читателей.

> Почему new-class не сливается с base-class?

В кратце: оно и не должно. Это будет (когда-нибудь) отдельная фича - #2200.

**Comment by seven-phases-max** [comment]
Merging to #2200.

**Comment by BeklievParviz** [comment]
> Не, так не выйдет, язык тут только английский, так что бремя использования Google Translator ложится на писателей, а не на читателей.

:smiley: я это делаю, чтобы у англо-говорящих появился интерес к русскому языку и России.

--
> В кратце: оно и не должно. Это будет (когда-нибудь) отдельная фича - #2200.

Ооо, вы уже являетесь разработчиком этой библиотеки! Отлично! :smiley:

**Comment by BeklievParviz** [comment]
Кстати, вопрос: когда это приблизительно будет?

**Comment by matthew-dean** [comment]
@BeklievParviz Since everything is done by volunteers, there aren't precise times for when things might be implemented.

**Comment by BeklievParviz** [comment]
@matthew-dean, да-да, я понимаю это.
Я задал этот вопрос исходя из того, что @seven-phases-max участник разработки этого репозитория и подумал, что он и собирается эта задачу реализовывать.

**Comment by matthew-dean** [comment]
Хорошо, без проблем.  :wink:

**Comment by BeklievParviz** [comment]
@matthew-dean, о и вы по-русски заговорили :smile:
