### ISSUE TITLE
Features from other pre-processors

### ISSUE THREAD

**Issue by ldetomi** [less/less.js#2708]
I was looking at [this page](http://csspre.com/compare/) that clearly shows differences between various pre-processors.

I know that certain differences are wanted by design, for example lack of default variables in LESS, due to lazy loading feature, but I would like to know if other missing features are expected in near future or definitely rejected. 

I personally think that these features could be very helpful:
* Lookup
* Selectors-nested
* Root parent reference

Indipendently by actual strategies, I suggest to have a public roadmap that clearly mantain "tuned" users about future of LESS, desired features, etc.

What do you think about it?

**Comment by SomMeri** [comment]
What does "Nest a set of selectors with parent reference below another selector" means?

**Comment by matthew-dean** [comment]
That's kind of a hilariously Sass-centric perspective of pre-processors.

**Comment by seven-phases-max** [comment]
>That's kind of a hilariously Sass-centric perspective of pre-processors.

Yep. But since the question is not about this table, but about particular features, here're we go:
* Lookup - #2433
* Selectors-nested - #1421 (assuming support for comma, `&` and other "high level" selector stuff).
* Root parent reference - #1075

**Comment by ldetomi** [comment]
Thanks seven-phases-max, and for last part of my question? I suggest to have a public roadmap to have an idea of what features we could expect for near future, and approved features requests. What do you think about it?

**Comment by seven-phases-max** [comment]
As for roadmap, roughly: I don't think any fair roadmap is possible currently, at least when it comes to timeline expectations.

**Comment by matthew-dean** [comment]
I've started a roadmap, not with timelines but just trying to list a summary of ready-to-implement features, but man, it's hard to get the extra time for organizational stuff like that. Keeping up with Github issues is already a decent chunk of work.

**Comment by matthew-dean** [comment]
It's currently private, but I could add anyone (outside of the less org who doesn't already have access) who wants to contribute. Not much there so far.

**Comment by matthew-dean** [comment]
Less could seriously use more people devoted to documentation, issue summaries for roadmap, and product evangelism. Along with, of course, JS coders to implement said features / bug fixes.

**Comment by SomMeri** [comment]
@matthew-dean Do you have some ideas about how to do product evangelism?

**Comment by Announcement** [comment]
transparent mixins please

**Comment by seven-phases-max** [comment]
Closing as neither issue report nor a feature request. For the roadmap and other meta discussion they have [roadmap](https://github.com/less/roadmap) and [meta](https://github.com/less/less-meta) ;)

**Comment by seven-phases-max** [comment]
Closing as neither issue report nor a feature request. For the roadmap and other meta discussion they have [roadmap](https://github.com/less/roadmap) and [meta](https://github.com/less/less-meta) ;)

**Comment by seven-phases-max** [comment]
Closing as neither issue report nor a feature request. For the roadmap and other meta discussion they have [roadmap](https://github.com/less/roadmap) and [meta](https://github.com/less/less-meta) ;)

**Comment by Announcement** [comment]
I thought this was a feature request board?

**Comment by matthew-dean** [comment]
I see someone made the roadmap repo public. Okay, then.

@seven-phases-max Roadmap is not for feature requests, nor is meta, really. But yes, this is probably smart to close since there is no one specific feature request.

@SomMeri At CSS / web confererences, it seems like there's always someone giving a presentation about Sass, but never about Less. Not sure why that is, but that would be a place to start. Plus, there is a Sass conference but no Less conference.

**Comment by seven-phases-max** [comment]
@Announcement 

Yes. Though it's not a good idea to throw multiple requests into the same thread. Each feature needs a separate discussion, separate decision and thus a separate ticket. I gave the link to the corresponding opened threads for the mentioned features [above](https://github.com/less/less.js/issues/2708#issuecomment-146693319).

I.e. for each new feature please create a dedicated topic (do not hesitate to read https://github.com/less/less.js/blob/master/CONTRIBUTING.md#feature-requests first).
