### ISSUE TITLE
Dynamic import

### ISSUE THREAD

**Issue by furyscript** [less/less.js#2710]
How can I import dynamic theme form angularJs/Javascirpt/jQuery by changing variable in html for import?? Is possible??

**Comment by seven-phases-max** [comment]
Sorry, the issue tracker is not a support forum, it's for Less language/compiler bug/issue reports and feature requests only. For a generic "How-To" Less related questions use other resources (like [SO](http://stackoverflow.com/questions/tagged/less) for example).

We usually still answer simple Less-usage questions here, but your one is waaay too broad (so if you'll be asking the same at SO - try to be more specific and provide more details about concrete use-cases you have in mind).

**Comment by seven-phases-max** [comment]
Closing as not an issue.
