### ISSUE TITLE
JavaScript Compiler Issue (maybe? perhaps I'm just inept)

### ISSUE THREAD

**Issue by Blake-Henderson-SB** [less/less.js#2712]
Compiling the following file http://jsfiddle.net/859mh9ga/ with the less.js seems to work just fine in browser if I get rid of the variable and replace it with static values. However, when I use the variables in their current form it throws the following error;

message: "variable @lightGreen is undefined"

I'm pretty confused at the moment.

**Comment by seven-phases-max** [comment]
Hmm, could you provide more details on how exactly you try to compile it when you got the error? The code is valid (and it's just too basic to not work with either complier version, so it's must be really something weird to happen aside of the compiler).

**Comment by Blake-Henderson-SB** [comment]
It ends up rendering as 

<link href="/resource/1444852869000/obfuscated__temp2" rel="stylesheet/less" type="text/css">
<script src="/resource/1444086228000/obfuscated__less" type="text/javascript"></script>

It's really that simple. The "temp2" file alluded to above is the exact same file that I included in the fiddle. 

Admittedly, and I just noticed this now, your instructions tell people to place this in the head however I'm trying to compile body of the HTML as I don't have access to the head on the platform I'm developing on top of (SFDC). However, it does seem to work to the exception of variables. 

Here's the full error information,
Uncaught (in promise):
(anonymous function)	@	less:719
(anonymous function)	@	less:616
(anonymous function)	@	less:4966
(anonymous function)	@	less:2624
finish	@	less:3189
ImportVisitor._onSequencerEmpty	@	less:9150
(anonymous function)	@	3_3_3.Finalorg.ajax4jsf.javascript.PrototypeScript:17
ImportSequencer.tryRun	@	less:9109
ImportVisitor.run	@	less:9144
Parser.parse	@	less:3195
parse	@	less:2622
render	@	less:4958
loadInitialFileCallback	@	less:613
(anonymous function)	@	less:632
doXHRCallback	@	less:475
handleResponse	@	less:417
doXHR	@	less:437
loadFile	@	less:470
loadStyleSheet	@	less:627
loadStyleSheets	@	less:638
(anonymous function)	@	less:716
less.refresh	@	less:712
2../add-default-options	@	less:85
s	@	less:13
e	@	less:13
(anonymous function)	@	less:13
(anonymous function)	@	less:13
(anonymous function)	@	less:13

**Comment by seven-phases-max** [comment]
I'm afraid you can't use `<link>` element in the `body` - it's just invalid HTML (which just can cause unexpected behaviour in either DOM-manipulating modules).
You can trick it with inline style and import, [demo](http://codepen.io/seven-phases-max/pen/BowdZQ?editors=100).

Also notice that client-side compilation is [not recommended](http://lesscss.org/#client-side-usage) anyway (except some special cases), so consider server-side compilation (the term also includes compiling it at the development machine - i.e. just where and when you edit the code) instead.

**Comment by rjgotten** [comment]
> I'm afraid you can't use `<link>` element in the `body` - it's just invalid HTML

You *can* use it in the body. It's supported by all browsers. The standard says it's not allowed, but contacts from the browser vendors are pushing to have that changed to assist with isolating above-the-fold first-render times. (The idea is that a link element pointing to a stylesheet would only render-block the HTML elements *after* it.)

**Comment by seven-phases-max** [comment]
> (Infact, link elements in the body already work that way in Internet Explorer.)

Does this mean that if you put a CSS link into the body neither `body` nor `html` tags there will have any effect? (oh, that sweet compatible MS-stuff :)).

**Comment by Blake-Henderson-SB** [comment]
Alright, thank you both very much for taking the time to respond! I'm thinking Max is most likely on to something in regards to one of several javaScript libraries potentially wreaking havoc. There's unfortunately no way to remove that javaScript from running on top of the SFDC ergo the idea located at https://success.salesforce.com/ideaView?id=08730000000l2Y8AAI . I think this is just going to be a known issue for people developing Visual Force pages on top of SFDC. It's not a big deal, I can just call/create a service to facilitate this anyways. Thanks again for your time.

**Comment by seven-phases-max** [comment]
Closing as not a Less issue.
