### ISSUE TITLE
custom @import

### ISSUE THREAD

**Issue by tcurdt** [less/less.js#2717]
I am using the API to render a less file like this:

    return Less.render(source, {}).then(function(result) {
      ...
    });

I found the following file manager implementations but no docs or indication on how/where to set them.

  https://github.com/less/less.js/blob/master/lib/less-node/file-manager.js
  https://github.com/less/less.js/blob/master/lib/less-node/url-file-manager.js

A pointer would be great.

**Comment by seven-phases-max** [comment]
>but no docs or indication on how/where to set them.

You don't need to set them (they already are default file-managers).

For custom file-manager example see https://github.com/less/less-plugin-npm-import.

**Comment by tcurdt** [comment]
Well, in my situation I need a custom manager -  that's why I am asking :)

But that pointer is great. Seems like that one is adding the file manager through the plugin interface.

https://github.com/less/less-plugin-npm-import/blob/master/lib/index.js#L13

**Comment by seven-phases-max** [comment]
There's also a minimal example in tests: https://github.com/less/less.js/tree/master/test/plugins/filemanager (though it's probably too minimal).

**Comment by tcurdt** [comment]
That helped a lot! Thanks, @seven-phases-max.

What I am still trying to figure out is the directory argument to the `loadFile` call. I would have expected the directory to be the directory the import is coming from - but that doesn't seem to be the case.
As the filename is not an absolute path it's a bit tricky to figure out the actual path for the import.

**Comment by tcurdt** [comment]
For reference: The following code works quite well - except for the directory issue.

    var resolver = {
      install: function(less, pluginManager) {
        var fm = new Less.FileManager();
        fm.loadFile = function(filename, dir, options, env, cb) {
          return new Promise(function(resolve, reject){

            console.log('DIR', Path.resolve(dir));

            // FIXME adding prefix while I shouldn't have to
            resolve({ contents: 'body', filename: 'design/styles/' + filename })

            // or
            // reject("could not find " + filename);

          });
        };
        fm.supportsSync = false;
        pluginManager.addFileManager(fm);
      }

The file importing is in the `design/styles/` directory as well as the file being imported. 

    design/
      styles/
        importing.less
        imported.less

The current dir of the process is `/`, the `dir` parameter of the function is just empty. I would have expected it to be `design/styles/`. If it's the difference between the two files the empty argument would make sense (as they are in the same dir) but then I still would need e.g. the directory of the importing file to resolve it to an absolute path.

Or what am I missing?

**Comment by rjgotten** [comment]
> The current dir of the process is `/`, the `dir` parameter of the function is just empty. I would have expected it to be `design/styles/`.

Enable the relative urls option. It defaults to false.

**Comment by seven-phases-max** [comment]
Also note that regardless of `relativeUrls` value, the `filename` option you pass to `less.render` should be a complete path of the interest, not just the file name alone (*if* you need the path to be considered at all, otherwise the compiler just *can't* know there's any `design/styles/` out there). In other words if you're doing something similar to `lessc design/styles/filename.less`, the `filename` is `design/styles/filename.less` (in many cases it's even better to provide an absolute path, since there's no guarantee that during compilation the `cwd` remains the same as it's at `less.render` step, though usually it is. E.g. #2342).

**Comment by seven-phases-max** [comment]
Closing as not an issue.

**Comment by tcurdt** [comment]
@seven-phases-max right now this is how I call `less.render`

    Less.render("less code", { plugins: [ resolver ] })

Should I pass the (absolute) `filename` in the options there as well?

**Comment by seven-phases-max** [comment]
>Should I pass the (absolute) filename in the options there as well?

Yes.
