### ISSUE TITLE
Parse error w/ comments?

### ISSUE THREAD

**Issue by zenspider** [less/less.js#2718]
I'm mixing documents via ERB before I pass it off to less and I've hit a syntax error after updating normalize.css:

```
a b[c="d"], /* 1 */
e[f="g"] {
}
```

Not sure if this is a real syntax error or a fault of my mixing.

**Comment by zenspider** [comment]
I should have added: if you remove the comment, it parses fine.

**Comment by seven-phases-max** [comment]
What Less version and what is the error message? This snippet on its own compiles just fine with current Less versions. 

>Not sure if this is a real syntax error or a fault of my mixing.

I'm afraid it's impossible to suggest anything useful until we know the exact code that causes the error.

**Comment by zenspider** [comment]
Entirely my fault. Version skew. Sorry. Closing.
