### ISSUE TITLE
syntax error on @media w/ specifier

### ISSUE THREAD

**Issue by zenspider** [less/less.js#2719]
Found this when upgrading skeleton on my site:

```
@media (min-width: 400px) {

}
```

If you remove the parenthetical, it compiles.

**Comment by seven-phases-max** [comment]
Same story as in #2718. The snippet is valid Less and compiles just fine with any Less version (so whatever error you get the problem is somewhere else).

**Comment by zenspider** [comment]
Entirely my fault. Version skew. Sorry. Closing.
