### ISSUE TITLE
Less files with multiline block comments break source maps when using minify-css

### ISSUE THREAD

**Issue by rros** [less/less.js#2725]
I reported this issue in the gulp-less repository, but found the issue is also present in less. (https://github.com/plus3network/gulp-less/issues/204)

Less generates invalid source maps when minifying a less file with multiline block comments. See the following example.

Test.less
```less
/*
This is a multiline block comment
*/
body {
        background: red;
}
```

`lessc --clean-css --source-map-less-inline --source-map=test.min.css.map --verbose test.less > test.min.css`

Output:
`{"version":3,"sources":["$stdin"],"names":[],"mappings":"AACA,KACE,WAAY","sourcesContent":[null]}`

Expected output:
`{"version":3,"sources":["test.less"],"names":[],"mappings":"AACA,KACQ,WAAA","sourcesContent":["/*\nThis is a multiline block comment\n*/\nbody {\n        background: red;\n}\n"]}`

Because I used the clean-css plugin, it could also be a problem in clean-css but I'm not certain.

**Comment by HarryBurns** [comment]
+1

**Comment by rros** [comment]
I finally found the issue is with clean-css: https://github.com/jakubpawlowicz/clean-css/issues/593

Basically the comments processor of clean-css assumes the newlines in the input sourcemap (the one generated by less) will match the newlines of the OS it's running on. Clean-css will corrupt the sourcemap when it assumes the incorrect newlines.

@HarryBurns: I will close this issue and try to get it solved in clean-css.
