### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

### ISSUE THREAD

**Issue by gsatheeshkumar** [less/less.js#2726]
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

**Comment by gsatheeshkumar** [comment]
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.   How do clear is warning ? please

**Comment by seven-phases-max** [comment]
See #2384.

**Comment by seven-phases-max** [comment]
Merging to #2384.
