### ISSUE TITLE
image-size functions are not supported in less-browser

### ISSUE THREAD

**Issue by niom** [less/less.js#2737]
We faced an interesting functionality when using image-size function in our project.
We compile less files with node on release but use browser version of less while development.

Apparently browser version of less does not support image-size functions since they are not implemented and will fail to undefined error.

the quick fix for this would be to give user a better error message. e.g. Functionality is not supported.

**Comment by niom** [comment]
I created a PR #2738 that would resolve the failing to undefined error with a proper exception.

**Comment by seven-phases-max** [comment]
Personally I wonder if it should have that kind of error-handling.  I.e. every environment build should know of every thing implemented in other environment build and provide a sweety message. It seems like a tiny stuff right now, but may become too bloating further. (After all, limited support [is documented](http://lesscss.org/functions/#misc-functions-image-size) in the docs. More over, in a perfect world I would actually vote for moving these `image` functions  into a plugin).

**Comment by niom** [comment]
True that this kind of sweet error messages can bloat up the code but in other hand will save a lot of time from debugging why some functionality fails to undefined exceptions. 

I agree, that the image functions would be better in own plugin.
