### ISSUE TITLE
Newest *npm* appears to be downgrading a dep in this project

### ISSUE THREAD

**Issue by Martii** [less/less.js#2739]
The current dep of [`33fa727`/package.json#L46](https://github.com/less/less.js/blob/33fa72767e7474f3aedbbff83d8343217c08f58a/package.json#L46) appears to be being downgraded automatically with *npm*@3.5.0

I've reported this at npm/npm#10612 

Will this damage some functionality of this project? It seems to me that going from 0.4.2 **down** to 0.2.0 is going to cause some headaches. Other projects may have this affect them as well. 

Sites, such as ours and our thousands of users, depend on a stable dependency tree and I'd much rather not see the packaged eco-system polluted with versions that are no longer supported or could be seriously bugged/security risks... all of this seems to be without this projects consent.

Thanks for your patience on this.

---

*(Clipped requote specific to this package)*
``` sh-session
npm WARN In less@2.4.0 replacing bundled version of source-map with source-map@0.2.0
```

**Comment by Martii** [comment]
Tracked back from https://github.com/emberfeather/less.js-middleware project... which is a little confusing since [it's asking for *less*@2.5.0](/emberfeather/less.js-middleware/blob/da35e9596e1b679342d643e4b9057bbb72af5907/package.json#L12) and *npm* is installing *less*@2.4.0 ?? 

Think I may be missing something here. Any assistance would be appreciated.

**Comment by seven-phases-max** [comment]
>which is a little confusing since it's asking for less@2.5.0 and npm is installing less@2.4.0 ??

I'm not quite sure I understand the problem, but tehe latest version is 2.5.3 and `npm` will install the latest one *unless* something in your project declares `2.4.0` dependency explicitly.

**Comment by Martii** [comment]
Thanks for the reply.

The middleware package we utilize is asking for 2.5.0 and *npm* is dowgrading it's asking of the higher version to 2.4.0 **and** it is downgrading it's dependency of *source-map*... regardless of the state of the current release of this project *(less)* that middleware is tested on 2.5.0 and expects the [tilde](https://docs.npmjs.com/misc/semver#tilde-ranges-1-2-3-1-2-1) to be honored... seems to me that a **downgrade** to 2.4.0 of *less* is going to break something with some other dependency e.g. *npm* is currently seems to be messing up on the dependency tree semver implementation. 

We've been forced to downgrade to a more stable version of *npm* even though *npm*3.5.0 is "considered stable". I understand this is a dep that the middleware should update at some point but the downgrade of *less* is completely unexpected and will most likely reintroduce all the bugs that *less* has already fixed all the way up *(or down depending on perspective)* the dependency tree.

What is to prevent a request for *less*@2.5.3 from being bumped down to *less*@2.4.0, or earlier with *npm*@3.5.0? *(I understand the usage of caret, tilde, [etc.](https://docs.npmjs.com/misc/semver) in [package.json](https://docs.npmjs.com/files/package.json) which is why our top-level project uses fixed versions)*

**Comment by Martii** [comment]
A simpler question ... shouldn't caret and tilde always go **up** in single [semver](http://semver.org/) *(e.g. not a range)* or is it acceptable to reintroduce bugs into every project throughout the dependency tree by downgrading the minor when it's **not** asked for?

I've [been using semver for over a year now](/OpenUserJs/OpenUserJS.org/search?q=some+dep+updates&type=Issues&utf8=%E2%9C%93) and something has changed in *npm*'s latest implementation that seems to affect negatively just about every project that uses it.

**Comment by Martii** [comment]
There's some followup at https://github.com/npm/npm/issues/10612#issuecomment-160844498 along with the post closing proof of *less* being installed as a lower/older version of this project by *npm*... this seeming bug appears to be exclusive to *npm*@3.x and isn't currently present in *npm*@2.x that is distributed with *node* 4.x LTS.

I hope this makes more sense for everyone here... and someone here might want address it too for the *node* community in general to establish what to do next.

**Comment by seven-phases-max** [comment]
I see. Well, I'm not sure how it's actually a Less problem in any way. By either means it's `npm` or `less-middleware`. I don't think we could target the issue in *this* repository.

**Comment by Martii** [comment]
It's definitely *npm* but is also a FYI that *npm* seems a bit broken, for quite a while, and you'll be getting issues that don't relate near this projects releases due to this and this will probably include the latest of 2.5.3 ... so it affects your project directly. :)

Closing as per consideration label.
