### ISSUE TITLE
Is it possible to lint more than 1 file?

### ISSUE THREAD

**Issue by ronkorving** [less/less.js#2740]
Right now, I find myself having to resort to something like this:

```sh
find www -name '*.less' -print0 | xargs -n1 -0 lessc --lint
```

It would be *much* nicer if I could simply write:

```sh
lessc --lint www
```

or

```sh
lessc --lint www/**.less
```

Is there a way already, or could this be added?

**Comment by seven-phases-max** [comment]
See #1631.

**Comment by seven-phases-max** [comment]
Closing as duplicate of #1631.
