### ISSUE TITLE
How to insert HSL, RGB or HSV to RGBA, HSLA construction?

### ISSUE THREAD

**Issue by acterhd** [less/less.js#2745]
Hello. How to insert rgb, hsl, hsv, etc. to rgba, hsla constructions?!
```
@color: rgb(0, 255, 0);
... 
color: rgba(@color, 0.1); //OH SH~
```

Also, I want cross pasting. For example, `hsla(rgb(...), ...)` or `rgba(hsl(...), ...)`. And conversion between. `rgba(hsla(...))`, `rgb(hsl(...))`, `hsl(rgb(...))`.

**Comment by seven-phases-max** [comment]
>`color: rgba(@color, 0.1);`

`rgba` is a CSS function that expects four arguments. What you need is the [`fade`](http://lesscss.org/functions/#color-operations-fade) function.
As for conversions between rgba/hsla/hex etc. formats - this depends on why exactly you need that (note a color thing is remains the same color thing no matter what format you specified it in. In particular the compiler always uses RGBA format to output semi-transparent colors and Hex format for non-transparent ones).

---
Also please note the issue tracker is not a support forum or so. For "How-To"/"How-Do-I" questions consider using [SO](http://stackoverflow.com/questions/tagged/less).

**Comment by seven-phases-max** [comment]
Closing as not an issue.
