### ISSUE TITLE
Typesafety: assert function to fail at compile time

### ISSUE THREAD

**Issue by slorber** [less/less.js#2747]
Hi,

What I'd like to do is something like:

```
.background-clip(@value) when (@value = border-box),
                              (@value = padding-box),
                              (@value = content-box),
                              (@value = inherit)
{
    -webkit-background-clip: @value;
       -moz-background-clip: @value;
            background-clip: @value;
}
```

When the `background-clip` is called with a wrong value, instead of ignoring that value, it could be nice to make the compilation fail.

Is it currently possible? or could it be in the future?

It would be really great to have a syntax to tell that the guard is a "compilation guard" and not simply "ignore-guard"

One simple solution i can think of is using a function that may fail. Something like:

``` less
.background-clip(@value) when (oneOf(@value,"border-box","padding-box","content-box","inherit")
{
            background-clip: @value;
}
```

The idea is that the function acts like an "assertion" that may make the compilation fail.

As far as I see there are already such functions that can make the compilation fail.

It would be nice to have more compilation safety with a oneOf function.

There are probably other useful options, like ensuring a list contains only know values.

For example when dealing with interaction modes, which can generally be mouse and/or touch. We have to handle special cases because the :hover is not possible on devices with only touch support.

``` less
.myMixin(@interactionMode) when (listOf(@interactionMode,"touch","mouse")
{

   div.someButton {
        & when (contains(@interactionMode,"touch")) {
            // ...
        }
        & when (contains(@interactionMode,"mouse"))  {
           &:hover {
                       // ...
           }
        }
        & when (contains(@interactionMode,"mouse","touch")) {
            // ...
        }
   }
}
```

The `contains()` function would be useful there :)

Maybe we could also pass as mixin arguments complex json objects and assert in functions that they have a certain "shape"

I don't know which functions would be useful exactly but I think it would be a nice progress for less to have more "typesafety".

**Comment by slorber** [comment]
Notice I tried to use this hack to declare js functions in less without success (inside a guard)

https://github.com/less/less.js/issues/637

**Comment by slorber** [comment]
Another idea could be this kind of syntax:


.mixin (@a) when (lightness(@a) >= 50%) {
  background-color: black;
}
.mixin (@a) when (lightness(@a) < 50%) {
  background-color: white;
}
.mixin (@a) {
  fail("This mixin can't be called with this value",@arguments);
}

**Comment by slorber** [comment]
Ok so I think @seven-phases-max has an answer for everything :)

As far as I understand I can provide custom functions by using a less plugin.

Here is a List plugin from which I can inspire myself to build some kind of "less-assertions-plugin"

**Comment by SomMeri** [comment]
This might be related to #1459 . It is not exactly the same thing, but has similar goal.

**Comment by seven-phases-max** [comment]
I think it's easier to introduce some "assert" function and use it like:
```less
@unused: assert(@condition, "doh!");
```
instead of inventing some special syntax. 

Taking the first use-case into account `less-plugin-lists` misses some `index-of` function or so, to be used together with such `assert` (currently functions there follow "Don't raise a error if a function fails" convention). But sure one easily can make some to fit either.
(Still I would not mind a built-in `assert`).

**Comment by slorber** [comment]
Yes a built-in assert would permit to reuse existing functions that do not throw!

Could we do something like this?

```less
.mixin (@list) when (assert( lengt(@list) < 3 )) {
  ...
}
```

**Comment by slorber** [comment]
@seven-phases-max I've done some tests and it seems that less can support quite complex expressions in a when clause, so definitively some simple assertion functions would be a huge win!

However I'm still interested in a case to make less compilation simply fail anyway.

See for example how ScottS here had the idea to call a mixin that does not really exist to make less fail (option 3): http://stackoverflow.com/questions/20959298/enums-documentation-with-less-mixins/21052115

Example where this can be needed is when there is a simple case for which you can to assert.
For example: 


```less
.complexMixin(@list,@list2) when ( sin(length(@list)) < cos(length(@list2)) ) {
  // not fail
}
.complexMixin(@list,@list2) when ( sin(length(@list)) > cos(length(@list2)) ) {
  // not fail
}
.complexMixin(@list,@list2) {
  fail("the cos and sin can't be equal!");
}
```

I mean I want to be able to express switch / pattern matching expressions where the default unhandled case should never happen (pattern often used to fail fast):

```javascript
switch (value) {
  case "x" ...
  case "y": ...
  default: throw new Error("fail!");
}
```

**Comment by slorber** [comment]
So I tried to make a plugin but not really successfully :'( not sure to understand how to make it work and even how to make unit tests. It seems the test does not find my new function:

https://github.com/slorber/less-plugin-assert/

**Comment by seven-phases-max** [comment]
Well, your mistake there is that you assume that Less `true` is equal to JS `true` - it's not actually.
All Less values (colors, numbers, strings of variuos types, and logical values in the end) are represented with dedicated JS objects (`Color`, `Dimension`, etc. you'll find in [`less.tree`](https://github.com/less/less.js/tree/master/lib/less/tree)). Thus in your `assert` impl. you would need to compare the condition value to `less.tree.True` constant raither than using `!condition`).

---
*However*

**Comment by slorber** [comment]
ok thanks for the explanation :) 

that seems not very better than the "mixin does not exist" than ScottS proposed on stackoverflow unfurtunatly

**Comment by seven-phases-max** [comment]
>that seems not very better than the "mixin does not exist"`

That was [your code](https://github.com/less/less.js/issues/2747#issuecomment-161929697) not mine :)

For your initial example me would start with something like:
```less
.background-clip(@value) when 
    (at(l(border-box, padding-box, content-box, inherit)), @value) = ~''") {
        // ...
}
```
then it's not a problem to derive a function to remove redudant `l()`, `= ~''` and/or generate a error in place. 
I.e. it's just a matter of deciding what the function of interest should actually do, i.e. is it `is-value-in-list` returning `true` or `false`, or `ensure-value-in-list` generating a error if not, etc. and so on).

**Comment by seven-phases-max** [comment]
Btw., thinking if the initial example yet more I recalled one more method (w/o bothering with custom functions) to generate a bit more readable error message with a bit less verbose code (if compared to the methods suggested in the SO Q above): [[1]](http://less2css.org/#%7B%22less%22%3A%22.background-clip(%40value)%20%7B%5Cn%20%20.-(%40value)%3B%5Cn%20%20.-(border-box)%20%20%7B%7D%5Cn%20%20.-(padding-box)%20%7B%7D%5Cn%20%20.-(content-box)%20%7B%7D%5Cn%20%20.-(inherit)%20%20%20%20%20%7B%7D%5Cn%20%20%2F%2F%20%5Cn%20%20ok%3A%20%40value%3B%5Cn%7D%5Cn%5Cn%2F%2F%20usage%3A%5Cn%5Cnfoo%20%7B%5Cn%20%20.background-clip(content-box)%3B%20%2F%2F%20ok%5Cn%7D%5Cn%5Cnfoo%20%7B%5Cn%20%20.background-clip(shooba-dooba)%3B%20%2F%2F%20error%5Cn%7D%5Cn%22%7D).

**Comment by rjgotten** [comment]
> one more method

Using the pattern matching mechanic on an inner mixin; clever!

**Comment by rjgotten** [comment]
@seven-phases-max 
I've been thinking about mixin assertions some more. Maybe the language should offer a parametrized version of the `default()` guard, that can be used to tell the compiler to throw when it is activated, rather than eval the mixin body.

E.g.
```less
.complexMixin(@list, @list2) when (sin(length(@list)) < cos(length(@list2))) {
  // ok
}
.complexMixin(@list, @list2) when (sin(length(@list)) > cos(length(@list2))) {
  // ok
}
.complexMixin(@list, @list2) when (default("the cos and sin can't be equal!")) {
  // will never be hit, because the guard will throw with the specified error.
}
```

If you attach this logic to the `default()` guard, you have the advantage of having access to the internals for the mixin name, the parameter values with which the mixin was called and the _callsite_.

You can generate really nice error messages with line numbers set to the correct location that way.

**Comment by matthew-dean** [comment]
@rjgotten Smart. I like it. It would allow library authors to enforce type safety and numerical ranges for mixins.

That said... The error where it's being generated isn't really the intended error location. That is, if you want mixin A to fail based on some criteria, you aren't defining it at mixin A. You're defining it at mixin B, which only happens to be encountered because the lack of match at mixin A. But mixin A and B have no real relationship other than they match a mixin call. (So they're both related to call X, but not directly to each other.)

So it seems to me what a developer REALLY wants is to have a failure at the location of a mixin, but that is illogical based on the concept of mixins. A non-match of a single mixin is not a "failure" at that point in the evaluation.

So it seems to me, echoing some of @seven-phases-max's statements, only functions serve this purpose. A function has a single entity (per scope) so they can establish a pass/fail on parameters. Mixins can't. They can only establish a pass, and not an exception.

Some plugin features in development (awaiting review) should make this a lot easier (via JS), and it's not out of the question that we could establish a native Less-based function syntax that allows these assertions down the road.

**Comment by rjgotten** [comment]
> That said... The error where it's being generated isn't really the intended error location. That is, if you want mixin A to fail based on some criteria, you aren't defining it at mixin A. You're defining it at mixin B, which only happens to be encountered because the lack of match at mixin A.

Ideally, you'll want argument errors to pop at the _call-site_, i.e. , the location where the mixin was being called.

```less
// This is where we accept (one possible set of) valid parameters
.foo(@num) when (isnumber(@num) and (@num >= 0) {}

// This is where we set-up the error to throw when no signature
// of the `.foo` mixin can be matched.
.foo(@ when (default("Not a positive number")) {}

// But this mixin **call** is what will throw the actual error, complete
// with line number, filename, etc.
.foo(-10);
```

This means you attach the throw logic to `MixinCall` nodes, which are _exactly_ where the `default()` handling logic currently also resides...

**Comment by matthew-dean** [comment]
> Ideally, you'll want argument errors to pop at the call-site

Or both? In a call stack you'd have both. I wonder if it might be possible to generate just a light stack with the normal line / column of the error (from the call), and what mixin is returning that error?

But yes, there is some logic to what you say, and you're right that that's where errors are typically generated, so maybe walking stuff back, maybe your proposal works after all.

Btw, I assume you meant to write:
```
.foo() when (default("Not a positive number")) {}
```
?

**Comment by rjgotten** [comment]
@matthew-dean 

No. I meant for the argument to be there.
Less already has a different built-in error that is thrown when you call a mixin with an incompatible number of arguments. ;-)

**Comment by matthew-dean** [comment]
@rjgotten Oh right right that makes sense. Duh.

@seven-phases-max Your thoughts?

**Comment by seven-phases-max** [comment]
>`default("Not a positive number")`

I like the semantics, nice spot!. Though due to [`default` implementation](https://github.com/less/less.js/blob/master/lib/less/tree/mixin-call.js#L76) it may be quite tricky to code, counting the edge cases like `not default("Boo!") // ?!`.
