### ISSUE TITLE
False parse error on parametric mixin...

### ISSUE THREAD

**Issue by bverley** [less/less.js#2751]
Code : 
--------------------------------------
@img-diplome-uri: 'bootstrap/3.3.5/tile.png'; //NB : same result if value is '' or null

.mx-first-paragraph-diplome (@img) when (image-width(@img) < 5px) {
  width: 100%
}
.first-paragraph {
  mx-first-paragraph-diplome ('bootstrap/3.3.5/tile.png')
}
Result in :
--------------------------------------
ParseError: Unrecognised input. Possibly missing opening '{' in /path/to/my/file.less on line 8, column 1:
7   mx-first-paragraph-diplome ('bootstrap/3.3.5/tile.png')
8 }

Any clue?

**Comment by bverley** [comment]
I stipped out the variable from the call without success...

**Comment by SomMeri** [comment]
You missed dot in front of the `mx-first-paragraph-diplome` [on the line 8 - preview](http://lesscss.org/less-preview/#%7B%22less%22%3A%22%40img-diplome-uri%3A%20'bootstrap%2F3.3.5%2Ftile.png'%3B%20%2F%2FNB%20%3A%20same%20result%20if%20value%20is%20''%20or%20null%5Cn%5Cn.mx-first-paragraph-diplome%20(%40img)%20when%20(image-width(%40img)%20%3C%205px)%20%7B%5Cnwidth%3A%20100%25%5Cn%7D%5Cn.first-paragraph%20%7B%5Cn.mx-first-paragraph-diplome%20('bootstrap%2F3.3.5%2Ftile.png')%5Cn%7D%22%7D).

Please use [backtics for format your code](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks), it will be easier to read and github wont sent email to whoever goes by img username. I added backticks to your comment.

**Comment by bverley** [comment]
So it was a real parse error! I was very very blind to that one. 
Many thanks for your enlightening response. 
I have to apologise for mistakenly saying that this was a false parse error. Sorry for this and thank you again!
