### ISSUE TITLE
Method for Resolving the Values of Variables

### ISSUE THREAD

**Issue by mikejr83** [less/less.js#2755]
I've built a site theming engine around using LESS to compile custom stylesheets. It works by allowing a user to edit various variables and then compiling the LESS with those edited values. Works perfectly! 

However, I have some need to resolve the values of variables inside of JavaScript so that they can be consumed by third party controls. Say I have the following defined in variables.less:

    @base-color: #428bca;
    @brand-primary: darken(@base-color, 6.5%);
    @link-color: @brand-primary;
    @link-hover-color: darken(@link-color, 15%);

Editing the "@base-color" will filter nicely to the other variables when the CSS is compiled and I'll get a nice hex color for "@link-color". However, if I look at this as a set of keys and values:

    {
      "@base-color": "#428bca",
      "@brand-primary": darken(@base-color, 6.5%)",
      "@link-color: @brand-primary",
      "@link-hover-color: darken(@link-color, 15%)"
    }

When consuming the value of "@link-color" in JavaScript I get the value of "@brand-primary" which basically I can do nothing with in regards to setting a value (ex setting a chart's link color). I suppose I could recursively navigate through the variables but I would still have to handle addition and any functions.

Could there be some manner of variable resolver or exposed list of resolved variables added to a future release? 

Ideally, I would like to hand the declarations and assignments which I included in my "variables.less" file and get a set of key/value pairs back, however, it would also be nice to look post processing on the processor to get a list of found and resolved variables.

**Comment by seven-phases-max** [comment]
See #2597.

**Comment by seven-phases-max** [comment]
Merging to #2597.

**Comment by seven-phases-max** [comment]
Merging to #2597.
