### ISSUE TITLE
Preserve Authors Color Formatting

### ISSUE THREAD

**Issue by badcrocodile** [less/less.js#2756]
When colors that are defined as variables get compiled to css the authors color values are lowercased and expanded when the color is defined in a variable.

Example:
@bgColor: #FFF; // compiles to #ffffff
@fontColor: black; // compiles to #000000

When colors are not defined in variables the formatting is not touched. Wondering if this is a feature or a bug?

It's causing issues on our team because some of us use Grunt and grunt-contrib-less, which does not modify color variables after compilation; while others use the lessc command with PhpStorm, which is modifying them - leading to VC conflicts.

Many thanks!

**Comment by seven-phases-max** [comment]
`grunt-contrib-less` and `lessc` both use the same Less lib so any difference in the output CSS is a result of using different Less version and/or other tools in your build chain (e.g. minifiers).

**Comment by seven-phases-max** [comment]
Closing as not an issue (at least something that can be solved in this repo anyway. Less preserve color values since 2.5.2).
