### ISSUE TITLE
Support CSS @apply Rule

### ISSUE THREAD

**Issue by panuhorsmalahti** [less/less.js#2757]
Currently using this rule causes an error: ``ParseError: directive options not recognised``.

See the @apply proposal here: http://tabatkins.github.io/specs/css-apply-rule/

This is a pressing issue when less.js is used with Polymer: https://github.com/Polymer/polymer/issues/1999

**Comment by seven-phases-max** [comment]
See #2715.

**Comment by seven-phases-max** [comment]
Closing as duplicate of #2715.
