### ISSUE TITLE
Option to dump all variables

### ISSUE THREAD

**Issue by battlesnake** [less/less.js#2758]
A nice aspect of less is immutable variables - this would be even nicer if there was an option to have less simply evaluate all top-level variables and output them instead of generating CSS.

*test.less*

    @base: hsv(200, 65%, 85%);
    @light: lighten(@base, 10%);
    @dark: darken(@base, 30%);
    @darker: darken(@base, 60%);
    
    /* Selectors and other CSS-generating stuff */
    /* ... */

*shell:*

    lessc --dump-vars test.less

*output:*

    base: #4caad9;
    light: #76bee2;
    dark: #195573;
    darker: #000000;

Currently, it seems that this can only be done by adding an "echo" selector:

    dump {
      base: @base;
      light: @light;
      dark: @dark;
      darker: @darker;
    }

And this will be stuck in the rest of the generated CSS.

Looking ahead, an optional parameter to specify the output format may also be a nice addition:

    lessc in.less --dump-vars=json

or

    lessc in.less --dump-vars=keyvalue

In addition to aiding debugging, it would allow the extensive colour functions of less to be used to generate values for other programs to use.

**Comment by seven-phases-max** [comment]
See #2597.

>In addition to aiding debugging, it would allow the extensive colour functions of less to be used to generate values for other programs to use.

That's weird. Instead of using Less code -> Less parser -> Less objects -> JavaScript functions -> Less objects -> Less output generator -> JavaScript data, one should really just have a descent JS color manipulation library.

**Comment by seven-phases-max** [comment]
Merging to #2597.

**Comment by battlesnake** [comment]
That last part was just an extra idea, the main intention was an easy way to dump top-level variables from the shell
