### ISSUE TITLE
Adding a library of mixins in the section "Using Less"

### ISSUE THREAD

**Issue by belyan** [less/less.js#2760]
Hi! Thanks for this great tool.

I wrote my own library of mixins. Please, add it to this page:
http://lesscss.org/usage/#frameworks-using-less-mixin-libraries

Name: Lessmore
Link: https://github.com/belyan/lessmore
Description: Lessmore - the modern library of LESS mixins that implements cross-browser support for the CSS3 features and more.

**Comment by seven-phases-max** [comment]
[Done](https://github.com/less/less-docs/commit/a2fecdbca2c8ee735ddde878bc6d651bdaae8e41).
(I assume you realize that the "vendorizing mixins" part of the lib is waste of time these days).

**Comment by belyan** [comment]
Thank you.
In the future I plan to focus on writing PostCSS mixins.
