### ISSUE TITLE
Reference importing outputs stuff when it's nested in a selector

### ISSUE THREAD

**Issue by diagramatics** [less/less.js#2762]
Not sure if this is intended, but I'm facing this issue right now.

Say if you have a mixin file called `mixins.less`:

```
.a-mixin {
  background: red;
}
```

And you import it as a reference inside a selector:

```
.a-selector {
  @import (reference) "a-mixin.less";
}
```

You'd expect nothing gets outputted, but there is an output:

```
.a-selector {
  .a-mixin {
    background: red;
  }
}
```

**Comment by seven-phases-max** [comment]
See #1896.

**Comment by seven-phases-max** [comment]
Closing as duplicate of #1896.

**Comment by diagramatics** [comment]
Ah okay, so the fix hasn't just been released yet?

Thanks for the info!
