### ISSUE TITLE
LESS processes non-spec properties

### ISSUE THREAD

**Issue by corysimmons** [less/less.js#2769]
We've had a few complaints from people using LESS that our PostCSS grid system isn't working when used with LESS.

- https://github.com/peterramsing/lost/issues/178
- https://github.com/peterramsing/lost/issues/229#issuecomment-170115431

It seems like LESS is tripping up when it gets to a property that is set as a fraction (e.g. `lost-column: 1/3;`).

Is this anticipated behavior? Would it be possible for LESS to ignore entire non-spec CSS declarations (or at least their properties)?

**Comment by seven-phases-max** [comment]
See [`--strict-math`](http://lesscss.org/usage/#command-line-usage-strict-math`). (And [escaping](http://lesscss.org/features/#features-overview-feature-escaping) as a workaround when `--strict-math=on` is not desired).

For a discussion on possible improvements see #1880.

---

As for "non-spec" declarations, in Less there's no difference between `color`, `lost-column` or `fnord` property names. It's totally property identifier agnostic (well, not counting some "to-be-removed" exceptions also mentioned in #1880).

**Comment by seven-phases-max** [comment]
Closing as expected behavior.

**Comment by peterramsing** [comment]
Yup, this looks to be expected and even documented. Thanks @seven-phases-max for the explanation! :smile:
