### ISSUE TITLE
Create a LESSCSS plugin for POSTCSS

### ISSUE THREAD

**Issue by renanvaz** [less/less.js#2774]
This will make the LESS proceed to fight with other precompilers and will not be a direct competitor of POSTCSS. This will also add your plugin list all plugins already compatible with POSTCSS.

Links:
https://github.com/postcss/postcss
https://github.com/postcss/postcss-plugin-boilerplate

**Comment by simaodeveloper** [comment]
+1 this will be awesome, I like it.

**Comment by rodrigoeddie** [comment]
+1

**Comment by gabrieldepaula** [comment]
+1

**Comment by matthew-dean** [comment]
I'm working on this here: https://github.com/matthew-dean/postcss-less, but it's currently a work-in-progress (not usable). However, star the project if you want to get updates.

**Comment by seven-phases-max** [comment]
Obviously such plugin would be another project (requiring its own repo), thus the feature-request is just beyond the scope of this repository.

So closing this as offtopic.

**Comment by seven-phases-max** [comment]
Discuss it at https://github.com/less/less-meta.
Or at a project started to target this, like https://github.com/matthew-dean/postcss-less.
