### ISSUE TITLE
.idea in your npm published package

### ISSUE THREAD

**Issue by rom1504** [less/less.js#2781]
I've recently noticed that git globally ignored filed are included in a npm package when publishing it and as a result some files are published by accident. See https://github.com/npm/npm/issues/5673 (and I'm working on https://github.com/rom1504/npm-safeguard)

The last version published of this package contain files in a .idea/. It doesn't seem like they contain actually private information in this case, but publishing these files by accident can lead to publishing passwords or any other private information (that would be put in webstorm run configurations for example)

**Comment by mrmlnc** [comment]
Yeap! Also need to remove all the excess files:

  * .idea (~32KB)
  * dot and CI files: `.jscsrc`, appveyor and etc
  * test directory (~600KB)
  * `Gruntfile.js`
  * bower (Why need it in npm package?)

This can reduce the package to ~700KB.

**Comment by seven-phases-max** [comment]
See #2617.

**Comment by seven-phases-max** [comment]
Merging to #2617.
