### ISSUE TITLE
Make "Less is more" the official slogan

### ISSUE THREAD

**Issue by scruffyfox** [less/less.js#2787]
I'm surprised that no one (that I have found) has thought of this

**Comment by BenPoulson** [comment]
+1 Surprised this isn't there already

**Comment by seven-phases-max** [comment]
See https://github.com/less/old-lesscss.org/issues/114 and https://github.com/less/less-docs/issues/99.

**Comment by seven-phases-max** [comment]
Merging to https://github.com/less/less-docs/issues/99.
