### ISSUE TITLE
Redundant whitespace in variable call syntax (i.e. DR).

### ISSUE THREAD

**Issue by seven-phases-max** [less/less.js#2796]
I accidentally noticed that currently a DR call may have a whitespace before parens, i.e.
```less
@foo: {1: 2};

bar {
    @foo ();  // OK
}
```

I suppose this should be forbidden since in future it may lead to conflicts between such "variable calls" and unknown `@at-rule` declarations. I.e. it must be only `@foo();` with no space allowed.

**Comment by matthew-dean** [comment]
:+1: I say go for it.
