### ISSUE TITLE
Compile LESS file to CSS into specific path

### ISSUE THREAD

**Issue by KennyJack** [less/less.js#2799]
Hi,

Is there workaround or method to compile LESS file to CSS into specific path?
Let said less file is in LESS folder and css file into CSS folder.

lessc test.less > test.css (i want my test.css in CSS folder)
How to do it?

Regards
Jack

**Comment by seven-phases-max** [comment]
Just like for any other command line utility, both `input file` and `output file` command line parameters specify file *path* (absolute or relative), not just file *name*. 
E.g. `lessc c:/foo/test.less e://myproject/css/test.css`.

---
Please note that the issue traker is not a support forum or a sort of. For generic "How-To"/"How-Do-I" questions consider using [SO](http://stackoverflow.com/questions/tagged/less) or so. For more details see https://github.com/less/less.js#reporting-issues.

**Comment by seven-phases-max** [comment]
Closing as not an issue.
