### ISSUE TITLE
Does LESS CSS Have a Function Similar to Stylus' +Cache Function?

### ISSUE THREAD

**Issue by moshemo** [less/less.js#2800]
Does LESS CSS Have a Function Similar to Stylus' [+Cache Function][1]?

If so, what is that function and where can I learn how to use it?  

Thanks.

  [1]: http://stylus-lang.com/docs/bifs.html#cachekeys

**Comment by seven-phases-max** [comment]
No. Basically it's the same feature as proposed in #1177.

**Comment by seven-phases-max** [comment]
Merging to #1177.
