### ISSUE TITLE
v2.6.0 Google maps not working

### ISSUE THREAD

**Issue by mateuszjarzewski** [less/less.js#2805]
I've got this good old gist that setup google map via HPNeo/gmaps lib.
It works well up to version 2.5.3, on lastest (2.6.0) it doesn't.

``` HTML
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<style type="text/less">
		#map {
  		height: 400px;
  		width: 100%;
  	}
	</style>
	<script src="http://cdnjs.cloudflare.com/ajax/libs/less.js/2.5.3/less.min.js"></script>
	</head>
<body>
	<div id="map"></div>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="http://maps.google.com/maps/api/js?sensor=false&amp;language=en"></script>
	<script src="http://cdn.rawgit.com/HPNeo/gmaps/master/gmaps.js"></script>
	<script>
		
		jQuery(document)
		  .ready(function($){
		    var map = new GMaps({
					div: '#map',
					lat: -12.043333,
					lng: -77.028333
				})
		  })

	</script>
</body>
</html>

**Comment by seven-phases-max** [comment]
"it dosn't" is not very helpful report, how do you think? Please provide more details about what exactly is broken...

**Comment by mateuszjarzewski** [comment]
Try it. WSoD tells the strory.

**Comment by matthew-dean** [comment]
@mateuszjarzewski Um. @seven-phases-max or anyone else is under no obligation to do extra work to to determine and accurately report the nature of the problem you're experiencing.

That said, despite your extremely dickish response, we would still be curious to know the nature of the problem, if indeed it might apply to other people who we might feel more motivated to help than you are currently inspiring for yourself. So, could you provide more detail or a jsfiddle or codepen link please? Thanks!

**Comment by mateuszjarzewski** [comment]
I dont care, you can do nothing about it, this project will be dead in no time since twBTv4 drops it.

**Comment by matthew-dean** [comment]
@mateuszjarzewski Cool, thanks for stopping by!

**Comment by mateuszjarzewski** [comment]
No problem, anytime pal.

**Comment by seven-phases-max** [comment]
Since it's not difficult to guess that this is the same issue as #2812, I'll merge this to that (just because there're it's more obvious).

**Comment by seven-phases-max** [comment]
Merging to #2812.
