### ISSUE TITLE
No download from lesscss.de possible

### ISSUE THREAD

**Issue by alve89** [less/less.js#2808]
If I click the "Download less.js" button (https://raw.github.com/cloudhead/less.js/master/dist/less-1.3.3.min.js) I get a .js file with this content "Not Found". Is there another link to implement this?

**Comment by seven-phases-max** [comment]
See https://github.com/less/less.js/tree/v2.5.3/dist

**Comment by seven-phases-max** [comment]
Closing as not a Less issue.
