### ISSUE TITLE
Release a new version (with bumped graceful-fs dependency)

### ISSUE THREAD

**Issue by ChALkeR** [less/less.js#2810]
`graceful-fs` versions lower than v4 reevaluate native `fs` module source, which is not supported.
You should update your `graceful-fs` dependency to v4 or later. 

It is already updated in the current master, but no new version has been released yet, so the current version still uses old `graceful-fs`.

Tracking issue: https://github.com/nodejs/node/issues/5213.

**Comment by jbruni** [comment]
Indeed. It triggers a warning upon `npm install less`:

> npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

**Comment by ChALkeR** [comment]
That's because of https://github.com/isaacs/node-graceful-fs/issues/58

**Comment by hgwood** [comment]
Looks like it was done in 2.7.

**Comment by ChALkeR** [comment]
@hgwood Thanks!
