### ISSUE TITLE
Discussion:  Preprocessor for less imports

### ISSUE THREAD

**Issue by sasrop** [less/less.js#2816]
I am in need of writing a preprocessor plugin for less files.  I would like to have the imports of a top level less file be commented out and then their respective contents inserted into the top level file.  

I have less files which import large numbers of other less files.  If the top level less file already has its imports included, this dramatically reduces the number of requests for imported less files and seems to be a better approach for performance and also for running in IE where we are experiencing crashes.

Has anyone written such a plugin?  Any ideas on how this might be accomplished are welcomed.

Thanks

**Comment by seven-phases-max** [comment]
>Has anyone written such a plugin? 

There're a few for pure CSS files (e.g. https://github.com/mariocasciaro/gulp-concat-css), but I did not hear of any Less specific tools (obviously CSS-dedicated tools may be confused by more complex Less syntax). I guess you could you them as a starting/learning point (Less `@import` statements are obviously pretty match the same, not counting some specific [import options](http://lesscss.org/features/#import-options), e.g. `(reference)`, that you can't implement by including anyway).

**Comment by seven-phases-max** [comment]
I'll close the ticket since it's beyond the scope of this particular repository (not an issue/bug, nor a feature that can be supported by the compiler). But feel free to continue the discussion here.

**Comment by matthew-dean** [comment]
I'm not quite understanding the use case or the specific issue.

**Comment by sasrop** [comment]
I'd like to preprocess my less files to bring in all of the imported less files, or at least the less files imported by the top level (parent) less file.  I need to be able to do this at build time.  Then at runtime, this combined less file is then used as input into the less parser/compiler. For reference, my application allows the user to make color selections that then get substituted for less variables to create custom css on the fly for a preview screen.  I was assuming I might be able to build a preprocessor to combine the less files ahead of time.  Hopefully this gives a little more info.  Thanks.

**Comment by lukeapage** [comment]
The less ast cannot output itself (other requested festures like prettify would need this). So im afraid we have nothing to help you. You could write something simple with a regex but it wont make urls relative. Your best off trying to work out if you can avoid runtime compilation.
