### ISSUE TITLE
Imports using `../` result in absolute paths in source map

### ISSUE THREAD

**Issue by MarcDiethelm** [less/less.js#2822]
This may be a regression of #1741
I made a testcase here: https://github.com/MarcDiethelm/lessc-sourcemap-bug

This is a real-world scenario that has cost me many, many hours of frustration. (This bug has been around a very long time.) In my projects I use a tool called [grunt-less-imports](https://github.com/MarcDiethelm/grunt-less-imports) to generate a file consisting of import statements. It's superior than using concatenation or maintaining a cascade of imports by hand, because it is generated using globbing to look for files that need to be imported.

However it turns out that if the generated file uses `../` to reach the files it is importing than the resulting source map will be broken, i.e. containing absolute paths.

I have tried to remedy this by using the available source map options, but no cigar.

**Comment by seven-phases-max** [comment]
I wonder if this is really a regression of #1741, as #1741 is not marked as fixed (there the OP refers to never merged #1611 that was tergeting a sligtly different pattern, thus when #1611 was said to be fixed it does nto autoamtically mean #1741 was fixed too).

In other words I simply mergethis to #1741.

**Comment by seven-phases-max** [comment]
Merging to #1741.

**Comment by seven-phases-max** [comment]
>I have tried to remedy this by using the available source map options, but no cigar.

Setting `--source-map-basepath` to `../` converted to absolute path wil do the trick.
