### ISSUE TITLE
calc -- not working correctly.

### ISSUE THREAD

**Issue by xblakestone** [less/less.js#2837]
[less.min.js - v2.5.3]
I tried to use 'calc' such as "width:calc(100% - 35px);" and it would calculate the 35px as a percent i.e. 100% - 35% (page displayed width:65%).

I am still new to LESS and not sure if this is a bug or maybe I am not using it correctly?

**Comment by Justineo** [comment]
You should use:

```less
width: ~"calc(100% - 35px)";
```

You can try it [here](http://ecomfe.github.io/est/fiddle/#est=false&code=LmJveCB7Cgl3aWR0aDogfiJjYWxjKDEwMCUgLSAzNXB4KSI7Cn0%3D).

**Comment by seven-phases-max** [comment]
See [`--strict-math`](command-line-usage-strict-math) and examples of escaping syntax (for the default `--strict-math=off`) [there](http://stackoverflow.com/a/33223373/2712740).

**Comment by seven-phases-max** [comment]
Closing as expected behaviour.
