### ISSUE TITLE
hello there

### ISSUE THREAD

**Issue by sanshiro** [less/less.js#2854]
hi guys :D can you send me some stickers here? i love your product and i wanna share the love on my laptop with all my nerdmigos

here is the address: 
Calle 27A Diagonal #348 por 26D y 26E. Polígono 108 itzimná.
C.P. 97143
Mérida, Yucatán. México

**Comment by seven-phases-max** [comment]
Honestly I have no idea what kind of "stickers" this is about, so I don't know what to do with this ticket... (close, keep open, redirect to something?) :) Could someone enlighten me please?

**Comment by matthew-dean** [comment]
Basically, a lot of projects have swag. Less.js currently does not. So, unfortunately, @sanshiro is out of luck, or would need to go to a print-on-demand shop add print a Less.js logo. This is really for less-meta? Yeah, go ahead and close.

**Comment by seven-phases-max** [comment]
Closing as not applicable.

**Comment by SomMeri** [comment]
Now I want some stickers too.
