### ISSUE TITLE
Absolute path in sourcemap for @imported files.

### ISSUE THREAD

**Issue by JulianRaya** [less/less.js#2864]
If a less file in one directory imports a less file from a sibling directory, the absolute file path is inserted in the sourcemap file. 
For less files that are siblings of import directory, the correct relative path is inserted.

Very simple example:
## Directory structure

```
work/
|-- imports/
|   `-- import.less
|-- bad/
|   `-- bad.less
`-- good.less
```
## file content

`good.less`

```
@import (reference) "imports/import";

div {
    .mixin();
    color: @color;
}
```

`bad/bad.less`

```
@import "../imports/import";

div {
    .mixin;
    color: @color;
}
```

`imports/import.less`

```
@color: #00ff00;
.mixin {
    backgorund: #ff0000;
}

```
## command lines and generated map files

**correct** - works in chrome
`lessc --source-map good.less good.css`

```
{"version":3,"sources":["good.less","imports/import.less"],"names":[],"mappings":"AAEA;ECAC,mBAAA;EDEA,cAAA","file":"good.css"}
```

**incorrect** - fails in chrome
`lessc --source-map bad/bad.less bad/bad.css`

```
{"version":3,"sources":["D:/work/imports/import.less","bad.less"],"names":[],"mappings":"AACA;EACC,mBAAA;;ACAD;EDAC,mBAAA;ECEA,cAAA","file":"bad.css"}
```

**correct** - works in chrome
`lessc --source-map --source-map-basepath=D:/work good.less good.css`

```
{"version":3,"sources":["good.less","imports/import.less"],"names":[],"mappings":"AAEA;ECAC,mBAAA;EDEA,cAAA","file":"good.css"}
```

**incorrect** - fails in chrome
`lessc --source-map --source-map-basepath=D:/work/ bad\bad.less bad\bad.css`

```
{"version":3,"sources":["imports/import.less","bad/bad.less"],"names":[],"mappings":"AACA;EACC,mBAAA;;ACAD;EDAC,mBAAA;ECEA,cAAA","file":"bad.css"}
```

**incorrect** - fails in chrome
`lessc --source-map --source-map-basepath=D:/work/bad bad\bad.less bad\bad.css`

```
{"version":3,"sources":["D:/work/imports/import.less","bad.less"],"names":[],"mappings":"AACA;EACC,mBAAA;;ACAD;EDAC,mBAAA;ECEA,cAAA","file":"bad.css"}
```

**expected results:** file paths in sourcemap files should not include "D:\anything".
I am not sure if the paths are supposed to be relative to the sourcemap or the css file or the less file, but it definitely should not be a full path with drive letter. .

**Comment by JulianRaya** [comment]
I should also add that, for my project, specifying directory names under the root less directory (like the last example where basepath=D:\work\bad) is not possible. I tried it anyways and still got bad results.

**Comment by JulianRaya** [comment]
Another side note, I looked at the code in lib/less/source-map-output.js.. And it looks like there is no support for relative directories or nested directories. 

The --source-map-basepath and --source-map-rootpath are not very useful unless all less files are in the same directory with no nested directories. So they are kinda pointless. They do nothing that cant be done with a simple search and replace.

Also why not use the nodejs path module? It is very useful for this kind of thing. The code would be so much easier to read and maintain.

**Comment by stasberkov** [comment]
Will someone merge this pull request? I also need this fix. Please....

**Comment by stasberkov** [comment]
As a workaround you can set `--source-map-rootpath="file:///"` that will make source file available at least locally.
