### ISSUE TITLE
Clean blank lines

### ISSUE THREAD

**Issue by jlchereau** [less/less.js#2867]
I am assuming here that this is the less compiler that webpack uses internally. 

This (with all the blank lines):

![image](https://cloud.githubusercontent.com/assets/2556751/14411065/eec9374e-ff35-11e5-9510-7e58d6418a0e.png)

First translates into this (less compiling)

![image](https://cloud.githubusercontent.com/assets/2556751/14411041/854230aa-ff35-11e5-8733-329becb92741.png)

then into this (webpack packaging):

![image](https://cloud.githubusercontent.com/assets/2556751/14411027/1e587ffc-ff35-11e5-90dc-ba1553ef1c17.png)

See also https://github.com/webpack/webpack/issues/2311 and their answer.

**Comment by jlchereau** [comment]
For reproducing and testing, the telerik files can be downloaded from https://github.com/telerik/kendo-ui-core and this is their response to the issue: https://github.com/telerik/kendo-ui-core/issues/1569.

**Comment by seven-phases-max** [comment]
So are you suggesting the compiler should analyse and transform comments? It does not sounds like its duty (at best it's up to a css-minifier).

**Comment by jlchereau** [comment]
I have tried configuring webpack with the compress option but it has no impact. It might be enabled by default.

**Comment by seven-phases-max** [comment]
Well, in short, no, it's either not Less duty to clean-up blank lines in CSS comments (CSS comments are supposed to be passed as-is). I'm afraid the only thing I can suggest is to look at for example [clean-css](https://github.com/jakubpawlowicz/clean-css) and its `s*` options, and find if you can use them within `webback` (`clean-css` is also available as a plugin for the Less compiler [too](http://lesscss.org/usage/#v2-upgrade-guide-clean-css)).
