### ISSUE TITLE
Request optional dependency

### ISSUE THREAD

**Issue by baderbuddy** [less/less.js#2870]
Is the optional dependency for request being used for anything? I can't see anything in the code that's referencing it, maybe we could eliminate the dependency to make this a little more lean?

**Comment by jeremyVignelles** [comment]
Just asked myself the same question, and this appears to be useless...

It has been introduced by this commit by @jurcovicovam : https://github.com/less/less.js/commit/ea122a8ea5c914f5ac48bc627e42a5d4705f5cd9

Removing this dependency would save about 5MB, about half the size of this library...

**Comment by jeremyVignelles** [comment]
This is the commit that introduced the dependency : https://github.com/less/less.js/commit/70d610f87749589092c3f2f436c0483d9228a93a
