### ISSUE TITLE
Should common LESS elements be combined in the CSS output?

### ISSUE THREAD

**Issue by jt000** [less/less.js#2877]
Take the following example (repro'd with 2.5.3):

```
.nav {
  min-height: 20px;
  
  > a {
    color: blue;
    text-decoration: none;
  }
}

.nav {
  display: block;
  
  > a {
    padding-top: 3px;
  }
}

.nav > a {
  padding-bottom: 2px;
  color: green;
}

.nav-sm {
  .nav;
  
  > a {
	color: red;
  }
}
```

The above LESS creates the following CSS

```
.nav {
  min-height: 20px;
}
.nav > a {
  color: blue;
  text-decoration: none;
}
.nav {
  display: block;
}
.nav > a {
  padding-top: 3px;
}
.nav > a {
  padding-bottom: 2px;
  color: green;
}
.nav-sm {
  min-height: 20px;
  display: block;
}
.nav-sm > a {
  color: blue;
  text-decoration: none;
}
.nav-sm > a {
  padding-top: 3px;
}
.nav-sm > a {
  color: red;
}
```

From this example, the `.nav`, the `.nav > a`, and `.nav-sm > a` are created multiple times which could lead to inheritance\ordering differences on different browsers. Should they be combined into a single `.nav`, `.nav > a`, and `.nav-sm > a` elements to be more explicit in the value & decrease the overall size of the CSS?

**Comment by seven-phases-max** [comment]
See #930. In short: no, Less does not analyze outcoming CSS (except some trivial stuff) and thus cannot perform any optimization of that kind for free. Considering you can get these optimizations with `clean-css`, this feature is most likely to stay beyond Less scope.

> are created multiple times which could lead to inheritance\ordering differences on different browsers.

No, no matter how many times `.nav-sm > a` appears in the output, inheritance\ordering remains the same in all conformant browsers.

**Comment by seven-phases-max** [comment]
Merging to #930.
