### ISSUE TITLE
Source map bug introduced in 2.7.0, but passes tests

### ISSUE THREAD

**Issue by matthew-dean** [less/less.js#2896]
Will put out a hotfix soon if the fix can be confirmed. It looks like PR #2834 introduced a bug that produces a blank source map, and throws an error like: 
```
Invalid mapping: {"generated":{"line":1103,"column":2},"source":"file.less","original":{"line":1,"column":null},"name":null}
```
(Also discussed at #2881.)

Reverting #2834 seems to fix it, but looking for confirmation.

**Comment by matthew-dean** [comment]
This issue should stay open until a Less.js test is added which catches this issue, since the source map tests didn't detect the bug.

**Comment by wolfy1339** [comment]
I'm experiencing the same issue.
I executed a `git bisect` and the first commit that broke the build was 470af20f641c9b5389475733dfe341aa4c180fba

**Comment by sunnylqm** [comment]
better unpublish this version

**Comment by seven-phases-max** [comment]
>better unpublish this version

It depends. For some the sourcemaps are totally insignificant if compared to for example https://github.com/less/less.js/issues/2841 of the previous release.

**Comment by architruc** [comment]
In case it can help, I could reproduce the issue with something like:

Less:

```less
.dl-horizontal {
    @media (min-width: 768px) {
        dt {
            float: left;
        }
    }
}
```

Gulp task:

```javascript
return gulp.src('./src/lib.less')
	.pipe(sourcemaps.init())
	.pipe(less())
	.pipe(sourcemaps.write('.'))
	.pipe(gulp.dest(bundleFolder));
```

**Comment by felixfbecker** [comment]
This just broke my builds, need a patch asap...

**Comment by icecreamliker** [comment]
Please fix this bug asap, or I can only froze the version to 2.6.X.
And I wish this bug could be fixed before tomorrow morning.

**Comment by olivierlesnicki** [comment]
Chaos on this side as well...

**Comment by BramVanBerkel** [comment]
Crashes my gulp build as well

**Comment by oBusk** [comment]
If you're having trouble with a dependenct using less as a dependency and simply can't downgrade in package.json.
Do a [`npm shrinkwrap --dev`](https://docs.npmjs.com/cli/shrinkwrap) and then modify the version of less to 2.6.1 then full npm reinstall will fix it until less.js is fixed

**Comment by gilly3** [comment]
Clearly the impact is widespread.  It blocked my production release.  Yes, please implement a hotfix, and provide workarounds, but in the meantime, for the love of all that is good and holy:

```
$ npm unpublish less@2.7.0
```

Unless you will have 2.7.1 published within, say, the next hour, nip this in the bud and unpublish.

**Comment by ReidBraswell** [comment]
Any line of sight for a fix on this yet?

**Comment by matthew-dean** [comment]
I've published 2.7.1 as a hotfix for 2.7.0, but it's unclear from #2881 if there isn't still an outstanding bug affecting source maps (multiple intersecting bugs from same commit?), or if that was a pre-existing bug which was introduced separately.

Please report back if 2.7.1 is working for you.

**Comment by felixfbecker** [comment]
works for me, thanks @matthew-dean

**Comment by nknapp** [comment]
[the bootprint-integration-test](https://travis-ci.org/bootprint/bootprint-integration-test/builds/122610568 ) had failed with less@2.7.0 and it succeeds with 2.7.1. Works for me. Thanks @matthew-dean

**Comment by matthew-dean** [comment]
Awesome. Sorry for the broken build, but glad it's working now. Will close this.

**Comment by olivierlesnicki** [comment]
@matthew-dean good job

**Comment by matthew-dean** [comment]
@olivierlesnicki 👍

**Comment by Piyamas2507** [comment]
Hi, My project have been compile all less file to css file already.
I'm not use less.js.
Could you tell me how to  do about debug css show less in get element inspector develope.
How to config sauce map?
