### ISSUE TITLE
LESS mixin interpolation not working

### ISSUE THREAD

**Issue by markdanial** [less/less.js#2899]
Using LESS 2.6.0 and when I create a mixin like this it fails silently. No error thrown:
```

.gridGutterClasses(@breakpoint; ) {
  .@{breakpoint}-grid-gutter {
    width:100%;
  }
}

.gridGutterClasses(mobile);
```

BUT, if I add a class to the beginning of the selector, like this:

```
.gridGutterClasses(@breakpoint; ) {
  .class.@{breakpoint}-grid-gutter {
    width:100%;
  }
}
```

It works. 

I do not want to have to prepend a class, however. Is there a solution to this issue?
Thanks

**Comment by DaveyJake** [comment]
I know this issue is closed by I'm experiencing the exact same thing with the following:
```
.tournamentRoundHeight(@n; @i: 1) when (@n =< @i) {
    &:nth-child(@{n}) {  	
        .match {
            height: calc(70px * @n);
        } 
    }
    .tournamentRoundHeight(@n; (@i + 1));
}

.round {
    .tournamentRoundHeight(5);
}
```
Still unable to find a solution though.
