### ISSUE TITLE
Inform that less is faster

### ISSUE THREAD

**Issue by aktywnitu** [less/less.js#2910]
Hi,

compilation must be fast like visual graphic programs. Yes?
Some blogs says that sass is faster, so i installed and it was not needed:

```
time lessc less/bootstrap.less > test.css
real    0m1.552s
user    0m1.836s
sys     0m0.096s
```

```
time sass stylesheets/_bootstrap.scss >test.css
real    0m2.294s
user    0m2.220s
sys     0m0.064s
```

**Comment by povrazor** [comment]
There's a C version of Sass.

https://github.com/sass/sassc

**Comment by seven-phases-max** [comment]
Either way this seems to be quite beyond the scope of this repository. Does it?
