### ISSUE TITLE
Security Contact?

### ISSUE THREAD

**Issue by fd0** [less/less.js#2914]
Hi,

I was unable to find a security contact for less on the website. Who is the right person to report a security vulnerability to?

**Comment by matthew-dean** [comment]
Yeah, Github doesn't have any private messaging functionality. I'm currently running the Less Twitter account. Maybe a DM there? https://twitter.com/LessToCSS

**Comment by fd0** [comment]
I've just sent you an email to your gmail address (extracted from the git logs), I hope that this is okay for you :)

**Comment by fd0** [comment]
Did you get my email? Any questions in regard to the advisory?

**Comment by fd0** [comment]
Ping

**Comment by matthew-dean** [comment]
Sorry it took me a while to get back to you. Just sent an email I drafted earlier today.

**Comment by fd0** [comment]
We've released an advisory for this vulnerability: https://www.redteam-pentesting.de/advisories/rt-sa-2016-003/

**Comment by matthew-dean** [comment]
Thanks! This will be better addressed in the next major release.
