### ISSUE TITLE
JS Evalution still works but is't documented

### ISSUE THREAD

**Issue by AndyOGo** [less/less.js#2923]
If you check old less documention, you will that it had this fancy section about backticks and JavaScript evaluation.
https://web.archive.org/web/20111231053900/http://lesscss.org/#-javascript-evaluation

Unfortunately it's gone, though this nice feature is still working.
I hope backticks are still intended to be supported. If so so please bring them back into the documentation.

**Comment by matthew-dean** [comment]
The feature should be listed as currently supported, but deprecated, as 
a) mis-use of this feature can create security issues, 
b) Less plugins are a cleaner approach to add script functionality.

This will likely be removed in the 3.0 release.

**Comment by matthew-dean** [comment]
Closing as not an issue.

**Comment by AndyOGo** [comment]
Well, I found it a very handy way to add functions to Less via `functions.functionRegistry.add`.
Do have any alternative, for adding user defined functions?

**Comment by AndyOGo** [comment]
No I can't find it being listed and marked as deprecated.
It is just not listed at all...

Do you have a link?

**Comment by matthew-dean** [comment]
You can include a plugin script with `@plugin` (works like `@import`), and in that JS file, just write:
```js
functions.add(name, function() { ... });
```
That's it. ^_^

**Comment by matthew-dean** [comment]
> No I can't find it being listed and marked as deprecated.

What I meant was that it should be (as in someone should do that), but no, it currently is not.

**Comment by AndyOGo** [comment]
ohhh, much nicer:) Thank you very much
