### ISSUE TITLE
Mixed Content Warnings over SSL for inline import of Google Fonts 

### ISSUE THREAD

**Issue by mazlix** [less/less.js#2926]
We recently moved many of our `@import`s to `@import (inline)`. Including google fonts. We previously were using protocol-less URLs (i.e. `//fonts.googleapis.com`).

When we moved to inline import though we started getting mixed content warnings because the urls https://fonts.googleapis.com/css?family=Droid+Serif and http://fonts.googleapis.com/css?family=Droid+Serif have hardcoded `https` / `http` in their `@font-face`.

**Comment by matthew-dean** [comment]
How is this a Less issue? It's just inlining the content.

**Comment by mazlix** [comment]
Hey, sorry I don't use GitHub's UI much. I thought I made a PR but accidentally made 2 of the same issue.

For protocol-relative URLs less is opting to download the assets over `http` the PR #2928 would fix this by choosing `https` over `http` when both are allowed. This fixed our issue of inlining google fonts when using protocol-relative URLs and I believe it's now best practice to opt for SSL over non SSL when both options are available.
