### ISSUE TITLE
Compiling less to css in browser

### ISSUE THREAD

**Issue by jonathanhotono** [less/less.js#2958]
Hi Guys,

My apologies if this is the wrong thread to start with.
I'm currently trying to parse a simple string containing less to css and less.js(version 2.7.1) kept on returning error: cannot read property 'pluginManager' of undefined.

![image](https://cloud.githubusercontent.com/assets/6864547/18091607/8ed8df82-6f0c-11e6-9ee0-dd04bd7249a3.png)

sample code here:
http://jsfiddle.net/3AHTW/6/

Many thanks

Jonathan

**Comment by Justineo** [comment]
Plz read the docs. The way you are using to compile Less code was deprecated.

**Comment by jonathanhotono** [comment]
Got it.. less.render is the solution!

Cheers
