### ISSUE TITLE
Expressions inside unnecessary parenthesis not processed with strict-math option

### ISSUE THREAD

**Issue by geleto** [less/less.js#2962]
Hello,
with the strict-math option on, this calculation:
`width: calc(100% - (10px  - 5px));`
is not optimized, the output is exactly the same.

Without the strict-math option the output is, as expected:
`width: calc(95%);`

Using less@2.7.1

**Comment by matthew-dean** [comment]
I doubt that "expression optimization" is something that would be added, since it's of little value.

**Comment by geleto** [comment]
Well, calling it 'optimization' was a bit of a stretch. If all values inside the parenthesis use the same unit - calculate the result, just as when strict-math is not active.
That;s what the behavior should be according to the docs:  http://lesscss.org/usage/#command-line-usage-strict-math
I used the example from the docs.

**Comment by matthew-dean** [comment]
@geleto Ha, it does say that! My mistake. I will say that the result is still effectively the same, so while that looks like changed behavior, the bug is not a breaking bug.

**Comment by geleto** [comment]
Well, I use a bunch of sizes, paddings and margins in my calcs, the result looks quite ugly.
IMO, it was never the intention of `strict math` to mean `no math at all`.

**Comment by seven-phases-max** [comment]
Closing as not an issue:

>With strict math on, only maths that is inside ***un-necessary parenthesis*** will be processed.

That is, if you want that `100% - (10px - 5px)` to be procesed by Less when the option is on it should be:
```less
width: calc((100% - (10px - 5px)));
```

**Comment by seven-phases-max** [comment]
Closing as expected and documented behaviour.

**Comment by geleto** [comment]
Thanks, you should update the example in the docs.

**Comment by seven-phases-max** [comment]
@geleto Indeed, thanks for pointing it out (I actually missed above that it's *the invalid example* that misdirected you).
