### ISSUE TITLE
Variables are actually variables?!

### ISSUE THREAD

**Issue by alixaxel** [less/less.js#297]
The LESS website says:

**Note that variables in LESS are actually ‘constants’ in that they can only be defined once.**

However, the following:

```
@var: red;
@var: blue;

#footer {
  color: @var; // red  
}
```

Generates:

```
#footer {
  color:blue;
}
```

Personally, I prefer variables to be variables, but I just can't get past the feeling that I might be missing something.

Are the docs wrong or outdated?

**Comment by gacekssj4** [comment]
Adding @var at end of documents yields results:

    // Equivalent to --modify-vars option.
    // Properties under options.modifyVars are appended as less variables
    // to override global variables.
    var modifyVarsOutput = parseVariableOptions(options.modifyVars);
    if (modifyVarsOutput) {
      srcCode += '\n' + modifyVarsOutput;
    }

https://github.com/gruntjs/grunt-contrib-less/blob/master/tasks/less.js @ line ~144
And it works.

**Comment by coresh** [comment]
Thanks, @matthew-dean

Also allowed:

.setColumn(@column-width, @column-color) {
  .column{
     width: @column-width;
     color: @column-color;
  }
}

.setColumn(60px, #ff0000);
.setColumn(40px, #ffffff);

**Comment by FrischeWelt** [comment]
ükk
