### ISSUE TITLE
Caching less imports

### ISSUE THREAD

**Issue by jws305** [less/less.js#2970]
I am using Less in the browser to allow users to dynamically update the styles of a page.  I have two less files on the server that define some mixins and these files never change.  Then on the browser, I am generating a short less snippet that calls these mixins with different parameters.  Every time I render the snippet, the two files from the server are downloaded again.  The less file is rendered many times a second so this presents a problem.  How can I force less to cache these files.

**Comment by rjgotten** [comment]
> How can I force less to cache these files.

Afaik Less just uses XmlHttpRequest. So; set proper cache headers on your server.
