### ISSUE TITLE
data-uri

### ISSUE THREAD

**Issue by txiaocao** [less/less.js#2972]
data-uri转换图片时，路径问题
// add rootPath
        if(typeof (filePathNode.currentFileInfo.rootpath)!=="undefined" && filePathNode.currentFileInfo.rootpath !==""){
            currentDirectory = filePathNode.currentFileInfo.rootpath;
        }

**Comment by Justineo** [comment]
请用英语提 issue，还有可以把问题描述得清楚一些吗？比如预期结果啥样，实际结果啥样。
(Please use English in issues and could you elaborate on this one? eg. the expected result vs. the actual result.)
