### ISSUE TITLE
Variables in media queries

### ISSUE THREAD

**Issue by fiftin** [less/less.js#2976]
Why next LESS:
```
@a: 10px;
@b: @a * 20px;
@media (max-width: @b) {
  a {
    width: @b
  }
}
```
compiles to next CSS:
```
@media (max-width: 10px * 20px) {
  a {
    width: 200px;
  }
}
```
Why max-width isn't 200px? And сan I do something to get 200px in media query instead of 10px * 20px?

Sorry for the stupid question.

**Comment by seven-phases-max** [comment]
See #1480.

**Comment by seven-phases-max** [comment]
Closing as a duplicate of #1480.
