### ISSUE TITLE
Css is not generated properly for child div (less nesting with element name, without class refence)

### ISSUE THREAD

**Issue by sukhoi1** [less/less.js#2977]
http://stackoverflow.com/questions/40227504/css-is-not-generated-properly-for-child-div-less-nesting-with-element-name-wit

`#parent { & > div { ... } } //does not work
#parent { > div { ... } }   //does not work
#parent { div { ... } }     //does not work

I expect the following result:
#parent div { ... }`

**Comment by seven-phases-max** [comment]
Closing as the op mistake.
(Assuming that the linked SO question is already deleted because apparently `#parent { div { ... } }` *does* work).
