### ISSUE TITLE
options.compress = true doesn't produce correct source map

### ISSUE THREAD

**Issue by sormy** [less/less.js#2989]
options.compress = true doesn't produce correct source map
example: font-awesome less
PS: clean-css works well

**Comment by seven-phases-max** [comment]
`compress` is [deprecated 1.5 years ago](https://github.com/less/less.js/blob/master/CHANGELOG.md#220). (selfnote: mark it as such at every occurrence in less-docs, [e.g.](http://lesscss.org/usage/#command-line-usage-compress))

**Comment by seven-phases-max** [comment]
Closing as not applicable anymore.
