### ISSUE TITLE
FIX YOUR SHIT GAHDAMN

### ISSUE THREAD

**Issue by candh** [less/less.js#3004]
![IRONY](http://i.imgur.com/yddtRvf.gif)

**Comment by GrimLink** [comment]
It would be helpful for the less-team if you gave a little more information than just this.

What browser are you using.
What browser version.
What OS are you running + version.

**Comment by candh** [comment]
I'm USING UMM: 
- CHROME Version 54.0.2840.98 (64-bit)
- MAC OS SIERRA 10.12.1 (Macbook Air, non-retina)
- I'M USING A TRACKPAD.
- My internet connection speed is 20 Mb

Other information that might help

- Bush did 9/11
- I went to a barber yesterday and he gave me the "fuck my life up" and I'm very sad 
- I am a virgin
- This is not really my computer it's my bros.
- I haven't installed any chrome extensions that might interfere with this
- I'm thinking about joining the military but I don't think they'll take me I'm not in a fit shape.
- I'm about to turn 18 on 31 December
- Its -7 C outside its freezing. (but i'm inside so i don't see how that'd affect)
- I am a big kanye west fan.
- Moon landings were not fake
- I am depressed and a little suicidal
- I like eating pizza
- She doesn't love me back 
- One time when I was a kid I purchased a p4 PC and played GTA Vice City on it
- I don't drink alcohol
- This GIF was made by giphy the app from app store. Its frame rate a little slower.
- My father died 4 years ago
- I had eggs for breakfast
- My favorite actor is Leonardo DiCaprio
- I've seen all of his movies
- 4 your eyez only had only 2 good songs
- I watched Arrival when it came out and it was fucking awesome
- My bro's kid is so annoying 
- My brightness settings are set like in the middle

I hope you have all the information 👍

**Comment by matthew-dean** [comment]
Closing as wrong repo. Moved to: https://github.com/less/less-docs/issues/427

**Comment by matthew-dean** [comment]
I've blocked @candh from the Less org for abusive behavior.

**Comment by aminozuur** [comment]
@matthew-dean u mad breh?

**Comment by seven-phases-max** [comment]
@aminozuur Here we are not welcome kiddish slang and aggressive talking. So please learn some communicative English before posting.

**Comment by matthew-dean** [comment]
@aminozuur Am I mad? Not at all. But abusive language is not tolerated.
