### ISSUE TITLE
What does the strictImports option do?

### ISSUE THREAD

**Issue by matthew-dean** [less/less.js#3011]
I'm working on updating Less documentation, and got to the `strictImports` option. There's no documentation of it anywhere, nor an issue tracking it.

What I see here is that there is a call to `evalImports` that is prevented by this option. https://github.com/less/less.js/blob/49cbe520f6b38b4b8797dcba491501c0c461c7f5/lib/less/tree/ruleset.js#L107 

I think this might mean that root variables in the import are not bubbled up / combined under one root scope. Is there someone familiar with the code base that can confirm this?

**Comment by matthew-dean** [comment]
@less/core

**Comment by seven-phases-max** [comment]
I found http://stackoverflow.com/questions/14763392/less-strictimports.

**Comment by matthew-dean** [comment]
Aha! Considering this has been undocumented (other than mentioning the option), and no one has complained about the ability to put an `@import` anywhere, I think the option should be removed for simplicity. Agree?

**Comment by seven-phases-max** [comment]
> I think the option should be removed for simplicity. 

+1

**Comment by matthew-dean** [comment]
Boom.
