### ISSUE TITLE
change theme

### ISSUE THREAD

**Issue by wwqking** [less/less.js#3014]
A variety of different topics, how to change a less file under the color variable value

**Comment by seven-phases-max** [comment]
I'm afraid if you're looking for a tutorials or so you'll need to search elsewhere. Neither [the issue tracker](https://github.com/less/less.js#reporting-issues) nor [the docs](http://lesscss.org/) are meant for this sort of things. (For a particular question/problem of the Less usage see also [SO](http://stackoverflow.com/questions/tagged/less)).

**Comment by seven-phases-max** [comment]
Closing as not an issue (and too broad for a question anyway).
