### ISSUE TITLE
Release 2.7.2 on GitHub

### ISSUE THREAD

**Issue by Justineo** [less/less.js#3015]
The latest npm package is `v2.7.2` but this version is missing here in repo releases.

**Comment by matthew-dean** [comment]
You're probably just looking at the wrong branch: https://github.com/less/less.js/tree/master

**Comment by Justineo** [comment]
I mean release `v2.7.2` [here](https://github.com/less/less.js/releases).

**Comment by matthew-dean** [comment]
Oh. There hasn't been any releases there since v2.5.1. Is there any reason you would need it there?

**Comment by Justineo** [comment]
I'm depending on the path of the release/tag file to load specific version in this Less playground: [estFiddle](http://ecomfe.github.io/est/fiddle/)
So can you just at lease add a tag?

**Comment by RinkAttendant6** [comment]
This appears to be resolved: https://github.com/less/less.js/releases/tag/v2.7.2

**Comment by seven-phases-max** [comment]
Closing as fixed with https://github.com/less/less.js/releases/tag/v2.7.2.
