### ISSUE TITLE
less sync routine?

### ISSUE THREAD

**Issue by publicocean0** [less/less.js#3017]
hi is there a sync routine for the less-css conversion?

**Comment by publicocean0** [comment]
less.render(s,{
    processImports: true,
    paths: [$.path.dirname(f)],
    fileInfo:{filename:$.path.basename(f)}
	}, function(e,o) { 
		    console.log(e,o)
		    if (e) throw new Error('error parsing file '+f+':'+e.message);
            compiled = o.css;

        });

  
    if (!compiled) throw new Error('error parsing file '+f);

**Comment by publicocean0** [comment]
passing the file bootstrap.less compiled is  undefined but no error is thrown

**Comment by seven-phases-max** [comment]
>Is there a sync routine for the less-css conversion?

No, I'm afraid there's no. As soon as the compiled code uses some `@imports`, `render` is asynchronous (#2546).

>passing the file bootstrap.less compiled is undefined but no error is thrown

It's expected if you try to use it outside of your `function(e,o)`.

**Comment by publicocean0** [comment]
ok you problably you use native async file reader for importing files.
I saw there is a fileManager .... maybe i can override some fileManager function for using sync version ?can It  sound possible to you?
