### ISSUE TITLE
Can't seem to install latest version

### ISSUE THREAD

**Issue by GreenFootballs** [less/less.js#3018]
I installed less 1.6.3 a while back, and wanted to upgrade to the latest version but nothing I've tried seems to work. I've tried all the variations of npm install I can think of, and even tried uninstalling first, but no matter what I do, when I check the version of lessc it shows 1.6.3.

Any ideas why this is happening?

**Comment by seven-phases-max** [comment]
>I've tried all the variations of npm install I can think of

We do not know what variations you can think of so it's a bit... 
At first glance a typical problem is global vs. local installations (like the other day you've installed it globally, now you're installing it locally or vice-versa).
