### ISSUE TITLE
jasmine:main test issues

### ISSUE THREAD

**Issue by seth-priya** [less/less.js#3020]
Hi All,

I am trying to install and test less.js on ppc64le. 317 test cases are passing, however the jasmine:tests are giving issues. They are timing out (due to phantomjs time out) on x86_64 and execution never seems to complete on ppc64le (although pressing ^C shows 100% completion, if I do so after a substantial period of time.

All Passed 317 run

Running "browserify:browser" (browserify) task
>> Bundle tmp/less.js created.

Running "uglify:test" (uglify) task
File tmp/less.min.js created: 381.14 kB â 143.65 kB
>> 1 file created.

Running "concat:browsertest" (concat) task

Running "connect:server" (connect) task
Started connect web server on http://localhost:8081

Running "jasmine:main" (jasmine) task
Testing Jasmine specs via PhantomJS

^C

Execution Time (2017-01-17 09:06:55 UTC-0)
jasmine:main     42m 14.9s  ââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ 100%
Total 42m 27.5s

As mentioned, tests time out on x86. Is that a known issues? Is there a way to debug this or workaround this?

Any pointers on this would be of great help. Thanks in advance!!!

Regards,
Priya

**Comment by matthew-dean** [comment]
Do you have PhantomJS installed?

**Comment by seth-priya** [comment]
Thanks for the response!

Yes, I have phantomjs installed. On ppc64le, since a phantomjs binary is not available currently, I have built and installed phantomjs 2.1.1 from source.

bash-4.2# phantomjs --version
2.1.1
bash-4.2# node --version
v6.2.1
bash-4.2# npm --version
3.9.3

npm install itself was failing for me without phantomjs.

**Comment by seth-priya** [comment]
This was not an issue with less.js, but with the phantomjs binary that I was using.

All test cases passed with the binary available at
https://github.com/ibmsoe/phantomjs/releases/download/2.1.1-rhel7.2/phantomjs-2.1.1-linux-ppc64.tar.bz2

Closing the issue. Thanks!
