### ISSUE TITLE
Syntax etc. errors in test file

### ISSUE THREAD

**Issue by edgework** [less/less.js#3024]
There's a bunch of errors in this file:

server/node_modules/less/test/less-bom/css-3.less

Our build system verifies every single file and fails if there's an error.  The latest version of LESS broke our builds.

Here's a few:

![image](https://cloud.githubusercontent.com/assets/5122883/22167431/1d749564-df1b-11e6-8d79-72c2827a5c9e.png)

![image](https://cloud.githubusercontent.com/assets/5122883/22167444/34bd81e0-df1b-11e6-9ff3-686817c7af8c.png)

**Comment by seven-phases-max** [comment]
Could you please provide more details on what your test is actually supposed to test? (I.e. why you're throwing Less test files at it?)

There're certain controversial things in the `css-3.less` file (like the not anymore valid `^^` combinator etc., thus thing to be eventually removed), but it's still "valid" Less ("valid" as in "not necessary making any sense but still passing the self-tests").

**Comment by edgework** [comment]
Our build system is a little too eager and validates every single file including everything deep in node_modules.  That's kinda dumb and I changed it to ignore node_modules.

Sorry I was a little annoyed that our build broke.  What you're doing makes perfect sense.
