### ISSUE TITLE
Add support for case-insensitive attribute selectors

### ISSUE THREAD

**Issue by murrayju** [less/less.js#3027]
According to [Mozilla](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors):

> `[attr operator value i]`
> Adding an i (or I) before the closing bracket causes the value to be compared case-insensitively (for characters within the ASCII range).

This appears not to be supported by Less currently, and results in a compiler error.

> expected ']' got 'i'

**Comment by seven-phases-max** [comment]
Oh, no: changin glabels since it's not in CSS3 (just a CSS4 draft).

**Comment by murrayju** [comment]
Yep, it is in working draft, but browsers seem to support it already (tested in Chrome 55 and Firefox 51).

**Comment by calvinjuarez** [comment]
For reference: https://caniuse.com/#feat=css-case-insensitive

**Comment by ccoenen** [comment]
activity!

**Comment by demaier** [comment]
Activity 2!

**Comment by ccoenen** [comment]
yeah... well... this is still missing as far as i can tell.

**Comment by matthew-dean** [comment]
@ccoenen @demaier Feel free to open a PR! ^_^

**Comment by seanCodes** [comment]
@matthew-dean I’d be happy to take a shot at this but I’ve never touched the codebase before so I’d need a little guidance. Would you be able to point me some files that might handle this?

**Comment by matthew-dean** [comment]
@seanCodes Let me know a time you might be on Gitter chat? https://gitter.im/less/less.js

**Comment by seanCodes** [comment]
@matthew-dean you free around 5 PM PST?

**Comment by parasg1999** [comment]
Hey, is it still up for grabs?

**Comment by matthew-dean** [comment]
@parasg1999 Currently, yes, unless @seanCodes is still into looking at it.

**Comment by seanCodes** [comment]
@parasg1999 @matthew-dean Yeah, sorry to say life got busy and I wasn’t able to make much progress on this one. ☹️ If you’re interested it’s all yours! 👍

**Comment by silverwind** [comment]
This should probably be classified as a bug, it breaks compatibility with CSS.

**Comment by jf-zens** [comment]
I’d be happy to take a shot at this but I’ve never touched the codebase before so I’d need a little guidance. Would you be able to point me some files that might handle this?

**Comment by seanCodes** [comment]
@jf-zens Based on my conversation with @matthew-dean the steps are pretty straight-forward:

1. Start with [parser.js](https://github.com/less/less.js/blob/b37922cfb2932f00d1e8b340f4799ff24a2af0f2/packages/less/src/less/parser/parser.js), and adjust the attribute parser: https://github.com/less/less.js/blob/b37922cfb2932f00d1e8b340f4799ff24a2af0f2/packages/less/src/less/parser/parser.js#L1401-L1421
2. Update the tree node ([attribute.js](https://github.com/less/less.js/blob/master/packages/less/src/less/tree/attribute.js)) to to handle the value and output it correctly
3. Add tests to verify that the case-sensitivity modifiers parse correctly

Just take care to follow the [CSS attribute-case spec](https://drafts.csswg.org/selectors-4/#attribute-case) in your implementation and you’ll be good to go. 👍🏽

**Comment by bharathks005** [comment]
Hi Team, I want to contribute this  project. Shall I start to fix this issue?

**Comment by iChenLei** [comment]
@bharathks005 PRs welcome

**Comment by bharathks005** [comment]
If I'm wrong correct me! I guess, This is the replicate issue no #3027. need to fix the case insensitively issue [I / i]
