### ISSUE TITLE
Node.js less render - configure @import paths

### ISSUE THREAD

**Issue by C1one-38** [less/less.js#3028]
Hello,
I am trying to handle less render in my node.js envirement, but I cannot specify default paths to look on `@import` directive.

In command line I can do this by `--include-path` option. Does node version has something like this?

I use `less.render(..)` method, tried to pass as options `{paths: ['mypath'] }`, but it doesn't work out

**Comment by seven-phases-max** [comment]
Make sure to set the `filename` option (w/o it Less can't know relative import paths - see #2342).
If it "does not work" with absolute path, provide more details.

**Comment by C1one-38** [comment]
Thank you, my mistake, it was an error in my code.
