### ISSUE TITLE
Double less on page

### ISSUE THREAD

**Issue by osoboopasen** [less/less.js#3030]
I made a living style switch on page. I need to add another less. How to add two less one page?

**Comment by seven-phases-max** [comment]
Note the issue tracker is primarily for issue/bug reports and feature requests. Generic "How-To"" questions are usually offtopic here (try [SO](http://stackoverflow.com/questions/tagged/less) or something).

Either way, aside from your question is a bit unclear, a generic quesswork answer is: "you add the second Less file the same way you've added the first one".

**Comment by seven-phases-max** [comment]
Closing as not an issue.
