### ISSUE TITLE
SyntaxError: Cannot set property 'parensInOp' of undefined

### ISSUE THREAD

**Issue by ampersanda** [less/less.js#3034]
I don't know what's happening but i got this error when saving LESS file in sublime text 3 which i use lessc when save LESS file

![screenshot_20170228_114346](https://cloud.githubusercontent.com/assets/13579812/23392041/a62574ec-fdab-11e6-9afb-1f74a1280cd9.png)

I tried to find and less.min.js has this, `8 matches in 1 file`

**Comment by rjgotten** [comment]
The only place where `parensInOp` is written to which is not guarded against attempting to set a property on a null/undefined value is [on line 1859 of `parser.js`](https://github.com/less/less.js/blob/49cbe520f6b38b4b8797dcba491501c0c461c7f5/lib/less/parser/parser.js#L1859) inside the `operand`  parser routine.

If I'd had to hazard a guess, I'd say the `stylesheet.css` file you're importing contains some illegal CSS used as an IE-only hack or some such, on which the parser is choking. Try directly inlining that sheet's contents without further processing by Less with `@import (inline) '../fonts/stylesheet.css'` instead.

**Comment by maulik31** [comment]
I am experiencing same issue while trying to compile theme purchased from themeforest. Were you able to address your issue and if so, how did you fix it?

**Comment by aleksey-bykov** [comment]
in my case it was invalid syntax:
```less
@wide: 300px;
div {
    width: wide; // <--- notice missing @ in font of wide
}
```
