### ISSUE TITLE
"ESPIPE ESPIPE: invalid seek, write" with gvfs

### ISSUE THREAD

**Issue by f0xacid** [less/less.js#3046]
When applying lessc on a file mounted on a gvfs filesystem (mounted through thunar) the error "Error: ESPIPE ESPIPE: invalid seek, write" occurs.

I was able to fix this by changing line 216 in the lessc binary (I don't know, where this maps to in the sources, fixing it there seems to work though) from

`fs.writeFile(output, result.css, {encoding: 'utf8'}, function (err) {`

to

`var wstream = fs.createWriteStream(output, {encoding: 'utf8', autoClose: false});`
`wstream.write(result.css, {encoding: 'utf8'}, function (err) {`

Most likely, this would also needed to be fixed in line 184 of lessc but changing it there doesn't seem to be necessary in my usecase.

My system:
OS: Arch Linux
Kernel: x86_64 Linux 4.10.6-1-ARCH
NodeJS: v7.7.3
Lessc: 2.7.2

**Comment by seven-phases-max** [comment]
Is it really a 'less` bug and not `node.js` bug? (if it's the latter I guess we should not pollute the code with version specific `node.js` bug workarounds).

**Comment by f0xacid** [comment]
Well, it seems like it might actually be a bug specific to `nodejs` as it also seems to occur in other `nodejs` products. But as my fix should also work, even if the apparent bug in `nodejs` is fixed I don't see any problems in adding the fix to `lessc`
