### ISSUE TITLE
User-level extend for import syntax?

### ISSUE THREAD

**Issue by thybzi** [less/less.js#3056]
Please tell me if LESS has any kind of API (or whatever) to extend import syntax (add one more option).

What I want in my project is the following:
```less
@import (standalone) 'foo';
```
That should do the following:
```less
@import 'foo__deps'; // if file exists
@import 'foo';
```
Of course, that seems to my some custom functionality, so I don't want to change `less.js` code itself, but make some kind of module or plugin.
Is that possible in any way?

Thank you in advance.

**Comment by seven-phases-max** [comment]
>Please tell me if LESS has any kind of API (or whatever) to extend import syntax (add one more option).

Well, you can't change *syntax* (i.e. what's handled by the parser), *however* depending on what you actually need (and you're going to handle it? plugin?) there're might be some options. After all, if it's plugin you will have to handle all the selector elements on your own anyway, so in fact any tag (or whatever) there can serve as a keyword, i.e. `extend(#foo.bar whatever)` *is* valid Less syntax hence no problem to use `whatever` tag as an option).

>`@import 'foo__deps'; // if file exists`

Again it depends on why you actually need that. When I see something like this I start to suspect something like [this](https://github.com/less/less.js/issues/1706#issuecomment-72377331). Aside of that, why, for example, can't you just have empty  'foo__deps' file there?

**Comment by calvinjuarez** [comment]
You might look at a plugin like https://github.com/less/less-plugin-npm-import as an example of how a plugin affecting `@import` behavior might work.

**Comment by thybzi** [comment]
Thank you for the example!
So, closing this issue now.
