### ISSUE TITLE
Something like less.js but compiler to CSS

### ISSUE THREAD

**Issue by lupik2** [less/less.js#3062]
Hi, how can i compile after every SAVE .less file to CSS?

**Comment by seven-phases-max** [comment]
Sorry, it's not very clear what you're asking. In telepathic mode I guess you mean something like "automatically compile Less file to CSS when you save it within some GUI editor", do you?

If so, well, there're too many options for this to list even briefly here. There a few [GUI editors](http://lesscss.org/usage/#guis-for-less) with built-in Less support, plus you can always set up a watcher (to perform any task) when somthing is saved in *any* editor (there're infinite "watch" faicilities too - starting from "big build systmes like `gulp` or `grunt` and ending with dedicated less watchers too).

---
Either way, please note that questions like this are beyond of the scope of [the issue tracker](https://github.com/less/less.js#contributing) it's not Less "community/support forum".

**Comment by seven-phases-max** [comment]
Closing as not an issue.
