### ISSUE TITLE
less watch auto compile

### ISSUE THREAD

**Issue by lupik2** [less/less.js#3063]
hi i want to use something like auto watch and compile every .less file after save.
I fount this: http://ericnish.io/blog/compile-less-files-with-grunt/

but after tap "grunt" it doesnt work for me :(

**Comment by seven-phases-max** [comment]
Yet again, please note this is not support or community forum. The issue tracker is for [issue and bug reports *only*](https://github.com/less/less.js#contributing) (as well as for feature requests). For questions like yours above appropriate resources, e.g. [SO](http://stackoverflow.com/questions/tagged/less+gruntjs).

**Comment by seven-phases-max** [comment]
Closing as not an issue.
