### ISSUE TITLE
Snap packages for Linux users

### ISSUE THREAD

**Issue by mhall119** [less/less.js#3064]
Linux users would benefit from having Snap packages of less.js/lessc available for easy installs and updates. 

Snaps are self-contained application bundles that can be installed on the most popular Linux distributions, such as Ubuntu, Debian, Fedora and Arch, without having to build separate versions for each one. They also give users immediate updates as soon as you publish a new release, without them having to manually download and unpack it.

The [Snapcraft](https://snapcraft.io/) tool makes it easy to build snaps, either from source or release tarballs. There is also a free build-hosting service at [build.snapcraft.io](https://build.snapcraft.io) that lets you setup automatic builds for every Github commit. The[ Snap Store](https://dashboard.snapcraft.io/) lets you separate these daily builds into an "edge" channel that early adopters can subscribe to, and then manually promoting official release builds into the public "stable" channel.

If anybody is interested, you can find documentation and examples on [snapcraft.io](https://snapcraft.io/) and ask questions on [forum.snapcraft.io](http://forum.snapcraft.io)

**Comment by seven-phases-max** [comment]
Closing as not an issue.
