### ISSUE TITLE
Dont work @supports with calc

### ISSUE THREAD

**Issue by Shperung** [less/less.js#3066]
Constuction dont work
`@supports (left: calc(~"-100% - 6px")) {
  .slider:before{
    width: 100%;
  }
}`

**Comment by seven-phases-max** [comment]
Less does not process any code in at-rules it has no idea of (currently it does `bubble` `@supports` like `@media` but nothing beyond that).

So the proper Less code for above would be just plain CSS - e.g. [this](http://less2css.org/#%7B%22less%22%3A%22%40supports%20(left%3Acalc(100%25%20-%206px))%20%7B%5Cn%20%20%20%20.slider%3Abefore%20%7Bwidth%3A%20100%25%7D%5Cn%7D%22%7D) (Not counting the CSS is pretty strange itself: `100%` of what?)

---
Nothing wrong in expecting `@support` to work like `@media` does but this does not come automatically - so this is basically a new feature request. (It was mentioned a few times before, e.g. in a few "contitionals" threads like #2776, then #3059 etc., but there's no dedicated ticket so I wonder if we could turn this one into `@supports should do everything @media does` and/or merge with #3059 (if `macro`-ting there moves into its own thread)).

**Comment by rjgotten** [comment]
Isn't `@supports` by its very nature going to be volatile, since its entire purpose is to test support of not yet widely adopted features? The parser for this would then need to be _extremely_ defensive so as to prevent blowing up on unknown constructs.

**Comment by seven-phases-max** [comment]
>The parser for this would then need to be extremely defensive so as to prevent blowing up on unknown constructs.

Well, as far as I understand `@supports` can't actually have any unknown *syntax* constructs, so in general it's only about unknown CSS semantics (Less does not care of at all)... So except certain edge cases (primarily when it comes to its complex logical statements) `@support` syntax is pretty straightforward.

(Which of course does not mean the implementation would be easy - ideally it'll end in refactoring `@media` code too so I seriously doubt this FR won't turn into another "never implemented ready-for-implementation" thing).

**Comment by matthew-dean** [comment]
Since the plain CSS version works (without string escaping), what exactly is needed here?

**Comment by seven-phases-max** [comment]
>what exactly is needed here?

Less basically does not evaluate anything after @supports (so any ~"" garbacgee remains unchanged). Essentially this feature is a trigger for "refactor `@supports` and `@media` implementation" (so far these are different code leafs having very few to do with each other, while ideally this should be one object/pattern with a minor conditions).
