### ISSUE TITLE
Parse error while adding comments

### ISSUE THREAD

**Issue by manojwtb** [less/less.js#3077]
I have following less code -
```less
@tableFooterTextColor: #FFFFFF; 
@categoryHeadingBackgroundColor: #d8deeb; /* sets background color for category & sub heading. */
@categoryHeadingTextColor: #000000; 
@subHeadingRowFontWeight: bold; /* sets font weight property for category heading & sub heading. By default it is set as 'bold'. You can set it as 'normal' as well. */
@tableRowBackgroundColor: #EFF2F8; 
@tableRowTextColor: #333333; 
```

and when I compile this code, I get following error- 
**The following error has been detected in your LESS CSS code: sets font weight property for category heading & sub heading. By default it is set as 'bold'. You can set it as 'normal' as well.** 

But If I remove all comments, it works OK. I don't have an idea why this is happening. 
I am using lessc 2.7.2 less compiler for node.js.

**Comment by seven-phases-max** [comment]
Please use [backticks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) to format your code.

>sets font weight property for category heading & sub heading. By default it is set as 'bold'. 

This is not a Less error (Less neither formats error messages this way nor it ever analyses property values like `bold`/`normal` like this).

**Comment by manojwtb** [comment]
Thanks for your quick response!
Yes, you're right, message is formatted for user friendliness but generally it gives error while I add comments along with less variables otherwise parse successfully. Moreover I'll try to provide the exact less error.

**Comment by seven-phases-max** [comment]
>but generally it gives error while I add comments along with less variables otherwise parse successfully

Well, the error cannot be reproduced just for the snippet you provide - [for example](http://less2css.org/#%7B%22less%22%3A%22%40tableFooterTextColor%3A%20%23FFFFFF%3B%20%5Cn%40categoryHeadingBackgroundColor%3A%20%23d8deeb%3B%20%2F*%20sets%20background%20color%20for%20category%20%26%20sub%20heading.%20*%2F%5Cn%40categoryHeadingTextColor%3A%20%23000000%3B%20%5Cn%40subHeadingRowFontWeight%3A%20bold%3B%20%2F*%20sets%20font%20weight%20property%20for%20category%20heading%20%26%20sub%20heading.%20By%20default%20it%20is%20set%20as%20'bold'.%20You%20can%20set%20it%20as%20'normal'%20as%20well.%20*%2F%5Cn%40tableRowBackgroundColor%3A%20%23EFF2F8%3B%20%5Cn%40tableRowTextColor%3A%20%23333333%3B%5Cn%5Cnfoo%20%7B%5Cn%5Ctbar%3A%20%40subHeadingRowFontWeight%3B%5Cn%7D%22%7D) - so more details needed.

**Comment by manojwtb** [comment]
Issue is fixed now , there was path issue so closing this. Thanks!
