### ISSUE TITLE
Plugin loader swallows up errors.

### ISSUE THREAD

**Issue by metasansana** [less/less.js#3081]
Try adding the following plugin to a `lessc` build (note the syntax error):

```js

function APlugin(options) {
  this.options = options;


APlugin.prototype = {

    install: function() {}, 
    setOptions: function() {},
    printUsage: function() {}
};

module.exports = APlugin

```

The error message I receive is `"Unable to load plugin APlugin.js please make sure that it is installed under or at the same level as less"`. Which is misleading, because what really takes place is this [block](https://github.com/less/less.js/blob/3.x/lib/less-node/plugin-loader.js#L78-L94) swallows up the the error syntax error.

Perhaps check the error message in each catch block and re-throw the error if It is not a module not found error? Of course that won't work if the plugin itself has a module import error.

Thanks!

**Comment by seven-phases-max** [comment]
>Perhaps check the error message in each catch block and re-throw the error if It is not a module not found error?

Mey be. Or may be not. Though everybody seems to know JS these days, Less itself is made for CSS users and some weird JS stack dump error messge may be frightenning for them (+ still hunting for "never used code" for client-side builds). Usually the kind of error you faced is caught by various tools like jshint, jscs, eslint etc.

**Comment by metasansana** [comment]
Depending on the configuration, a lint tool may not pick up for example a plugin author using JS apis that the target node version does not support yet. Errors thrown when the plugin itself tries to do an import that is not a dependency are troublesome but there would have to be some way to distinguish between the plugin missing and the plugin's dependency missing.

For the first scenario though, how about simply printing to STDERR: 'There is a problem with the plugin X , please contact the author. '?
