### ISSUE TITLE
Generate browserified version with sourcemap support in "dist"

### ISSUE THREAD

**Issue by webextensions** [less/less.js#3085]
**Use case**
I want to use "less" with sourcemap support in the browser.

**Why?**
I use it in the browser extension `Live editor for CSS and LESS` (https://github.com/webextensions/live-css-editor / https://chrome.google.com/webstore/detail/ifhikkcafabcgolfjegfcgloomalapol) via a CodeMirror based code editor to show the user the CSS selector their cursor is currently positioned at.

**My current solution**
Using this project, run the following command to generate a browserified bundle:
`$ browserify --entry index.js --outfile less.browserified.js --standalone less`
(More details at: https://github.com/webextensions/live-css-editor/blob/d9c1d173b0eb46af5a326348c004894041361397/extension/scripts/3rdparty/less.browserified.uglified.js.source.txt)

**Currently, the version under "dist" doesn't support sourcemaps.
Would it be possible to generate such a browserified version as well, in the "dist" folder?**

**Comment by matthew-dean** [comment]
I'm not following. If you are able to generate a browserify'd build that serves your needs, what is the issue? The repo is set up so that you can build Less for custom environments using custom file sources, etc.

**Comment by webextensions** [comment]
@matthew-dean 
Thanks ... I hadn't gone through all the grunt options. Now I realize that my requirement is more of a custom thing. So, I will have to build less on my own with customized versions of lib/less-node/index.js lib/less-node-environment.js.

Closing.
