### ISSUE TITLE
Netbeans - contains files with errors

### ISSUE THREAD

**Issue by egon69** [less/less.js#3089]
All affected files are in the test and lib directories. It hasn't caused any build errors so far, but it had a big fat X on the node_modules and the aforementioned folders . It's more annoying than anything to see the X, but I figured since it ended up getting flagged, you ought to know about it

**Comment by seven-phases-max** [comment]
This repo has nothing todo with Netbeans so I'm wonder what is the propose of the ticket... Could you elaborate?

**Comment by seven-phases-max** [comment]
Closing as 'wrong repo'.

**Comment by egon69** [comment]
I haven't been on in a while...what it has to do with Netbeans is that when you create a new html5 project  twitter-bootstrap is an option to template your site, but the files it acquires actually comes from this repo...or at least that was the notification that NB had given me

**Comment by egon69** [comment]
I'll try to recreate it if you like, if even interests you enough...really I don't see any site output errors. I was just using this to pass along info regarding this. some care, some don't...I drive myself nuts with errors that are more warnings that anything....I hate being a perfectionist sometimes
