### ISSUE TITLE
Trying to isolate Bootstrap by using less

### ISSUE THREAD

**Issue by Mikelee16** [less/less.js#3090]
I am following this tutorial https://formden.com/blog/isolate-bootstrap   I am using Terminal on my Mac. I have done steps 1-3.  When I try to do step 4 it says " lessc: ENOENT: no such file or directory, open '/Users/mikelee/prefix.less' ". Can anyone figure out what is going wrong or suggest a better/easier way to isolate bootstrap css? Thanks.

**Comment by seven-phases-max** [comment]
The issue tracker is not a support forum. For a questions like this consider using [SO](https://stackoverflow.com/questions/tagged/less) (counting that the basic answer to your problem is already in your Q and your need to provide more details anyway).

**Comment by seven-phases-max** [comment]
Closing as out of the issue tracker scope.
