### ISSUE TITLE
Parse error on new CSS grid property

### ISSUE THREAD

**Issue by DonCarnohan** [less/less.js#3092]
The parser seems to not like when an area label comes before a css method like minmax.

`grid-template-columns: [full-start] 1fr [content] minmax(100%, 1000px) 1fr [full-end];`

The above is the example in my code. It is correct formatting for the new CSS Grid feature. Excluding it using `~" ... "` causes the page to work. I just figured this shouldn't be necessary.

**Comment by seven-phases-max** [comment]
Not a surprise since this introduces a new grammar Less has no clue about. I'm adding "feature request" and "ready for implementation" labels with the following remark though: 
>Note the particular syntax is a CSS draft (i.e. *not a CSS yet*), they are famous for changing syntax/grammar of new features several times before TR, so when preparing the PR please be ready to maintain your code for some time (down to rewriting everything from scratch in a half of a year) - Less in its current state can't afford to support a browser developers *experiments* on a daily basis. 
(For example see #2623)

**Comment by matthew-dean** [comment]
CSS Grid is getting implemented un-prefixed in every major browser pretty much now. Support should be implemented. http://caniuse.com/#feat=css-grid
