### ISSUE TITLE
Importing LESS files from node_modules

### ISSUE THREAD

**Issue by emaildano** [less/less.js#3093]
Is this at all possible?

`@import './../node_modules/package-name/example';`

```
.
├── styles
│   ├── main.less
├── node_modules
│   ├── package-name/example.less
```

I've tried this a few times with no luck. Searching online there are packages that help solve this issue, some users throw a tilde in there but LESS seems to ignore `node_modules` completely.

Most users also recommend writing a script that copies LESS files from `node_modules` to a folder within the project which seems like a complete hack.

If it's possible what's the proper way to do this. If it's not, why?

Thanks!

**Comment by matthew-dean** [comment]
Currently no, not without a plugin. But this is being added to the eventual 3.0 release.

**Comment by matthew-dean** [comment]
In the meantime, have you looked at this? https://github.com/less/less-plugin-npm-import

**Comment by emaildano** [comment]
@matthew-dean Thanks for the update. Yes, I tried that and it threw an error. I assumed it was my config but doing a few searches online other people had issues as well so it might be the plugin. It was last updates 2 years ago..
