### ISSUE TITLE
Debugging Custom Plugins

### ISSUE THREAD

**Issue by Jscherbe** [less/less.js#3094]
I have read through the documentation and searched the internet for a method for debugging custom plugins but I haven't been able to find anything.

Is there a way to debug values within a LESS custom function?

The following is what I am trying to accomplish (plugin is the example on the LESS documentation site, with the added console.log):

(function (root, factory) { 
  if (typeof define === 'function' && define.amd) { 
     define([], factory);
    } else if (typeof module === 'object' && module.exports) { 
        module.exports = factory();
    } else { 
        (root.LESS_PLUGINS = root.LESS_PLUGINS || []).push(factory());
    } 
}(this, function () {
    // Less.js Plugin object
    return {
        install: function(less, pluginManager, functions) {
            functions.add('pi', function() {
                console.log('hello world');
                return Math.PI;
            });
        }
    };
}));

I tested both in node with "--inspect" flag and also in the browser (checking the console), but nothing is output when the function get's called from within LESS.

**Comment by matthew-dean** [comment]
@Jscherbe The 3.x branch is still in alpha, so there are a few pieces missing. Technically, though, if a plugin executes, you should be able to set breakpoints in a developer tool like Google Chrome.

**Comment by Jscherbe** [comment]
Thanks for the reply. I think I it figured out. I have a test plugin working (using the older method, passing plugin to less options). I was then able to run the node --inspect and inspect! 

Sorry for posting the issue, I felt dumb after posting, as it is not an issue but realized I couldn't remove /delete the issue myself.

**Comment by matthew-dean** [comment]
Great!
