### ISSUE TITLE
Add the functions with more simple config

### ISSUE THREAD

**Issue by lichenhao** [less/less.js#3097]
less = {
functions: {
  a  (){ return 'what ever the result is ')
}
}

// in less

b: a(); // just output b: "what ever the result is "

It's too hard to write some plugins with less ~~~

**Comment by matthew-dean** [comment]
You mean like: http://lesscss.org/usage/#using-less-in-the-browser-functions ?

😉

**Comment by matthew-dean** [comment]
Were you requesting the `functions` method that exists? Or were you suggesting a simpler return value?

**Comment by lichenhao** [comment]
What should I do with the return value? `new` what Instance ?
If there some more doc details for the extend plugins, I think  it will be more better.
Thank you for all this~
