### ISSUE TITLE
Output of interpolated selector with nested rules is different than written out

### ISSUE THREAD

**Issue by chazsolo** [less/less.js#3098]
I noticed this while playing around with selector interpolation on [less2css.org](http://less2css.org/#%7B%22less%22%3A%22%40classes%3A%20~%5C%22.a%2C%20.b%2C%20.c%5C%22%3B%5Cn%5Cn%40%7Bclasses%7D%20%7B%20%20%5Cn%20%20%2B%20.z%20%7B%5Cn%20%20%20%5Ctcolor%3A%20blue%3B%20%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn.p%2C%20.q%2C%20.r%20%7B%5Cn%20%20%2B%20.z%20%7B%5Cn%20%20%20%20color%3A%20blue%3B%5Cn%20%20%7D%5Cn%7D%22%7D) (v2.5.3):

If I use an interpolated selector with nested rules, the output is not what I expected (when compared to written out). For example, the given input:

```
@classes: ~".a, .b, .c";

@{classes} {  
  + .z {
    color: blue; 
  }
}

.p, .q, .r {
  + .z {
    color: blue;
  }
}
```

provides the following output:

```
.a, .b, .c + .z {
  color: blue;
}
.p + .z,
.q + .z,
.r + .z {
  color: blue;
}
```

Shouldn't the interpolated class output include `+ .z` for each selector instead of just the final one, `.c`?

**Comment by seven-phases-max** [comment]
No. In short `~".a, .b, .c"` is not a list of selectors. See #1421 and other issues referenced there for more details.

**Comment by seven-phases-max** [comment]
Closing as duplicate of #1546 (but the mother issue is #1421, there's also an issue somewhere with more details on possible implementations and syntax for the desired feature but I can't find it right now: todo).
