### ISSUE TITLE
less.modifyVars does not work with less-loader

### ISSUE THREAD

**Issue by zunder** [less/less.js#3100]
I am using webpack and less-loader in order to output my bundle. Providing following works:

```
use: ['less-loader?{"modifyVars":{"@my-color":"red"}}']
```

This on other hand does not:

```js
const less = require('less')

less.modifyVars({
    '@my-color': 'red'
})
less.refreshStyles()
```

But I actually need the latter one, as I would like to change the variables dynamically by user.

**Comment by deepika-Gopala** [comment]
Hi , any update on this , i have the saem requirement and the styles doesnt seems to work , problem is its not recompiling again as the reference in the browser is  text/css instead of text/less

**Comment by matthew-dean** [comment]
Wouldn't this be more of a less-loader question?

**Comment by deepika-Gopala** [comment]
Exactly , the reason why the already compiles less file is not taking the recent values and recompiling to the new style.css in the browser, it doesnt work ,  oplus the new styles that are to be reflected are authentication specific and dynamic from the api result. which we cannot call  in the webconfig.js

**Comment by seven-phases-max** [comment]
> ...
```js 
less.modifyVars({
    '@my-color': 'red'
})
less.refreshStyles()
```

Both are browser-script specific functions. In the node version the `modifyVars` stuff should be passed as an option (just like any other option/parameter see below) - for example see `lessc` code: 
* https://github.com/less/less.js/blob/v2.7.3/bin/lessc#L244
* https://github.com/less/less.js/blob/v2.7.3/bin/lessc#L481:

Technically there's no modifying/set/do-something functions in the node version at all except **the only** official [`render`](http://lesscss.org/#using-less-usage-in-code).

**Comment by lgomes2m** [comment]
@lxwbr @deepika-Gopala 
Did you guys solved this?
I have the same problem.

**Comment by naclcaleb** [comment]
Same problem here

**Comment by itayganor** [comment]
Anything?

**Comment by noasil** [comment]
Anything?

**Comment by matthew-dean** [comment]
AFAICT, this hasn't changed as this is still a `less-loader` issue, not a less issue, unless someone can demonstrate otherwise. This team does not maintain less-loader.
