### ISSUE TITLE
.LESS files stopped updating in gae-init

### ISSUE THREAD

**Issue by daspots** [less/less.js#3101]
I'm updating welcome.less but my changes don't load on the local server. 

I started with creating a new file under main/static/src/style/ called welcome.less and appended @import "welcome" in style.less

Everything was working fine, untill now. All the updates I make in welcome.less don't load anymore when I open the local server. 

Anybody knows why? 

Thanks!

**Comment by rjgotten** [comment]
Sounds more like a problem with gae-init than one with Less.

**Comment by matthew-dean** [comment]
Less won't download a new copy in the browser unless the last modified header of the root file has changed, if that's where you're executing Less.

**Comment by matthew-dean** [comment]
Closing as either expected behaviour or a problem in something other than Less.
