### ISSUE TITLE
Minor version bump of Request dependency has removed support for Node 0.x

### ISSUE THREAD

**Issue by MarkSG93** [less/less.js#3104]
https://github.com/request/request/issues/2772

request now only supports Node Version 4+ but in doing so has only bumped a _minor_ version of the package. This has caused less to pull in this new version and break some of our builds. 

Is it possible you can pin down the version of request because your package.json states that it supports >= 0.12 .

**Comment by elliottcrush** [comment]
We're also suffering from the same issue

**Comment by phlptt** [comment]
I also have the same issue :(

**Comment by RossLote** [comment]
Same here

**Comment by MarkSG93** [comment]
Closed because PR has been merged
https://github.com/less/less.js/pull/3107
