### ISSUE TITLE
 Less files keep downloading again and again and again and again and again

### ISSUE THREAD

**Issue by duckisland** [less/less.js#3109]
Warning: Total Newbie question.
Why is an existing project prompting for the .less files to be downloaded almost every second?
What is that all about? How do I turn that behavior off?

I know very little about using less. It's being used in an existing Frankenstein project and my intuition as a lifelong programmer tells me this should not be happening.

Error in console:
[Violation] 'setInterval' handler took 200ms 
[Violation] 'setInterval' handler took 192ms
for infinity

and the same .less files are downloaded repetitively.

Update - over 24 hours and no response. Did the Less developers code themselves in to a corner?

I can see now that the Less library starts out right away with the setInterval call so sure enough, the endless loop is initiated by the library: 
   function f() {
        r.env === "development" ? (r.optimization = 0,
        r.watchTimer = setInterval(function() {
            r.watchMode && g(function(e, t, n, r, i) {
                t && S(t.toCSS(), r, i.lastModified)
            })
        }, r.poll)) : r.optimization = 3
    }

This project is running from Visual Studio.NET Is the browser repeatedly downloading the .Less files because the .Less files need to be compiled and then updated anytime there is a change from the server? Should they be pre-compiled before running the project?

So much for K.I.S.S.

**Comment by rjgotten** [comment]
Your predecessor has enabled the watch mode / live reloading feature in the browser build of Less.
This causes it to periodically poll the server for (potentially) updated copies of the files.

If you don't want that feature enabled, disable it?

**Comment by duckisland** [comment]
Thanks rjGotten!
