### ISSUE TITLE
Less not exposing 

### ISSUE THREAD

**Issue by filipemir** [less/less.js#3110]
Hi! For our client-side library, we compile some of our CSS at runtime from a Less string. We ran into issues when we assembled the bundle to use within unit tests: it would throw a reference error even before any tests ran because node-browser (the entry point within the `dist` folder) expects the `window` global to be defined and doesn't expose an API for it to be passed in.

Here is the initial import I had, which worked well in the browser but failed for our test build:
```js
import Less from 'less';

export default function buildCss({ str }) {
    Less.render(str).then(() => { ... });
}
```

After some poking around I found a solution that worked both within the browser and the node, but as best as I can tell it's not properly document. Here it is:
```js
import Less from 'less/lib/less';

export default function buildCss({ str, window = global }) {
    Less(window).render(str).then(() => { ... });
}
```

The closest to documentation I found for this alternative was here: http://lesscss.org/usage/#developing-less-how-to-run-less-in-other-environments However, that `createLess` function appears to no longer be exposed. I also found it a bit surprising that there seemed to be no way to import Less in the expected way and still have it work in a unit test environment. Is this intentional?

### Error:
```bash
chimp] Running...
.../node_modules/@smarter/chimp/dist/lib/mocha/mocha-wrapper.js:86
    throw e;
    ^

ReferenceError: window is not defined
    at i (.../tmp/test/test-bundle.js:19355:17)
    at Object.<anonymous> (.../tmp/test/test-bundle.js:19373:3)
    at Object.module.exports (.../tmp/test/test-bundle.js:30222:30)
    at __webpack_require__ (.../tmp/test/test-bundle.js:20:30)
    at Object.<anonymous> (.../tmp/test/test-bundle.js:15933:63)
    at Object.<anonymous> (.../tmp/test/test-bundle.js:16335:30)
    at __webpack_require__ (.../tmp/test/test-bundle.js:20:30)
    at Object.<anonymous> (.../tmp/test/test-bundle.js:13209:94)
    at Object.<anonymous> (.../tmp/test/test-bundle.js:13985:30)
    at __webpack_require__ (.../tmp/test/test-bundle.js:20:30)
    at Object.__webpack_exports__.a (.../tmp/test/test-bundle.js:4865:88)
    at __webpack_require__ (.../tmp/test/test-bundle.js:20:30)
    at Object.<anonymous> (.../tmp/test/test-bundle.js:32538:18)
    at __webpack_require__ (.../tmp/test/test-bundle.js:20:30)
    at .../tmp/test/test-bundle.js:66:18
    at Object.<anonymous> (.../tmp/test/test-bundle.js:69:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
Mocha failed
```

**Comment by matthew-dean** [comment]
I'm not getting the issue here. If you run the client-side build not in a client, yes it will fail because `window` is not exposed. It's designed to run in a browser. If you import in Node, then it shouldn't throw that error, and you can run tests against the Node version.

**Comment by filipemir** [comment]
If I can avoid it, I would rather not be importing different builds for my tests, which strikes me as an unnecessary indirection. I find it surprising that a statement as innocuous as `import Less from 'less';` would prevent any of my tests from running. This is not an issue I've had with any with other libraries, I suspect because in most cases it is easily avoidable by not using the `window` object directly (especially not within the code that executes immediately upon import) but instead using a variable defined by an optional parameter that defaults to `global`. And in fact you do seem to expose a way to define the global environment. Why not expose such an option by default in the browser build? If that is not an option, I'd imagine it would be worthwhile to at least update the documentation above so that it accurately reflects the functionality that already exists.

**Comment by matthew-dean** [comment]
Okay, well feel free to make a PR. If all tests still pass, then it should be fine.

**Comment by duclet** [comment]
Isn't `import 'less';` supposed to figure out whether or not the code is running in a browser context versus the node context? If it is, then I do feel like there is some invalid code happening for it to run in a browser context even though it is node. If the main less export doesn't do that detection and it assumes imports are in a browser context, then that seems a little weird for node. The main "index" file should be for node and using the "browser" properly should be used for the browser.

**Comment by matthew-dean** [comment]
> Isn't import 'less'; supposed to figure out whether or not the code is running in a browser context versus the node context?

No, that's not how NPM module resolution works. Although that depends on what's doing the module resolution. If it's not Node, and some other mechanism, like a transpiler, then it would depend on the transpilation settings.

In short, for Less, the NPM module resolution imports less-node. Separately, there's a build process manually run for releases that compiles a browser version that imports less-browser and puts those releases into `dist/`.

In the example given, the OP says they are using less-browser in a Node context. Not sure why that would be.

**Comment by duclet** [comment]
From what I'm reading, it seems like the author is importing `less` and expecting it to return `less-node` but it is returning `less-browser` while in Node's context.

**Comment by Kelly-Bramford** [comment]
@duclet yes that is whats what happening
