### ISSUE TITLE
Failed call to function registry

### ISSUE THREAD

**Issue by pierre-arlaud** [less/less.js#3112]
Consider following code:

```javascript
var less = require('less');
var src = `
@file: ext();
@import '@{file}';
`;

less.functions.functionRegistry.add('ext', () => new less.tree.Anonymous('file'));
less.render(src, {}, (error, output) => {
    if (error) return console.log(error.stack);
    console.log(output);
});
```

Provided "file.less" exists, this code compiles in less 2.4.0 and does include "file.less".
For any newer version however, I'm getting the following:

> TypeError: Cannot read property 'get' of undefined
>     at new functionCaller (C:\Users\pgarlaud\tmp\less\node_modules\less\lib\less\functions\function-caller.js:9:51)
>     at Node.Call.eval (C:\Users\pgarlaud\tmp\less\node_modules\less\lib\less\tree\call.js:32:30)
>     at Node.Expression.eval (C:\Users\pgarlaud\tmp\less\node_modules\less\lib\less\tree\expression.js:31:37)
>     …

**Comment by matthew-dean** [comment]
Which Less version does this apply to?

**Comment by pierre-arlaud** [comment]
@matthew-dean I've see it fail on 2.5.0, 2.5.1, 2.6.0, 2.6.1, 3.0.0-pre.1 and I just checked the bug is also occuring on 3.0.0-alpha.3.

As I said, I believe the 2.4.0 is the last version where the given test case works.

Thank you for your concern.

**Comment by matthew-dean** [comment]
Fixed. Will be in next alpha release.
