### ISSUE TITLE
TypeError: pluginLoader.tryLoadPlugin is not a function 

### ISSUE THREAD

**Issue by ztkIsAlreadyTaken** [less/less.js#3116]
at /usr/local/node/lib/node_modules/less/bin/lessc:327:22

when I use 'lessc init.less --clean-css"--s1 --advanced"'.

lessc version 3.0.0
less-plugin-clean-css version 2.1.0

**Comment by ztkIsAlreadyTaken** [comment]
the 2.7.2 version is ok.

**Comment by Alastair-Spencer** [comment]
Can confirm it's an issue with version 3. `2.7.2` seems to work fine for me when downgrading.
