### ISSUE TITLE
Version 3.0.0-alpha.3 is published to npm under the "latest" dist-tag

### ISSUE THREAD

**Issue by vp2177** [less/less.js#3123]
The latest stable version seems to be `2.7.2`, but `3.0.0-alpha.2` is published to the `npm` registry as `next`, even though `3.0.0-alpha.3` is already available, and `3.0.0-alpha.3` is published as `latest`, even though that is the version used by default (i.e. `npm install less`), and should point to the **latest stable** version, currently `2.7.2`.

You can rectify this using the [`npm dist-tag`](https://docs.npmjs.com/cli/dist-tag) command

**Comment by matthew-dean** [comment]
Crap, that is a mistake.

**Comment by robhuzzey** [comment]
^ Oh... this is what caused me to find a bug in v3 as I'd just done `npm install less` thinking it was the stable version :/ (so a small win really)

**Comment by matthew-dean** [comment]
@robhuzzey Well finding bugs is great, but it was unintended.
@seven-phases-max Do you have time to fix this? I probably won't until tomorrow evening. Or anyone else on @less/core ?

**Comment by matthew-dean** [comment]
Tags are now fixed. `3.0.0-alpha.4` is published under `next` and `2.7.3` is pushed to `latest`.
