### ISSUE TITLE
How to write a less-to-less transformer?

### ISSUE THREAD

**Issue by rulatir** [less/less.js#3132]
I need to write a less-to-less transformer to recursively inline all locally resolvable `@import`s. Can this be done as a plugin, or must I fork less.js?

I am trying to implement fast in-browser preview powered by `modifyVars()` without refactoring a huge LESS codebase that was originally developed for command line compilation and uses custom file managers that can't be easily implemented in browser.

**Comment by seven-phases-max** [comment]
It's possible with a plugin but that would be very suboptimal and dramatically tedious. The problem that you'll have to render the internal AST format back to Less code and there's *nothing* in the compiler code-base to help you with that (the compiler is built around AST->CSS conversion)
It would be much easier if you simply parse your input files for imports with some regexs and perform basic string-based substitutions.

**Comment by seven-phases-max** [comment]
Closing in favour of #2428 (see my comment there too).
