### ISSUE TITLE
Question: how to access the file managers functionality from within a visitor plugin?

### ISSUE THREAD

**Issue by rulatir** [less/less.js#3136]
I need to reconstruct some less source from the AST, and for that I need to be able to use the exact same file manager setup that was used to parse the source. How do I go about obtaining/constructing all the parameters that `less.environment.getFileManager()` requires?

I have a `currentFileInfo` object from an AST node and it provides `filename` and `currentDirectory`, but I still need the `options`/`context` object and I seem to be running into a dependency hell while trying to construct it. This seems to indicate that I am doing it wrong.

What is the right way to do it?

**Comment by seven-phases-max** [comment]
Hmm, I'm not sure about details but for the root object `options` is just the compiler options (see `lessc` code) and context should be empty (or resolving to the root object itself if it's not handled that way there already). Basically a context is the "current scope" thing (and for the root one it's basically the root ruleset itself, while for the nested rulesets it also includes parent rulesets).
I'm afraid I'm not of much help in this regard as when it comes to such dark areas my source of information is the same as yours (just the source-code).

**Comment by seven-phases-max** [comment]
(fixing wrong label - well, 'documentation' would also make sense in a perfect world but I don't think anyone is going to ever document continiuosly changing thing. So I did really mean just 'question').

**Comment by rjgotten** [comment]
Given a `context` and a `currentFileInfo` a file at `filePath` can be loaded via:

```js
function loadFile( filePath, context, currentFileInfo ) {
  var
    environment      = context.pluginManager.less.environment,
    currentDirectory = currentFileInfo.relativeUrls
      ? currentFileInfo.currentDirectory
      : currentFileInfo.entryPath,
    fileManager,
    fileSync;

  fileManager = environment.getFileManager(
    filePath, currentDirectory, context, environment, true 
  );
  if ( fileManager != null ) {
    fileSync = fileManager.loadFileSync(
      filePath, currentDirectory, context, environment
    );
    return String( fileSync.contents );
  }

  return null;
}
```

This also works for user-defined functions added via `@plugin` plugins, btw. (You can access `this.context` and `this.currentFileInfo` inside the function body.)
