### ISSUE TITLE
calc() in between percentage and pixels

### ISSUE THREAD

**Issue by luisgizirian** [less/less.js#3137]
When i.e.

* `width: calc(25% - 20px)` get's pre processed, results in a .css containing `width: calc(5%)`

The spec allows for px to be added or taken from the percentage calculation result. But these are getting mixed and mistakenly deduced. So, the process spits out a modified result.

**Comment by seven-phases-max** [comment]
See #2837.

**Comment by seven-phases-max** [comment]
Closing as expected behaviour (and in favour of #1880).
