### ISSUE TITLE
Parser does not record start index for MixinDefinition

### ISSUE THREAD

**Issue by rulatir** [less/less.js#3138]
The parser does not record the start index in a `Definition` node (`node.type === "MixinDefinition"`). The index key is absent in the node, and set to `undefined` in both the `Selector` node at `node.selectors[0]` and the `Element` node at `node.selectors[0].elements[0]`.

This makes it impossible to determine where the mixin definition begins in the source, which is necessary for selective source reconstruction.

Sample Less code that causes the issue:

```
.font-handwrite() {
  font-family: @handwrite-font;
}
```

**Comment by seven-phases-max** [comment]
Yes, [it does not](https://github.com/seven-phases-max/less-plugin-lists/blob/v1.1.1/lib/for.js#L194-L197) (So I adding the FR label). 
But regardless of the issue I start to suspect there's something wrong in your approach of "reconstructing".. Honestly  I can't see how exactly the source file/index info can affect the location (or anything at all) of the mixin definition (or any other Less object) in the reconstructed text, the location should *solely* be determined by the index of the object within parent object rules (or rulesets?) array.
So... how exactly are you using the source file/index info in you code and what for? And what do you mean by "*selective* reconstruction"?

**Comment by rulatir** [comment]
Selective reconstruction: inlining local `@import`s, dumping anything else as is.

I use `index`es to maintain a walking range of file offsets as I traverse a ruleset, and combined with currentFileInfo this **almost** lets reconstruct interesting parts of the input simply by cutting substrings from sources. Even with all the challenges this entails (e.g. implementing `loadFileSync()` in our custom file manager so I can re-obtain the input), this approach is still orders of magnitude simpler than a thorough grammar-driven unparser that would need to encapsulate a small bit of knowledge for **every** AST node type.

Unfortunately this approach trips on nodes that don't record the start index. At least all nodes that can be direct children of a ruleset should record it.

**Comment by seven-phases-max** [comment]
This simply wrong. If you decided to use the AST for reconstruction (remember I told you not to) then you should use the AST and not some kind of guesswork-text-copy-cut-paste based on the debugging info. (The debugging /friendly-error-reporting info *may* not present in the AST at all. We barely decide to remove such info as it's required for sourcemaps, but its format is a subject for changes ans it's not part of an the plugin API in anyway. In fact personally I have some plans for its major refactoring as the way it is now is deadly inefficient).

**Comment by rulatir** [comment]
Now that's a bummer. Can you offer any advice based on inside knowledge on how to simplify writing a full unparser in closer to a day than a month? I **will** have to do it, since I **principally refuse** to write the inliner using regex hackery when a complete parser is available.

**Comment by seven-phases-max** [comment]
>closer to a day than a month?

Using AST It's impossible even for "close to a week".

>It would be much easier if you simply parse your input files for imports with some regexs and perform basic string-based substitutions.

Why do you think I wrote *much easier* there? Just out of fun? Yet again, Less is not a parsing library. It does include a parser, but this parser (and the AST it produces) has been developed for years with one and *the only* one goal: "evaluate Less statements entities and produce CSS.

> I principally refuse to write the inliner using regex hackery when a complete parser is available.

Then prepare for weeks (if not months) months of inventing kludges and workarounds around the thing you're trying  to use for something it was never assumed to be used for. Sure one or two simple regexes to catch `@import "file";` statements are times more complicated...

**Comment by rulatir** [comment]
Variable interpolation. I read that it is supported in `@import` statements, therefore I *will* have to support it in the inliner. And suddenly there's much more to it than one or two simple regexes.

**Comment by matthew-dean** [comment]
Just as a side note - some of the issues with indexes not being assigned to nodes I addressed while refactoring the `3.x` branch. It's just something I came across during that work, and it also was part of the work of improving the `@plugin` syntax, so that newly-created nodes (I think) inherited the start index of whatever they were replacing. But I have no doubt that the parser might have pieces of inaccuracy in indexing. @rulatir Are you testing against `2.x` or `3.x`?

Either way, despite the narrow use case, I think we would accept PRs which correct any source mapping errors, as long as doing so wouldn't have an impact on parsing / evaluation performance. AFAIK, source mapping and accurate indexing don't have solid tests (or tests at all?) in the Less `test/` files. If a MixinDefinition isn't granted a start index during parsing, that's an oversight / error. All of the (root-level) nodes are supposed to be assigned a start index. Some of the sub-nodes, like parts of expressions may not have them.

**Comment by rulatir** [comment]
Thank you @matthew-dean. I decided to go the unparser way after all. It isn't as hard as I and @seven-phases-max feared. I'm running it against our project's less for now, but later I will need input with as good AST coverage  as possible - will I find it in the test directory?

**Comment by seven-phases-max** [comment]
>Variable interpolation. 

It may also have `reference` option.. And then (just like with "variable interpolation") the generated all-in-one file is no longer an exact equivalent of the original. It will produce different result as soon as one of this variables is affected and/or when you put or not put (un)referenced rulesets in... There're more things (like `inline` etc.). So if you imagine you're in process of developing some generic/reusable solution - no, you are not.

**Comment by seven-phases-max** [comment]
Closing as implemented (`MixinDefinition` is indexed in `v3` if I'm not mistaken).

**Comment by matthew-dean** [comment]
@seven-phases-max It is not. I didn't change it. See: https://github.com/less/less.js/blob/master/lib/less/tree/mixin-definition.js#L9

**Comment by seven-phases-max** [comment]
OK, so I just restore `slate` label.
