### ISSUE TITLE
Less is merging ::selection styles preventing them to work properly

### ISSUE THREAD

**Issue by Topograph** [less/less.js#3140]
I had a hard time figuring this out. Less compiles the following
`
::selection {
    background: @darkgreen;
}
::-moz-selection {
    background: @darkgreen;
}
::-webkit-selection {
    background: @darkgreen;
}`
to
`::selection,
::-moz-selection,
::-webkit-selection {
  background: #6f7e2d
}`

this outcome will be ignored by browsers because:

> When browsers find a part of a select they don't understand, they drop the entire thing, so this will fail all the time. ([Source](https://css-tricks.com/almanac/selectors/s/selection/))

**Comment by seven-phases-max** [comment]
Less [never](http://less2css.org/#%7B%22less%22%3A%22%40darkgreen%3A%20foo%3B%5Cn%3A%3Aselection%20%7Bbackground%3A%20%40darkgreen%7D%20%5Cn%3A%3A-moz-selection%20%7Bbackground%3A%20%40darkgreen%7D%20%5Cn%3A%3A-webkit-selection%20%7Bbackground%3A%20%40darkgreen%7D%22%7D) does this kind of merging. Ever. So it's most likely some other tool (css-minifier?) in your build-chain (or something wrong elsewhere).

**Comment by Topograph** [comment]
ohh...you're right! it was a sneaky little minifier that was integrated in our internal tools. thanks you :)
