### ISSUE TITLE
When compress is true, "flex: 1 0 0px;" gets output as "flex: 1 0 0;", which doesn't work in IE11

### ISSUE THREAD

**Issue by distinctdan** [less/less.js#3141]
The flex property in IE11 only supports numbers with units for the basis property of "flex". When compress removes the px value from 0px, it breaks it.

**Comment by seven-phases-max** [comment]
The "compress" option is [deprecated](http://lesscss.org/usage/#command-line-usage-compress) more than [two years ago](https://github.com/less/less.js/blob/v2.7.3/CHANGELOG.md#220).

**Comment by seven-phases-max** [comment]
Closing as not applicable.
