### ISSUE TITLE
Omitting parent selector

### ISSUE THREAD

**Issue by Satheeskumar-1989** [less/less.js#3143]
Hi Folks,

I ran into a strange requirement in less selectors and I am not aware whether any selector already available to meet our requirement. Can anyone to help me out?
Requirement: Is there any selector to omit the parent class as we include the parent using ampersand?
**Example Scenario**:

**Actual Parent Selector**:

Less | CSS
-- | --
`&.f-js {      &.f-spreadsheet {        display:   none     }                   .f-spreadsheet {                                  display:   none;                   }   }` | `.f-js.f-spreadsheet   {     display: none;   }   .f-js .f-spreadsheet   {     display: none;   }`

**Expected Selector**:

Less | CSS
-- | --
`&.f-js {                   &.f-spreadsheet {                                  display:   none                   }                   (any-selector).f-spreadsheet {                                  display:   none;                   }   }`|  `.f-js.f-spreadsheet   {     display: none;   }    .f-spreadsheet {     display: none;   }` 

Let me know if you need any further details.

Thanks,
Sathish

**Comment by Satheeskumar-1989** [comment]
Thanks for your update.
Is there any way to achieve the below in CSS,

Less | Expected CSS
-- | --
.one, .two {    &1.three {     display:   none     } &2.four {     display:   none;  }} | .one.three {     display: none;   }   .two.four {     display: none;   }

**Comment by seven-phases-max** [comment]
>Is there any way to achieve the below in CSS,

No. It's basically the same example as the initial one. In summary: in Less if you have something as a nesting-parent selector (be it a single entity or a list of selectors item) - you will get this as part of the resulting selector one way or another. There's no workarounds, no hacks, nothing that can overcome this.

**Comment by rjgotten** [comment]
> nothing that can overcome this.

well... technically you could write a plugin function that manipulates the selector output.
But that would be horridly complicated to write correctly. ;)
