### ISSUE TITLE
Lessc error with nested calc()

### ISSUE THREAD

**Issue by turnerhayes** [less/less.js#3149]
I'm trying to compile Bootstrap's CSS with lessc and getting the following error:

Bootstrap version: `4.0.0-beta.3`
Lessc version: `lessc 2.7.3 (Less Compiler) [JavaScript]`

```
$ lessc node_modules/bootstrap/dist/css/bootstrap.css
OperationError: Operation on an invalid type in [project directory]/node_modules/bootstrap/dist/css/bootstrap.css on line 3719, column 3:
3718   display: block;
3719   height: calc(calc(2.25rem + 2px) - 1px * 2);
3720   padding: 0.375rem 0.75rem;
```

Seems to be objecting to the nested `calc()`. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/calc), this is valid syntax (although I read on SO that that clarification was added in the past year or two, so maybe lessc was correct at some point).

**Comment by seven-phases-max** [comment]
See http://lesscss.org/usage/#command-line-usage-strict-math.

**Comment by seven-phases-max** [comment]
Closing in favour of #1880.

**Comment by turnerhayes** [comment]
That seemed to work, but shouldn't `lessc` accept any valid CSS without flags?

**Comment by seven-phases-max** [comment]
> but shouldn't lessc accept any valid CSS without flags?

The default `--strict-math=on` will break too much legacy code (for more details see #1880, #974 etc.).

**Comment by turnerhayes** [comment]
I guess I don't really understand why nested `calc()`s can't be passed through as is, rather than being regarded as something to (potentially) calculate during compilation.

**Comment by matthew-dean** [comment]
@turnerhayes This works in 3.x.
