### ISSUE TITLE
Mangles #RGBA colors when compress = true

### ISSUE THREAD

**Issue by Svish** [less/less.js#3153]
**less:** v2.7.3
**less-loader:** v4.0.5
**node:** v8.9.3
**os:** Microsoft Windows [Version 10.0.16299.125]

**input:**
```less
background: #0001;
border-color: transparent transparent #0005 transparent;
border-color: #0005 transparent transparent transparent;

```

**output with `compress=false`:**
```css
background:#0001;
border-color:transparent transparent #0005;
border-color:#0005 transparent transparent;
```

**output with `compress=true`:**
```css
background:background:#0001 1;
border-color:transparent transparent #0005 5;
border-color:#0005 5 transparent transparent;
```

Maybe related to #1013? Not sure what is meant by "support" in that issue, but for now it would at least be nice if the value was left alone rather than being weirdly converted from `#RGBA` to `#RGBA A`...

**Comment by seven-phases-max** [comment]
The "compress" option is [deprecated](http://lesscss.org/usage/#command-line-usage-compress) more than [two years ago](https://github.com/less/less.js/blob/v2.7.3/CHANGELOG.md#220).

**Comment by seven-phases-max** [comment]
Closing as not applicable.
