### ISSUE TITLE
Less-Calc-CSS3 Vars wont compress

### ISSUE THREAD

**Issue by florianschommertz** [less/less.js#3155]
Quick, short summary:
Less-Calc-CSS3 Vars compress to empty string
example:
:root { --hs:20px; }
border-radius: ~"calc(var(--hs)*(0.6))";

Expected results:
border-radius: calc(var(--hs)*(0.6));
Actual results:
Renders to nothing if compression is activated

**Comment by seven-phases-max** [comment]
The "compress" option is [deprecated](http://lesscss.org/usage/#command-line-usage-compress) more than [two years ago](https://github.com/less/less.js/blob/v2.7.3/CHANGELOG.md#220).

**Comment by seven-phases-max** [comment]
Closing as not applicable.
