### ISSUE TITLE
element as variable

### ISSUE THREAD

**Issue by olton** [less/less.js#3156]
Is it possible to add a similar structure?
**Mixin**:
```
.hideElemet(el){
    @{el} {
    ...
    }
}
```

**Use**:
```
.class {
    .hideElement(input);
}
```
 Now this causes an error: No matching definition was found for `.hideElement(input)` in filename.less
Thanks

**Comment by seven-phases-max** [comment]
See [Parametric Mixins](http://lesscss.org/features/#mixins-parametric-feature). I.e. should be:
```less
.hideElemet(@el) {
    @{el} {
        ...
    }
}

**Comment by seven-phases-max** [comment]
Closing as not an issue.
