### ISSUE TITLE
font-face @import force http protocol

### ISSUE THREAD

**Issue by zapatoche** [less/less.js#3157]
Hi there

We have encountered and issue with google font import on some of our sites.

`@import url('//fonts.googleapis.com/css?family=Montserrat:300,600');`

When calling the font resource without protocol to be able to  serve it over http or https , the less compiler adds the http protocol to the url, which block the resource from loading on https servers.

Is there a way to force the less compiler to preserve the url string as it is?

Cheers

**Comment by seven-phases-max** [comment]
Are you sure it's Less compiler (and not something else in your build-chain for example) modifying the url? Under normal circumstances it's not supposed to touch the statement at all ([example](http://lesscss.org/less-preview/#%7B%22less%22%3A%22%40import%20url('%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DMontserrat%3A300%2C600')%3B%22%7D)). So more details are needed.

**Comment by zapatoche** [comment]
Interesting, We use gulp to process the styles. 

I'm going to have to check if it comes from one of the plugins then:

~~~
var gulp = require('gulp');
var less = require('gulp-less');
var watch = require('gulp-watch');
var prefix = require('gulp-autoprefixer');
var plumber = require('gulp-plumber');
var minifycss = require('gulp-minify-css');
~~~

Cheers

**Comment by zapatoche** [comment]
Yep right, it's gulp-minify-css the culprit!!!

Sorry for the bother
