### ISSUE TITLE
File not found when @import relative path;

### ISSUE THREAD

**Issue by DongShelton** [less/less.js#3166]
I am using less api to develop some plugin, but there is a problem when I using less to render.
This is my project example:
```
project
│
└───src
│   │   index.less
│   └───less
│       │   header.less
│   
└───test
    │   index.ts
```
And this is my index.less file:
```less
@import './less/header.less';

.index-body {
    color: green;
}
```
And this is my header.less file
```less
.index-header {
    color: red;
}
```
And this is my index.ts file
```typescript
import * as less from 'less';
import * as fs from 'fs';
import * as path from 'path';

const content = fs.readFileSync(path.resolve(__dirname, '..', 'src', 'index.less'));
const rs = less.render(content.toString());
rs.then((value: any) => {
  console.log(value);
}, (err: any) => {
  console.log(err);
});
```
When run this file, it would cause error: 
```shell
'./less/header.less' wasn't found. Tried - ./less/header.less,less/header.less
```
But if change the import path from relative path to absolute path, it would works.
```less
/* @import './less/header.less'; */
@import '/Users/shelton/Documents/FrondEnd/rollup-demo/src/less/header.less';
```

**Comment by seven-phases-max** [comment]
See the docs, http://lesscss.org/usage/#programmatic-usage:
>If you wanted to render a file, you would first read it into a string (to pass to `less.render`) and then set the `filename` field on options to be the filename of the main file. Less will handle all the processing of the imports.

For more details see https://github.com/less/less.js/issues/2717#issuecomment-151711749.

**Comment by seven-phases-max** [comment]
Closing as not an issue.

**Comment by wKich** [comment]
Hello. I think it would be better if your provide list of options that `render` accepts.
