### ISSUE TITLE
Old request dependency with old depencies wich have vulnerabilities

### ISSUE THREAD

**Issue by Kartoffelsalat** [less/less.js#3169]
The Less Npm Module uses request in version 2.81.0 wich is using an old hawk module, wich is using hoek versoin 2.16.3 wich has the following [nodesecurity]( https://nodesecurity.io/advisories/566) vulnerability.

Updating request to 2.83.0 should solve this.

**Comment by matthew-dean** [comment]
Can you make a PR?

**Comment by seven-phases-max** [comment]
https://help.github.com/articles/creating-a-pull-request/

Well, in the simplest case GitHub will automatically the fork things for you when you edit when you [edit and save](github.com/less/less.js/edit/master/package.json) the file(s) of interest right through web-interface.

**Comment by Kartoffelsalat** [comment]
Not sure if it was correct to update the versions last digit, if not change it back.

**Comment by Kartoffelsalat** [comment]
Can you state a date when there will be a new Tag with this update available?

**Comment by seven-phases-max** [comment]
No idea, sorry (e.g. see https://github.com/less/less-meta/issues/26).

**Comment by seven-phases-max** [comment]
Closing as done in #3177.
