### ISSUE TITLE
Can we extend hidden classes?

### ISSUE THREAD

**Issue by blachawk** [less/less.js#3171]
Can we extend hidden classes, this way our CSS file is optimized even further?  The best visual example I can give you is the following....

```
.processor() {
width:100px;
height:50px;
}
.ps3 {
&:extend(.processor)
}
.xbox {
&:extend(.processor)
}
```

There is really no need for me to add .processor {} as a CSS selector to my rule set in the compiled output. I simply want the following results...

```
.ps3,
.xbox {
width:100px;
height:50px;
}

```

Thanks for any creative ideas

**Comment by seven-phases-max** [comment]
See #1177. But currently - no, we can't. There's a hacky workaround though: move the `.processor` thing to a separate file imported with `(reference)`.

**Comment by seven-phases-max** [comment]
Closing as dupicate of #1177.
