### ISSUE TITLE
lessc can't find plugins when not in cwd(?)

### ISSUE THREAD

**Issue by Franziskus1988** [less/less.js#3181]
I have encountered a weird behaviour. When I use the less command line tool with a path it doesn't detect that the css-clean plugin is installed. Whereas when I use it in the folder where the node_modules are placed it works. See image:

![grafik](https://user-images.githubusercontent.com/5774027/36715999-0b339330-1b99-11e8-8ffe-6ee7fbaaeb8e.png)

**Comment by seven-phases-max** [comment]
Does this happen only with the `clean-css` plugin or ...?

**Comment by Franziskus1988** [comment]
![grafik](https://user-images.githubusercontent.com/5774027/36777237-125cbbb6-1c69-11e8-9f85-951a4f2cdfc4.png)

Seems to be plugin independant.

**Comment by mikekasprzak** [comment]
I just started getting the above autoprefix error myself. I haven't touched my code in weeks.

**Comment by twiginteractive** [comment]
Bug was introduced in v3.x, so I had to downgrade to less 2.7.3

**Comment by mikekasprzak** [comment]
I _just_ made the same discovery and fix. I didn't notice 3.x was out due to how the Releases page looked.

![screenshot from 2018-03-06 13-59-28](https://user-images.githubusercontent.com/1570313/37052224-ab5e011c-2146-11e8-81fe-a6f3d81de50d.png)

**Comment by WraithKenny** [comment]
@seven-phases-max it seems to be all plugins

**Comment by luccasxds** [comment]
I was in version 3.0.1 and it is not working. Just do this to solve.
See your lessc version:

lessc -v

after that enter:

npm install less@2.7.1 -g

**Comment by Franziskus1988** [comment]
@seven-phases-max Any plan to fix this?

**Comment by matthew-dean** [comment]
@Franziskus1988 If you or anyone else would like to submit a PR for this, that would be welcome.

**Comment by Franziskus1988** [comment]
@matthew-dean I've tried to fix it. Unfortunatelly the "failing import" test is failing. I don't know if there is a more convenient way to find the root folder of the node_modules installation. The test is now failing because I'm using a path which is relative to the less-node/index.js script position. In a node installation it works, but in the test enviroment it resolves to the wrong location.

**Comment by Franziskus1988** [comment]
I think the problem is that process.cwd()/node_modules is added as path, although it should point to the node_modules folder of the less installation. Since process.cwd() always resolves to the current location in terminal the plugins, which are installed in the same package as less aren't found.

**Comment by matthew-dean** [comment]
@Franziskus1988 Please see #3200.
