### ISSUE TITLE
Request dependency causes security risk

### ISSUE THREAD

**Issue by lyndsey-ferguson** [less/less.js#3184]
We are seeing security issues related to a vulnerability in `request` due to it's reliance on `hawk` which uses the vulnerable `hoek`. I am opening up this issue so that when `request` updates to v7.x.x of `hawk`, `less` can be updated. 

`less@3.0.0` > `request@2.83.0` > `hawk@6.0.2 > hoek@4.2.0`

https://nodesecurity.io/advisories/566
https://hackerone.com/reports/310439

**Comment by seven-phases-max** [comment]
Please just create a PR when this happens.

**Comment by lyndsey-ferguson** [comment]
I'll keep my eye out for it and create that PR

**Comment by seven-phases-max** [comment]
Closing to not keep thing piling up.

**Comment by lyndsey-ferguson** [comment]
I personally would prefer to keep this open and resolve the ticket once this future PR is merged. People finding this issue would then see it open and not create another one.

**Comment by seven-phases-max** [comment]
Could be or could be not. So far nothing can be done at the Less side so this is not even an issue at this repo.

**Comment by hughns** [comment]
@seven-phases-max The dependency on request was updated in https://github.com/less/less.js/commit/bd2a93f7b9879b0c3fff29d7904512eedffa1f72#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 which brings in a non-vulnerable version. However, `less@3.0.2` has yet to be released in npm form. Is there a plan to release this to npm?

**Comment by matthew-dean** [comment]
@hughns If this addresses the plugin issue, then this can be published soon - https://github.com/less/less.js/pull/3200. Just waiting on review from @seven-phases-max. More collaborators for Less are always welcome!
