### ISSUE TITLE
Imports are not updated when recompiling via the same (?) less object

### ISSUE THREAD

**Issue by xinglie** [less/less.js#3185]
bug report
I write a compile tool for my project, it depend less.

my project style folder and files likes
``` bash
- styles
   _utils.less
   index.less
```

and `index.less`　content is
```less
@import "./utils"
```
I use less api to compile the less files like

```js
let less=require('less');
//....
less.render(indexContent,options,(err,result)=>{
       console.log(result.css)
});
```

when i change `_utils.less`　content , the above code will automatically execute

but since 3.0.x , when i change `_utils.less` content ,the `result.css` is the first time result, whatever change how many times.

but 2.7.x is ok, when i change `_utils.less` content ,the `result.css` also changed.

**Comment by seven-phases-max** [comment]
Sounds similar to https://github.com/stevelacy/gulp-less/issues/283.
I guess in a these "auto-watch" cases it's *the same* Less object used to compile each update, right? Then I guess it's something with not reseting some imports cache between different `render` calls or something like that.

**Comment by xinglie** [comment]
@seven-phases-max yes,use ***the same*** Less object to compile each update.
i am not use gulp-less tool, i use less api directly .
it seems less cache the result and not update correctly

**Comment by seven-phases-max** [comment]
So the quick workaround (until the bug is fied) in your case wil be in:
```js
require('less').render(indexContent,options,(err,result)=>{
       console.log(result.css)
});
```

**Comment by shobhitsharma** [comment]
Yes, it seems the issue lies in this commit where the calltree is manipulated based on arguments https://github.com/less/less.js/commit/a48c24c4dd3c13e00a20ece80323768496a96b36#diff-a6b31db4e862654ae597161e441689bb

**Comment by seven-phases-max** [comment]
Hmm, honestly I can't see anything that could affect imports... Pretty mysterious.

**Comment by tiodot** [comment]
In Node environment, manual clear less compile cached file:
```
const less = require('less');
const fileManagers = less.environment && less.environment.fileManagers || [];
fileManagers.forEach(fileManager => {
     if (fileManager.contents) {
               fileManager.contents = {};
     }
});
```

**Comment by TigersWay** [comment]
Thanks @tiodot it seems to be working so far... But hope we'll get a "cleaner" way soon!

**Comment by matthew-dean** [comment]
It might have something to do with these lines added for 3.0.  https://github.com/less/less.js/blob/master/lib/less/tree/mixin-definition.js#L9

Try removing the specific if/else to just the else statement and see if the problem still happens. If it doesn't, this optimization may need to be removed. However, what would be more ideal is clearing the file manager or any internal cache per new parse/render call.

**Comment by stevelacy** [comment]
Just checking if there are any updates for this issue? 
gulp-less is getting quite a few developers hitting this.

**Comment by TigersWay** [comment]
Just gave another try a few hours ago and it seemed to be working fine (without patch). Anyone else?
```
  "dependencies": {
    "browser-sync": "^2.24.4",
    "gulp": "^4.0.0",
    "gulp-autoprefixer": "^5.0.0",
    "gulp-clean-css": "^3.9.4",
    "gulp-hb": "^7.0.1",
    "gulp-less": "^4.0.0",
    "gulp-load-plugins": "^1.5.0",
    "gulp-rename": "^1.2.2"
  },
  "optionalDependencies": {
    "less": "^3.0.4"
  }
```

**Comment by hawkerboy7** [comment]
I have the same issue descibed by @xinglie upgrading from 2.7.3.

The workaround provided by @tiodot did not seem to work for me (tried: less@3.0.0 and less@3.0.4).
Also using the `require('less').render()` workaround provided by @seven-phases-max didn't do the trick :(
Are there maybe more suggestions? :)

**Comment by xvilo** [comment]
Also affected with this :(

**Comment by hawkerboy7** [comment]
Hi, though I am not sure what I did differently the workaround @tiodot provided DOES work for me now!
I tried it again and I must have made a mistake somewhere in the code.
(using less@3.0.4).
Thanks @tiodot !

**Comment by matthew-dean** [comment]
@tiodot  @hawkerboy7 @TigersWay Does this branch resolve the issue? If so, I'll make a PR - please check this out - https://github.com/matthew-dean/less.js/commits/cache-modified

**Comment by TigersWay** [comment]
Just did checks in 2 clearly different projects, commenting out @tiodot great patch inside package.json, and it seems to be working perfectly!!
```
  "optionalDependencies": {
    "less": "github:matthew-dean/less.js#cache-modified"
  },
```

**Comment by nexces** [comment]
@matthew-dean works for me!

**Comment by hawkerboy7** [comment]
@matthew-dean Yes it has resolved the issue! PR to the rescue!! :)

**Comment by matthew-dean** [comment]
@tiodot @hawkerboy7 @TigersWay Cool, the nice thing is, you should get slightly faster Less compiling with a warm cache (a 3.x feature), so it's preferable to have it fixed; otherwise I would have suggested taking it out. Will do a PR.
