### ISSUE TITLE
How do I get js to pass variable values to less?

### ISSUE THREAD

**Issue by wwqvincent** [less/less.js#3186]
How do I get js to pass variable values to less?

**Comment by seven-phases-max** [comment]
Pass them via `modifyVars` option (exact usage depends on how you actually "use less in js").

---
Note the issue tracker is not a support forum or Q/A portal. If you have a generic question "How Do I" questions use dedicated resources, e.g. [SO](https://stackoverflow.com/questions/tagged/less).

**Comment by seven-phases-max** [comment]
Closing as not an issue.
