### ISSUE TITLE
Can we still maintain a 2.x branch?

### ISSUE THREAD

**Issue by Justineo** [less/less.js#3204]
2 &rarr; 3 introduced breaking changes and some people may still have to stuck with 2.x for some time. Can we still maintain a `2.x` branch and release more 2.x versions to fix security vulnerabilities inside dependencies (by just updating `package.json`)? eg. `2.7.3` had fixed the version of `request` to `2.81.0` which depend on a risky `hoek@4.2.1`. We may just need to update `request` to `2.82.0`.

**Comment by seven-phases-max** [comment]
You can always create a fork I suppose. This is how the things are supposed to work in a perfect open-source minded world (fork fork fork) - strange they never do in reality.

**Comment by Justineo** [comment]
In case I got you wrong, I'm willing to help if the suggestion is acceptable and owners are to help updating npm packages, not to tell me to publish my own `less` package.

**Comment by seven-phases-max** [comment]
You are ignoring the fact that there's nearly zero efforts in shallow copying such fork back here and then releasing it under "the official" credential (so user don't even notice anything).
 
But, you know... I just suspect that in:
>Can we still maintain...
By `we` you  mean ... who exactly? And when things will go wrong and users come here complaining about issues who would be "responsible for response"? Maintenance is the main problem (obviously changing one or two characters in `package.js` is not).

**Comment by matthew-dean** [comment]
> 2 → 3 introduced breaking changes and some people may still have to stuck with 2.x for some time. 

Which breaking changes?

**Comment by matthew-dean** [comment]
As to the general question of doing a 2.x future release, if someone wants to maintain that, I'd have nothing against that. It's more publishing / maintenance work, so I'd love if someone wants to be added as an NPM publisher. I'm still waiting for someone else to take on that role.

**Comment by matz3** [comment]
We are having the same issue, but with v1.

We are (unfortunately) still using v1.6.3 which has a (potential) security vulnerability, which is now showing up quite prominent with the new npm client (see [npm audit](https://docs.npmjs.com/getting-started/about-audit-reports)).
An upgrade to v3 isn't possible right now as we have several projects relying on that old version and it won't be that easy to migrate, so this will take us quite some time. I think even upgrading to v1.7.5 (which anyway has the same vulnerability) isn't that easy.

Also here, an update within the `package.json` would be sufficient:
`"mime": "1.2.x"` => `"mime": "^1.4.1"`

See https://github.com/SAP/less-openui5/issues/25

**Comment by matthew-dean** [comment]
@matz3 There haven't been that many backwards-incompatible changes over the years. Have you tried upgrading?

**Comment by matthew-dean** [comment]
Less doesn't really have enough maintainers at the moment to properly maintain a current release, let alone two separate major releases, so I think this issue should be closed as something we can't really do without more contributors.

**Comment by matthew-dean** [comment]
Closing as won't fix.
