### ISSUE TITLE
Variable Interpolation Error

### ISSUE THREAD

**Issue by idsbllp** [less/less.js#3210]
1.Now I get an error when I use `Variable Interpolation` with Less:

    .loopElipsis(@i) when (@i > 0) {
      .loopElipsis((@i - 1));
      animation: 'type@{i}' 1s linear infinite;
      // some code...
    }

it will compile to: 

    animation: 'type1' 1s linear infinite;
    animation: 'type2' 1s linear infinite;
    ...

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/YJwwz.png

2.but this code in chrome isn't working correctly, then I change my code like this:

    .loopElipsis(@i) when (@i > 0) {
      .loopElipsis((@i - 1));
      animation: type@{i} 1s linear infinite;
      // some code...
    }

> Unrecognised input. Possibly missing opening '{'

3.I get an error,oh no, another retry: 

    .loopElipsis(@i) when (@i > 0) {
      .loopElipsis((@i - 1));
      animation: type@i 1s linear infinite;
      // some code...
    }

It compiles like this:

    animation: type 1 1s linear infinite;
    animation: type 2 1s linear infinite;
    ...

I am using

    "less": "^2.7.2",
    "less-loader": "^4.0.5",
    "webpack": "^2.6.1",

Is there any solutions with this issue?

**Comment by seven-phases-max** [comment]
See [escaping](http://lesscss.org/#escaping).

**Comment by seven-phases-max** [comment]
Closing as expected behaviour.
