### ISSUE TITLE
Less not working on mobile browser

### ISSUE THREAD

**Issue by peddimanoj** [less/less.js#3211]
<link rel="stylesheet/less" href="css/styles.less" type="text/css" /> working on desktops but not working on mobile browser.  styles.less not loading on mobiles anybody please guide me how to fix this.

**Comment by seven-phases-max** [comment]
See ["Browser Support"](https://github.com/seven-phases-max/less-docs/blob/master/content/usage/browser-support.md).

**Comment by seven-phases-max** [comment]
Closing as not an issue (firing the corresponding docs issue though: https://github.com/less/less-docs/issues/481).
