### ISSUE TITLE
Aspect ratio fraction is being converted to a number

### ISSUE THREAD

**Issue by bendytree** [less/less.js#3225]
On less `3.0.4` it is converting the aspect ratio in media queries to a number:

    // Less 3.0.4
    @media (max-aspect-ratio: 1/2) {
      .foo { color:red; }
    }

    // CSS
    @media (max-aspect-ratio: 0.5) {
      .foo { color: red; }
    }

For whatever reason, this ratio [is supposed to be a fraction](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/aspect-ratio) and not a number. So it's currently broken on Chrome, etc. [Here's an example](http://ecomfe.github.io/est/fiddle/#est=false&code=QG1lZGlhIChtYXgtYXNwZWN0LXJhdGlvOiAxLzIpIHsKICAuZm9vIHsKICAgIGNvbG9yOnJlZDsKICB9Cn0K)

--------------------------------------------------------

For anyone having this issue, escaping is a good workaround:

    @media (max-aspect-ratio: ~"1/2") {
      .foo { color:red; }
    }

**Comment by seven-phases-max** [comment]
Yes, this is expected behaviour after 3.x turned `@media` to conform the strict-math option behavior (to unify with arithmetics handling in other contexts - #1480).

"What to do with `/`" and related things are discussed at #1880.

**Comment by seven-phases-max** [comment]
Closing in favour of #1880.
