### ISSUE TITLE
How can I use Math.Random in browser?

### ISSUE THREAD

**Issue by lilirg** [less/less.js#3226]
like this:
`@version:random(0,100);`

**Comment by seven-phases-max** [comment]
[Like this](http://lesscss.org/less-preview/#%7B%22less%22%3A%22%5Cnfoo%20%7B%5Cn%5Ct%40x%3A%20%60Math.random()%60%3B%5Cn%20%20%20%20a%3A%20%40x%3B%5Cn%20%20%20%20b%3A%20%40x%3B%5Cn%7D%5Cn%22%7D) for example.

**Comment by seven-phases-max** [comment]
Closing as not an issue.

**Comment by lilirg** [comment]
TKS.
`javascriptEnabled: true`
