### ISSUE TITLE
Add real-world Less libs to tests

### ISSUE THREAD

**Issue by matthew-dean** [less/less.js#3231]
While Less has hundreds of tests, sometimes real-world Less libraries do things that are unexpected, which breaks them with new releases - https://github.com/ant-design/ant-design/issues/7850#issuecomment-399904195

It wouldn't be too much work to pull a few popular Less libs (via NPM) and add them to the testing suite, especially since `@import` can pull from NPM by default (in Node) in 3.0+.

**Comment by Jogai** [comment]
Same with https://github.com/less/less.js/issues/3268. Its about bootstrap 3, I imagine its quite a lot used still.

Maybe include some listed here: https://github.com/LucasBassetti/awesome-less#readme Probably the more experimental libraries have more edge cases.

**Comment by Jogai** [comment]
Yeah, no problem. Maybe add it to the readme under 'more information'?
