### ISSUE TITLE
Import less code into wrapper

### ISSUE THREAD

**Issue by gibbsfromncis** [less/less.js#3232]
Hey all, 

I'm working on themes support for my project and in general my idea was like this:

**darkTheme.less**
```
body.darkTheme {
  @import "~library/style.less";

  @primary-color: #000;
}
```

But it doesn't work on this case:

**library/style.less**
```
.libraryPrefix-collapse {
  background: blue;
  & > &-item {
    background: red;
  }
}
```

Because in result I see the following code:
**output.css**
```
body.dark .libraryPrefix-collapse {
  background: blue;
}
body.dark .libraryPrefix-collapse > body.dark .libraryPrefix-collapse-item {
  background: red;
}

```

Can you please advice something that may help on this case. I've read all LESS docs and issues like that but no luck. Maybe there may be used some trick or can you add some specific symbol that will help to use parent selector only for the first-level children like: 
```
body.darkTheme % {
  @import "~library/style.less";

  @primary-color: #000;
}
```

I found some issues on stackoverflow & your repo like this which mention this case but no one provides solution. I wouldn't post issue there is I had this issue with my local project only. But I'm trying to work on theming for vendor library and unfortunately I cannot touch its LESS code.

**Comment by gibbsfromncis** [comment]
All answers for tickets like mine was:
> It works as designed 

And I agree that. I do not try to report bug. I want to know how people like me can handle the case described above because it's really useful for theming.

**Comment by calvinjuarez** [comment]
I tend to process the imported file on its own, then import the processed CSS inline.  Depending on what you're using to compile your Less, there are a number of ways to automate it.

So,

### First

*library/style.less*
```less
.libraryPrefix-collapse {
  background: blue;
  & > &-item {
    background: red;
  }
}
```
outputs *library/style.css*
```css
.libraryPrefix-collapse {
  background: blue;
}
.libraryPrefix-collapse > .libraryPrefix-collapse-item {
  background: red;
}
```

### Then

*darkTheme.less*
```less
body.darkTheme {
  @import (inline) "~library/style.css";

  @primary-color: #000; // note that Less vars use `@`, not `$`.
}
```
*output.css*
```
body.darkTheme .libraryPrefix-collapse {
  background: blue;
}
body.darkTheme .libraryPrefix-collapse > .libraryPrefix-collapse-item {
  background: red;
}
```

Now, if you're theming the library, this won't help as much, but there are ways around that, too.  For example, put all your variables in a separate file (_variables.less_) and then you can import those variables in both the library styles _and_ in your theme stylesheet.

**Comment by gibbsfromncis** [comment]
@calvinjuarez Thanks for your answer. I appreciate your help. I had hope to do not do it... Did you find solution how to automate it with webpack in dev/prod? Maybe can you advise some plugins/loaders for it?
 
For now I see only one solution to move compiled themes files to separate repo and then add it as npm dependency but it would be much better to keep all under the same repo...

**Comment by gibbsfromncis** [comment]
Btw. If somebody try to find simple solution for Webpack (but this doesn't cover all cases) I have used this solution:

(for dev config)
```
{
   "loader":"string-replace-loader",
   "options":{
      "multiple":[
         {
            "search":"([^a-zA-Z}][ ])body\\.darkTheme",
            "replace":"$1",
            "flags":"g"
         },
         {
         // another theme prefix add there
         }
}
```
(and for prod config)
```
{
   "loader":"string-replace-loader",
   "options":{
      "multiple":[
         {
            "search":"([^}])(body.darkTheme)",
            "replace":"$1",
            "flags":"g"
         },
         {
         // another theme prefix add there
         }
      ]
   }
}
```

I've used `string-replace-loader` to remove wrong usages of wrapper class name from minified css code (prod config) and not minified (dev config). 

if you want you can merge this 2 RegExps into one. If was just fast-handed solution

**Comment by calvinjuarez** [comment]
@gibbsfromncis  Thanks for sharing your solution!  If this is a strong enough use case for you a Less plugin could be a great way to accomplish what you need, and I'm sure others would appreciate having that tool available!

**Comment by gibbsfromncis** [comment]
@calvinjuarez what do you mean about Less plugin? I've never heard about Less plugins

**Comment by matthew-dean** [comment]
@gibbsfromncis See: http://lesscss.org/features/#plugin-atrules-feature . 😁

**Comment by gibbsfromncis** [comment]
@matthew-dean @calvinjuarez I'm already working on plugin to do it. Just reused npm-import plugin. It looks like less.render doesn't support `javascriptEnabled` option:
```
less.render(
    fs.readFileSync(path.resolve(__dirname, src)).toString(),
    {
      filename         : path.resolve(__dirname, src),
      javascriptEnabled: true,
      plugins          : [new LessImprortCompilePlugin()]
    }, function (e, data) {

    });
``` 

Unfortunately I can't find any docs regarding node less and its parameters. Can you redirect me in the right way please?

**Comment by rjgotten** [comment]
@matthew-dean 
@calvinjuarez 
@gibbsfromncis 

Sounds like what's needed here is functionality to reflect on the current selector and then extract the right-hand key from it, like so:

```less

.libraryPrefix-collapse {
  @selector: selector();
  @key-class: rh-key(@selector);

  background: blue;

  & > @{key-class}-item {
    background: red;
  }
}
```

I.e. this is https://github.com/less/less.js/issues/3053

**Comment by matthew-dean** [comment]
@rjgotten I'm actually still confused what the issue is.

After all, the statement that the following "doesn't work" doesn't make sense.
```less
body.darkTheme {
  @import "~library/style.less";

  $primary-color: #000;
}
```
@gibbsfromncis
There's not enough information about `library/style.less` to make it clear what should happen, but doesn't. And obviously `$primary-color` is not a Less variable. So without clarification of the issue, I'm not sure there's an issue to address or respond to. It's just not clear what you're trying to accomplish.

**Comment by matthew-dean** [comment]
🤔 

Hmmmm..... @gibbsfromncis Honestly it just feels like you're taking the wrong approach for theme files. 

For example:

> In output I'll have 2 different css files for each theme and I'll include this 2 files into my project. When user wants to change theme from dark to blue or vise versa I'll just replace "class name" of body from "darkTheme" to "lightTheme".

Why have the top class in there at all? Why not generate both files and just have instructions for one of them to be used? You're right that if you include it at the base, it will be added to every child selector.

My question is, if you DON'T want it to be added to every child selector in the root, how are you expecting a body class to actually be applied? You are correct that I still don't understand what you are trying to achieve. Based also on the feedback from @rjgotten, I think probably this is not a Less issue?

**Comment by gibbsfromncis** [comment]
@matthew-dean partially you're right. It's real to compile separate themes files and include them into project when you need without using specific parent selector. But it's a little bit hard to configure a build system to do what you said. I saw issues like mine beginning from 2016 year and till now and that's why I came there to discuss ability to support cases like mine on less compiler level. But if you think it's much effort for non common case you can close it. 

I've solved my issue by compiling sources twice. First time I compile them by using command line tools to get built of library styles with my applied colors and the second time my Webpack compile files like:
```
body.darkTheme{
  @import (less) "dark-theme-build.css"
}
```

I just had hope to get an ability to solve my issue on Less compiler level instead of reconfiguring my build system with some tricks.

**Comment by nruhe** [comment]
Just want to add that I'm also in the same boat as @gibbsfromncis and I'm having to resolve it the same way.

**Comment by atvilelas** [comment]
@gibbsfromncis  and @nruhe I made a simple plugin that allows you to use multiple ant design themes at the same time.

https://github.com/atvilelas/antd-theming-engine

It might generate larger css, but you can easily split that up with WebPack and load them as need. This is for development only right now. I wanted something that worked consistently without feeling like I was hacking it too much.

My next steps will be performance and clean up improvements.
