### ISSUE TITLE
Plugin method install() runs before setOptions()

### ISSUE THREAD

**Issue by calvinjuarez** [less/less.js#3233]
This breaks plugins like [less-plugin-autoprefix](https://github.com/less/less-plugin-autoprefix) in Less v3.x.

# Test Plugin
_less-plugin-test/index.js_ in global _node_modules_:
```js
module.exports = {
	install: function (less, pluginManager) {
		console.group('running install()')
		console.log('this.options:', this.options)
		console.groupEnd()
	},
	setOptions: function(options) {
		console.group('running setOptions()')
		this.options = options
		console.log('this.options:', this.options)
		console.groupEnd()
	},
}
```

# Less 2.x
```
npm i -g less@2 && lessc --test="test" empty.less
```
Result:
```
running setOptions()
  this.options: test
running install()
  this.options: test
```

# Less 3.x (including 3.5.0-beta)
```
npm i -g less@3.5.0-beta && lessc --test="test" empty.less
```
Result:
```
running install()
  this.options: undefined
running setOptions()
  this.options: test
```

**Comment by calvinjuarez** [comment]
Might be related to #3187.

**Comment by matthew-dean** [comment]
🤔 

Oh. I guess I didn't understand this as a previous behavior when refactoring. How can a plugin have options set before it's installed? Install seems intuitively like the first option.

**Comment by matthew-dean** [comment]
@calvinjuarez Here's another argument against the opposite order - https://github.com/less/less.js/blob/master/lib/less/environment/abstract-plugin-loader.js#L40

Historically, Less plugins were essentially registered and called once, run either directly before or after code (so called "pre-" or "post-" processing plugins).

However, now you can have this:

```
.foo {
  @plugin (options=foo) "my-plugin";
}
.bar {
   @plugin (options=bar) "my-plugin";
}
```
So, here, we definitely call `setOptions` twice, but `install()` can only be called once. It's called once on first-load, when the plugin is registered. So, as a necessity, the second call will always call `setOptions()` after `install()`, no matter what. So switching the order for the first one could lead to unexpected behavior. 

So I'm inclined to say that the current behavior is the correct approach. Although it may have been a breaking change. If you want a function that will _always_ run after setOptions, that would be the new `use()` method.

**Comment by calvinjuarez** [comment]
The only reason for it is that the plugins we're currently boosting everywhere depend on the old behavior.  3.x was a breaking release, though, but we should make sure we update, for example, [less-plugin-autoprefix](https://github.com/less/less-plugin-autoprefix) to work (currently it does not).  I'm already updating it to use the latest Autoprefixer and PostCSS (see https://github.com/less/less-plugin-autoprefix/pull/34), so I can update it to the install is init, setOptions is config paradigm.  We'll wanna be sure other plugins we boost in official spaces are updated as well, where necessary.

**Comment by matthew-dean** [comment]
@calvinjuarez  Ah, yeah I'm looking right now at https://github.com/less/less-plugin-autoprefix/blob/master/lib/index.js#L12

I think tests I added only check that the plugin is called; I can't think of a way to write a test that the options were received by the plugin.

🤔 

The only way I can think of handling this is calling `setOptions()` twice? Before and after first install, and then only after subsequent calls? As a back-compat measure? I'm just wondering if there would be any side effects from anyone expecting `setOptions` to run once. Thoughts?

For the following code, based on the way `less-plugin-autoprefix` is written, an autoprefixer would only be created once, which is probably correct. (Hence the new `use()` method.)
```less
@plugin (option=1) "autoprefix";
@plugin (option=2) "autoprefix";
```

**Comment by matthew-dean** [comment]
Alternatively, maybe it SHOULD run before first `install()` only? It all depends on what the user expects I guess.

**Comment by matthew-dean** [comment]
@calvinjuarez Possible fix for this on this branch - https://github.com/matthew-dean/less.js/tree/bugfix-3187 - browser tests currently failing tho.

**Comment by matthew-dean** [comment]
Tests passing.

**Comment by calvinjuarez** [comment]
Hot, I'll test this.  Yeah, I'm not sure what the best thing to do would be.  I think `setOptions()` before `install()` the first time would be good.  I haven't worked extensively with plugins, so I'm not the most qualified, but it seems like that's kind of the option we've got, if its important to support existing plugins.

Maybe we can check the minimum version of the plugin and run `setOptions()` first for those?  Then plugins for 3.x don't need to perpetuate the old behavior, but we're supporting backwards?  Is that unrealistic?

**Comment by calvinjuarez** [comment]
Yup, this fixes less-plugin-autoprefix.  I'm gonna quick look into maybe only doing the double-run for plugins with minimum version < 3, but I don't think this should wait for that, since it's possibly getting in the way of people's workflows.

**Comment by matthew-dean** [comment]
Okay, I merged, so I'll close this.

**Comment by calvinjuarez** [comment]
Lol, just now seeing you merged 3 days ago.  Thanks for being patient with me.  :P
