### ISSUE TITLE
Issue with variable followed by parentheses

### ISSUE THREAD

**Issue by dfung** [less/less.js#3266]
In 3.0.4, the following example seems to work, but now fails in 3.5:
```
@jumbotron-padding: 30px;

.q {
  padding: @jumbotron-padding (@jumbotron-padding/2);
}
```

The issue seems to be related to the variable name having a dash in it.

**Comment by superheri** [comment]
I have the same problem on my side

**Comment by matthew-dean** [comment]
Confirmed. This is error introduced in 3.5.0 where parsing thinks `@var (` is a variable call `@var()`. Not sure why this wasn't covered in tests, but will be now. Pushing fix.
