### ISSUE TITLE
IE8 hack not parseable in less 3.5

### ISSUE THREAD

**Issue by Jogai** [less/less.js#3268]
Bootstrap 3 contains a hack for ie8 (see https://github.com/twbs/bootstrap/blob/v3-dev/less/carousel.less#L204)

``background-color: #000 \9;

Less 3.5 on windows 10 gives this error:

> ../Content/Styles/Backend/Admin.less
  111:13  error  Module build failed (from ../node_modules/css-loader/index.js):
                 ModuleBuildError: Module build failed (from
     // set alpha../node_modules/less-loader/dist/cjs.js):
     background-color: #000cy for the best results possible.
       inised input       ^
                 c:\project\node_modules\bootstrap\less\carousel.less
                 (line 204, column 27)     at runLoaders
                 (~\AppData\Roaming\npm\node_modules\webpack\lib\NormalModule.js:
                 at
                 ~\AppData\Roaming\npm\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:364:11

**Comment by matthew-dean** [comment]
Does this compile on previous versions (3.0)?

**Comment by Jogai** [comment]
Yes, I was at 3.0.4.

**Comment by matthew-dean** [comment]
Confirmed. I tried to narrow down why one passes and the other doesn't, but I haven't been able to figure it out yet. I don't see where support for escaping currently (previously) happens in the parser.

**Comment by matthew-dean** [comment]
@Jogai Please try latest release (v 3.5.2). Re-open if you still have an issue.

**Comment by aleen42** [comment]
Fix quite fast, @matthew-dean well done 👍 .

**Comment by matthew-dean** [comment]
@aleen42 Verified fixed for you?

**Comment by aleen42** [comment]
@matthew-dean verified.!

**Comment by matthew-dean** [comment]
@aleen42 Hooray! Sorry about the hiccup on this release!

**Comment by Jogai** [comment]
Verified! Thanks for the fast response!
