### ISSUE TITLE
`--math` AKA align strict math behavior with documentation.

### ISSUE THREAD

**Issue by calvinjuarez** [less/less.js#3273]
Per a gitter discussion:

```--math=(always|no-division|parens|strict|strict-legacy)```
```-m=...```

`always`:
- `height: (5px + 5px) + 2px;` → `height: 12px;`
- `width: 10px + 1;` → `width: 11px;`
- `width: (10px + 1);` → `width: 11px;`
- `font: 16 / 4;` → `font: 4;`
- `font: (16 / 4);` → `font: 4;`

`no-division`:
- `height: (5px + 5px) + 2px;` → `height: 12px;`
- `width: 10px + 1;` → `width: 11px;`
- `width: (10px + 1);` → `width: 11px;`
- `font: 16 / 4;` → `font: 16 / 4;`
- `font: (16 / 4);` → `font: 4;`

`parens` AND `strict`:
- `height: (5px + 5px) + 2px;` → `height: 10px + 2px;`
- `width: 10px + 1;` → `width: 10px + 1;`
- `width: (10px + 1);` → `width: 11px;`
- `font: 16 / 4;` → `font: 16 / 4;`
- `font: (16 / 4);` → `font: 4;`

`strict-legacy`:
- `height: (5px + 5px) + 2px;` → `height: (5px + 5px) + 2px;`
- `width: 10px + 1;` → `width: 10px + 1;`
- `width: (10px + 1);` → `width: 11px;`
- `font: 16 / 4;` → `font: 16 / 4;`
- `font: (16 / 4);` → `font: 4;`

### Some Questions to Consider:

What about `calc()`?

**Comment by matthew-dean** [comment]
@calvinjuarez  I went with `parens-all` and `parens-division` - see PR - https://github.com/less/less.js/pull/3274

**Comment by matthew-dean** [comment]
Closing just so we can keep the discussion about naming in one place (in PR)
