### ISSUE TITLE
[Up For Grabs] Improve Less parser for VSCode and other IDEs

### ISSUE THREAD

**Issue by matthew-dean** [less/less.js#3277]
VSCode implements a Less parser in Language Server Protocol, which is also used by a number of other IDEs. (LSP is documented here - https://microsoft.github.io/language-server-protocol/specification). The code as it is used in VSCode is here: https://github.com/Microsoft/vscode-css-languageservice/tree/master/src/parser

The Less parser in LSP could definitely be improved, which would help out people using Less. Anyone interested in making their development life easier and the lives of others easier is welcome to take it on! 

Related issue in VSCode - https://github.com/Microsoft/vscode/issues/43087

**Comment by matthew-dean** [comment]
Note, I'm working with @bd82 on documenting the Less grammar, so ping me if you would need grammar help.

**Comment by matthew-dean** [comment]
VSCode PR here: https://github.com/Microsoft/vscode-css-languageservice/pull/135

**Comment by kevinramharak** [comment]
I think this was closed and shipped in august? https://github.com/microsoft/vscode-css-languageservice/commit/3df5c700437cdea8cb2681efd15bb7eba619c187.

**Comment by matthew-dean** [comment]
@kevinramharak Correct! Thanks for reminding me.
