### ISSUE TITLE
How to locate the location of less source quickly when nesting of less is used

### ISSUE THREAD

**Issue by Taisen1991** [less/less.js#3287]
I want to modify the style of an element, but it is hard to locate the location of this element less because I used nested less.
![image](https://user-images.githubusercontent.com/24730038/42685804-9adf9f86-86c6-11e8-8f96-0dfeb0838425.png)
then click 
![image](https://user-images.githubusercontent.com/24730038/42685913-ecbb7578-86c6-11e8-9d4c-45c48b28e5b9.png)
but it is not what i want
![image](https://user-images.githubusercontent.com/24730038/42686076-6a3c9838-86c7-11e8-9692-9e636a291c1e.png)
anyone has solutions?
Forgive me，my English is not good!

**Comment by rjgotten** [comment]
source maps.

**Comment by Taisen1991** [comment]
ok got it! thank you for your answer!

**Comment by wufeng87** [comment]
@rjgotten  Could I do it programmatically without sourcemap?  Here is the detail question: https://github.com/less/less.js/discussions/3775
Thanks.
