### ISSUE TITLE
3.8.0 '../lib/less/math-constants' -> '../lib/less/constants' rename breaks semver

### ISSUE THREAD

**Issue by ojab** [less/less.js#3295]
As can be seen in https://github.com/ant-design/ant-design/issues/11417 — 3.7.1 -> 3.8.0 update breaks real world packages, so it should be named 4.0.0 and this change should be reverted for 3.x branch.

**Comment by matthew-dean** [comment]
@anantoghosh Thanks for tracking that down! That was a confusing bug report.

**Comment by anantoghosh** [comment]
For people who are facing this issue:

- Remove less from your project
- Remove all the less packages from yarn cache
- Add the latest less again
- Verify with `yarn check`

**Comment by ojab** [comment]
Thanks! I've assumed that `math-constants` is used somewhere in antd & it's rename have caused an issue.
Sorry for the confusion.
