### ISSUE TITLE
rootpath option prepends absolute system path in Git Bash

### ISSUE THREAD

**Issue by enepomnyaschih** [less/less.js#3296]
We use shell files to build the application. One step involves less files compilation. It works perfectly in Linux environment, however, in Windows, running these files via Git Bash has unexpected results.

**input.less**

```
.a {
	background: url('logo.png');
}
```

**Shell command:**

```
lessc --rootpath=/ input.less output.css
```

**Actual result**

```
.a {
  background: url('C:/Program Files/Git/logo.png');
}
```

**Expected result**

```
.a {
  background: url('/logo.png');
}
```

The issue can be reproduced only if you run this command in Git Bash. Running it in cmd works fine, however, we don't want to implement a corresponding set of bat files to carry our build process.

**Comment by rjgotten** [comment]
afaict at no point does Less run the passed in `--rootpath` option through any kind of normalization that would result in the full disk path.

Rootpath is literally just a string path segment that is pre-pended on all paths after they've been rewritten by relative url rewriting.

Is Git Bash itself maybe doing something weird, like auto-expanding `/` as a hack to deal with feeding unix-y rooted paths to Win32 executables?

**Comment by enepomnyaschih** [comment]
You are right, this explains what happens http://www.mingw.org/wiki/Posix_path_conversion

Double slash is not a good solution, because the modified shell scripts won't work in Linux environment anymore. I've decided to rewrite the whole thing in NodeJS using less as a library.

Thank you
