### ISSUE TITLE
If define a class style inside an id, it won't work with browser rendering less

### ISSUE THREAD

**Issue by freewind** [less/less.js#3298]
Sample code:

### index.html

```
<html>
<head>
    <link href="/index.less" rel="stylesheet">
    <script src="./node_modules/less/dist/less.js"></script>
</head>
<body>

<div class="hello1">
    [hello1] I have a expected border
</div>

<div id="main">
    <div class="hello2">
        [hello2] where is my border?
    </div>
</div>

</body>
</html>
```

### index.css

```
#main {
    .hello2 {
        border: 3px solid blue;
    }
}

.hello1 {
    border: 3px solid red;
}
```

Page:

![image](https://user-images.githubusercontent.com/333781/43402488-6cb9e878-9445-11e8-8301-6f36778f8ee3.png)

Complete demo here: <https://github.com/css-demos/css-lesscss-class-inside-id-no-effect-demo>

**Comment by matthew-dean** [comment]
There's something wrong with your path to the JavaScript file, so Less isn't actually running in this instance. Therefore it's only applying the rule that is valid CSS.  See a working version here: https://codepen.io/matthewdean/pen/gjvNer

**Comment by matthew-dean** [comment]
Closing.
