### ISSUE TITLE
i try send size "14px" but it dont work

### ISSUE THREAD

**Issue by gwmaster** [less/less.js#3304]
you can try it:
https://bitbucket.org/gwmaster_gwm/multiprojectstarter/src/master/

run project on 
starterProject:start
press on
Open Theme Manager
and then
@card-padding-base 20px

**Comment by rjgotten** [comment]
How about hosting the example yourself, rather than requiring people to `git clone` and set up locally?
And maybe provide a reduced test-case which shows that this is an actual problem with Less and not with your own application doing something wrong?

**Comment by gwmaster** [comment]
AntTheme.js run
  window.less.modifyVars(vars)
http://gwmaster.byethost32.com/starterProject/
