### ISSUE TITLE
Problems resolving relative paths, while compiling less programatically.

### ISSUE THREAD

**Issue by migrachev** [less/less.js#3308]
I identified two problems with **less.render** while trying to use **less.js** programatically in order to compile my projects' **CSS**. For sake of simplicity and to ease the discussion here I created an example [repo](https://github.com/migrachev/less-problem) to isolate only the problems that I am having. To set up the repo - **_clone and npm install_**. In order to run the code that invokes **less.render** programatically - **_npm run lessify_**

**[My goal] to compile less/index.less into index.css and having correct relative url paths in the result index.css**

**[Problem 1] less.options.paths acts differently when supplied with relative or absolute path**
In **/js/lessify.js** alternate between
````js
{
    paths:["../less"],
    relativeUrls: true
}
````
And
````js
{
    paths:[path.resolve(__dirname, "../less")],
    relativeUrls: true
}
````
And invoke **npm run lessify**. In the first case the compilation will end with errors, in the second the compilation will succeed. Is there any reason why absolute paths and relative paths should act differently in less options? To me that seems not intuitive and incorrect. My expectations in the given example were that the compilation should fail in both of the cases. According to less.js documentation in **options.paths** we provide additional import resolition paths. Therefor regardless if we provide the less directory by its relative or absolute path, we should not be able to resolve the inner.less file!

**[Problem 2] When supplied with absolute path, options.path will disregard relativeUrls option and the compilation will result in full paths in the output CSS**
To see that use the second **options.path** configuration above and see the resulting index.css in the root directory of the project. In its content you should see the **_url_** statements to point to a full path on your machine. In my case: (As you can see I am using Windows)
````sh
.refer-inner-img {
  background-image: url("C:/Users/m.igrachev/Desktop/New folder/less-problem/img/github-logo.png");
}
.refer-img {
  background-image: url("C:/Users/m.igrachev/Desktop/New folder/less-problem/img/github-logo.png");
}
.rule {
  width: 100%;
}
````
As I indend to further **npm publish** this result css, having full paths in it is unacceptable to me. Also it seems strange to supply **_options.relativeUrls_** and get full urls in the end result.

**Comment by rjgotten** [comment]
> When supplied with absolute path, options.path will disregard relativeUrls option and the compilation will result in full paths in the output CSS

It doesn't disregard the `relativeUrls` option.

Your example code uses URLs for `.refer-inner-img` and `.refer-img` that walk back up to parent directories. Those are being resolved relative to the component less files, indicating that the `relativeUrls` option is being honored. Were it not honored, the paths would be resolved against the entry point less file instead, which would result in different paths in your output as `.refer-inner-img` is set up to travel back up 3 levels, whereas `.refer-img` is set up to only travel up 2 levels.
