### ISSUE TITLE
Static Code Analysis Findings

### ISSUE THREAD

**Issue by codeanalysis9876** [less/less.js#3310]
Cross-Site Request   Forgery - At Line: 13 of File:   processes/Server/WebContent/lib/less/less.min.js
--
HTML5: Overly Permissive Message Posting   Policy - At Line: 16 of File:   processes/Server/WebContent/lib/less/less.min.js
JavaScript Hijacking - At Line: 13 of   File: processes/Server/WebContent/lib/less/less.min.js

**Comment by rjgotten** [comment]
You'd think that someone clever enough to cook up a bot capable of static code analysis, they'd be clever enough not to run static code analysis on minified files.
You'd also be wrong.
