### ISSUE TITLE
each function is broken in strict mode

### ISSUE THREAD

**Issue by eight04** [less/less.js#3313]
`this` is `undefined` in strict mode hence it throws a TypeError:
https://github.com/less/less.js/blob/a84358d2956d3245f45083adc50069119de2e431/lib/less/functions/list.js#L74
I guess it should pass `this` argument to the `forEach` method?
https://github.com/less/less.js/blob/a84358d2956d3245f45083adc50069119de2e431/lib/less/functions/list.js#L92
```
}, this);
```

**Comment by rjgotten** [comment]
No. It should use an arrow function, which preserves the parent scope's lexical `this` binding. :)
