### ISSUE TITLE
Compress will break calc when use 0px

### ISSUE THREAD

**Issue by NE-SmallTown** [less/less.js#3318]
Hi, I'm using a loader which would set the `compress` option in production mode. But in the production mode, less will do this:

```
https://github.com/less/less.js/blob/b8140d4baad18ba732e2b322d8891a9b0ff065d5/lib/less/tree/dimension.js#L43-L54

if (context && context.compress) {
    // Zero values doesn't need a unit
    if (value === 0 && this.unit.isLength()) {   //    <<<<<<<<<<<------ see here
        output.add(strValue);
        return;
    }

    // Float values doesn't need a leading zero
    if (value > 0 && value < 1) {
        strValue = (strValue).substr(1);
    }
}
```

So, if I use something like:
`calc(0px + 1rem + 2rem)`
it will output:
`calc(0 + 1rem + 2rem)`
**which will make the css broken in production mode.**

Yea, why I don't just use `calc(1rem + 2rem)`? That's because this is just an example, actually I use `calc(@offset - env(safe-area-inset-bottom))` in my less file(`@offset` will be `0` sometimes).

So, is this a bug? IMO, we could don't remove the unit(i.e. 'px') when in the `calc` expression but  I'm not familiar with the less codebase.

**Comment by matthew-dean** [comment]
The `compress` option is deprecated. So I'm not sure if it's worth setting a priority for this edge case, if it will be removed eventually.

**Comment by NE-SmallTown** [comment]
Yea, but I can't control the option setting because the 3rd party loader does it. So I think fix this case may be useful

**Comment by seven-phases-max** [comment]
>because the 3rd party loader does it. 

Then this is a just bug in that 3rd party loader that should be fixed *there*. The `compress` options was marked as deprecated more than 3.5 years ago specifically because *there's no way to fix it* (simply because the way it was designed and implemented is *fundamentally* incompatible with the current CSS state/features).

**Comment by NE-SmallTown** [comment]
Thanks for your clarification! Sure, the loader should fix this but before I just mean it will do some work to do that, but if we could fix this(as you suggested just set it to false in less codebase), the loader could just update the version and fix it later
