### ISSUE TITLE
Defaults for ruleset as map

### ISSUE THREAD

**Issue by Jscherbe** [less/less.js#3326]
Hello, 

I am working on a project using the new map [] syntax. I was wondering if it is possible to test if a property exists in a ruleset or if there is a method to have default values. Example of functionality below with fake functions to convey the idea.

I know that mixins have default values which won't work for what I am planning.

```
@ruleset: {
  size: 10px;
};
@defaults: {
  size: 20px;
};

.test {
  // Example inline function
  content: default(@ruleset[size], 20px);

  // Example using guard
  & when (@ruleset[size]) {
    content: @ruleset[size];
  }
  
  // Example using  a function that merges the properties of the two rulesets
 @merged: merge(@ruleset, @defaults);
 content: @merged[size];

}
```

**Comment by matthew-dean** [comment]
I would use a much simpler strategy by using mixins vs. variables. In Less, mixins are all "merged" by default if they match your call. So you can set defaults, and then selectively "override" your defaults in subsequent mixins with the same name.

```less
// defaults.less
.rules() {
  size: 20px;
}

// custom.less
.rules() {
}

.test {
  content: .rules[size];  //20px
}
```
However, there may be a need to add a method to return a default value if a prop doesn't exist, if someone can provide a use case that the above doesn't address. If it's needed, I could see something like `.rules[size, 10px]` being a good form. But if there are ways to get the same result, I wouldn't recommend expanding the language.

**Comment by Jscherbe** [comment]
Thanks for the reply Mathew. 

I reworked my approach using a mixin with a ruleset to accomplish the goal. Example code pasted below. This pattern will allow for merging defaults and then carrying the options to other mixins. Although there have been other situations in which it would be helpful to have fallbacks for map lookups.

Example Code:
`// Namespace
#NS() {

  // Main Mixin
  // - Will contain required component CSS
  // - Will be the mechanism for including default options
  // - Will serve as the scope for child mixins so they can use the final options/args/defaults
  // - Child mixins will be included in a detached ruleset so they can be exposed to the main mixin scope
  
  .main(
    @var1: 12,
    @var2: 12,
    @optional: false 
  ) {

    .test-output-1 {
      content: @var1;
    }

    // Calling the ruleset to expose the mixins that 
    // scope are included to this
    & when not (@optional = false) {
      @optional();
    }
  }

  // Optional Mixin
  // - Will inherit the scope of the parent so arguments don't need to be repeated on user side
  // - This allows for simpler more intuitive interface for mixin users
  .optional() {

    .test-output-2 {
      content: @var1;
    }
  }
}


// Example call to component by user
#NS.main(
  @var1: 10, 
  @var2: 10, 
  @optional: {
    #NS.optional();
  }
);`

**Comment by matthew-dean** [comment]
Glad that worked for you.
