### ISSUE TITLE
Operation.prototype.accept

### ISSUE THREAD

**Issue by legu2009** [less/less.js#3327]
Operation.operands is Array, but use visitor.visit ？

>Operation.prototype.accept = function (visitor) {
      this.operands = visitor.visit(this.operands);
};

**Comment by matthew-dean** [comment]
I'm sorry, is this a bug report?

**Comment by legu2009** [comment]
"visitor.visit(this.operands)" is wrong, it will not visit operands[0] or operands[1]. 
use "visitor.visitArray(this.operands)" will work

**Comment by legu2009** [comment]
> I'm sorry, is this a bug report? If so, what is the bug?

"visitor.visit(this.operands)" is wrong, it will not visit operands[0] or operands[1].
use "visitor.visitArray(this.operands)" will work

**Comment by matthew-dean** [comment]
@legu2009 Can you make a PR for this?
