### ISSUE TITLE
Comments inside ruleset maps are parsed by the each-function

### ISSUE THREAD

**Issue by IIFLIPII** [less/less.js#3328]
Let's say I have the following map and iterate over it with the each-function:

![bildschirmfoto 2018-11-12 um 14 55 10](https://user-images.githubusercontent.com/38748359/48352909-5627e600-e68e-11e8-87f0-065c58a56bd0.png)

This will result in the following compiled output (with less.js):

![bildschirmfoto 2018-11-12 um 14 58 11](https://user-images.githubusercontent.com/38748359/48352918-5d4ef400-e68e-11e8-8438-5776cebe5349.png)

The lines that are commented out are also parsed and the index is used as the key-variable somehow.

I don't think this is the intended behaviour.

**Comment by matthew-dean** [comment]
Hmm, technically it's not defined behavior, so this would be more of a feature request.
