### ISSUE TITLE
Cannot use mixins in subsequent imports

### ISSUE THREAD

**Issue by ReverendDG** [less/less.js#3329]
I have this code:

@import "vars.less";

@import "mixins-d-1.less";
@import "positioning.less";
@import "containers-d-1.less";

Inside containers-d-1.less I reference a mixin from mixins-d-1.less. However, I get an error saying that it's undefined. If I explicitly rewrite the mixin inside containers-d-1.less, it works fine. It seems that the code inside containers-d-1.less can't see the code inside mixins-d-1.less. It can, however, see the variables declared in vars.less.

If I'm able to pull my variables out of vars.less, why can't I pull my mixins out of mixins-d-1.less?

**Comment by rjgotten** [comment]
The question you should be asking yourself is the reverse:

"If mixins are properly kept out of scope unless actually imported, why aren't variables?"

Relying on import order is a fallacy and an anti-pattern in Less.
Have each sheet import the parts it needs. The compiler will handle deduplication and will emit anything that's part of those sheets in the correct import order, once.

**Comment by matthew-dean** [comment]
> Less handles import scoping a lot better than the shit-tastic approach SASS takes.

@rjgotten No need for mud-slinging. They just have different approaches.
