### ISSUE TITLE
modifyVars with variable

### ISSUE THREAD

**Issue by pit07** [less/less.js#3330]
Hi!

Just a question. I have to use:

`less.modifyVars({
	'@navbar-fluid' : true
});`

But i'm trying to do this:

`var lessVariable = "@" + $input.attr("data-variable");
less.modifyVars({
     lessVariable : true
});`

But lessVariable isn't understood by modifyVars.

I tried:

`var lessVariable = "'@" + $input.attr("data-variable") + "'";
			less.modifyVars({
				lessVariable : true
			});`

But it don't work too...

Thanks a lot !

**Comment by taurz** [comment]
less.modifyVars({ [lessVariable] : true }) may works

**Comment by pit07** [comment]
Perfect !! Thanks a lot !
