### ISSUE TITLE
Map property that uses another property in the same map causes "Maximum call stack size exceeded" error

### ISSUE THREAD

**Issue by aofolts** [less/less.js#3331]
Let's say I want to store all my colors in a a `.color` map.

One of the colors needs to be a mix, so I create `mixedColor`.

However, referencing another color inside the same map seems to cause an infinite feedback loop.

I get a `Maximum call stack size exceeded` error.

Is this a bug or intentional?

And are there any workarounds?

```
.color() {
  red: red;
  mixedColor: mix(.color[red],blue,50%);
}

h1 {
  color: .color[mixedColor];
}
```

**Comment by matthew-dean** [comment]
Without going into details, it's not exactly supported but seems like an intuitive thing to do, and definitely the call stack error is a bug, so will mark as such.

**Comment by seven-phases-max** [comment]
But this *is* really infinite self-recursion code by how mixins are supposed to work. Mixins are supposed to be evaluated as a whole - hence `.color[red]` leads to another `.color[mixedColor]` evaluation that leads to another `.color[red]` and so on.

It's not hard to invent a language kludge (e.g. "partial mixin evaluation" for `.mixin[property]` constructions) to allow such code but it still would smell wrong.
---
As for the use-case, shouldn't it be simply:
```less
.color() {
  red: red;
  mixedColor: mix($red, ...);
}
```
or something like this?

**Comment by aofolts** [comment]
@seven-phases-max Nice! I notice the new `Properties as Variables` section in the docs at first, but they solve the problem. Thanks!

**Comment by matthew-dean** [comment]
@seven-phases-max  That's true, but I think Less does have code that prevents other types of referential recursion, so I'm wondering if this shouldn't be left open as a bug, dunno. Seems like maybe `.color[red]` could be detected as being `$red` in that context. But it's also true there's a workaround. I'm not attached either way.
