### ISSUE TITLE
error : webpack compile less of file 

### ISSUE THREAD

**Issue by shencailiang** [less/less.js#3332]
box-shadow: 0 0 1px 6px color(#f7f800 alpha(20%));
                                          ^
Error evaluating function `alpha`: color.toHSL is not a function

**Comment by seven-phases-max** [comment]
>`color(#f7f800 alpha(20%))`

This is just an invalid statement, what it is supposed to do? Neither `color` nor `alpha` work like this. See [the docs](http://lesscss.org/functions/#functions-overview).

**Comment by seven-phases-max** [comment]
Closing as OP error.
