### ISSUE TITLE
repeating  hover property in compiled css

### ISSUE THREAD

**Issue by fz-sl** [less/less.js#3344]
i have made .box_a which is grandfather  of .box_b and .box_c ...
the :after property in .box_b and .box _c is different ...
in compiled css  .box2 and .box3 have two :after properties ..
it shouldn't write two of them .. it just needs to rewrite them

[name space.zip](https://github.com/less/less.js/files/2670724/name.space.zip)

**Comment by matthew-dean** [comment]
Less doesn't try to get overly clever with reducing your selectors. It will generally output them the way that you wrote them.

Note if you write:
```less
.a {
  foo: bar;
}
.a {
  bar: foo;
}
```
You will get: in your output:
```css
.a {
  foo: bar;
}
.a {
  bar: foo;
}
```
And not:
```
.a {
  foo: bar;
  bar: foo;
}
```
If you want to reduce your output, there are CSS tools which can apply different transforms to shrink and collapse selectors. All of that is outside the scope of Less.

Closing as designed.
