### ISSUE TITLE
Nth-Of-Type Compilation Failure

### ISSUE THREAD

**Issue by Lukargo** [less/less.js#3353]
I'm seeing an issue where if I try to use nth-of-type on a tag name instead of a class name, compiling fails with the error "Unrecognised input in file".

For example:
`span:nth-of-type(2) { display: none; }`

will fail but

`.test:nth-of-type(2) { display: none; }`

Will succeed. To get around this, I've been using the following format which does compile.
`span { &:nth-of-type(2) { display: none; } }`

**Comment by KevinRamharak** [comment]
What version of less are you using? Is this the exact code that is throwing an error?

When trying it out in the online preview http://lesscss.org/less-preview/ (3.7) and on my local machine it compiles just fine (3.7)
