### ISSUE TITLE
Encrypt your Website

### ISSUE THREAD

**Issue by jhabdas** [less/less.js#3355]
Please add or renew your TLS cert and provide users access at https://lesscss.org

**Comment by matthew-dean** [comment]
Just use http://lesscss.org

**Comment by jhabdas** [comment]
I don't think you get it.

**Comment by matthew-dean** [comment]
@jhabdas There's no data exchanged on the documentation site, so trying to browse with https is not necessary. Regardless, no one active on the core team has the ability to add an SSL for that domain.

**Comment by jhabdas** [comment]
You said there's no data exchanged on this website. But a casual glance at your cookies says otherwise.

**Comment by jhabdas** [comment]
You said there's no data exchanged on this website. But a casual glance at your cookies says otherwise. And this: https://doesmysiteneedhttps.com

**Comment by jhabdas** [comment]
You said there's no data exchanged on this website. But a casual glance at your cookies says otherwise. Your attitude seems unethical and irresponsible given the traffic you likely get.
