### ISSUE TITLE
No lessc.cmd in node_modules

### ISSUE THREAD

**Issue by Artyom-Ganev** [less/less.js#3357]
I've installed less package in modules, but there is no lessc.cmd in node_modules, so I can't add watcher to WebStorm (It doesn't work with lessc.js).
I used npm i less --save-dev command

**Comment by kevinramharak** [comment]
Do you have any more info? When running `npm install --save-dev less` with `npm@6.4.1` i will find `less.cmd` inside the `node_modules/.bin/` directory.

**Comment by Artyom-Ganev** [comment]
Just installed my project dependencies with npm install and got no lessc.cmd or lessc shell script.
![image](https://user-images.githubusercontent.com/13161268/58563803-77b87b80-8234-11e9-8945-580c57cd2220.png)

**Comment by kevinramharak** [comment]
Please check the `node_modules/.bin` folder instead of the less folder. A install of 3.9 works fine
