### ISSUE TITLE
Unrecognised input

### ISSUE THREAD

**Issue by v5zz** [less/less.js#3358]
webpack 3
react 16
index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= htmlWebpackPlugin.options.title %></title>
  <meta charset="utf-8">
  <meta name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no"/>
  <meta name="apple-mobile-web-app-capable" content="yes"/>
  <meta name="apple-touch-fullscreen" content="yes"/>

</head>
<body>

<link rel="stylesheet/less" type="text/css" href="./src/static/color.less"/>
<script>
  window.less = {
    async: true,
    env: 'production',
    javascriptEnabled: true,
    dumpLineNumbers: "mediaQuery",
  };
</script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/less.js/2.5.3/less.min.js"></script>
<div id="App">loading...</div>
</body>
</html>

**Comment by matthew-dean** [comment]
This is not a clearly written issue.
