### ISSUE TITLE
import statements options issue 

### ISSUE THREAD

**Issue by mohamedafzal03** [less/less.js#3359]
//index.less
@import (multiple) "foo.less"; 
@import (multiple)  "foo.less"; 

//foo.less
@import (once) "themes/haha/variable.less";
@import (once) "themes/haha/variable.less";

//themes/haha/variable.less
.className{
color:red;
}

css created by less compiler : (the "once" import option did not make sense here)
.className{
color:red;
}
.className{
color:red;
}
.className{
color:red;
}
.className{
color:red;
}

**Comment by matthew-dean** [comment]
Are you saying you're getting imports duplicated?

Note that using the same filename twice in one file doesn't make sense, so I feel like there's something contrived about this example that doesn't map to what's really being used. Is there a repo or online project that demonstrates how this is actually being used?

**Comment by mohamedafzal03** [comment]
As You mentioned "Note that using the same filename twice in one file doesn't make sense", it make sense in some cases beacause i can define some variables in one file and i can import it under any classes ,so check it up the example
https://github.com/mohamedafzal03/less_import_issues

**Comment by matthew-dean** [comment]
@mohamedafzal03 🤔 There's no reason to do that because the variables you import in the top level will be accessible within that class. I suspect you may have some misconceptions either about how vars and/or how imports work?

**Comment by mohamedafzal03** [comment]
what if i want to import variables in only some classes which is  not imported in top level? 
Actually the point is if i import a file in multiple option like **@import (multiple) "new.less"**
if i imported another file inside new.less as **@import (one) "newone.less"** twice , the once option does'nt work (it is importing newone.less as twice without considering once option).
i.e Once option in import statement inside nested imported files  did'nt works
once option inside multiple option file didn't works

**Comment by matthew-dean** [comment]
> what if i want to import variables in only some classes which is not imported in top level?

You can do this.

```less
& {
  @import "themes/haha/variable.less";
  .class {
    // etc
  }
}
```

**Comment by mohamedafzal03** [comment]
dude @matthew-dean 
kindly consider this example
###  test.less
`@import (multiple) "h1.less";
@import (multiple) "h1.less";`
###  h1.less
`@import (once) "h2.less";
@import (once)"h2.less";`
###  h2.less ( example )  
`class{
color:red;
}`
### as per docs
### **once
The default behavior of @import statements. It means the file is imported only once and subsequent import statements for that file will be ignored.
Released v1.4.0
This is the default behavior of @import statements.
Example:
```
@import (once) "foo.less";
@import (once) "foo.less"; // this statement will be ignored
```
**
I am using same "once"option  twice inside a importing file with option "multiple" it doesnt make any sense.(ie)once option doesn't make any sense in this case.
you can say there is no need to use like this
`@import (once) "h2.less";
@import (once)"h2.less";`
but as per docs
`@import (once) "foo.less";
@import (once) "foo.less"; **// this statement will be ignored**`
which is not ignored in this case

**Comment by seven-phases-max** [comment]
I'm not quite sure I can follow the discussion - but I suspect this is basically one of faulty cases I mentioned in https://github.com/less/less.js/issues/3374#issuecomment-472455250
Also (just in case)
@mohamedafzal03, when you say:
> "once" import option did not make sense here
Do you actually mean:
> "once" import option does not have any effect (or is not applied) here
?

**Comment by seven-phases-max** [comment]
I'm not quite sure I can follow the discussion - but I suspect this is basically one of faulty cases I mentioned in https://github.com/less/less.js/issues/3374#issuecomment-472455250
Also (just in case)
@mohamedafzal03, when you say:
> "once" import option did not make sense here

Do you actually mean:
> "once" import option does not have any effect (or it is not applied) here

?

**Comment by mohamedafzal03** [comment]
@seven-phases-max 
Yes , as you said 

> "once" import option does not have any effect (or it is not applied) here

i.e when once is not effective only in the cases where the once option is written on the file which is imported in another file with multiple option .check it out !
