### ISSUE TITLE
Can't use Map inside each

### ISSUE THREAD

**Issue by omidgfx** [less/less.js#3366]
let's say I have this less:
```
@threshold:{
  a:50;
  b:200;
};

@themes:{
  a:red;
  b:blue;
};

.mymixin(@name,@color,@thrshld){
  //do-something
}

each(@themes,{
  .mymixin(@key,@value,@threshold[@key]);
});
```

This code gives following error:

> RuntimeError: error evaluating function `each`: variable @key not found...

I'm using v3.9.0

How can I use Maps in each function?

**Comment by dmgawel** [comment]
You can achieve that using `$@` (Variable properties):
```
each(@themes,{
  .mymixin(@key,@value,@threshold[$@key]);
});
```

See: #3362 and docs issue: https://github.com/less/less-docs/issues/500

**Comment by seven-phases-max** [comment]
Closing as not an issue.
