### ISSUE TITLE
wrong result

### ISSUE THREAD

**Issue by Serega5j** [less/less.js#3367]
If I write `element { :hover:after{ } }` I get `element :hover:after{ }`. It isn't working code. Result must look `element:hover:after{}` - without space between element and pseudoclass

**Comment by seven-phases-max** [comment]
*Result must look* - no, it must not. Please see [the documentation](http://lesscss.org/features/#parent-selectors-feature).

**Comment by seven-phases-max** [comment]
Closing as expected behavior.

**Comment by seven-phases-max** [comment]
Closing as expected behavior.
