### ISSUE TITLE
Does anyone know why LESS is inserting a space between the selector and itʼs pseudo class?

### ISSUE THREAD

**Issue by TheMouster** [less/less.js#3377]
Basically I have the following Less for styling a table and I'm making use of pseudo classes to manage the column widths.

       .Inbound th {
            &:nth-child(-n+3),:nth-child(5),:nth-child(8){
                width: 10%;
            }
            &:nth-child(4) {
                width: 20%;
            }
            &:nth-child(n+6):nth-child(-n+7) {
                width: 5%;
            }
        }

This is resulting in:

    .Inbound th:nth-child(-n+3),
    .Inbound th :nth-child(5),
    .Inbound th :nth-child(8) {
      width: 10%;
    }
    .Inbound th:nth-child(4) {
      width: 20%;
    }
    .Inbound th:nth-child(n+6):nth-child(-n+7) {
      width: 5%;
    }

Which is invalid, note the space on lines 2 & 3 after the **th** selector and prior to the **nth-child** pseudo class. 

If itʼs not supposed to do this then I've found a bug in LESS.

If this is correct behavior, which is not what want, can someone point me in the direction of what I should be doing?

I have already tried the following:

 - Putting all the nth-child pseudo classes on separate lines.
 - Left aligning the "," & ":nth-child" pseudo classes to the far left.

Neither of which had any affect.

If itʼs of any interest Iʼm using WinLess to pre-process the Less for me and itʼs running 2.1.2 of LESS.js for parsing.

**Comment by TheMouster** [comment]
Found out what I was doing wrong. Not overly obvious, but I needed to change this:

    .Inbound th {
        &:nth-child(-n+3),:nth-child(5),:nth-child(8){
            width: 10%;
        }
        &:nth-child(4) {
            width: 20%;
        }
        &:nth-child(n+6):nth-child(-n+7) {
            width: 5%;
        }
    }

into this:

    .Inbound th {
        &:nth-child(-n+3)
        ,&:nth-child(5)
        ,&:nth-child(8){
            width: 10%;
        }
        &:nth-child(4) {
            width: 20%;
        }
        &:nth-child(n+6):nth-child(-n+7) {
            width: 5%;
        }
    }

Newlines for clarity.

**Comment by seven-phases-max** [comment]
Yes, basically every selector in the comma list is a distinct thing so it needs its own `&`.
