### ISSUE TITLE
Tests failing on Travis, NodeJS 6 with 'undefined is not an object'

### ISSUE THREAD

**Issue by ajmas** [less/less.js#3387]
The build failed due to an nodejs 6 related failure. This seems to be impacting other PRs too. Is nodejs 6 support still a requirement? If it is then there should be a fix for this failure made available to master.

Failure is for 'jasmine:rootpathRelative':

```
 less.js browser test - rootpath and relative urls
   - original-less:test-less-urls should match the expected output...X original-less:test-less-urls should match the expected output
     TypeError: undefined is not an object (evaluating 'less.pageLoadFinished
            .then') in http://localhost:8081/test/browser/common.js (line 131) (1)
```

I did run locally on my Mac with NodeJS v6.16.0, with npm 3.10.10, and I do see 'jasmine:rootpathRelative' passing.

**Comment by matthew-dean** [comment]
Travis has always failed on Node 6, not sure why. I removed it since it's covered with Appveyor. Seems like tests are passing now.

**Comment by ajmas** [comment]
I closed it, since the bot decided it was stale and since it got no attention I thought maybe it wasn’t valid anymore? 

In terms of Node version support, is Node 6 is still a valid target?

**Comment by matthew-dean** [comment]
@ajmas I think we've just sorta guesstimated on Node version support. Node is fairly trivial to upgrade for the most part, but there are isolated environments where it can be more work to move up a Node version, such as when it's embedded in another system. I think as a general rule we've been targeting the last 4 LTS versions?
