### ISSUE TITLE
Lists + calc() breaks lookups for mixin-generated maps

### ISSUE THREAD

**Issue by zaquest** [less/less.js#3393]
As the title suggests using a variable containing a list and `calc()` breaks maps that were generated by calling a mixin and saving the result in a variable.
Below is a minimal example I was able to come up with.

```
@textClasses: .h1, .h2, .h3;

@alias: @textClasses; // uncommenting this breaks things
// @{textClasses} { color: white; } // or this

// calc() is involved too, commenting this make the style compile again
div { width: calc(100px * 2); }

.mk-map() {
  text: white;
  background: black;
}

@p: .mk-map();
h1 { color: @p[text]; }
```

Trying to compile it results in `SyntaxError: Could not evaluate variable call @p`.

Less version 3.9.0

Is it a bug? Or am I missing something?

**Comment by zaquest** [comment]
Seems like it doesn't matter if the variable contains a list or something else. For example the following doesn't work either:

```
@a: 10;
h2 { width: unit(@a, px); } // uncommenting this breaks the stylesheet

// calc() is involved somehow too, commenting this make the style compile
div { width: calc(100px * 2); }

.mk-map() {
  text: white;
  background: black;
}

@p: .mk-map();
h1 { color: @p[text]; }
```

**Comment by rgroothuijsen** [comment]
Curiously, if you reverse the two halves, it doesn't throw an error. What appears to be the case is that the calculation causes Less to become stuck in calculation mode, which causes subsequent variables to be wrongly evaluated.

**Comment by zaquest** [comment]
#3493 seems to solve the issue. Thank you!
