### ISSUE TITLE
@import (optional) throws error in console.log

### ISSUE THREAD

**Issue by jeradrutnam** [less/less.js#3399]
When using less.js on client side it throws 404 (File not found) for optional imports. So when we have multiple optional imports, console.log get stack with 404 errors in complex apps.

```less
@import (optional) "other.less";
```

![image](https://user-images.githubusercontent.com/7569427/59187918-1e394080-8b94-11e9-8857-7606104739c9.png)

![image](https://user-images.githubusercontent.com/7569427/59190659-eaade480-8b9a-11e9-88eb-2e3473d0bf8a.png)

**Less version:** 3.9.0

Also noted that sourceMap function also breaks because of it. May be that issue is related to this: #2599

---

I know we can't suppress this when do ajax calls. Any solution? Nothing comes to my mind though.

**Comment by seven-phases-max** [comment]
I don't see how this can be solved at all except "by not using (optional) in a browser-less-code". By definition of `optional) Less *has* to request the file and hence goes 404 when it does not exist (note this is not Less error message but a browser message instead).

The only workaround to imagine is the old one trick with creating an *empty* "other.less" (the method was a solution for this kind of use-cases long before the `(optional)` kludge came in).

**Comment by seven-phases-max** [comment]
I don't see how this can be solved at all except "by not using `(optional)` in a browser-less-code". By definition of `(optional)` Less *has* to request the file and hence goes 404 when it does not exist (note this is not Less error message but a browser message instead).

The only workaround to imagine is the old one trick with creating an *empty* "other.less" (the method was a solution for this kind of use-cases long before the `(optional)` kludge came in).

**Comment by seven-phases-max** [comment]
Closing as an expected behavior.
