### ISSUE TITLE
A lot of Missing semicolons

### ISSUE THREAD

**Issue by i0n-** [less/less.js#3400]
I'm trying to use the `less.js` file into the **Rhino** that is an open-source implementation of JavaScript in Java, and start failing because there is a lot of Missing semicolons.

I use https://jshint.com/ to confirm this.

Release file inside less-less.js-v3.9.0-5-g162327a

![image](https://user-images.githubusercontent.com/293840/59298174-cc99c000-8c3e-11e9-9131-8e5eb512bc0d.png)

**Comment by matthew-dean** [comment]
...okay? This isn't a failing issue so I'm not sure what the issue is.

**Comment by kevinramharak** [comment]
I am not familiar with Rhino and its compliance to the ecmascript specs.
I'd suggest you read in to automatic semi colon insertion: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Automatic_semicolon_insertion.

I assume the 'errors' that JShint reports are mere suggestions. Note that all those messages report on minified lines. Javascript minifiers use ASI to omit semi colons whenever possible to compress the amount of characters used in the code they are compressing.

I suggest you look into Rhino and its stance about ASI as this is not a problem with Less.

**Comment by matthew-dean** [comment]
@i0n- Note that Less no longer has official support for Rhino (and didn't really in the first place). There was some work to try to get a port for Nashorn though. https://github.com/less/less.js/pull/2985

**Comment by i0n-** [comment]
I try after with the `less.min.js` file and the semicolon issues was solved.

But a new one appear.
There are some window object utilization that escape from the current object validation, trying to use it and failing. I'm going to review this better, and may be open another issue to work in the solution.

Thanks.
