### ISSUE TITLE
Silent mode not working in Less Compiler 3.9.0

### ISSUE THREAD

**Issue by LuomaJuha** [less/less.js#3401]
When using Lessc with terminal and adding -s or --silent to suppress errors, they are still shown.

Test case is simple, use lessc to compile a less file with an undefined variable and with -s or --silent parameters:
`background-color: @background-test-silent; < will raise an error`

Output is:
```
NameError: variable @background-test-silent is undefined in /test/test.less on line 423, column 27:
422         width: 100%;
423         background-color: @background-test-silent;
424       }
```
This used to work in older versions but after 3.0.0 it started to raise the errors.

**Comment by matthew-dean** [comment]
The documentation says `--silent` "Stops any warnings from being shown."

This appears to be an error and not a warning. I'm not sure what warnings the documentation was even referring to, and it doesn't appear to have tests for silent output, so I'm afraid I'm not sure what that feature was intended to do.

**Comment by alecpl** [comment]
There are a couple of uses of logger.warn() in the code.
