### ISSUE TITLE
AJAX error at XforWooCommerce plugin less compiler [URGENT!]

### ISSUE THREAD

**Issue by justdudeone** [less/less.js#3403]
Hello!

I buy XforWooCommerce but it all the time cause a some "AJAX error!" on CSS compiling and all logs points that error occur at/by less-compiler. XforWooCommerce developer Mikhailovich Nenand are too lazy/incompetent and can't resolve this problem already for more than two weeks! All my works just fkng stuck for two weeks, it's a total nightmare! I ask you to help to resolve this problem, PLEASE!

== Problem behavior:
XforWooCommerce plugin is some kind of aggregator of a many small plugins for WooCommerce styling setup, most of which use less-CSS-compiler.
When XforWooCommerce is just installed and anyone of it small plugins are running for a FIRST TIME - IT WORKS GOOD! And after that ALL NEXT RUN'S of less-CSS-compiler from EXACTLY THIS FIRST small plugin - also works good! But any similar runs from OTHER small plugins - only creates an errors and compiling CSS wrong that just blow up a whole shop!
(For example if firstly run "ShopDesigner-ProductLoops" - ProductLoops CSS compiling will always works good, but all other small plugins parts CSS compiling as Badges/Filter/etc - will always only cause an "AJAX error"!)
This behavior was re-checked and repeated at main site and 2 staging copies with absolutely the same results.

So it seems that script or template or settings etc of less-complier are hardly saved and fixing at first less-compiler run and then cannot be changed on all next runs form other small plugins CSS compiling. Or something like that. 

Please, look logs by yourself. 
Why it can happen??? How to resolve it???

I can give a full access to my server to a main Less-CSS-compiler developers.

PLEASE HELP!!!

== Logs details:
`
strace result: write(5, "2019-06-15T07:57:23+00:00 CRITICAL Uncaught Exception: load error: failed to find https://staging1.domain.com/wp-content/plugins/xforwoocommerce/x-pack/product-loops/assets/less/product-loops.less in 
/home/account/staging/1/wp-content/plugins/xforwoocommerce/svx-settings/less/lessc.inc.php:133\nStack trace:\n#0 
/home/account/staging/1/wp-content/plugins/xforwoocommerce/svx-settings/less/lessc.inc.php(226): lessc->compileFile('https://staging...')\n#1 
/home/account/staging/1/wp-content/plugins/xforwoocommerce/svx-settings/svx-settings.php(1096): lessc->cachedCompile('https://staging...')\n#2 
/home/account/staging/1/wp-content/plugins/xforwoocommerce/svx-settings/svx-settings.php(842): SevenVXSettings::compile_less(Array, Array)\n#3 
/home/account/staging/1/wp-includes/class-wp-hook.php(286): SevenVXSettings->ajax_factory('')\n#4 
/home/account/staging/1/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)\n#5 
/home/account/staging/1/wp-includes/plugin.php(465): WP_Hook->do_action(Array)\n#6 
/home/account/staging/1/wp-admin/admin-ajax.php(17 \320\262 /home/account/staging/1/wp-content/plugins/xforwoocommerce/svx-settings/less/lessc.inc.php \320\275\320\260 \321\201\321\202\321\200\320\276\320\272\320\265 133\n\n", 1176) = 1176

account@esm59 [~/staging/1/wp-content/plugins/xforwoocommerce/x-pack/product-loops/assets/less]#
drwxr-xr-x 3 account account 4096 Jun 15 09:59 ./
drwxr-xr-x 6 account account 4096 May 30 10:52 ../
-rw-r--r-- 1 account account 6354 May 30 10:52 _effects.less
-rw-r--r-- 1 account account 1363 May 30 10:52 _functions.less
-rw-r--r-- 1 account account 344 May 30 10:52 _responsive.less
-rw-r--r-- 1 account account 7424 May 30 10:52 _rtl.less
drwxr-xr-x 3 account account 4096 May 30 10:52 loops/
-rw-r--r-- 1 account account 17185 Jun 15 09:59 product-loops.less -- FILE ARE EXIST AT RIGHT PLACE!!!

on line 133 is trying to load an automatically generated PHP file via this code:
public function compileFile($fname, $outFname = null) {
if (!is_readable($fname)) {
throw new Exception('load error: failed to find '.$fname);

[15-Jun-2019 19:54:35 UTC] PHP Fatal error: Uncaught Less_Exception_Compiler: error evaluating function `unit` The first argument to unit must be a number. index: 14352 in product-loops.less in product-loops.less in product-loops.less in /home/account/staging/1/wp-content/plugins/xforwoocommerce/svx-settings/less/Less/Tree/Mixin/Call.php:124
Stack trace:
#0 /home/account/staging/1/wp-content/plugins/xforwoocommerce/svx-settings/less/Less/Tree/Ruleset.php(147): Less_Tree_Mixin_Call->compile(Object(Less_Environment))
#1 /home/account/staging/1/wp-content/plugins/xforwoocommerce/svx-settings/less/Less/Tree/Ruleset.php(88): Less_Tree_Ruleset->EvalMixinCalls(Object(Less_Tree_Ruleset), Object(Less_Environment), 249)
#2 /home/account/staging/1/wp-content/plugins/xforwoocommerce/svx-settings/less/Less/Parser.php(185): Less_Tree_Ruleset->compile(Object(Less_Environment))
#3 /home/account/staging/1/wp-content/plugins/xforwoocommerce/svx-settings/less/lessc.inc.php(153): Less_Parser->getCss()
#4 /home/account/staging/1/wp-content/plugins/xforwoocommerce/svx-settings/le in /home/account/staging/1/wp-content/plugins/xforwoocommerce/svx-settings/less/Less/Tree/Mixin/Call.php on line 124
`

**Comment by matthew-dean** [comment]
The Less compiler used here does not appear to be Less.js, so it isn't related to this repo.
