### ISSUE TITLE
Issue with modifyVars

### ISSUE THREAD

**Issue by marlo22** [less/less.js#3404]
Hi there :hand: 
I have an issue with `modifyVars` function and variables defined as Less function. For example this code works good:
```
@first-color: #ff0000;
```

```
less.modifyVars({ 'first-color': '#ffffff' });
```

but when variable use function, for example `fade` `modifyVars` doesn't apply new value
```
@first-color: #ff0000;
@second-color: fade(@first-color, 60);
```

```
less.modifyVars({ 'first-color': '#444444' });
```

(`@second-color` has still the same value as previously).

My question is: what can I do to modify `@second-color` value by `modifyVars` function? Thanks for answers. :smile:

**Comment by vvscode** [comment]
try instead of `.modifyVars` next:

```js
less.refresh(true, { 'first-color': '#444444' }, true);
```

according to https://github.com/less/less.js/blob/33a3830342e0af1555c6355b8e83d9474ffa80a8/lib/less-browser/index.js#L214

**Comment by marlo22** [comment]
> marlo22 try instead of `.modifyVars` next:
> 
> ```js
> less.refresh(true, { 'first-color': '#444444' }, true);
> ```
> 
> according to
> 
> https://github.com/less/less.js/blob/33a3830342e0af1555c6355b8e83d9474ffa80a8/lib/less-browser/index.js#L214
> 
> P.S. after reading more docs - don't think it will work ))

Thank you for answer, but this approach doesn't work. :disappointed: 

I divided into this problem and I see that in my `.less` files sending to browser by webpack, "dynamic" variable like `@something: fade(@green, 20%);` is parsed to `rgba(0, 255, 0, 0.2)`. I think that this is a problem. Can I pass to Less configuration property to compiler to not parse variables? I see that in some places in my finally `*.less` file variables are not parsed. What it depends on?

**Comment by marlo22** [comment]
Problem resolved. It was not fault Less.js. One of style plugins in my project accept only variables that contains `-` char in your name.

**Comment by baiyunshenghaishang** [comment]
> Problem resolved. It was not fault Less.js. One of style plugins in my project accept only variables that contains `-` char in your name.

Face the same problem.  which plugin causes this problem.
