### ISSUE TITLE
There is no lib folder  in 3.10.0

### ISSUE THREAD

**Issue by babich-a** [less/less.js#3415]
Prior to the 3.10.0 we have the `lib` folder in the package with less-browser, less-node modules.

Now it is not available (https://github.com/less/less.js/commit/c0f5e976967db742b3ccb064cd6db00466cbfc40#diff-0fd4ef892d9d4990033701887c2f9bccR9).

Is [http://lesscss.org/usage/#developing-less-how-to-run-less-in-other-environments](http://lesscss.org/usage/#developing-less-how-to-run-less-in-other-environments) still actual or we should use some single entry point?

**Comment by matthew-dean** [comment]
@babich-a It was still in the repo, but I added it back to NPM.

**Comment by babich-a** [comment]
Hm. Thanks for quick update, but `require('less/lib/less-node')` does not work anymore.
It fails with 
```
node_modules\devextreme-cli\node_modules\less\lib\less-node\index.js:1
(function (exports, require, module, __filename, __dirname) { import environment from './environment';
                                                                     ^^^^^^^^^^^
```

But `require('less')` is working fine in the same place. I'll use it.

**Comment by matthew-dean** [comment]
@babich-a That's because Less has been converted to ES2015 modules. You can either use with a module bundler, or if you need the CommonJs version, there's a build in the `/dist` folder.

**Comment by matthew-dean** [comment]
@babich-a And yes `require('less')` just requires `/dist/less.cjs.js`, which is the `less-node` CommonJs build.
