### ISSUE TITLE
`npm install less` fails with EISGIT (node_modules/less appears to be a git repo or submodule)

### ISSUE THREAD

**Issue by JSalazar88** [less/less.js#3416]
It appears that the `.git` folder is part of the package now.
Installing less using `npm install less` fails with the following:

```
npm ERR! code EISGIT
npm ERR! git (repo)/node_modules/less: Appears to be a git repo or submodule.
npm ERR! git     (repo)/client/node_modules/less
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

Note that I am at Node v10.16.1, and npm v6.10.2.

**Comment by matthew-dean** [comment]
Hmm, weird, ok I'll check it out.

**Comment by matthew-dean** [comment]
`.git` folder added to `.npmignore`, but not sure why this caused a problem, since it didn't add the `.git` folder before even if it was present.
