### ISSUE TITLE
Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue - while installing web3 ( npm & minimatch version is 6.11.2 )

### ISSUE THREAD

**Issue by DineshSachdeva** [less/less.js#3428]
a- I am trying to install web3 in Windows / DOS. 
b- I get the errors when I run "npm install web3" ( updated 1 package and audited 951972 packages in 70.992s, found 3 vulnerabilities (1 low, 2 high),   run `npm audit fix` to fix them, or `npm audit` for details ) 
c- When I run "npm audit fix", I get the error 
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
d- My npm and minimatch version is already 6.11.2.

**Comment by kevinramharak** [comment]
This is the repository for [Less](http://lesscss.org/). It seems you have an issue with [web3](https://github.com/ethereum/web3.js/issues)?

**Comment by DineshSachdeva** [comment]
> This is the repository for [Less](http://lesscss.org/). It seems you have an issue with [web3](https://github.com/ethereum/web3.js/issues)?

**Comment by DineshSachdeva** [comment]
My apologies. I did not realize. Thanks for pointing. I am closing the issue and raised under web3.
