### ISSUE TITLE
redundancies and impossibilities in nested @media queries are not optimized

### ISSUE THREAD

**Issue by wpalmer** [less/less.js#3429]
nested `@media` queries, such as:

````
@media (min-width:768px) {
  @media (min-width:800px){
    div {
      color: red;
    }
  }
}
````

are not well-optimized, resulting in, for example:

````
@media (min-width: 768px) and (min-width: 800px) {
  div {
    color: red;
  }
}
````

when this could equivalently-written, more-tersely as:
````
@media(min-width: 800px) {
  div {
    color: red;
  }
}
````

similarly, nested `@media` queries may result in impossibilities, eg:

````
@media (min-width:768px) {
  @media (max-width:599px){
    div {
      color: red;
    }
  }
}
````

result in "impossible" media queries, ie:

````
@media (min-width:768px) and (max-width:599px){
  div {
    color: red;
  }
}
````

this is, on the face of it, not a problem: you have asked LESS to combine two conflicting rules, and so it combines two conflicting rules. However, this situation can easily arise when using `@import` rules, eg:

````
@media (min-width:768px) {
    @import 'buttons';
}
````

where `buttons.less` contains `@media` rules of its own, as it is written independently.

Ideally, rather than generating such impossible `@media` queries, LESS should notice the impossibility, and skip the entire `@media` block.

I suspect that LESS could solve both of these issues by attempting to build an understanding of the requested constraints in a `@media` query, and rewriting these constraints in the most-efficient method possible. The current behaviour could be used as a fallback if LESS is unable to confidently understand the `@media` queries involved.

This issue *may* relate to a similar-seeming issue regarding nested `@media` queries and negations, #3395. I suspect that the solution for this issue would apply equally to that one.

**Comment by seven-phases-max** [comment]
This is basically an "Analyze and optimize media queries" feature request.
The idea pops up from time to time and in general  considered to bee too burdening and thus rejected (or equally marked "up for grabs" or so to be closed for inactivity after some time). The feature more likely belongs to a CSS optimizer tool (you usually use after Less anyway) than to Less itself (just like most of other "CSS analyze/optimize" features with only a few exceptions)).

**Comment by seven-phases-max** [comment]
This is basically an "Analyze and optimize media queries" feature request.
The idea pops up from time to time and in general  considered to be too burdening and thus rejected (or equally marked "up for grabs" or so to be closed for inactivity after some time). The feature more likely belongs to a CSS optimizer tool (you usually use after Less anyway) than to Less itself (just like most of other "CSS analyze/optimize" features with only a few exceptions)).
