### ISSUE TITLE
'border-radius' resolve error

### ISSUE THREAD

**Issue by tuhongwei** [less/less.js#3436]
When I set the value of 'border-radius' similar to '0 0 50% 50% / 0 0 100% 100%', it will be resolved '0 0 50% Infinity% 0 100% 100%'

**Comment by seven-phases-max** [comment]
See [Math options](http://lesscss.org/usage/#less-options-math).
(Did not I answer at less-docs already?).

**Comment by yinsang** [comment]
border-radius: ~"100% 100% 100% 100% / 0% 0% 50% 50%";
