### ISSUE TITLE
@media query : Potentially unhandled rejection. Possibly missing something.

### ISSUE THREAD

**Issue by jackflyer** [less/less.js#3437]
```
@media only screen and (min-width:1200px) and (max-width:1386px) {
   .....
}
```
Is this valid input?
Less compiler throws error for _`invalid input: missing something`_. When I comment it error gone away, so it confirms that there is no other syntax error in my less file.

**Comment by kevinramharak** [comment]
This is valid input. Test it here http://lesscss.org/less-preview/. Can you show the contents of the media query? Pretty sure your syntax error is inside the braces.

**Comment by jackflyer** [comment]
It was hidden character, may be due to copy paste. Cleaning spaces and line-breaks helped. Not issue with Less.
