### ISSUE TITLE
[help] less Calculation in `display: grid`

### ISSUE THREAD

**Issue by longzhangtong** [less/less.js#3439]
less Compile `grid-row: 2 / 4;` to generate `grid-row: 0.5`;

less Compile `grid-column: 2 / 4;` to generate `grid-column: 0.5`;

less vesion:
"less": "~3.9.0",
"less-loader": "^4.1.0",

So terrible!

**Comment by seven-phases-max** [comment]
See [Math options](http://lesscss.org/usage/#less-options-math).

**Comment by seven-phases-max** [comment]
See [Math options](http://lesscss.org/usage/#less-options-math).
In short: set `parens-division` option.

**Comment by seven-phases-max** [comment]
Closing as not an issue.
