### ISSUE TITLE
Less has finished and no sheets were loaded

### ISSUE THREAD

**Issue by zboboan** [less/less.js#3440]
I made less. ModifyVars in Vue to change the less variable, but there was no effect, and it suggested that "less has finished and no sheets were loaded" less is the latest version, I hope to give you a solution

**Comment by matthew-dean** [comment]
We would need a simplified test case to verify this.

**Comment by amed** [comment]
After creating a fresh react app with CRA & craco:
    "react": "^16.13.1"
    "less": "^3.11.3"

This issue appears.

**Comment by SinHide** [comment]
> After creating a fresh react app with CRA & craco:
> "react": "^16.13.1"
> "less": "^3.11.3"
> 
> This issue appears.

Same react's version, this issue also appears.
