### ISSUE TITLE
How to reintroduce global variables in less

### ISSUE THREAD

**Issue by lanxiaoyuan** [less/less.js#3441]
How to reintroduce global variables in less as files
![image](https://user-images.githubusercontent.com/44766565/66459148-040e6100-eaa7-11e9-81e8-306af2e44d0b.png)
![image](https://user-images.githubusercontent.com/44766565/66459163-0ec8f600-eaa7-11e9-82b4-5111aa682855.png)
A lot of methods on the Internet are not good.

**Comment by matthew-dean** [comment]
I don't understand the question?

**Comment by lanxiaoyuan** [comment]
less不能自己出个可以引用通用.less文件，作为全局变量的吗

**Comment by matthew-dean** [comment]
@lanxiaoyuan According to Google Translate (note that this repo's issues should be English), your question is something like:

> Can you not be able to quote a generic .less file as a global variable?

Which still doesn't really make sense to me: as in what the use case is, what your intended output is, etc. Are you asking how to define an import based on a variable? I really don't understand the nature of the question, sorry.
