### ISSUE TITLE
3.10: Breaks IE Compat Option

### ISSUE THREAD

**Issue by bdkjones** [less/less.js#3446]
If I pass `--ie-compat` to `lessc` using 3.10.3, I now get this error:

    Unable to load plugin ie-compat please make sure that it is installed under or at the same level as less

As far as I can tell, you did not factor the IE Compatibility option out to a separate plugin (no reference in Changelog and I can't find any such plugin online). The `--ie-compat` option still appears when running `lessc -h`.

Please advise. Has this functionality been silently removed?

**Comment by matthew-dean** [comment]
@bdkjones  🤔  You're correct that while this is deprecated for a long time (as it only applies to the long-defunct IE8), it wasn't intended to be intentionally removed without a proper semver major version bump. This was probably a refactoring oversight.

**Comment by matthew-dean** [comment]
@bdkjones Note that the only appropriate fix would be to essentially silently _do nothing_, instead of throwing an error, as IE8 isn't supported as a browser version in 3.0+, even if the option should still be present.

**Comment by bdkjones** [comment]
I figured it was something like this. I’ve silently disabled the option in my app and will remove the option from the UI entirely in the next release. I’d recommend, at the very least, removing the description from the “help” printout and documentation so folks don’t pass the option. Doing that (and fixing this issue so the flag does nothing when passed, but does not error) would not be a breaking change.

**Comment by matthew-dean** [comment]
@bdkjones Agreed. It definitely wasn't intentional. It should be trivial to add the silent option to an upcoming release, if I can find the time soon.
