### ISSUE TITLE
Why not provide a sync `render` method for compiling less to css?

### ISSUE THREAD

**Issue by ChrisCindy** [less/less.js#3448]
or is there another way to do less->css compilation synchronously? In the doc i can't find that...

**Comment by matthew-dean** [comment]
@ChrisCindy On Node, there is a sync rendering option. Not sure why it's missing from docs but it's `syncImport: true` - https://github.com/less/less.js/blob/cae5021358a5fca932c32ed071f652403d07def8/lib/less/contexts.js#L27

In the browser, sync imports stopped being supported by browsers at all, so that's not an option there.

**Comment by ChrisCindy** [comment]
> @ChrisCindy On Node, there is a sync rendering option. Not sure why it's missing from docs but it's `syncImport: true` -
> 
> https://github.com/less/less.js/blob/cae5021358a5fca932c32ed071f652403d07def8/lib/less/contexts.js#L27
> 
> In the browser, sync imports stopped being supported by browsers at all, so that's not an option there.

@matthew-dean thanks for replying, but what i want is like the following:

```
const less = require('less');
const result  = less.render(content);
console.log(result); // {css: ..., map: ...}
```

**Comment by ChrisCindy** [comment]
> Well, searching the tracker for "sync" would give you a few ideas on why it is as it is now (notice it was synchronous a while ago).

@seven-phases-max i'm not quite aware of the reason....since both of stylus and sass provides a sync render method.

**Comment by seven-phases-max** [comment]
>since both of stylus and sass provides a sync render method.

I'm not quite sure I understand what other languages & their tools have to do with all this.

---
For the rest: well, starting somewhere at #2325 would be a good read.

**Comment by matthew-dean** [comment]
> For the rest: well, starting somewhere at #2325 would be a good read.

Especially this: https://github.com/less/less.js/issues/2325#issuecomment-127044616

That is, writing a `renderSync` function for yourself is fairly straightforward.
