### ISSUE TITLE
Guarding against undefined variables.

### ISSUE THREAD

**Issue by warrentmills** [less/less.js#3456]
I know this topic has come up a lot, but the answers provided for these questions don't work well for my needs or several cases I don't think have been properly discussed.

I strongly disagree with this being a feature that's not required, there are definitely cases that can not be addressed as easily with just defining a variable ahead of time. Any case in which you are not the one in charge of defining the values you're working with for example. In my case I'm creating utility mixins, such as the one below:
```
#util() {
    .border(@path) when (~'@{@{path}-type}' = individual) {
        border-top: ~'@{@{path}-top-definition}';
        border-bottom: ~'@{@{path}-bottom-definition}';
        border-left: ~'@{@{path}-left-definition}';
        border-right: ~'@{@{path}-right-definition}';
    }
    .border(@path) when not (~'@{@{path}-type}' = individual) {
        border: ~'@{@{path}-definition}';
    }
}
```
And the And an example usage:
In variables.less
```
@main-header-border-type: individual;
@main-header-border-definition: none;
@main-header-border-top-definition: 1px solid #e1e1e1;
@main-header-border-bottom-definition: none;
@main-header-border-left-definition: none;
@main-header-border-right-definition: none;
```
in main stylesheet
```
.page .header {
    #util.border(main-header-border);
}
```
Now I'm working with a site that shows all variables in a variables.less file in a web interface, so I'm defining all the potential variables for the end user to configure.

That mixin works fine and I have no problems with it. However another mixin I have is the two following:
```
.font(@path) {
        font-family: ~'@{@{@{path}-font}}';
        color: ~'@{@{@{path}-color}}';
        font-size: ~'@{@{path}-size}';
    }
    .fontHover(@path) {
        font-family: ~'@{@{@{path}-font}}';
        color: ~'@{@{@{path}-color}}';
        font-size: ~'@{@{path}-size}';
        &:hover {
            color: ~'@{@{@{path}-hover-color}}'
        }
    }
```
I have two mixins here for dealing with text properties, one for text that should have a hover color and one for when it shouldn't. I'd love to combine these two into the same mixin, and put a guard on the `&:hover` testing for whether the hover-color subproperty exists to determine whether it should be used.

I feel the other suggestions on this topic were closed with too little consideration to the possibility of people making libraries for other users, or multiple people working on different files with reusable code.

**Comment by rjgotten** [comment]
You can write a custom plugin function to determine whether a particular variable exists or not.

In a wider sense; your implementation strategy using variable-variables is wrong.
Use the [maps feature](http://lesscss.org/features/#maps-feature) to pass in objects with sub-properties.

**Comment by warrentmills** [comment]
This is an old issue. But I did mention that I do not have control over  the installation of less.js, I only had control over the less files, I could not install plugins. I never understood the "just make a plugin" or the "modify the installation" answers to things like this, because not everyone has the ability, means or permission to do so. Relying on plugins, replying on customers to fill gaps in your product that by many people are considered basic essentials is what many consider as lazy development. The maps feature is nice, but this response doesn't address the point. This is a request that has been made several times, should be trivial in implementation, and has no arguably valid reason to have been constantly rejected.
