### ISSUE TITLE
less.refresh() won't watch changes in included documents. 

### ISSUE THREAD

**Issue by snorripall** [less/less.js#346]
I just tried the setInterval approach for development and it seems to me that less.refresh is a bit bugged. It doesn't detect changes made in included files. 
# Example

My index.html points to main.less and nothing else. less.refresh() detects changes in main.less but not the files that are included by main.less or init.less. 
## main.less

```
@import "../shared/base.less";
@import "../skin1/init.less";
```
## /skin1/init.less

```
@import "header.less";
@import "top.less";
@import "middle.less";
@import "footer.less";
```

**Comment by naansun** [comment]
Do you have resolved this question?
