### ISSUE TITLE
Less doesn't support new math functions (e.g. min, max)

### ISSUE THREAD

**Issue by joe223** [less/less.js#3463]
```
border-width: max(.01rem, 1px);
```
This code will break compile process.

**Comment by kbav** [comment]
Note: This is likely also true for the related `clamp()` function.

## A workaround
For anyone coming across this needing a workaround, you can always use LESS' string escaping capabilities to pass along a plain string to the CSS, eg.

```border-width: ~"max(.01rem, 1px)";```

**Comment by joe223** [comment]
@kbav Thanks，that's really helpful!

**Comment by WofWca** [comment]
If you need to use Less variables, e.g. `max(@my-var, 1px)`, you can do
```less
@my-var: .01rem;
--my-var: @my-var;
border-width: ~"max(var(--my-var), 1px)";
```

**Comment by matthew-dean** [comment]
Should be working as of Less 4

**Comment by blackmambahk** [comment]
less 4.1.2
this is still generating incompatible types error

`min-width: max( percentage(@i * .083333333333), unit(round(@i * 80), px) );`
