### ISSUE TITLE
Variable @supports is undefined on v3.10.x

### ISSUE THREAD

**Issue by awebdev** [less/less.js#3465]
Looks like support for CSS's "@support" is broken after v3.0.4, any ideas? change-log doesn't seem to have anything about it

<img width="884" alt="Screen Shot 2020-01-17 at 5 38 24 PM" src="https://user-images.githubusercontent.com/9402326/72656553-f7749100-3950-11ea-9fdd-db0fb1bf1e0e.png">

**Comment by matthew-dean** [comment]
I'm surprised there's not a specific test for this. Looks like it was missed. Will investigate.

**Comment by matthew-dean** [comment]
@awebdev I'm not sure what's going on for you, but there are lots of tests for `@supports`, and using your example on the latest version of Less (3.12.2), it compiled fine. 🤷‍♂️

**Comment by RajaJaganathan** [comment]
Still, we are getting the same error on v3.12.2 with less-loader v7.1.0

```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):


/* csslint ignore:start */
@supports ( -webkit-appearance: none ) or ( appearance: none )
        ^
Variable @supports is undefined
```
