### ISSUE TITLE
Less 3.11.0 breaks build that contain SASS files

### ISSUE THREAD

**Issue by xavierfoucrier** [less/less.js#3472]
Hi @matthew-dean,

Doesn't know if it is related to the PR #3453 by @life777, but when using the latest release `less@3.11.0`, I am unable to `@import` a SASS file inside a LESS build, even if the file is empty... causing this to fail:

```less
// build.less

@import 'vendor/foundation.scss'; // this is working with the previous version :/
@import 'theme/grid.less'; // this work fine
@import 'theme/color'; // this work fine too
```

> I am using `webpack@4.41.5`, `css-loader@3.4.2`, `less-loader@5.0.0`, `sass-loader@8.0.2` and some other stuff like `mini-css-extract-plugin` to make the build compile CSS+LESS+SASS together

I will rollback to `less@3.10.3` for now.
Thanks for your feedback! :wink:

**Comment by matthew-dean** [comment]
Please see if this is fixed on 3.11.1

**Comment by matthew-dean** [comment]
Please see if this is fixed on 3.11.1

**Comment by xavierfoucrier** [comment]
@matthew-dean will take a look asap :+1:

**Comment by xavierfoucrier** [comment]
@matthew-dean works like a charm, thanks! :+1:
