### ISSUE TITLE
LESS 3.11.0 breaks build importing a file with a webpack resourceQuery

### ISSUE THREAD

**Issue by yellowsunday** [less/less.js#3473]
Hi, I have a project with a custom webpack loader set up to transform a file before importing it into LESS. This is probably not a very usual setup, but it has worked until now. 

Maybe this is related to https://github.com/less/less.js/pull/3453 somehow?

In the .less file, I'm importing projectColors.json with an additional resourceQuery string:

`@import "./projectColors.json?projectcolors";`

With 3.11.0 it prints an error that it can't find `/path/to/projectColors.json?projectcolors.less`

In the webpack config module rules:

        {
          test: /\.json$/,
          resourceQuery: /projectcolors/,
          use: [
            {
              loader: 'text-transform-loader',
              options: {
                transformText: content => {
                  // generates and returns LESS content with color variables
                }
              }
            }
          ]
        },

Thanks for looking at this :)

**Comment by matthew-dean** [comment]
Please see if this is fixed on 3.11.1

**Comment by yellowsunday** [comment]
It is! Thank you for fixing it so quickly :)
