### ISSUE TITLE
Use less.js with CDN, there has no idea to resovle the error " Inline JavaScript is not enabled. "

### ISSUE THREAD

**Issue by qq240814476** [less/less.js#3478]
I use less with `CDN`

```html
<script src="https://cdn.jsdelivr.net/npm/less@3.11.1/dist/less.min.js"></script>
```
But I can't compile the `.less`file which include  inline js

![image](https://user-images.githubusercontent.com/21209891/74223179-19172d00-4cf1-11ea-819e-4fc37b1bbf3c.png)

I `don't` want to use dynamic compile package like `webpack`. 

How can I do.

**Comment by matthew-dean** [comment]
This should work:
```html
<script>
less = { javascriptEnabled: true }
</script>
<script src="https://cdn.jsdelivr.net/npm/less@3.11.1/dist/less.min.js"></script>
```

**Comment by matthew-dean** [comment]
Note that any JS within your `.less` files will be eval'd. For this reason, inline JS is disabled by default as a security precaution.
