### ISSUE TITLE
'request' package retires.. should find alternatives

### ISSUE THREAD

**Issue by gizmohd** [less/less.js#3479]
Per the announcement: https://www.theregister.co.uk/AMP/2020/02/12/requiem_for_request/   

the 'request' package is no longer receiving updates (no has it for a while now...)

Should probably consider removing/changes references to this package

**Comment by Siebes** [comment]
Additionally it seems the request package uses SHA-1 which is causing vulnerability scanners to flag it as a vulnerability due to weak cryptography.

**Comment by matthew-dean** [comment]
Replace with `native-request`
