### ISSUE TITLE
Visual studio code does not recognize @ import "~xxx"

### ISSUE THREAD

**Issue by kaysonwu** [less/less.js#3480]
I am referring to the class library in my less file, but `vs` cannot recognize it correctly. Later, I tried in `webstorm`, and it was recognized correctly.  Except VS doesn't recognize it, the compilation works normally.

```less
@import '~antd/es/style/themes/default.less';
```

**Visual studio code**

Report a file nonexistent error, the path is relative

**Webstorm**

It works fine

**Comment by DenisBratchikov** [comment]
+1
Can't specify absolute path to imports less

**Comment by rjgotten** [comment]
Not a Less.js issue but a VSCode issue.

Visual Studio Code as well as Visual Studio have _terrible_ support for Less that is lagging behind multiple major revisions of the compiler. It has been stuck in a rut for years and no-one within Microsoft's VS or VSCode dev team cares enough to do anything about it.

**Comment by matthew-dean** [comment]
@rjgotten That's not entirely true. I've personally submitted a number of improvements to the Less language service for VSCode. 🤷‍♂️  To be fair, a `~` is not part of basic Less syntax, it's just valid for certain plugins or for loaders for webpack. It's also not necessary.

**Comment by matthew-dean** [comment]
Closing as a VSCode issue.
