### ISSUE TITLE
is there a way to prevent evaluation of  "${prop}"?

### ISSUE THREAD

**Issue by forceuser** [less/less.js#3485]
is there a way to prevent evaluation of  "${prop}"?

i need to pass generated css to template engine that uses `${}` syntax for template interpolation, but i cant make less to generate string value like for example
```less
background: url("${resourcesPath}img/123");
```

**Comment by charsboo** [comment]
Hi, @forceuser:

Does this work?
```
background: e(%('url("%s{resourcesPath}img/123")', "$"));
```

**Comment by forceuser** [comment]
thanks a lot, it realy works 👍
