### ISSUE TITLE
How to replace node value in visitor "visitImport"?

### ISSUE THREAD

**Issue by aixfox** [less/less.js#3486]
I wanna a less plugin transforming `@import "a.less"` to `@import "b.less"`.

Here is my visitor:
```javascript
visitImport: function (importNode) {
  if (importNode.path.value === 'a.less') {
    importNode.path.value = 'b.less';
  }
  return importNode;
},
```

Visitor is walked in but value replacement is not working. Is there something doc or help?

**Comment by siyu77** [comment]
Is there some ‘official’ doc for plugin development.

**Comment by matthew-dean** [comment]
I don't believe such a thing is currently possible, but I could be wrong. Imports are visited quite early. You might need something like a pre-eval visitor (a visitor whose constructor sets `isPreEvalVisitor` to true). Originally, imports were collected during parsing, not evaluation, although I'm not sure how this was changed when variable evaluation was added to imports.

**Comment by matthew-dean** [comment]
Closing as not possible currently
