### ISSUE TITLE
Prototype Pollution for minimist

### ISSUE THREAD

**Issue by vmatchenko** [less/less.js#3487]
Please update minimist version in Your repository. 

  Moderate       Prototype Pollution                                                                          
  Package         minimist                                                                               
  Patched in      >=1.2.3                                                        
  Dependency of   grunt-contrib-less [dev]                                      
  Path                grunt-contrib-less > less > mkdirp > minimist                 
  More info       https://npmjs.com/advisories/1179

**Comment by boutell** [comment]
This; `npm audit` is failing. Straightforward fix. Thanks!
