### ISSUE TITLE
NPM audit: 8 high vulnerabilities

### ISSUE THREAD

**Issue by sjkummer** [less/less.js#3489]
I don't think anyone should actually use the current version in production:
`npm audit: found 21 vulnerabilities (3 low, 10 moderate, 8 high) in 2340 scanned packages`

**Comment by matthew-dean** [comment]
@sjkummer Okay, can you make a pull request to address this?

**Comment by matthew-dean** [comment]
@sjkummer Also, note that, in production, not all packages are used. Are you sure you're auditing just the dependencies, of which there is, I think one?

**Comment by sjkummer** [comment]
You are right!
I did a `npm install --production` before the `npm audit` and expected the dev-dependencies to be ignored, but that's not the case.
To ignore dev-dependencies you have to explicitly run `npm audit --production` ... and this looks pretty good.

**Comment by matthew-dean** [comment]
Closing as not a regular dependency issue.
