### ISSUE TITLE
Acorn has security vulnerability

### ISSUE THREAD

**Issue by limitedmage** [less/less.js#3496]
When installing LESS via NPM, it seems to install version 6.3.0 of Acorn inside `node_modules/less/packages/less/node_modules/acorn` which has a security vulnerability: https://www.npmjs.com/advisories/1488

This is tripping our internal security checks. Is there a way to fix it? This doesn't seem to be installed via normal NPM dependency chain and does not show up in `npm list` or `npm audit`.

**Comment by Sukesh-Gundoji** [comment]
Even we are facing the exact same issue. Please do let us know how we can fix it.
