### ISSUE TITLE
prevent caching of less files when using clientside rendering

### ISSUE THREAD

**Issue by scanacs-awuttig** [less/less.js#3502]
How can we achieve disable the browser caching for less files when we use the clientside rendering mechanism in our browser.

In earliers versions we use:

@random: ``Math.random()``;
@import 'variables.less?@{random}';

I also try to get it working with plugin http://lesscss.org/features/#plugin-atrules-feature but the expression is evaluated after import of less files takes place and the random number is not generated.

**Comment by matthew-dean** [comment]
@scanacs-awuttig Does the latest (3.11.3) still have this issue?
