### ISSUE TITLE
Replace `request` with `node-fetch`

### ISSUE THREAD

**Issue by sntran** [less/less.js#3505]
Even though `request` is one of the `optionalDepedencies`, it is still installed through normal `npm install`, and not many people will remember to use the `--no-optional` flag.

I did a search and `request` is only used in `lib/less-node/url-file-manager.js`. In that case, it's probably leaner to switch to something like `node-fetch`. `request` is [3.84MB installed](https://packagephobia.now.sh/result?p=request) while `node-fetch` is only [153KB installed](https://packagephobia.now.sh/result?p=node-fetch).

I would be happy to create a PR for it if it's worth considering.

**Comment by jburson** [comment]
Also, `request` generates warnings for all consumers:
**warning** less > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

**Comment by matthew-dean** [comment]
This has been replaced with `native-request` via this PR: https://github.com/less/less.js/pull/3501
