### ISSUE TITLE
3.11.2 broke less compiling in Parcel.js

### ISSUE THREAD

**Issue by kirkone** [less/less.js#3513]
Hi,

I upgraded less in my parcel project from 3.11.1 to 3.11.2.
After this the watcher for imported less files seems not to trigger the recompile anymore.

This is my configuration:

```
"devDependencies": {
    "autoprefixer": "9.8.0",
    "less": "3.11.2",
    "parcel-bundler": "1.12.4",
    "postcss-modules": "2.0.0",
    "typescript": "3.9.3"
}
```

When I revert to 3.11.1 everything works fine again.
Less is the only thing that changed in this case so I assume it has something to do with the last Update.
Maybe #3498 changed something in an unexpected way.

Any idea what is wrong here?

**Comment by matthew-dean** [comment]
@kirkone Does this fix it? https://github.com/less/less.js/pull/3509

**Comment by kirkone** [comment]
@matthew-dean yes, it is working again with 3.11.3

Thank you very much
