### ISSUE TITLE
[Programmatic usage] cannot read options of undefined

### ISSUE THREAD

**Issue by aminya** [less/less.js#3533]
I am trying to use Less in a programmatic fashion inside node, but I get this error:
```js
import less from 'less'
let lessRender = less.render;

// then I call lessRender on something
let y = lessRender(`
body {
    a: 1;
    b: 2;
    c: 30;
    d: 4;
}`, {sourceMap: {}},  function(error, output) {return output})

```

```js
TypeError: Cannot read property 'options' of undefined
```

what am I doing wrong? The documentation is vaguely written, and there is no tutorial on how to import the library and its functions. It also says API coming soon!
http://lesscss.org/usage/#programmatic-usage
Also, a couple of links don't work for example: https://github.com/less/less.js/blob/master/lib/less/environment/environment-api.js

Note: the code is written for less 2 inside Node, and I am trying to update it.

**Comment by matthew-dean** [comment]
> Also, a couple of links don't work for example: https://github.com/less/less.js/blob/master/lib/less/environment/environment-api.js

Please submit documentation problems to https://github.com/less/less-docs

**Comment by matthew-dean** [comment]
@aminya You're using the API correctly. You've encountered a bug when importing via ES6 modules (instead of CommonJS). Fixing now, thanks for reporting.
