### ISSUE TITLE
How to define variables containing ${ServletURL} ?

### ISSUE THREAD

**Issue by zsmj1994** [less/less.js#3555]
In version 2.0
```
@fontUrl: "${ServletURL}/resource/a.jpg";
.test {
  background: url("@{fontUrl}");
}
````
Will successfully compile to this , contains an Expression Language
```
.test {
  background: url("${ServletURL}/resource/a.jpg");
}
```

When i upgrade to 3.0 , I get an error
`variable $ServletURL is undefined in file ...`

**Comment by matthew-dean** [comment]
@zsmj1994 - In a quoted string `${prop}` is a reference to a property within the current scope.
