### ISSUE TITLE
« Promise » is undefined (Internet Explorer 11)

### ISSUE THREAD

**Issue by SimonDlgs** [less/less.js#3562]
Error found on Internet Explorer 11 when I try to lunch my website on this for watch compatibility and design problems, etc.

![image](https://user-images.githubusercontent.com/57448240/96150255-7e6b8f80-0f0a-11eb-9707-f1c824e40a24.png)
(Error writed in French).

I know is an old browser and isn't really important.

**Comment by SimonDlgs** [comment]
PS : My Less version is **v3.12.2**.

**Comment by matthew-dean** [comment]
You need a Promise polyfill installed if you want to run Less in IE11. You can use something like: https://polyfill.io/v3/
