### ISSUE TITLE
isundefined() needed as base of functionality, really really

### ISSUE THREAD

**Issue by applibs** [less/less.js#3565]
I have seen many contributions on the topic of "undefined variable", very many and I can not believe that this basic logical evaluation of jv Less is not yet. It is in every programming language as a basis as well as bool, number, string, etc.
Please do not discuss this and do it for the developer community, which will be very helpful.
There are too many requests for this to be ignored.

I've spent a huge amount of time bypassing this, and I still don't have the perfect solution. All other workarounds are bad. I used to like Less, but more and more a developers are leaving some similarly restrictive technology because they have to make too many bad workarounds, which are much more expensive than switching to something else and the technology dies.

It is a very small requirement and small modification, but long reach.

Thank you

**Comment by matthew-dean** [comment]
Can you explain your use case and why you personally believe it has a long reach that isn't resolved here? https://github.com/less/less.js/issues/1400

**Comment by matthew-dean** [comment]
@applibs On second thought, with some recent changes to function evaluation, a function like this is fairly trivial.

I've [added it here](https://github.com/matthew-dean/less.js/blob/next/packages/less/src/less/functions/boolean.js#L18-L25) and plan to release with 4.0, unless there's any objections.
