### ISSUE TITLE
Missing tags and versions

### ISSUE THREAD

**Issue by ite-klass** [less/less.js#3566]
This repository changelog file goes up to v3.12.0.

However, npm has _less_ in version v3.12.0 as well as v3.12.1 and v3.12.2.

This repository has a tag v3.12.0 as well as v3.13.0, but no 1 and 2 patch releases.

This is super confusing. Can someone explain this, and preferably add the missing tags?

**Comment by matthew-dean** [comment]
@ite-klass The short answer is that Less would benefit from more contributors. If tags are missing, you could make PRs that have them.

**Comment by matthew-dean** [comment]
Tags and changelogs updated in the meantime.

**Comment by ite-klass** [comment]
I don’t think I understand what you mean.

Git tags can not be suggested as changes with PRs. And neither do I know which commits are delivered as releases through the projects release channels.

For me the Git tags are what would allow me to contribute more based on them. Not the other way around.

**Comment by matthew-dean** [comment]
> Git tags can not be suggested as changes with PRs.

That I didn't know! Tags remain somewhat confusing to me. I thought I had tagged all releases, but apparently they were not pushed to this `master` from my fork's `master`.

**Comment by ite-klass** [comment]
I see them now. Thank you. :)

Git tags are handled somewhat differently to branches by Git. Depending on how you set up your local Git tags may or may not be pushed automatically to a remote.

I presume by _fork_ you mean your local repository (_clone_).

If you have questions regarding it, or how to set it up for your use case, feel free to ask (me).

**Comment by matthew-dean** [comment]
@ite-klass 

> I presume by fork you mean your local repository (clone).

No, I work with my `origin` set up as `matthew-dean/less.js` and `upstream` remote set to `less/less.js`, so I don't push unneeded branches to the less repo. Sometimes that gets me into hairy situations with tags because, as you say, they don't get included with PRs, so I kind of have to "hard push" them onto `less/less.js`.

If you know of a good way to manage that, I'd love to know.

**Comment by matthew-dean** [comment]
@ite-klass 

Additionally, I'd love any support you (or anyone) could offer with repo maintenance / CI configuration / automating tests etc.

**Comment by ite-klass** [comment]
Tagging my personal account @Kissaki

I’ve mostly switched to SCSS, but would be interested to help some. My time is quite limited too though.

**Comment by Kissaki** [comment]
Do you want to discuss separately what and how you would want/like? Should we create a separate ticket for it? Or discuss elsewhere?

**Comment by matthew-dean** [comment]
@Kissaki @ite-klass I'll try to check Gitter if you want to discuss: https://gitter.im/less/less.js
