### ISSUE TITLE
Less isn't recognising my background property that has 3 images at once

### ISSUE THREAD

**Issue by desbest** [less/less.js#3568]
If I have a `background:` property like this

```
.listingback {
background:
     url('images/listingback-top2.png') repeat-x,
     linear-gradient(transparent,rgba(0,0,0,0.03)) 0 00/100% 16px,
     linear-gradient(#000000,#171717)
;
}
```

The background won't load for elements with the `listingback` class.
Please fix this.

**Comment by matthew-dean** [comment]
It's likely because you don't have the math mode on `parens-division`, and so the first shorthand declaration essentially isn't valid. A good way to troubleshoot this is to look in devtools to see if that property is rendering.

**Comment by desbest** [comment]
But I'm not trying to use maths so I don't need to use `parens-division`. I am instead using CSS in shorthand to mean `background-position/background-size` `X Y/width height`

**Comment by matthew-dean** [comment]
>  I am instead using CSS in shorthand to mean background-position/background-size

@desbest Right. In order to do that, you need to make sure that `0/100%` isn't interpreted as division, which it is in Less 1.x-3.x by default. So you can either set the math mode to `parens-division`, or use Less 4.0, which has that mode on by default.

**Comment by desbest** [comment]
It works now. I think I was using an old version of less by accident.
Thank you for your help.
