### ISSUE TITLE
Less converts media-query aspect-ratio values from ratios to numbers

### ISSUE THREAD

**Issue by dmland** [less/less.js#3569]
Aspect ratios in media queries are expressed as [ratios](https://developer.mozilla.org/en-US/docs/Web/CSS/ratio)¹: Two numbers, separated by a slash, with whitespace permitted.

Unfortunately, since at least version 3.0², less appears to "resolve" this ratio-expressed-as-a-fraction into a real number.

Thus,

`@media (max-aspect-ratio: 16/9)` becomes `@media (max-aspect-ratio: 1.77777778)`

The browser³ does not find a ratio, so rules within the affected media query fail to take effect.

Thankfully, there is a workaround: declare the aspect ratio media query as a variable:

```
@max_square: (max-aspect-ratio: 16/9);
@media @max_square and (max-device-width: 767px) {
  ⋮
}
```
---

¹ MDN: "the **ratio** data type consist[s] of a strictly positive **number** followed by a forward slash and a second strictly positive **number**. In earlier versions of Media Queries, the **number**s had to be **integer**s.

² I used the highly configurable [estFiddle](http://ecomfe.github.io/est/fiddle/)) to try compiling media queries under various versions of the less preprocessor. This behavior seems to have changed at less 3.0. Prior versions compile correctly, at least on that site.

³ Google Chrome Version 87.0.4280.67 (Official Build) (x86_64) on MacOS Catalina 10.15.7

**Comment by matthew-dean** [comment]
The solution is simple: set the Less option for math (http://lesscss.org/usage/#less-options-math) Less version 4 will have `parens-division` by default.

**Comment by dmland** [comment]
Thank you. I will take this up with the developer of the CSS editor that has embedded less (who sent me to you).
