### ISSUE TITLE
How to use @property and --var with less?

### ISSUE THREAD

**Issue by JLEBSPeach** [less/less.js#3571]
I've literally looked everywhere online and cannot find an answer, and cannot see anything in the documentation.

```
@property --num {
  syntax: "<integer>";
  initial-value: 0;
  inherits: false;
}

h1 {
  transition: --num 5s;
  counter-set: num var(--num);
  font: 800 40px system-ui;
}
h1::after {
  content: counter(num);
}
h1:hover {
  --num: 100;
}
```

How would I write this in Less, I cannot figure out at all and i've tried everything! I tried using CSS.registerProperty as well and that didn't work, there was nothing in the documentation to explain how to do this.

Thanks,

Jacques

**Comment by matthew-dean** [comment]
@JLEBSPeach What CSS spec is this referring to?

**Comment by JLEBSPeach** [comment]
> @JLEBSPeach What CSS spec is this referring to?

https://developer.mozilla.org/en-US/docs/Web/API/CSS/registerProperty
https://drafts.css-houdini.org/css-properties-values-api-1/#at-property-rule

I was basically trying to do this:

https://css-tricks.com/animating-number-counters/

in LESS but had no luck.

**Comment by matthew-dean** [comment]
If I copy / paste your code into http://lesscss.org/less-preview/ it compiles fine. If you're talking about the experimental CSS, it wouldn't work in a browser where this isn't implemented. I don't think this issue has anything to do with Less.
