### ISSUE TITLE
webpack build error when version is 3.13.0

### ISSUE THREAD

**Issue by TopGrd** [less/less.js#3574]
I have some code like bottom.
```css
	@root-name: business-bundle
    /* other file */
	.@{root-name} .wrapper{
		/* css... */
	}
```

When webpack use less 3.12.2, that is ok. But when use 3.13.0, webpack build error.
![image](https://user-images.githubusercontent.com/4202848/102106371-73ca6980-3e6b-11eb-9e51-cff62d6d01f6.png)

**Comment by matthew-dean** [comment]
@TopGrd That really isn't enough to go on, especially when it's an error in a package that Less doesn't maintain. Can you make a test repo with a minimal test case? Also, does this error occur when just using `lessc` to compile your Less code?

**Comment by endbay** [comment]
Having a similar issue with v3.13.0 - 3.12.2 working for me as well.

![image](https://user-images.githubusercontent.com/38842789/102287129-0a655c00-3f3a-11eb-8e8b-11053c80cb77.png)

It's a huge project, so nearly impossible to find where in the less file this happend.

**Comment by matthew-dean** [comment]
@endbay @TopGrd 

I'm not sure what's expected here. With no reproducible example, and with the error not thrown in Less itself, there's no hope in a resolution. Someone will need to set a breakpoint at that error and see what selector was expected.

**Comment by matthew-dean** [comment]
@TopGrd 

One clue, this Less code is invalid:
```less
	@root-name: business-bundle
    /* other file */
	.@{root-name} .wrapper{
		/* css... */
	}
```
`@root-name: business-bundle` is missing a semi-colon. So it could be that you have some library layered on top of Less which is expecting an error, doesn't find one, and tries to re-parse, and says there's no parseable output.

**Comment by Justineo** [comment]
I'm experiencing a similar problem in 3.13.0. (Still trying to find out a minimal reproduction.)

Related code looks like:

```less
// button.less
@import "./lib.less";

.@{prefix}-button {
  color: red;

  &:hover {
    color: blue;
  }
}
```

```less
// lib.less
@plugin "~some-less-plugin"; // where @prefix is injected which preprocessing plugins
```

Which is compiled as:

```css
{
  color: red;
}

:hover {
  color: blue;
}
```

It's weird that no compilation error occurred.

**Comment by TopGrd** [comment]
@matthew-dean It is a very huge project where error occurred. I am trying to reproduce it in a demo

**Comment by TopGrd** [comment]
> @TopGrd
> 
> One clue, this Less code is invalid:
> 
> ```css-less
> 	@root-name: business-bundle
>     /* other file */
> 	.@{root-name} .wrapper{
> 		/* css... */
> 	}
> ```
> 
> `@root-name: business-bundle` is missing a semi-colon. So it could be that you have some library layered on top of Less which is expecting an error, doesn't find one, and tries to go ahead and parse Less's output, but fails with this "missing selector" error. That's just a guess, since I have no repo to look at.


@root-name: business-bundle;   Sorry, this is my code. It have a semi-colon.

**Comment by TopGrd** [comment]
> I'm experiencing a similar problem in 3.13.0. (Still trying to find out a minimal reproduction.)
> 
> Related code looks like:
> 
> ```css-less
> // button.less
> @import "./lib.less";
> 
> .@{prefix}-button {
>   color: red;
> 
>   &:hover {
>     color: blue;
>   }
> }
> ```
> 
> ```css-less
> // lib.less
> @plugin "~some-less-plugin"; // where @prefix is injected which preprocessing plugins
> ```
> 
> Which is compiled as:
> 
> ```css
> {
>   color: red;
> }
> 
> :hover {
>   color: blue;
> }
> ```
> 
> It's weird that no compilation error occurred.

I use style-resources-loader to inject some global variables too. Maybe it has something to do with that?

```js
{
  test: /\.less$/i,
  use: [
    {
      loader: MiniCssExtractPlugin.loader,
      options: {
        hmr: process.env.NODE_ENV === 'development',
        reloadAll: true,
      },
    },
    {
      loader: 'css-loader',
    },
    {
      loader: 'postcss-loader',
      options: {
        config: {
          path: path.resolve(__dirname, '../postcss.config.js'),
        },
      },
    },
    {
      loader: 'less-loader',
      options: {
        lessOptions: {
          javascriptEnabled: true,
          paths: [path.resolve(cwd, 'node_modules')],
        },
      },
    },
    {
      loader: 'style-resources-loader',
      options:{
            patterns: path.resolve(
              cwd,
              './node_modules/@somemodule/style/index.less',
            ),
            injector: 'prepend',
          },
    },
  ],
},
```

**Comment by TopGrd** [comment]
My code:
![image](https://user-images.githubusercontent.com/4202848/102316155-62d74080-3fb0-11eb-94fd-914c3e8d283d.png)

debugger output: no selector
![image](https://user-images.githubusercontent.com/4202848/102316214-7c788800-3fb0-11eb-831b-2c869291fe05.png)

**Comment by Justineo** [comment]
Still cannot find out a simple reproduction. It's very weird that when hot module replacement is triggered and the compiled output of the changed file seems to be correct. And the problem only occurs for selector interpolation:

```less
@import "./lib.less";

.@{prefix}-button {
  val: @prefix;
}
```

Compiles to:

```css
{
  val: foo;
}
```

**Comment by matthew-dean** [comment]
@Justineo

> the compiled output of the changed file seems to be correct

Can you expand on this a bit more? The compiled output from Less seems to be correct, but it's not getting replaced correctly?

**Comment by matthew-dean** [comment]
>  It's very weird that when hot module replacement is triggered and the compiled output of the changed file seems to be correct. 

@Justineo This is a helpful clue. It's likely related to the resolution of this: https://github.com/less/less.js/issues/3434

In short, tree caching was removed from Less for a time, but it seemed to have too much of a negative performance impact in some scenarios, so I put it back in. It could be that Less is therefore not resetting some state of import trees, which ONLY causes an issue in a "live" environment where less.parse is called multiple times. Hmm, I wonder if I can test that theory in a reproduction.

**Comment by matthew-dean** [comment]
@Justineo @TopGrd @endbay 

Unfortunately, I still cannot reproduce this issue, so it's not debuggable. ☹️  If someone can make a repo where it's easily reproducible, I could step through it.

**Comment by PengJiyuan** [comment]
> > I'm experiencing a similar problem in 3.13.0. (Still trying to find out a minimal reproduction.)
> > Related code looks like:
> > ```
> > // button.less
> > @import "./lib.less";
> > 
> > .@{prefix}-button {
> >   color: red;
> > 
> >   &:hover {
> >     color: blue;
> >   }
> > }
> > ```
> > 
> > 
> > ```
> > // lib.less
> > @plugin "~some-less-plugin"; // where @prefix is injected which preprocessing plugins
> > ```
> > 
> > 
> > Which is compiled as:
> > ```css
> > {
> >   color: red;
> > }
> > 
> > :hover {
> >   color: blue;
> > }
> > ```
> > 
> > 
> > It's weird that no compilation error occurred.
> 
> I use style-resources-loader to inject some global variables too. Maybe it has something to do with that?
> 
> ```js
> {
>   test: /\.less$/i,
>   use: [
>     {
>       loader: MiniCssExtractPlugin.loader,
>       options: {
>         hmr: process.env.NODE_ENV === 'development',
>         reloadAll: true,
>       },
>     },
>     {
>       loader: 'css-loader',
>     },
>     {
>       loader: 'postcss-loader',
>       options: {
>         config: {
>           path: path.resolve(__dirname, '../postcss.config.js'),
>         },
>       },
>     },
>     {
>       loader: 'less-loader',
>       options: {
>         lessOptions: {
>           javascriptEnabled: true,
>           paths: [path.resolve(cwd, 'node_modules')],
>         },
>       },
>     },
>     {
>       loader: 'style-resources-loader',
>       options:{
>             patterns: path.resolve(
>               cwd,
>               './node_modules/@somemodule/style/index.less',
>             ),
>             injector: 'prepend',
>           },
>     },
>   ],
> },
> ```

+1

Less @plugin + sourcemap will cause this problem

@matthew-dean 🙏

**Comment by matthew-dean** [comment]
@PengJiyuan Can you create a reproducible example in a cloneable repo?

**Comment by kirazxyun** [comment]
+1
![image](https://user-images.githubusercontent.com/10192144/102439873-0f213180-405a-11eb-96ff-1ada5bb26fc9.png)
I think the problem is caused by this code. The tree node have wrong fileInfo In the case of parallel, which causes the inputSource is undefined.

**Comment by PengJiyuan** [comment]
> +1
> ![image](https://user-images.githubusercontent.com/10192144/102439873-0f213180-405a-11eb-96ff-1ada5bb26fc9.png)
> I think the problem is caused by this code. The tree node have wrong fileInfo In the case of parallel, which causes the inputSource is undefined.

@matthew-dean Wait a minute, we create a mini repo. We have located this line of code, hope to help you solve it quickly...

**Comment by kirazxyun** [comment]
> +1
> ![image](https://user-images.githubusercontent.com/10192144/102439873-0f213180-405a-11eb-96ff-1ada5bb26fc9.png)
> I think the problem is caused by this code. The tree node have wrong fileInfo In the case of parallel, which causes the inputSource is undefined.

This line of code has appeared since 3.10.0

**Comment by kirazxyun** [comment]
> @PengJiyuan Can you create a reproducible example in a cloneable repo?

https://github.com/kirazxyun/less-question

This repo can reproduce the problem. You can run with 'npm run build'，then view the results in the dist folder.

**Comment by kirazxyun** [comment]
> > @PengJiyuan Can you create a reproducible example in a cloneable repo?
> 
> https://github.com/kirazxyun/less-question
> 
> This repo can reproduce the problem. You can run with 'npm run build'，then view the results in the dist folder.

@matthew-dean

**Comment by PengJiyuan** [comment]
@matthew-dean We use @plugin and it affects all our projects, please help us 🙏

**Comment by matthew-dean** [comment]
@PengJiyuan You're right, the code in question shouldn't fail outputting the chunk if source map building doesn't work. It should be like:
```js
                if (inputSource === undefined) {
                    this._css.push(chunk);
                    return;
                }
```
That would be a short-term fix, with the longer term fix being figuring out why one of the files has an incorrect import mapping. (It's probably being re-used when compiled in parallel.)

So I can do the temporary band-aid solution soon, and figure out the cause after.

**Comment by matthew-dean** [comment]
@PengJiyuan @kirazxyun @Justineo etc please try testing with `less@3.13.0-alpha.3`

**Comment by Justineo** [comment]
Problem solved with less@3.13.0-alpha.3. Thank you Matt!

**Comment by PengJiyuan** [comment]
@matthew-dean It works, thanks 🙏

**Comment by m1heng** [comment]
@matthew-dean  confirm that problem is solved with less@3.13.0-alpha.3, hoping for a official release soon

**Comment by TopGrd** [comment]
It is solved with less@3.13.0-alpha.3.

**Comment by TopGrd** [comment]
It is solved with less@3.13.0-alpha.3.

**Comment by matthew-dean** [comment]
3.13.1 published

**Comment by matthew-dean** [comment]
4.0.0 is also published, which contains this fix.
