### ISSUE TITLE
Media definitions require block statements after any features

### ISSUE THREAD

**Issue by Alymbek** [less/less.js#3577]
Hi, getting error while compiling *.less file for Uikit, see here - https://github.com/uikit/uikit/issues/4357

PS. `"less": "4.0.0"`, with "`less": "3.13.1"` no error

**Comment by matthew-dean** [comment]
This is expected. Less 4.0.0 is a breaking change, hence the major version increment. This is due to parentheses being required for mixin calls. Please see the release notes: https://github.com/less/less.js/releases/tag/v4.0.0
