### ISSUE TITLE
About .css.map file(v 4.0.0)

### ISSUE THREAD

**Issue by mysmlz** [less/less.js#3581]
Although it doesn't affect the usage, shouldn't the `version` in the `*.css.map` file be changed to 4?

**Comment by matthew-dean** [comment]
I think it's the version of sourcemaps, not the Less version, but I could be wrong.

**Comment by rjgotten** [comment]
It's the version of the sourcemaps protocol, yes.

**Comment by matthew-dean** [comment]
Thanks @rjgotten

**Comment by matthew-dean** [comment]
@rjgotten Can you message me on one of the messaging apps?
