### ISSUE TITLE
Disabling required parentheses for mixin calls?

### ISSUE THREAD

**Issue by urikalish** [less/less.js#3584]
We're considering an upgrade (v3.13.1 --> v4.0.0), but have thousands of old-style no-parentheses mixin calls in our current code.
Is it possible to disable this in some way?

**Comment by matthew-dean** [comment]
It's a change in parser code, so no, there's not currently a way to disable it.

Just so you know, the last, most recent v3 release and v4 are nearly identical and were released close together.  v4 has the paren requirement, the `parens-division` default setting for math, and a few other minor things.

**Comment by urikalish** [comment]
I understand. Thank you for the quick reply.

**Comment by matthew-dean** [comment]
Maybe this change was too aggressive in the interest of syntactic conformity? I'm going to keep this open as something that would accept a PR with an option.

**Comment by matthew-dean** [comment]
I'm gonna roll back the parens requirement

**Comment by matthew-dean** [comment]
4.1.0 released without the paren requirement. https://github.com/less/less.js/releases/tag/v4.1.0

**Comment by urikalish** [comment]
Thanks!
