### ISSUE TITLE
TypeError: Class constructor debugInfo cannot be invoked without 'new'

### ISSUE THREAD

**Issue by eight04** [less/less.js#3591]
https://github.com/less/less.js/blob/dc3a3105300930e2df14062fcf3de97d43db61b0/packages/less/src/less/tree/ruleset.js#L501
https://github.com/less/less.js/blob/dc3a3105300930e2df14062fcf3de97d43db61b0/packages/less/src/less/tree/debug-info.js#L1

Found this issue when trying to use less from the source. This works in dist because the class is compiled into a function.

**Comment by matthew-dean** [comment]
I remember finding the same when trying to convert to TypeScript. I'm not sure what the resolution should be / was though.

**Comment by drdevlin** [comment]
Is there a reason that debugInfo is defined as a class? I think defining it as a function would resolve the issue. I have refactored it to a function locally and there's no regression (that is, all existing tests pass). If all this sounds right, I'm happy to make a PR. (This is literally my first comment on GitHub and would be my first PR.)
