### ISSUE TITLE
中文官方文档错别字

### ISSUE THREAD

**Issue by DouMJun** [less/less.js#3592]
https://less.bootcss.com/#%E5%B5%8C%E5%A5%97%EF%BC%88nesting%EF%BC%89
页面下，嵌套章节的结尾，“了解有关**夫**选择器的详细信息”错误，应为“了解有关**父**选择器的详细信息”

**Comment by DouMJun** [comment]
https://less.bootcss.com/#%E5%B5%8C%E5%A5%97%EF%BC%88nesting%EF%BC%89
页面下，嵌套章节的结尾，“了解有关_**夫**_选择器的详细信息”错误，应为“了解有关**_父_**选择器的详细信息”

**Comment by matthew-dean** [comment]
Issues must be posted in English, sorry.
