### ISSUE TITLE
uncaughtException: Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by Ockejanssen** [less/less.js#3594]
TypeError: Cannot read property 'statusCode' of undefined
    at node_modules//less/lib/less-node/url-file-manager.js:33:40
    at done (node_modules/needle/lib/needle.js:468:14)

**Comment by zxfrank** [comment]
I logged my error

```LessError: resource 'https://fonts.googleapis.com/css?family=Roboto%20Slab' gave this Error:
    Error: socket hang up
```
I'm fixing it right now, status in #3597
