### ISSUE TITLE
数学运算：less编译为css是，除法没有被编译成功，这是一个bug嘛？

### ISSUE THREAD

**Issue by huangyangquang** [less/less.js#3598]
less文件：
`@width: 100px;
@height: @width / 10;

div {
width: @width;
height: @height;
border: 1px solid #000;
position: relative;
top: 100px + 100px;
left: 100px - 2;
margin: 10px * 2;
padding: 10px / 2;
}`

编译命令： lessc styles.less styles.css
编译后产生的css文件：
div { width: 100px; height: 100px / 10; border: 1px solid #000; position: relative; top: 200px; left: 98px; margin: 20px; padding: 10px / 2; }

有人知道是怎么回事嘛？

**Comment by matthew-dean** [comment]
Bug reports should be in English, thank you.
