### ISSUE TITLE
Error evaluating function `round`: argument must be a number

### ISSUE THREAD

**Issue by miloslavkostir** [less/less.js#3603]
Hello, it's not possible to use expression without parentheses as function argument  in v 4.x?
```
round(@table-cell-padding-vertical / 3)  // Works in v3.x but throws Error evaluating function `round`: argument must be a number in 4.x
round((@table-cell-padding-vertical / 3))  // This works in 4.x
```
I haven't find anything in documentation. So is this expected behavior, or is this bug?

**Comment by matthew-dean** [comment]
@miloslavkostir See: https://github.com/less/less.js/releases/tag/v4.0.0

> Parens-division now the default math setting
