### ISSUE TITLE
How to use custom functions

### ISSUE THREAD

**Issue by Pasoul** [less/less.js#3605]
We can create custom functions in sass like this. And how to do it in less？
```
@function vw($px) {
    @return ($px / 375) * 100vw;
}

div {
    padding: vw(15);
}
```

**Comment by iChenLei** [comment]
No, not support `@return` statement, you can create custom less function like follow.

<img src="https://user-images.githubusercontent.com/14012511/120273343-f4c5d200-c2e0-11eb-83d7-991d44219553.png" width="600px">
