### ISSUE TITLE
empty less block was removed after using "less.render" 

### ISSUE THREAD

**Issue by LyunKi** [less/less.js#3609]
when I use "less render" to transform LESS to CSS, I found the empty less block was removed.
![image](https://user-images.githubusercontent.com/21052565/111278083-1dd8ae00-8674-11eb-9b0e-d758cacfd756.png)
![image](https://user-images.githubusercontent.com/21052565/111278107-23ce8f00-8674-11eb-9306-703e249a86a4.png)
if there are any methods to avoid it, I need the complete selector information.

**Comment by iChenLei** [comment]
Duplicated https://github.com/less/less.js/issues/1006

You can witre simple code like follow to reach your goal.
```less
.a {
  .b {
    /* keep */
  }
}
```
It compile to:

![2021-06-12 17 07 44](https://user-images.githubusercontent.com/14012511/121771228-b792f700-cba0-11eb-9432-1d2753c75e80.png)

/cc @matthew-dean  close the duplicated issue, thanks.
