### ISSUE TITLE
less grammar validation(Pseudo classes) support

### ISSUE THREAD

**Issue by stefango** [less/less.js#3620]
https://youtrack.jetbrains.com/issue/WEB-50647#focus=Comments-27-4853266.0-0
```
// wrong（no error in WebStorm）
&:not(first-child) {
background: red;
}
// true
&:not(:first-child) {
background: red;
}
```

**Comment by iChenLei** [comment]
> Less compiler doesn't report any errors for this code, and the generated CSS is accepted by W3C validator; what errors would you expect to see here?

https://validator.w3.org/nu/#textarea
you can use this validator to check less generated code, it's valid, so it work as expetced and not bug.
