### ISSUE TITLE
Dimension is not a number.

### ISSUE THREAD

**Issue by rockey2020** [less/less.js#3633]
![image](https://user-images.githubusercontent.com/64777114/124778249-6bef2580-df73-11eb-9970-218a26b89044.png)

**Comment by rockey2020** [comment]
It doesn't work

**Comment by iChenLei** [comment]
Not less bug, just a `Math` logic error.
You write a invalid math compute `@witdh: (@designWidth / @i)` (the @i  variable can be __**zero**__!).

```diff
- .loop (@className, @i) when (@i >= 0) {
+ .loop (@className, @i) when (@i > 0) {
  .@{className}-@{i} {
    @witdh: (@designWidth / @i);
    width: @witdh * @i;
  }
  .loop(@className, @i - 1);
}
```

`non-zero / zero ` => we get a `Infinity`,  and then we  compute `@witdh * @i` , get a `NaN`.
So you will encount this error log:
```bash
var Dimension = function (value, unit) {
    this.value = parseFloat(value);
    if (isNaN(this.value)) {
        throw new Error('Dimension is not a number.');
    }
```
