### ISSUE TITLE
less import path resolver

### ISSUE THREAD

**Issue by doiya46** [less/less.js#3639]
In my case, I create main file: `src/app/styles/main.less`

```css
@import 'antd/lib/style/themes/default.less';
@import 'antd/dist/antd.less';
@import '@ant-design/pro-table/dist/table.less';
```
and in `@ant-design/pro-table/dist/table.less` used `@import '~......` like:

```css
//Its used '~antd....'
@import '~antd/es/style/themes/default.less';

@pro-table-prefix-cls: ~'@{ant-prefix}-pro-table';
....
...
```

So when I used the command line in `package.json`

```json
"scripts": {
  "less:build": "lessc --js --rewrite-urls=all --include-path=node_modules src/app/styles/main.less src/app/styles/main.css"
},
```

It will throw error:

```txt
FileError: '~antd/es/style/themes/default.less' wasn't found. Tried - /home/mi/Documents/work/react-demo/node_modules/@ant-design/pro-table/es/~antd/es/style/themes/default.less
```

The path `node_modules/@ant-design/pro-table/es/~antd/es/style/themes/default.less` should be `node_modules/antd/es/style/themes/default.less`. How can I use command line and resolve this problem?

**Comment by iChenLei** [comment]
For less native
https://lesscss.org/usage/#less-options-include-paths

For webpack
https://github.com/webpack-contrib/less-loader#imports
