### ISSUE TITLE
Try fix when script run with TamperMonkey or GreaseMonkey

### ISSUE THREAD

**Issue by langren1353** [less/less.js#3655]
When useing TamperMonkey or GreaseMonkey with less.js as a @require resource, sometimes there will be an error.
I trace the code found a small problem.
At `https://github.com/less/less.js/blob/master/packages/less/src/less-browser/utils.js`
function addDataAttrs param `tag` may be null, then the script will exec failed.
A short `if` may fix this, will you please add the code to check if tag is null

**Comment by iChenLei** [comment]
Hi, @langren1353  PR welcome !
