### ISSUE TITLE
Slow build of file with too many imports

### ISSUE THREAD

**Issue by kariae** [less/less.js#3657]
I'm using [Fomantic UI](https://github.com/fomantic/Fomantic-UI), which contains a  [.less](https://github.com/fomantic/Fomantic-UI-LESS/blob/master/semantic.less) file with many imports, and webpack/less-loader for the build. The build takes around 17 seconds, and when I do remove the imports the build goes to 2 seconds.

npx webpack-cli info` here in case they might help:
```
System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 70.17 MB / 8.00 GB
  Binaries:
    Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
    Yarn: 1.22.11 - /opt/homebrew/bin/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm
  Browsers:
    Chrome: 94.0.4606.81
    Safari: 15.0
  Packages:
    babel-loader: ^8.2.2 => 8.2.2
    css-loader: ^6.2.0 => 6.4.0
    css-minimizer-webpack-plugin: ^3.0.2 => 3.1.1
    less-loader: ^10.0.1 => 10.0.1
    postcss-loader: ^6.1.1 => 6.1.1
    sass-loader: ^12.1.0 => 12.1.0
    speed-measure-webpack-plugin: ^1.5.0 => 1.5.0
    style-loader: ^3.2.1 => 3.3.0
    ts-loader: ^9.2.5 => 9.2.6
    tsconfig-paths-webpack-plugin: ^3.5.1 => 3.5.1
    webpack: ^5.52.1 => 5.58.1
    webpack-cli: ^4.8.0 => 4.9.0
    webpack-dev-server: ^4.2.0 => 4.3.1
    webpack-merge: ^5.8.0 => 5.8.0
```

**Comment by ryouaki** [comment]
mark

**Comment by kariae** [comment]
thanks @ryouaki, since I'm watching files on change I'm not sure if I can build then import it would be the same.

I ended up cleaning the .less file, which made things much faster (around 3s) which is fine since I won't change it often.

Feel free to close this one, thank you.

**Comment by iChenLei** [comment]
Closed via https://github.com/less/less.js/issues/3657#issuecomment-1012838228

**Comment by zxkws** [comment]
I have the same question, if there has a good solution by tools
