### ISSUE TITLE
`@plugi` and `@impor` are supported

### ISSUE THREAD

**Issue by edhgoose** [less/less.js#3660]
We discovered that the regex used for `import` and `plugin` have a `?` at the end of them, which means `@plugi` and `@impor` work as well as `@plugin` and `@import`.

These are defined here: https://github.com/less/less.js/blob/master/packages/less/src/less/parser/parser.js#L1687 and https://github.com/less/less.js/blob/master/packages/less/src/less/parser/parser.js#L1847.

This doesn't look like an intentional decision and more of a regex mistake. See here for example inputs: https://regex101.com/r/NUw7E2/2

Is this correct?

**Comment by iChenLei** [comment]
Thanks for report this issue.
