### ISSUE TITLE
Empty Classes getting omitted automatically

### ISSUE THREAD

**Issue by deadmann** [less/less.js#3661]
I naturally tend to backup my JS codes with CSS classes for intellisense support in HTML file, and when what LESS does after compile, is to omit all empty classes, make the IDE dumb. how can I disable it in JetBrains products?

**Comment by iChenLei** [comment]
jetbrains issue tracker: https://youtrack.jetbrains.com/issues/WEB 

And I know your issue, maybe https://github.com/less/less.js/issues/1006  and https://github.com/less/less.js/issues/3609 can help you.

**Comment by iChenLei** [comment]
Feel free to reopen this issue if it's still a issue.
