### ISSUE TITLE
Import statements do not load in parallelless(importStatement)

### ISSUE THREAD

**Issue by aquapi** [less/less.js#3664]
I have to import multiple files in a LESS file:

```less
@import "./banner.less";
@import "./createdarticle.less";
@import "./lists.less"; 
@import"./searchbar.less";
@import "./navbar.less";
```

And it throws an error
```
Import statements do not load in parallelless(importStatement)
```
How do I fix that?

**Comment by iChenLei** [comment]
Can you provide a simple reproducation project ? Thanks

**Comment by iChenLei** [comment]
less `v4.1.2` can't reproduce, close it.
feel free to reopen this issue if you can provide reproduce code snippet.
