### ISSUE TITLE
Use less, I feel abandoned by the world.

### ISSUE THREAD

**Issue by PengJiyuan** [less/less.js#3680]
Use less, I feel abandoned by the world.
Next.js, create-react-app... I need do a lot of work to be compatible with less.
So how did less become like this?

**Comment by iChenLei** [comment]
What's wrong ? Bro

**Comment by PengJiyuan** [comment]
> What's wrong ? Bro

Now many popular tools do not have less built-in, such as next.js, create-react-app, they chose sass.
So I need do a lot of work to be compatible with less.
I upgraded react-scripts to 5.0 today and I was driven crazy...

**Comment by PengJiyuan** [comment]
Finally, I upgraded react-scripts successfully. 
Hope less can reshape the brilliance.

**Comment by iChenLei** [comment]
https://github.com/vercel/next.js/pull/23185
