### ISSUE TITLE
how can I use remainder(%) in less?

### ISSUE THREAD

**Issue by zjjjjjjjjjjd** [less/less.js#3684]
**To reproduce:**

```less
@num: 10 % 6 // error
```

**Current behavior:**

error

**Expected behavior:**

right

**Environment information:**

- `less` version:
- `nodejs` version:
- `operating system`:

**Comment by iChenLei** [comment]
use builtin [mod](https://lesscss.org/functions/#math-functions-mod) function.
```less
@num: mod(10, 6);
```
