### ISSUE TITLE
There is no way to copy the css interpreted on the right area

### ISSUE THREAD

**Issue by truelove4044** [less/less.js#3742]
Can you please fix this problem please?, the website works fine.

**Comment by iChenLei** [comment]
I can't understand your question, bro.

**Comment by truelove4044** [comment]
I can't use ctrl+c to copy the translated css, 
sorry, English is not my native language, so there may be errors in expression.

I made a picture to explain the problem I'm having
https://upload.cc/i1/2022/07/20/eZL2r4.jpg

**Comment by rakeshkumawat12** [comment]
I'll see to it why it is not working
