### ISSUE TITLE
Rename translated domain to new url

### ISSUE THREAD

**Issue by xoex** [less/less.js#3743]
Hi.
I'm owner of less-css.ir (Persian translation of lesscss.org documentation in https://lesscss.org/about/ , Iranian section).
Unfortunately I wasn't careful about renewing domain address and now the Url is broken. 
I registered a new domain and transferred data from old site to new url at : 
http://lesscss-iran.ir

Please change from 
  Iranian: http://less-css.ir/
to 
  Iranian: http://lesscss-iran.ir

Thank you

**Comment by iChenLei** [comment]
I got it. Thanks for notification.
