### ISSUE TITLE
variable in @import statement

### ISSUE THREAD

**Issue by arnaudgaudin** [less/less.js#410]
The lastest version introduced the possibility to "access the value of an abstract property from a string using { } operators" (section "String interpolation" in http://lesscss.org/#-string-interpolation).

But the problem is that it doesn't work in import statements. It would be great to write code such like this :

//define the template
@mainTemplate: "BaseTheme";

//import the template
@import "_templates/@{mainTemplate}/Config/_ConfigTemplateDefault.less";

I don't know if it is possible to resolve this issue, but it would be great !

**Comment by joeSaad** [comment]
:+1: for  @import "@{url}/less/file.less"

**Comment by seven-phases-max** [comment]
@joeSaad Just in case, you do realize this feature [is implemented](http://lesscss.org/features/#variables-feature-import-statements) quite a while ago, do you?

**Comment by mihmilicio** [comment]
Having the same issue using Less with Angular 8. Any updates?
```
"less": "3.9.0",
"less-loader": "5.0.0"
```
I tried updating to latest, didn't work.

The console outputs the following:
```
./src/styles.less (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/less-loader/dist/cjs.js??ref--16-3!./src/styles.less)
Module build failed (from ./node_modules/less-loader/dist/cjs.js):



@import  "assets/less/@{client-dir}/_variables.less";
^
Maximum call stack size exceeded
      in C:\localpath\styles.less (line 709, column 0)
```

**Comment by SheldonLaw** [comment]
> Having the same issue using Less with Angular 8. Any updates?
> 
> ```
> "less": "3.9.0",
> "less-loader": "5.0.0"
> ```
> 
> I tried updating to latest, didn't work.
> 
> The console outputs the following:
> 
> ```
> ./src/styles.less (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/less-loader/dist/cjs.js??ref--16-3!./src/styles.less)
> Module build failed (from ./node_modules/less-loader/dist/cjs.js):
> 
> 
> 
> @import  "assets/less/@{client-dir}/_variables.less";
> ^
> Maximum call stack size exceeded
>       in C:\localpath\styles.less (line 709, column 0)
> ```

same issue in
```
"less": "3.11.1",
"less-loader": "4.1.0"
```

**Comment by matthew-dean** [comment]
@SheldonLaw Causing a loop (`Maximum call stack exceeded`) is a bug. You should file as a new issue.
