### ISSUE TITLE
[Question]: Version 4.2.0 reported in NPM but neither tag or release is shown in repository.

### ISSUE THREAD

**Issue by Aglezabad** [less/less.js#4156]
Sorry for putting a question in a bug report but I didn't see the appropiate way. Two days ago, NPM reported a new version of this library but there's no changelog, tag or release in repository. Also, the recent events of bad actors spamming the issue reporting area causes me to raise this question:

Is version 4.2.0 in NPM a legitimate version?

Thank you.

**Comment by iChenLei** [comment]
see https://github.com/less/less.js/pull/3814

**Comment by Aglezabad** [comment]
Thank you very much.
