### ISSUE TITLE
Accessing specific properties from rule-sets

### ISSUE THREAD

**Issue by bhavinkamani** [less/less.js#76]
Hi,

Does less.js allows accessing specific properties from a rule-set? I was trying with following less-css
<pre>
#color {
    @brand-color: #EEE;
}

html,body {
  background-color: #color[@brand-color];
}
</pre>
However, it is giving syntax error. From official LESS documentation this appears to be the correct syntax (Ref: http://lesscss.org/docs - Namespaces & Accessors).

Thanks for making a truly rocking solution.

Regards
Bhavin

**Comment by seven-phases-max** [comment]
Merging to #1848.
