### ISSUE TITLE
Questions about the "variables" param of tree.toCSS()

### ISSUE THREAD

**Issue by curvedmark** [less/less.js#797]
The docs says we can access the compiler like this:

```
var parser = new(less.Parser);

parser.parse('.class { width: 1 + 1 }', function (err, tree) {
    if (err) { return console.error(err) }
    console.log(tree.toCSS());
});
```

and from [this line of the source code](https://github.com/cloudhead/less.js/blob/master/dist/less-1.3.0.js#L507) it looks like we can pass a list of less variables to the compiler, which I supposed would override or add global less variables, something like #207 asked about.

But it turns out that's not the case. After digging the code a little deeper, I find out that the supplied variables are always [put at the bottom of the frame stack](https://github.com/cloudhead/less.js/blob/master/dist/less-1.3.0.js#L2765), which makes this param pretty much useless I guess, since less variables need to be defined before they can be used.

Maybe I misunderstand something here, and would like to be enlightened. :)

**Comment by gingur** [comment]
I too would like to know more about this, I am trying to re-use a parseTree by simply modifying just variables on the root and then re-running `toCSS` but with override variables.

**Comment by seven-phases-max** [comment]
@gingur See #2293.

**Comment by seven-phases-max** [comment]
Removing "bug" label as nothing in the initial post shows any bug anywhere. Insteed the report is based on totally wrong assumption:

>makes this param pretty much useless I guess, since less variables need to be defined before they can be used.

**Comment by gingur** [comment]
So, I still don't see the variables option working in `transform-tree.js`.  Can you provide an example gist that overrides the variables in the initial root tree by simply passing variables to the `toCSS` function?  As a workaround, I'm doing http://jsbin.com/luxisah/3/edit?js,console,output

**Comment by seven-phases-max** [comment]
>Can you provide an example gist that overrides the variables in the initial root tree by simply passing variables to the toCSS function? 

Sorry, I don't have such example (Nor I can't write it right now).
Did you actually read  https://github.com/less/less.js/issues/2293#issuecomment-63166934?
I.e. even if the `variables` option does not work (I actually doubt anyone tested it for a while) you simply need to take the tree and append those variables (in Less i.e. "parsed" format, not strings) to it before `toCSS`.
