### ISSUE TITLE
warn when invalid values are passed to functions and clamped?

### ISSUE THREAD

**Issue by lunelson** [less/less.js#821]
If you define a color like this:

```
@color: hsla(0,100,100,1);
```

...it should produce 100% red, but it produces 100% cyan.

Also, the corresponding readout function of `hue()` is producing the incorrect value too; although if you use the two functions together the errors cancel each other out. 

Still `hsla()` should be fixed to work correctly for defining new colors.

**Comment by seven-phases-max** [comment]
Changing label to "feature-request" (since this is definitely not a bug but intended behaviour).

**Comment by matthew-dean** [comment]
I think generating "warnings" is a separate issue, yes? Can someone find which issue this is dependant on?

**Comment by seven-phases-max** [comment]
I'm not sure if there's corresponding issue. The specific `no %` warnings for colour function were discussed at #1665/#1669.
