### ISSUE TITLE
Mixins should accept LESS blocks

### ISSUE THREAD

**Issue by rbu** [less/less.js#965]
It would be helpful if mixins had access to a content block passed to them, so one could encapsulate media queries or browser hacks in a central place and reference them symbolically.

This is basically the "Passing Content Blocks to a Mixin" feature of SASS:
http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#mixin-content

In LESS this would mean something like:

```
.mobile() {
  @media all and (max-device-width: 480px) {
    @content
  }
}
.big-desktop-button {
  ...
  .mobile {
    display:none;
  }
}
```

**Comment by AndrewEastwood** [comment]
is it working right now?

**Comment by seven-phases-max** [comment]
@AndrewEastwood See [the docs](http://lesscss.org/features/#detached-rulesets-feature).

**Comment by AndrewEastwood** [comment]
Thanks
