### ISSUE TITLE
LESS file compiling 3x (or more) slower in Firefox

### ISSUE THREAD

**Issue by levi** [less/less.js#967]
I have been using Chrome with less.js. The compile time is around 500ms for a 9000 line less file with about 11 different imports being prefetched with XHR. However, when I run the same project in Firefox, the fastest compile time I encounter is about 1600ms. Sometimes it increases up to 4500ms.

Is there a reason for this slow down in performance on Firefox and are there any way to improve the speed beyond restructuring my LESS document?

**Comment by chhantyal** [comment]
I wish someone could look into this.

I recently switched to Firefox as my default browser, and this issue is really annoying that first broken page appears and after sometime LESS does it's thing and final page is displayed properly.

Obviously, I use LESS for developing and compile to CSS in production.

**Comment by lukeapage** [comment]
We know its one or more regular expressions. I keep meaning to work on this
but get distracted. I will try tonight.

**Comment by lukeapage** [comment]
My current guess based on reports we've had is that it effects long less files only and is caused by one or more of the regular expressions, probably because I removed chunking of the input (it was causing a bug). If its 1 regexp causing the issue we can fix - if its all then we are stuck.

Can someone post or send me their large css file showing worse performance in firefox? I cannot reproduce a browser difference with bootstrap.

You can try setting chunkInput to true (its an option) and let me know if it improves things too. The solution may be to split up your less files so you do not have 1 massive one.

**Comment by chhantyal** [comment]
@lukeapage The usual convention with LESS files is to split into multiple files and import in single file. It's not different from having one big file, right?

I will try to reproduce the it.

**Comment by himanshuwt** [comment]
I'm also facing performance issue while compiling 17k lined LESS file to CSS on the client side. Can you help me?

**Comment by seven-phases-max** [comment]
@himanshuwt

I'm afraid the only proper help in this case would be to say: "Do not compile at the client-side".
There's no secret option or hack to make faster.

Except a few specific edge-cases ("online Less-to-CSS compile tool", "Theme/framework show-case demos" and similar stuff) there's no fair reasons to go with the browser-side script. 
And if you do choose a browser script way you are automatically agreed with a poor performance
(While certain improvements are possible, there simply no volunteers to contribute into this area. Though the PRs are always welcome).

**Comment by himanshuwt** [comment]
@seven-phases-max
Thank you for information.
I agree with you but I need to increase performance anyhow, we're working to create a theme editor in which user can create their own theme.

**Comment by seven-phases-max** [comment]
>I need to increase performance anyhow

Like at any cost and in infinite time? (OK, just jocking).
So I guess this can be split into three or so steps:

1. Find what can be optimized at the project side. Like "Do all subparts of this 17k-lines thing actually depend on the theme values?" (Usually not, so do not pass the constant parts through the Less compiler).
2. Check if some (relatively light-weight) tricks may help (e.g. #2640, #2746 - sometimes they do, sometimes they don't).
3. Finally optimize the compiler itself (start with considerations made in #2501 and #3145 here and be prepared for weeks wasted for 5% speed improvements, months for 20%, etc.).

**Comment by matthew-dean** [comment]
> Finally optimize the compiler itself (start with considerations made in #2501 and #3145 and be prepared for weeks wasted for 5% speed improvements, months for 20%, etc.).

I wouldn't call it "wasted" 😉 If someone wants to help a bunch of people out, that work is always welcome. There are probably lots of potential places to optimize. I think one unknown with that is how you concretely verify the difference in code A vs code B in terms of performance. I don't know of any easy way to do that. I've said it before, but that's probably some low-hanging fruit to figure out before trying optimization work.

**Comment by seven-phases-max** [comment]
<sub>Indeed. I should minimize my use of demotivating generalizations.</sub>

**Comment by matthew-dean** [comment]
> Indeed. I should minimize my use of demotivating generalizations.

Haha it’s all good.

**Comment by himanshuwt** [comment]
Thanks @seven-phases-max
I will try to optimize my code.
