### ISSUE TITLE
Add color scaling functions

### ISSUE THREAD

**Issue by OlsonDev** [less/less.js#975]
As evidenced by #282, many people feel the color functions should work relatively instead of absolutely. For example, calling ```darken(hsla(0,0,10%,1), 10%)``` should result in ```hsla(0,0,9%,1)``` instead of ```hsla(0,0,0,1)```.

Due to obvious backwards compatibility issues, we shouldn't change the behavior of the existing functions completely. However, it would be nice if we added relative variations or possibly overloads.

I propose the convention ```darkenrelative(@color, @percent)``` instead of ```darken(@color, @percent, true)``` because it's more obvious what you're doing. Personally, I'd rather see ```darkenRelative``` but it appears your standards are all lowercase (e.g. ```isnumber```, ```iscolor```, etc.).

The functions that should have relative counterparts added are:

    lighten
    darken
    saturate
    desaturate
    fadein
    fadeout

I also propose new color functions follow this convention where applicable -- ```somefunction``` and ```somefunctionrelative```.

**Comment by Heartx** [comment]
Any progress on this issue?

**Comment by miroslav-mrazek** [comment]
There is error in implementation, see https://github.com/bassjobsen/less.js/commit/622a521b11ede8be8930b438aa4ed9d6bfb376d9#commitcomment-14811312
Can I reopen same issue, or must create a new issue?

**Comment by SomMeri** [comment]
@miroslav-mrazek If it is just a but, open a new issue. It is easier to track what was done already and what is not that way.

**Comment by seven-phases-max** [comment]
@miroslav-mrazek In fact there's no error in the implementation. #2504 implements it as specified in this and #282 issues. What you're suggesting is *another* algorithm (technically there's infinite count of possible algorithms for this kind of adjustments), so yes, opening a new ticket is the way to go in either case.
